### ISSUE TITLE
Association scopes Example

### ISSUE THREAD

**Issue by samanmohamadi** [RobinBuschmann/sequelize-typescript#103]
Is there any way to use [association scopes](http://docs.sequelizejs.com/manual/tutorial/associations.html#scopes) with this great decorator ?

**Comment by RobinBuschmann** [comment]
See the example from issue #45: https://github.com/RobinBuschmann/sequelize-typescript/issues/45#issue-241086728

Does this help?

**Comment by samanmohamadi** [comment]
Yes, Thanks

**Comment by samanmohamadi** [comment]
considering this:
```
Post.belongsToMany(Tag, {
  through: {
    model: ItemTag,
    unique: false,
    scope: {
      taggable: 'post'
    }
  },
  foreignKey: 'taggable_id',
  constraints: false
});
```
How should I define through Options ?
according to [this](https://github.com/RobinBuschmann/sequelize-typescript/blob/000fbb11503a622085c8735e2d3f96ebd6c46d6a/lib/interfaces/IAssociationOptionsBelongsToMany.ts#L5) interface I think it isn't possible, right ?

**Comment by RobinBuschmann** [comment]
You're right. This isn't supported yet. I will create an issue for that.

**Comment by RobinBuschmann** [comment]
#122
