### ISSUE TITLE
composite unique constraint

### ISSUE THREAD

**Issue by samanmohamadi** [RobinBuschmann/sequelize-typescript#105]
Is it possible to define composite unique constraints like this ?
```
const ItemTag = sequelize.define('item_tag', {
  id : {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  tag_id: {
    type: DataTypes.INTEGER,
    unique: 'item_tag_taggable'
  },
  taggable: {
    type: DataTypes.STRING,
    unique: 'item_tag_taggable'
  },
  taggable_id: {
    type: DataTypes.INTEGER,
    unique: 'item_tag_taggable',
    references: null
  }
});
```

**Comment by RobinBuschmann** [comment]
With the `Column` annotation:

```typescript
@Column({
  unique: 'item_tag_taggable',
  ...,
})
```

**Comment by samanmohamadi** [comment]
tnx

**Comment by NickTaylor98** [comment]
Is it possible to define two composite unique constraints where there is an intersection between columns?
I mean:
`
 await queryInterface.addConstraint('a_b', ['a_id', 'b_id'], {
      type: 'unique',
      name: 'a_b_unique_constraint',
    });
    await queryInterface.addConstraint('a_c', ['a_id', 'c_id'], {
      type: 'unique',
      name: 'a_c_unique_constraint',
    });
`
As you see there is a column `a_id` which is a part of two composite unique indexes. 
How can I define this property in model description?
Smth like ?
`
@Column({
    unique: [
      'a_b_unique_constraint',
      'a_c_unique_constraint'
    ]
    type: DataType.INTEGER,
  })
`

**Comment by RobinBuschmann** [comment]
Hey @NickTaylor98, I'm not sure. What does the sequelize docs say?

**Comment by akoidan** [comment]
@NickTaylor98 were you able to solve 2 unique constraints issue?

**Comment by FilipKubis** [comment]
@NickTaylor98 @RobinBuschmann @akoidan 

You can define composite multiple composite indices in the table options, which should in effect solve the issue.

`
// This string binds unique constraint to the combinations
const UNIQUE_CONSTRAINT_EMAIL: string = "unique_email_per_tenant"
const UNIQUE_CONSTRAINT_PHONE: string = "unique_phonenumber_per_tenant"

@Table({
    indexes: [
    {
        name: UNIQUE_CONSTRAINT_PHONE,
        unique: true,
        fields: ['phone', 'userId']
    },
    {
        name: UNIQUE_CONSTRAINT_EMAIL,
        unique: true,
        fields: ['email', 'userId']
    },
    ]
})
`
