### ISSUE TITLE
Adding postbuild for automatic building

### ISSUE THREAD

**Issue by bilby91** [RobinBuschmann/sequelize-typescript#108]
Hello,

I wanted to know if a pull request that added https://github.com/exogen/postinstall-build would be accepted ?

This will allow the installation of the project from a different source than npm (for example git, I also use it with file type of packages) without having to maintain a different branch with the compiled source.

**Comment by RobinBuschmann** [comment]
Hey @bilby91 ,

`postinstall-build` will be a dependency for all users who install `sequelize-typescript` then, despite of they probably doesn't need it. Probably we can find another solution. A branch called `build` for example, that is created automatically on every push to the master. Maybe there is a github plugin that achieves this? This would fit your requirements very well, I think? Without having an additional dependency.

**Comment by RobinBuschmann** [comment]
@bilby91 Any thoughts on this?

**Comment by bilby91** [comment]
@RobinBuschmann Yep, I guess that is the only drawback. The dependency will be shipped always :(. 

Yep, I guess that we can have a `master-compiled` branch that can be automatically generated by CI after a merge on master. That should work for master. 

The only "problem" will be if people want to install a particular branch that is not master.
