### ISSUE TITLE
Support for managed transactions? 

### ISSUE THREAD

**Issue by a-moss** [RobinBuschmann/sequelize-typescript#1084]
# Issue
It's possible I missed it when scanning the source code, but it would be nice if this could support managed transactions (see Sequelize docs (https://sequelize.org/master/manual/transactions.html). It does seem to work fine for unmanaged transactions, but that results in harder to read code and is more prone to errors.

If I didn't just miss this in the source for sequelize-typescript, I'm happy to open a PR that adds support for this.

## Versions

- sequelize: ^6.6.2
- sequelize-typescript: ^2.1.0
- typescript: ^4.2.4

## Issue type

- [ ] bug report
- [x] feature request

## Expected behavior

TS support for managed transactions, so you could do something like this (taken from Sequelize docs)

```ts
  const result = await Sequelize.transaction(async (t: Transaction) => {

    const user = await User.create({
      firstName: 'Abraham',
      lastName: 'Lincoln'
    }, { transaction: t });

    await user.setShooter({
      firstName: 'John',
      lastName: 'Boothe'
    }, { transaction: t });

    return user;

  });
```

**Comment by a-moss** [comment]
After doing some more digging, it turns out the DT types for sequelize had definitions for transactions. I just had to call the transaction function on my original sequelize instance.

Closing.

**Comment by ThanhDeveloper** [comment]
> After doing some more digging, it turns out the DT types for sequelize had definitions for transactions. I just had to call the transaction function on my original sequelize instance.
> 
> Closing.

How did you use transaction in this lib ?
