### ISSUE TITLE
enum column

### ISSUE THREAD

**Issue by lilling** [RobinBuschmann/sequelize-typescript#11]
@RobinBuschmann 

How do I write an enum column?

``` ts
enum RoleStatus { ACTIVE, DELETED, PENDING}
```

I want the default value to be pending

**Comment by RobinBuschmann** [comment]
If you want to use the data type ENUM, you could implement it like this:

````typescript
@Default('ACTIVE')
@Column(DataType.ENUM('ACTIVE', 'DELETED', 'PENDING'))
state: 'ACTIVE'|'DELETED'|'PENDING';
````
Therefore you need to map your TypeScript enum values to its string representations. (`RoleStatus[RoleStatus.ACTIVE]`) or you're could use literal types instead:
````typescript 
type RoleStatus = 'ACTIVE'|'DELETED'|'PENDING';
````
````typescript 
@Default('ACTIVE')
@Column(DataType.ENUM('ACTIVE', 'DELETED', 'PENDING'))
state: RoleStatus;
````
(Regarding enum types in databases in general it might be useful to read this http://stackoverflow.com/a/8792748)

**Comment by lilling** [comment]
thanks @RobinBuschmann I tried it and It worked perfectly!

**Comment by mwaeckerlin** [comment]
How can it be done without duplication of the enum constants?

**Comment by mwaeckerlin** [comment]
Found a solution:

Since I don't want to repeat enum constants, this is a solution:
```
export enum MyEnum {
  FIRST = 'FIRST',
  SECOND = 'SECOND',
  THIRD = 'THIRD',
}
```
…
```
  @Column({ type: DataType.ENUM({ values: Object.keys(MyEnum) }) })
  value: MyEnum;
```

**Comment by reekoz** [comment]
I don't know how to declare `STATES` in `SingleLan` constant

![image](https://user-images.githubusercontent.com/29949267/152377897-df97a713-ac5c-41a5-a4fa-de8a50605144.png)

**Comment by dcsan** [comment]
@mwaeckerlin nice extra, i too don't want to duplicate all the types around.
did you find a solution for default values?

I tried a few options like the commented out line here.

```ts
export enum RocketStatus {
    READY,
    RACING,
    ENDED
}

...

    // @Default(RocketStatus.READY)
    @Column({
        type: DataType.ENUM({ values: Object.keys(RocketStatus) }),
        // defaultValue: RocketStatus.READY
    })
    status: RocketStatus;
```

```sql
'CREATE TABLE IF NOT EXISTS "Rockets" ("id" UUID NOT NULL , "name" VARCHAR(255), "raceId" UUID REFERENCES "Races" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "tokenId" INTEGER, "meta" JSONB, "path" JSONB, "status" "public"."enum_Rockets_status" DEFAULT 0, "staked" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));',
```

gives error:

```
  original: error: column "status" is of type "enum_Rockets_status" but default expression is of type integer
```



i also can't see a good way to override the constructor since that's used for Sequelize internally and I didn't get `super()` working.

**Comment by dcsan** [comment]
no, i think i went back to using strings
