### ISSUE TITLE
Question about model extension

### ISSUE THREAD

**Issue by Pritilender** [RobinBuschmann/sequelize-typescript#116]
Hello! Extending `Model` class is supported, If I got #74 correctly?

The thing is I want to add `findOneOrFail` and `findByIdOrFail` on my models (nearly all of my models have it) which is just a wrapper around `findOne`/`findById`, but I don't want to have manually add it to every new model class of mine, so I wanted to make a new `BaseModel` class having this methods defined. Currently, I have this:

```typescript
export class BaseModel<T> extends Model<T> {
  public static findByIdOrFail<T>(id: number, options?: IFindOptions): Promise<BaseModel<T>> {
    return new Promise(async (resolve, reject) => {
      const model: BaseModel<T> = await Model.findById(id, options)
      if (model == null) {
        // no instance for this ID so throw an error
        reject('Woops')
      } else {
        resolve(model)
      }
    })
  }
}
```

and I have a class looking something like:
```typescript
class SomeModel extends BaseModel<SomeModel> { ... }
```

But when I do `await SomeModel.findByIdOrFail<SomeModel>(2)`, I get an error: `Error: Model not initialized: "Model" needs to be added to a Sequelize instance before "findOne" can be called.`, so I'm a bit puzzled here.

My question is how do I go with extending base model class and implementing my own methods?

**Comment by RobinBuschmann** [comment]
@Pritilender Did you initialized `SomeModel` via `import {Sequelize} from 'sequelize-typescript'; const sequelize = new Sequelize({modelPaths: [__dirname + 'path/to/models-folder']})`or `sequelize.addModels([SomeModel])` before calling `findByIdOrFail`?

**Comment by Pritilender** [comment]
@RobinBuschmann Yes I did. I do it with `{modelPaths: [__dirname...}`.

**Comment by RobinBuschmann** [comment]
Ah OK, I think I've solved your problem. You need to call `findById` on `this` instead of `Model.findById`:

```typescript
const model: BaseModel<T> = await this.findById(id, options)
```

**Comment by Pritilender** [comment]
Thanks! Works like a charm :) I missed 
To sum up, the whole function with proper types (I had a bit of problem with working the types out and it was due to `<T>` behind function name which should be `<T extends BaseModel<T>>`) looks like this:

```typescript
  public static findByIdOrFail<T extends BaseModel<T>>(id: number, options?: IFindOptions): Promise<T> {
    return new Promise(async (resolve, reject) => {
      const model = await this.findById<T>(id, options)
      if (model == null) {
        // no instance for this ID so throw an error
        reject(/* whetever error you want to throw */)
      } else {
        resolve(model)
      }
    })
  }
```
