### ISSUE TITLE
Cannot find module 'sequelize/types/lib/hooks' or its corresponding type declarations.

### ISSUE THREAD

**Issue by hcancelik** [RobinBuschmann/sequelize-typescript#1198]
# Issue

Getting this error while building a project.

../node_modules/sequelize-typescript/dist/hooks/shared/hook-meta.d.ts(2,32): error TS2307: Cannot find module 'sequelize/types/lib/hooks' or its corresponding type declarations.

Not 100% sure but it seems like with this commit the files are no longer under `lib` directory.

https://github.com/sequelize/sequelize/commit/6b8fbb48d0d12f2c500f69ce79f7f54386c32b40

## Versions

- sequelize: 6.16.0
- sequelize-typescript: 2.1.2
- typescript: 4.5.4

## Issue type

- [x] bug report
- [ ] feature request

I apologize for removing the remaining comments from the issue template.

**Comment by smouchsiadis** [comment]
The same is happening to me. I am using nest and I followed [this guide](https://docs.nestjs.com/techniques/database#sequelize-integration)  

I also have these dependencies installed. 

```
npm install --save-dev @types/node @types/validator
npm install sequelize reflect-metadata sequelize-typescript
```  

Please look into it

**Comment by haozi23333** [comment]
sequelize rollback to 6.15.1
`npm install sequelize@6.15.1`

**Comment by agrofcsik** [comment]
+1
