### ISSUE TITLE
Rename uri config to url

### ISSUE THREAD

**Issue by bilby91** [RobinBuschmann/sequelize-typescript#121]
Today we fixed the problem that didn't allow the passing of options when using the uri constructor. Sequelize configuration file for running migrations used `url` instead of `uri` in the configuration file. This basically enforces users with this configuration to have something like this in their config file:

```
...
development: {
  uri: process.env.DATABASE_URL,
  url: process.env.DATABASE_URL,
}
...
```

My suggestion is to use the same convention that is used in Sequelize.

**Comment by RobinBuschmann** [comment]
@bilby91 Can you provide a link to the sequelize docs where this is defined? I couldn't find it. Thank you.

**Comment by bilby91** [comment]
@RobinBuschmann Here https://github.com/sequelize/cli#configuration-file
