### ISSUE TITLE
TypeError: Cannot read property 'createdAt' of undefined

### ISSUE THREAD

**Issue by TalissonJunior** [RobinBuschmann/sequelize-typescript#123]
Hello i´m getting this error "TypeError: Cannot read property 'createdAt' of undefined" do you have any idea what i can be?

## Sequelize initialize

```js
import {Sequelize} from 'sequelize-typescript';

const sequelize = new Sequelize(new Connection().Localhost());

/**
 * Connections to dabase
 */
export class Connection {
    
    private modelPaths = [__dirname + "/Models/Database"];

    Development(){
        return {
            name: "db_a28301_escolar",
            username: "a28301_escolar",
            password: "N@escr14",
            host:"mysql5013.smarterasp.net",
            dialect:"mysql",
            modelPaths: this.modelPaths
            
        }
    }

    Production(){
        return {
            name: "db_production",
            username: "user name",
            password: "password",
            host:"server/host",
            dialect:"mysql",
            modelPaths: this.modelPaths
        }
    }

    Localhost(){
        return {
            name: "db_restapi",
            username: "root",
            password: "root",
			host:"localhost",
			dialect: "mysql",
			modelPaths: this.modelPaths
        }
    } 
}
```
## Model class
```js

import {Table, Column, Model, PrimaryKey,AutoIncrement, DataType} from 'sequelize-typescript';

/**
 * reference docs: https://github.com/RobinBuschmann/sequelize-typescript
 * Model that reflect on databse table.
 */
@Table({ tableName: 'place'})
export class Place extends Model<Place> {

  @PrimaryKey
  @AutoIncrement
  @Column({ type: DataType.BIGINT})
  id: number 

  @Column({ type: DataType.STRING(45)})
  name: string

  @Column({ type: DataType.STRING(45)})
  description: string 
 
}

```

## ERROR LOG
![image](https://user-images.githubusercontent.com/18445152/29998290-7756c262-8ffd-11e7-8b62-5deff079e48d.png)

**Comment by RobinBuschmann** [comment]
Hey @TalissonJunior when does this error occur?

**Comment by TalissonJunior** [comment]
Well is not that easy to explain , but would help me If you clone the project from https://github.com/TalissonJunior/Nodejs-WebApi. And try to run It.

So , i'm trying to get a list of "places" from my local database , acessing "Localhost:3000/api/places", and to achieve that i have a controller.ts class that handles all the requests , then Business.ts class that handles the logic, and finally the repository.ts that will use the model to execute a query.

The error occurs when my Business class tries to use the repository passing my Model to get the places from my database.

I know that i'm not explaining It well , but i would really appreciate some help to figure out  this error.

I left a dump file If my database  inside database_scripts folder in case you clone the repository.

To test the project you just need to run "npm install" and "gulp serve".

**Comment by RobinBuschmann** [comment]
I've noticed several issues: You're creating an instance of `Model` in your BaseRepository. If you want to create instances of your models, you rather should call `new` on your specific models like `Place` (=> `new Place(...)`) than  on`Model` (`new Model()`) - `Model` is an abstract `class`.

Additionally this is not what you meant to do here. You want to use `find`, `findAll`, `create` and so on, which are static functions of the model class, not of the instances. So that
```typescript
const instance = new Place(...); 
instance.findAll(..) // <= not available here
// ... but
Place.findAll(...) // ... this works :)
```
Besides that, you are never passing the `Place` model class in `PlaceRepository` to the `BaseRepository`. I assume you want something like this:

```typescript
class BaseRepository {

    constructor(protected model: typeof Model) {}

    ListAll(){  
        return this.model.findAll({where:{id:{gt:0}}});
    }

}
```

```typescript
// PlaceRepository.ts
class PlaceRepository extends BaseRepository {

    constructor() {
      super(Place);
    }
}
```

**Comment by TalissonJunior** [comment]
hm, i did what you said, and things now start to make sense.

changes to BaseRepository:
https://github.com/TalissonJunior/Nodejs-WebApi/blob/master/src/Repository/Repositories/BaseRepository.ts

changes to PlaceRepository:
https://github.com/TalissonJunior/Nodejs-WebApi/blob/master/src/Repository/Repositories/PlaceRepository.ts

But now i get this error:

![image](https://user-images.githubusercontent.com/18445152/30002907-1e3b86fc-908b-11e7-87d2-556a41be90a6.png)

**Comment by RobinBuschmann** [comment]
This is cause you are compiling your ts files to `es5` while using sequelize 4+, which uses es6 classes. "es5 classes" cannot extend es6 classes. So you need to set `target` to `es6` in you tsconfig if you want to get it to work with sequelize 4+

**Comment by TalissonJunior** [comment]
i actually change ```target``` to ```es6``` before posting the error here and got the same error.

I just tried to change it again and didn´t work, i also tried to downgrade to sequelize 3v and target ```es5``` and ```es6``` but still nothing.

It´s a little bit strange because:

```js

//repository.ts
 ListAll(){           
        return  "hello from repository"; //this works fine :) so the problem might be some where in my model
 }

//repository.ts
constructor(protected model: typeof Model) {}

 ListAll(){           
        return  this.model.findAll({where:{id:{gt:0}}}); //this won´t working, and will trow that error of "Model cannot be invoked without 'new'"
}
```
}

so, what am i doing wrong? do i need to add an extra option to work with sequelize-typescript?

I´m kinda lost now

**Comment by RobinBuschmann** [comment]
When you push you're last changes I can have a look.

**Comment by TalissonJunior** [comment]
okay, i just did. thank you man

**Comment by TalissonJunior** [comment]
hey Robin, did you had any time to take a look?

**Comment by RobinBuschmann** [comment]
Sry, I missed that. But it works for me, after I set target to es6 (!). You didn't do that ;) So, set the target to es6 and it should work very well :)

**Comment by TalissonJunior** [comment]
No problem, you change tsconfig target to es6 and it works? what version of nodejs are you on? because din´t work for me, i´m currently on v8.4.0 of nodejs i don´t really know if that matters

**Comment by RobinBuschmann** [comment]
`8.2.1` - Can you add your compiled files to the repo? So that I can have a look?

**Comment by TalissonJunior** [comment]
Yea, sure i Just did. I'm using gulp to compile .ts files and my tsconfig file is set to target es6.

**Comment by TalissonJunior** [comment]
found something?

**Comment by RobinBuschmann** [comment]
Hey, you did not add the compiled files (dist/**/*.js) to your repo :(

**Comment by TalissonJunior** [comment]
Ohhhh,Sorry my bad o Will add them.

**Comment by TalissonJunior** [comment]
Ohh Sorry , my bad i will add them ***

**Comment by TalissonJunior** [comment]
@RobinBuschmann  okay i just add the dist folder that has the compiled files to the repo.

**Comment by TalissonJunior** [comment]
@RobinBuschmann  i notice something weird, when i don´t have any data at my table it doesn´t show the error, in fact it returns an empty array as expected

log
![image](https://user-images.githubusercontent.com/18445152/30275215-fcb6c454-96d6-11e7-9623-b6a661730f3c.png)

my database table
![image](https://user-images.githubusercontent.com/18445152/30275244-1974bb3c-96d7-11e7-827e-fad4ed0767a5.png)

And when i add some data to it, i get the error.
Log
![image](https://user-images.githubusercontent.com/18445152/30275693-974888f8-96d8-11e7-977c-3bd2d7cf05c1.png)

my database table.
![image](https://user-images.githubusercontent.com/18445152/30275717-aa1efd2c-96d8-11e7-8403-b2a8223bd587.png)

i´m starting to wonder if the problem is on my model.

my database table script can be located at:
https://github.com/TalissonJunior/Nodejs-WebApi/tree/master/database_script

**Comment by RobinBuschmann** [comment]
It seems so, that your `tsconfig.json` isn't used by your compile process. Your ts files are still compiled to `es5`. See here: https://github.com/TalissonJunior/Nodejs-WebApi/blob/master/dist/Models/Database/Place.js#L23 
In `es6` `Place` would be compiled to `class Place { ... }`  instead of a constructor function.

**Comment by TalissonJunior** [comment]
actually it is compiled to ```es6``` but i change 2 hours ago to make some test and forgot to commit.

As you can see:
https://github.com/TalissonJunior/Nodejs-WebApi/blob/master/dist/Models/Database/Place.js#L13

**Comment by RobinBuschmann** [comment]
The error comes from `Nodejs-WebApi/node_modules/class-transformer/TransformOperationExecutor.js:108:47)`.. so it is caused by the `class-transformer` package. As the error message says `Class constructor Place cannot be invoked without 'new'`, the `transform` function in `TransformOperationExecutor` tries to invoke `Place` without `new`: `subValue = value[valueKey]();`

**Comment by nullpixel** [comment]
I get this error too, really stumped. It occurs when calling any constructor on the model :(

**Comment by RobinBuschmann** [comment]
@nullpixel can you provide an example project? So that i can have a Look? :)

**Comment by nullpixel** [comment]
Uhh, is it okay if I make a private repo with a lot of half finished code? Or do you want me to try and reproduce it in a sample project

**Comment by RobinBuschmann** [comment]
Half finished code is okay ;)

**Comment by nullpixel** [comment]
I'll invite you, gimme a sec

**Comment by nullpixel** [comment]
Invited, https://github.com/nullpixel/SuperchargeBackend/invitations

**Comment by doovers** [comment]
Was this issue resolved? I'm having the same problem.

**Comment by RobinBuschmann** [comment]
@doovers For nullpixel it was a typo like here: https://github.com/RobinBuschmann/sequelize-typescript/issues/72#issuecomment-319155934 (See more about this issue here https://stackoverflow.com/a/23289441)

**Comment by doovers** [comment]
@RobinBuschmann Oops I should have mentioned I was referring to the `Class constructor MyModel cannot be invoked without 'new'` error. Any ideas on that? 

tsconfi.json: 

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**Comment by RobinBuschmann** [comment]
@doovers What is the compile target (es5, es6?)? Where is the error thrown (stack trace)?

**Comment by doovers** [comment]
es5:

```
TypeError: Class constructor Model cannot be invoked without 'new'
    at new Customer (/Users/cduve/Work/Contracker/Projects/contracker-api2/.build/src/models/customer.js:28:42)
    at Function.build (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize/lib/model.js:1932:12)
    at Function._target.(anonymous function) [as build] (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize-typescript/lib/models/BaseModel.js:35:41)
    at valueSets.map.values (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize/lib/model.js:1952:41)
    at Array.map (native)
    at Function.bulkBuild (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize/lib/model.js:1952:22)
    at Function._target.(anonymous function) [as bulkBuild] (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize-typescript/lib/models/BaseModel.js:35:41)
    at Query.handleSelectQuery (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize/lib/dialects/abstract/query.js:303:27)
    at Query.formatResults (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize/lib/dialects/mysql/query.js:116:21)
    at Utils.Promise.then.then.results (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/sequelize/lib/dialects/mysql/query.js:69:29)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/cduve/Work/Contracker/Projects/contracker-api2/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

es6:

```
~/my-project/src/models/address.ts (1,61): Cannot find module 'sequelize-typescript'.
~/my-project/src/models/customer.ts (1,46): Cannot find module 'sequelize-typescript'.
~/my-project/src/models/phone.ts (1,61): Cannot find module 'sequelize-typescript'.
src/handlers/customers.ts (4,27): Cannot find module 'sequelize-typescript'.
src/handlers/customers.ts (32,22): Property 'findById' does not exist on type 'typeof Customer'.
src/handlers/customers.ts (41,22): Property 'findAll' does not exist on type 'typeof Customer'.
src/handlers/customers.ts (53,22): Property 'findById' does not exist on type 'typeof Customer'.
src/handlers/customers.ts (70,20): Property 'create' does not exist on type 'typeof Customer'.
src/handlers/customers.ts (100,22): Property 'findById' does not exist on type 'typeof Customer'.
```

**Comment by doovers** [comment]
@RobinBuschmann Why is module sequelize-typescript not found using es6?

**Comment by RobinBuschmann** [comment]
@doovers The path looks strange to me `~/my-project/...`. Can provide your sequelize configuration as well?

**Comment by nullpixel** [comment]
@RobinBuschmann I could make a PR to make that error have more meaning, atm it’s thrown for a lot of things

**Comment by RobinBuschmann** [comment]
@nullpixel any help is appreciated :) What exact error message do you mean?

**Comment by doovers** [comment]
@RobinBuschmann Sorry I just removed the full path to make it easier to read!

```
import { Sequelize } from 'sequelize-typescript';

const db = new Sequelize({
  database: process.env.DB,
  dialect: process.env.DB_DIALECT,
  host: process.env.DB_HOST,
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  modelPaths: [__dirname + '/../models']
});
```

**Comment by RobinBuschmann** [comment]
@doovers Looks good to me. I need to have a look at the code to - do you have an example project?

**Comment by nullpixel** [comment]
@RobinBuschmann Talking about the createdAt error. It's confusing - it should be possible to figure out what makes it undefined, and throw a more helpful error at sequelize-typescript level

**Comment by RobinBuschmann** [comment]
@nullpixel Can you give me an example of when the createdAt error occurs? I'm unable to reproduce it

**Comment by doovers** [comment]
@RobinBuschmann Code sample below. If you need any more detail, let me know. Also curious how to associate the same model twice to the same parent... Note commented properties in customer and phone models... Try `npm run offline` with target es5 and es6

excerpt from package.json:
```
  "dependencies": {
    "mysql2": "^1.4.2",
    "reflect-metadata": "^0.1.10",
    "sequelize": "^4.13.5",
    "sequelize-typescript": "^0.5.0",
    "serverless-webpack": "^3.1.1"
  },
  "devDependencies": {
    "serverless-offline": "^3.16.0",
    "serverless-plugin-typescript": "^1.1.3"
  },
  "scripts": {
    "offline": "rm -rf .build && sls offline start --stage dev",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```
handler.ts
```import Address from '../models/address.model';
import Customer from '../models/customer.model';
import Phone from '../models/phone.model';
import { CustomerService } from '../services/customer.service';
import { Sequelize } from 'sequelize-typescript';

const db = new Sequelize({
  database: process.env.DB,
  dialect: process.env.DB_DIALECT,
  host: process.env.DB_HOST,
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  modelPaths: [__dirname + '/../models']
});

export function customer(event, context, callback) {
  context.callbackWaitsForEmptyEventLoop = false;

  // Parse request body for lambda (not required for local invocation)
  var requestBody;
  try {
    requestBody = JSON.parse(event.body);
  } catch (e) {
    requestBody = event.body;
  }

  db.authenticate()
    .then(() => {
      switch (event.httpMethod || event.method) {
        case 'GET':
          if ((event.pathParameters && event.pathParameters.id)) {
            Customer.findById(event.pathParameters.id)
              .then(customer => {
                callback(undefined, response(200, customer));
              })
              .catch(err => {
                console.error('Sequelize:', err);
                callback(undefined, response(500, { error: err.message }));
              });
          } else {
            Customer.findAll()
              .then(customers => {
                callback(undefined, response(200, customers));
              })
              .catch(err => {
                console.error('Sequelize:', err);
                callback(undefined, response(500, { error: err.message }));
              });
          }
          break;
        case 'DELETE':
          if ((event.pathParameters && event.pathParameters.id)) {
            Customer.findById(event.pathParameters.id)
              .then(customer => {
                customer.destroy({ force: true });
                callback(undefined, response(200, customer));
              })
              .catch(err => {
                console.error('Sequelize:', err);
                callback(undefined, response(500, { error: err.message }));
              });
          } else {
            console.error('No ID parameter supplied');
            callback(undefined, response(400, { error: 'No ID parameter supplied' }));
          }
          break;
        case 'POST':
          Customer.create(requestBody)
            .then(customer => {
              customer.set('phone', Phone.create(requestBody.phone));
              customer.set('fax', Phone.create(requestBody.fax));
              customer.set('address', Address.create(requestBody.address));
              callback(undefined, response(200, customer));
            })
            .catch(err => {
              console.error('Sequelize:', err);
              callback(undefined, response(500, { error: err.message }));
            });
          break;
        case 'PATCH':
          if ((event.pathParameters && event.pathParameters.id)) {
            Customer.findById(event.pathParameters.id)
              .then(customer => {
                customer.update(requestBody)
                callback(undefined, response(200, customer));
              })
              .catch(err => {
                console.error('Sequelize:', err);
                callback(undefined, response(500, { error: err.message }));
              });
          } else {
            console.error('No ID parameter supplied');
            callback(undefined, response(400, { error: 'No ID parameter supplied' }));
          }
          break;
        default:
          console.error(`Unsupported http method ${event.httpMethod}`);
          callback(undefined, response(501, { error: `Unsupported http method ${event.httpMethod}` }));
          break;
      }
    })
    .catch(err => {
      console.error('Unknown Error:', err);
      callback(undefined, response(500, { error: err.message }));
    });
}

function response(statusCode: number, body: any) {
  return {
    headers: { 'Content-Type': 'application/json' },
    statusCode: statusCode,
    body: JSON.stringify(body)
  }
}
```
customer.model.ts
```
import { Table, Column, Model, HasOne } from 'sequelize-typescript';
import Address from './address.model';
import Phone from './phone.model';

@Table({
  tableName: 'customer'
})
export default class Customer extends Model<Customer> {
  @Column company: string;
  @Column email: string;
  @Column firstName: string;
  @Column isActive: boolean;
  @Column lastName: string;
  @Column notes: string;
  @HasOne(() => Address, { foreignKey: 'customerId' }) address: Address;
  // @HasOne(() => Phone) fax: Phone;
  @HasOne(() => Phone) phone: Phone;
}
```
phone.model.ts
```
import { Table, Column, Model, BelongsTo, ForeignKey } from 'sequelize-typescript';
import Customer from './customer.model';

@Table({
  tableName: 'phone'
})
export default class Phone extends Model<Phone> {
  @Column number: string;
  @Column extension?: number;
  @Column type: PhoneType;
  @BelongsTo(() => Customer, 'phoneId') customer: Customer;
  // @BelongsTo(() => Customer, 'faxId') customer: Customer;
}

export enum PhoneType {
  Cell,
  Fax,
  Home,
  Work,
}
```
address.model.ts
```
import { Table, Column, Model, BelongsTo, ForeignKey } from 'sequelize-typescript';
import Customer from './customer.model';

@Table({
  tableName: 'address'
})
export default class Address extends Model<Address> {
  @Column street: String;
  @Column city: String;
  @Column country: String;
  @Column region: String;
  @Column postalCode: String;
  @BelongsTo(() => Customer, { foreignKey: 'customerId' }) customer: Customer;
}

```

**Comment by nullpixel** [comment]
It happens for seemingly unrelated things, such as incorrect casing on a file name

**Comment by RobinBuschmann** [comment]
hey @doovers, thanks, but do you have a repo instead? Would be much easier for me :)

**Comment by doovers** [comment]
@RobinBuschmann No worries! [aws-lambda-api-test](https://github.com/doovers/aws-lambda-api-test)

**Comment by RobinBuschmann** [comment]
@doovers As stated before you need to set target to `es6` when using es6 classes. Furthermore you need to tell the typescript compiler how to resolve the modules. So the following configuration works for me:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**Comment by doovers** [comment]
@RobinBuschmann Awesome! Thanks for figuring that out. My problem was I was missing the module & module resolution params in the tsconfig! Do you have any insight on the other problem of having the phone model as a child of customer twice? As a fax and phone property?

**Comment by RobinBuschmann** [comment]
@doovers This should help https://github.com/RobinBuschmann/sequelize-typescript#multiple-relations-of-same-models :)

**Comment by doovers** [comment]
@RobinBuschmann Thanks. I did actually read that but the problem I have is setting the belongs to in the phone model. 

```
@Table({
  tableName: 'phone'
})
export default class Phone extends Model<Phone> {
  @Column number: string;
  @Column extension?: number;
  @Column type: PhoneType;
  @BelongsTo(() => Customer, 'phoneId') customer: Customer;
  @BelongsTo(() => Customer, 'faxId') customer: Customer;
}
```

Ideally I would set it up like this but it gives me a duplicate identifier error as both phoneId and faxId have the same parent identifier customer. Is there any way to apply multiple foreign keys to the same identifier? Something like:

`@BelongsTo(() => Customer, ['phoneId', 'faxId']) customer: Customer;`

**Comment by doovers** [comment]
@RobinBuschmann Revisiting this after some time away from the project. Have you seen my previous comment?

**Comment by RobinBuschmann** [comment]
Hey @doovers, sry for the late response. I have completely overseen you last post. What about naming the property differently? Like `@BelongsTo(() => Customer, 'faxId') customerWithFax: Customer;`

**Comment by spacem** [comment]
One thing I find is if the configuration is not quite right or you pass the wrong type of data you get strange unhelpful messages. I just got this error and searching found this issue. In my case I was doing something silly, it is entirely my fault but it was not easy to track it down.

My issue was that I was calling model.bulkCreate([[null],[],[],[]]). Yes there was a bug in my code that generated that array of empty arrays.

Here is the error:
TypeError: Cannot read property 'createdAt' of undefined
    at Promise.try.then.then (C:\work\project1\node_modules\sequelize\lib\model.js:2370:37)
    at tryCatcher (C:\work\project1\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\work\project1\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\work\project1\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\work\project1\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\work\project1\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\work\project1\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\work\project1\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\work\project1\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by adamtLICOR** [comment]
@RobinBuschmann I know this is a closed Issue, but hopefully this might help someone else stumbling across this thread via Google (as I did).

I received this exact same error `TypeError: Cannot read property 'createdAt' of undefined` when I forgot to add a data model to the array passed to my `sequelize.addModels()` call.

This error is 100% me being careless, but the seemingly unrelated error message that @nullpixel mentioned did make it a bit difficult to track down!

**Comment by nullpixel** [comment]
@adamtLICOR: yeah, the error is terrible. makes these bugs really hard to track down!

**Comment by talkl** [comment]
> @RobinBuschmann I know this is a closed Issue, but hopefully this might help someone else stumbling across this thread via Google (as I did).
> 
> I received this exact same error `TypeError: Cannot read property 'createdAt' of undefined` when I forgot to add a data model to the array passed to my `sequelize.addModels()` call.
> 
> This error is 100% me being careless, but the seemingly unrelated error message that @nullpixel mentioned did make it a bit difficult to track down!

wow, that was the case for me also, thank you so much!!!
