### ISSUE TITLE
Sequelize Column type is always optional

### ISSUE THREAD

**Issue by NU11B0T** [RobinBuschmann/sequelize-typescript#1266]
# Issue
Sequelize Column type is always optional.

## Versions
- sequelize:"6.6.2"
- sequelize-typescript:"2.1.0"
- typescript:"4.3.2"

<img width="664" alt="image" src="https://user-images.githubusercontent.com/24702934/164992660-75f33a5e-0a12-4940-94be-6fc28bb2fbeb.png">

**Comment by ephys** [comment]
Sequelize 6.6 is more than a year old, see if the issue still occurs with Sequelize 6.19

**Comment by NU11B0T** [comment]
> Sequelize 6.6 is more than a year old, see if the issue still occurs with Sequelize 6.19

Thanks. That solved my issue.
