### ISSUE TITLE
Feature Request: Support Self joins

### ISSUE THREAD

**Issue by georgeedwards** [RobinBuschmann/sequelize-typescript#128]
I have the following definition:

    @Table
    export default class Group extends Model<Group> {
     
        @Column
        name: string;
            
        @ForeignKey(() => Group)
        @Column
        parentId: number;
    
        @HasOne(() => Group)
        parent: Group;
    
    // + associations with the members model
    
    }

However, I get the warning:

> MSSQL does not support self-referential constraints, we will remove it but we recommend restructuring your query

SQL Server does support self-joins, it even supports this directly as a foreign key to the table itself. What it does not support  is creating such keys with ON [UPDATE/DELETE] CASCADE. I think the default in sequelize is to specify ON DELETE CASCADE, - I believe sequelize-typescript has no way to override that? and it would clearly be helpful for this use case.

**Comment by RobinBuschmann** [comment]
You could give the following a try:
```typescript
@HasOne(() => Group, {
    constraints: false
  })
```

**Comment by RobinBuschmann** [comment]
@georgeedwards Same here: Did this help?
