### ISSUE TITLE
Time and Geo DataTypes

### ISSUE THREAD

**Issue by mtabaj** [RobinBuschmann/sequelize-typescript#129]
Maybe a newbe question, but I cant set or use Time Data Type nor Geo DataType.
The plus important for me now is a sample about how to set and use geo (point) in a Postgres db.
Thanks in advance

**Comment by RobinBuschmann** [comment]
Hey @mtabaj :)

See:
```typescript
  @Column(DataType.GEOMETRY('point'))
  geo: Date;

  @Column(DataType.TIME)
  time: Date;
  // or
  @Column({
    type: DataType.TIME
  })
  time: Date;
```

and for more information: http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

**Comment by OrenSchwartz** [comment]
> http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

DataType.GEOMETRY('point') and geo:Date ?

**Comment by RobinBuschmann** [comment]
@OrenSchwartz, oh, sry, no it’s not, just a typo. Actually I don’t know what js type it is. I would need to check it by myself

**Comment by RoelRoel** [comment]
@RobinBuschmann  When I use 

  @Column(DataType.TIME)
  time: Date;

It still in reality is a string with this format HH:mm:ss.
