### ISSUE TITLE
Executing text query

### ISSUE THREAD

**Issue by mtabaj** [RobinBuschmann/sequelize-typescript#130]
Robin, I have a model like
   
export class Department extends Model<DepartmentDTO> {

 @PrimaryKey
  @Column
  DepartmentID: number;

  @Column
  DepartmentName: string;

  @Column
  Available: boolean;

  @Column
  Description: string;
}

and I need to execute a string query (made from different options): 
"Select DepartmentID, Available from Department"

I can't found how I can do it within sequelize-typescript.
Thanks in advance
Marcos

**Comment by Pritilender** [comment]
@mtabaj it's same like it's in pure Sequelize ([see docs](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html)).
You just have to get hold of the `sequelize` object. You can get it from your database object or, if you have a model instance, as `this.sequelize`.

So if you want to add a custom find function, you can do something like this:
```typescript
// your db instance in some other file
const options = ...
export const db = new Sequelize(options)

// your model in some other file
export class Department extends Model {
  /** all your column defintions **/
  public static selectWithOptions(options: string) {
    return db.sequelize.query(`select ${options} from Department`)
  }
}

// usage
const deps = await Department.selectWithOptions("DepartmentID, Available")
```

By the way, if you **just** want to select **different attributes** included in `select`, you can pass `attributes` property to your `.find` method on the model. Here is [the docs](http://docs.sequelizejs.com/manual/tutorial/querying.html#attributes).
