### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature.

### ISSUE THREAD

**Issue by georgeedwards** [RobinBuschmann/sequelize-typescript#131]
I have the following model:

```
import {
  Table, Column, Model, IsEmail,
  Unique, AllowNull, BeforeCount
} from 'sequelize-typescript';

@Table
class User extends Model<User> {

  @IsEmail
  @Unique
  @Column
  email: string;

  @AllowNull(false)
  @Column
  password: string;

}
```

However, I get the typescript compiler error:

> $ tsc
src/services/users/users.service.ts(9,17): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "C:/Users/George/Source/Repos/backend/src/models/user.model"' has no compatible call signatures.
error Command failed with exit code 2.

What is wrong with my code? 

NB: I am using Typescript v**2.5.2**

**Comment by RobinBuschmann** [comment]
Hey @georgeedwards , what sequelize-typescript version are you using?

**Comment by georgeedwards** [comment]
@RobinBuschmann v0.5.0

**Comment by RobinBuschmann** [comment]
I cannot reproduce the issue. Can you provide an example repo?

**Comment by georgeedwards** [comment]
@RobinBuschmann  Oh - I think I have caught the bug. Can you confirm, how do you get access to a model instance with this library? I am trying to add Typescript support to the Feathers-cli and think sequelize-typescript is the best way to go, but I need to replicate this behaviour:

```
const Model = createModel(app);
```
where `createModel()` is required from this file:

```
module.exports = function (app) {
  const sequelizeClient =  new Sequelize(connectionString, {
    dialect: 'sqlite',
    logging: false,
    define: {
      freezeTableName: true
    }
  });

  const test = sequelizeClient.define('test', {
    text: {
      type: DataTypes.STRING,
      allowNull: false
    }
  });
  return test;
};
```

**Comment by RobinBuschmann** [comment]
@georgeedwards I think, I do not fully understand: You want to write your pure sequelize example (`module.exports = function (app) {  ...  return test; };`) with sequelize-typescript. Is this correct?

**Comment by georgeedwards** [comment]
Well, how can I get access to the model instance, i.e. the equivalent of what would have been created if I defined my models like:

```const test = sequelizeClient.define('test', {
    text: {
      type: DataTypes.STRING,
      allowNull: false
    }
  });
```

How would I access the equivalent of `test`?

**Comment by RobinBuschmann** [comment]
So you want to access your models via the sequelize instance? With `sequelize-typescript` you can do: `sequelize._.User` or `sequelize._['User']`

**Comment by georgeedwards** [comment]
Well, I want to access the model instance. That looks about right, but if I do:

```
  const User = app.get('sequelizeClient')._['User'];

  console.log(User)
```

I just get "User" printed to the log, not an object?

**Comment by RobinBuschmann** [comment]
Yes it prints the name of the class, but it holds the reference to the class.

**Comment by georgeedwards** [comment]
Aha - got it!! Thanks for your help, this is now working! Are you on any of the sequelize slack channels?

**Comment by RobinBuschmann** [comment]
You're welcome :) 

No, I'm not on any of these channels. Would you recommend it?

**Comment by georgeedwards** [comment]
They are pretty good. The reaosn I ask is that I have one more issue, where in my pure js (feathers generated) project, I have the user model like this:

```
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const users = sequelizeClient.define('users', {
  
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false
    },
  }, {
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  return users;
};
```
and I initialize sequelize like this:

```
  const sequelize = new Sequelize(connectionString, {
    dialect: 'postgres',
    logging: true,
    define: {
      freezeTableName: true
    }
  });
```
When I make a call to the feathers authentication API, the SQL generated is this `SELECT count(DISTINCT("users"."id")) AS "count" FROM "users" AS "users" WHERE "users"."email" = 'feathers@example.com'`.

However, in the version where I have converted to using TypeScript with your package, I am creating sequelize like this:

```
    const sequelize = new Sequelize({
        name: 'feathers-test',
        dialect: 'postgres',
        username: 'postgres',
        password: 'xxx',
        host: 'localhost',
        modelPaths: [__dirname + '/models'],
        define: {
            freezeTableName: true
        },
        logging: false
    });
```
where this is my model definition:

```
@Table
export default class User extends Model<User> {

  @IsEmail
  @AllowNull(false)
  @Unique
  @Column
  email: string;

  @AllowNull(false)
  @Column
  password: string;

}
```

However, the generated SQL for the same action is this: `SELECT count(DISTINCT(*)) AS "count" FROM "User" AS "User" WHERE "User"."email" = 'feathers@example.com';`

Which throws error: 

> syntax error at or near "*"

any idea why this might be different form using your package rather than vanilla sequelize?

**Comment by RobinBuschmann** [comment]
It is okay to create a new issue for that :)
