### ISSUE TITLE
@CreatedAt annotation prevents the update of the column

### ISSUE THREAD

**Issue by santiagodoldan** [RobinBuschmann/sequelize-typescript#132]
I'm not sure if it is an issue or if I'm not using the annotation correctly.

Saying that, here you have how I'm using it.

```
@Table({
  tableName: "users",
  underscored: true,
  timestamps: true,
})
export default class User extends Model<User> {
  ...

  @CreatedAt
  @Column({ field: "created_at", type: DataType.DATE })
  public createdAt: Date

  @UpdatedAt
  @Column({ field: "updated_at", type: DataType.DATE })
  public updatedAt: Date

  ...
}
```

Then, when trying to update the `createdAt` for test purposes, it doesn't work, I don't get an error, but the createdAt isn't updated.

Any ideas?

Thanks

**Comment by RobinBuschmann** [comment]
@santiagodoldan Do I understand you correctly: You tried to update the `createdAt` field manually? When using `@CreatedAt` and `@UpdatedAt` decorators, sequelize is setting these values automatically for you. And I assume that sequelize do not let you set these values manually.

**Comment by santiagodoldan** [comment]
Yeah, I need to update the `createdAt` value to test and edge case where the date needs to be older than 1 day ago, I understand the part that sequelize automatically fills both columns (created_at and updated_at), but IMO it could be a good idea to also be able to update them manually if needed. if you think that's ok, I can try to update both annotations and change how they work now.

**Comment by RobinBuschmann** [comment]
Hey @santiagodoldan, I think we shouldn't change as less of the behavior of sequelize as possible. So this should not be implemented in sequelize-typescript but in sequelize. Here is a discussion on this issue: https://github.com/sequelize/sequelize/issues/3759
