### ISSUE TITLE
Feature Request: Support Model Self-References

### ISSUE THREAD

**Issue by georgeedwards** [RobinBuschmann/sequelize-typescript#133]
I currently have a database schema, where a member can belong to a sub-group and a sub-group can belong to a group. I want to redesign the model to be more flexible (e.g. there could be a sub-sub-group etc.). So I wanted to associate a group with itself, so it could have a "parent" group.

Using NodeJS, sequelize and sequelize-typescript, I have the following definition:

```
@Table
export default class Group extends Model<Group> {
 
    @Column
    name: string;

    @ForeignKey(() => Group)
    @Column
    parentId: number;

    @HasOne(() => Group)
    parent: Group;
}
```

However, I get the error:

> MSSQL does not support self-referential constraints, we will remove it but we recommend restructuring your query

As I understand, SQL Server supports self-joins, it even supports this directly as a foreign key to the table itself. What it does not support is creating such keys with ON [UPDATE/DELETE] CASCADE. As it so happens, the default in sequelize is to specify ON DELETE CASCADE, and sequelize-typescript has no way to override that. Is that correct, and if so is it possible to add this as a feature?

**Comment by RobinBuschmann** [comment]
Hey, [this](https://github.com/RobinBuschmann/sequelize-typescript/issues/128#issuecomment-327013362) does not help?

**Comment by richpoteto** [comment]
Cool
