### ISSUE TITLE
Generating invalid postgres queries

### ISSUE THREAD

**Issue by georgeedwards** [RobinBuschmann/sequelize-typescript#135]
They are pretty good. The reaosn I ask is that I have one more issue, where in my pure js (feathers generated) project, I have the user model like this:
```
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const users = sequelizeClient.define('users', {
  
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false
    },
  }, {
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  return users;
};
```
and I initialize sequelize like this:
```
  const sequelize = new Sequelize(connectionString, {
    dialect: 'postgres',
    logging: true,
    define: {
      freezeTableName: true
    }
  });
```
When I make a call to the feathers authentication API, the SQL generated is this `SELECT count(DISTINCT("users"."id")) AS "count" FROM "users" AS "users" WHERE "users"."email" = 'feathers@example.com'`.
However, in the version where I have converted to using TypeScript with your package, I am creating sequelize like this:
```
    const sequelize = new Sequelize({
        name: 'feathers-test',
        dialect: 'postgres',
        username: 'postgres',
        password: 'xxx',
        host: 'localhost',
        modelPaths: [__dirname + '/models'],
        define: {
            freezeTableName: true
        },
        logging: false
    });
```
where this is my model definition:
```
@Table
export default class User extends Model<User> {

  @IsEmail
  @AllowNull(false)
  @Unique
  @Column
  email: string;

  @AllowNull(false)
  @Column
  password: string;

}
```
However, the generated SQL for the same action is this: `SELECT count(DISTINCT(*)) AS "count" FROM "User" AS "User" WHERE "User"."email" = 'feathers@example.com';`
Which throws error:

>syntax error at or near "*"

any idea why this might be different form using your package rather than vanilla sequelize?

**Comment by georgeedwards** [comment]
@RobinBuschmann moved from #131

**Comment by RobinBuschmann** [comment]
Did you try to set the beforeCount hook in the sequelize-typescript version as well?

**Comment by georgeedwards** [comment]
@RobinBuschmann yes, same result...

**Comment by georgeedwards** [comment]
@RobinBuschmann Any other thoughts?

**Comment by RobinBuschmann** [comment]
@georgeedwards I'm getting the same error with pure sequelize - strange. Which sequelize versions are you using?

**Comment by snewell92** [comment]
I encountered the `DISTINCT(*)` on mysql as well. I reverted to `0.4.0` and do not observe that behavior anymore.

**Comment by RobinBuschmann** [comment]
Strange, since I'm getting this error with pure sequelize, I assume, that this isn't a sequelize-typescript issue at all.

**Comment by snewell92** [comment]
@RobinBuschmann I'll look into reporting it to sequelize. Mind sharing the repro you have?

**Comment by RobinBuschmann** [comment]
Do we know on which sequelize version this happens? You said, you switched back to `sequelize-typescript@0.4.0` and it worked again? Are you changed the sequelize versions with that as well?

**Comment by snewell92** [comment]
Oh wait, I revert sequelize-typescript and feathers-sequelze. I kept sequelize at `4.8.4` This is the commit of my package.json:

```diff
-    "feathers-sequelize": "2.3.1",
+    "feathers-sequelize": "2.2.1",
-    "sequelize-typescript": "0.5.0",
+    "sequelize-typescript": "0.4.0",
```

So that's interesting, because 4.8.4 is the latest sequelize, and that's what I've ran all my tests against. It could be feathers-sequelize.... let me run a few more tests on my project.

**Comment by snewell92** [comment]
I just ran my tests with `0.5.0` and all are green.

I'm updating `feathers-sequelize` to see if I get the bug. In that case it will be feather's problem. Every test run has the latest sequelize `4.8.4` still

Woo! I repro'd the `DISTINCT(*)` with `feathers-sequelize: 2.3.1`

**Comment by snewell92** [comment]
But the problem is that I had a cli generated app with the same sequelize (i think - can dbl check...) that did not have this bug. :(

**Comment by snewell92** [comment]
@georgeedwards Try running your code with `feathers-sequelize: 2.2.1` - does it work with the latest `sequelize` and `sequelize-typescript` with feathers-sequelize pinned to the previous stable release?

That can be a viable work around. The problem now is how does the vanilla js cli generated differ from our typescript apps

**Comment by snewell92** [comment]
`feathers-sequelize: 2.3.0` is also good. No distinct * thing. So the observed behavior, as far as I can tell, is not in plain sequelize js apps, but can only be repro'd in feathers-sequelize: 2.3.1 :\

So I looked [at the commit from 2.3.0 -> 2.3.1](https://github.com/feathersjs/feathers-sequelize/commit/d98b10ee5c1186bb8773cd6b27256c3a8589c240#diff-1fdf421c05c1140f6d71444ea2b27638), maybe his has something to do with it?

That commit references and is related to [this code](https://github.com/sequelize/sequelize/blob/7e441a6a5ca44749acd3567b59b1d6ceb06ae64b/lib/model.js#L1780-L1782) But why would our ts apps hit an execution path that the js apps don't?

@RobinBuschmann any direction you can think of? I think I've exhausted all my sleuthing abilities, and I'm not sure if I found an answer or not... I don't understand how this commit changes behavior exactly, and I don't think the `include` option is messed with by sequelize-typescript... feathers adds it in, but the vanilla js app seems to handle that perfectly fine.

#confused

**Comment by RobinBuschmann** [comment]
I haven't used `feather-sequelize`yet. So I would say `feather-sequelize` is not the cause of the error - I think, sequelize is. I will have a look ..and will try with different sequelize version.

**Comment by georgeedwards** [comment]
@snewell92 Yes, using:
```
"sequelize-typescript": "0.5.0",
"sequelize": "4.9.0",
"feathers-sequelize": "2.2.1",
```
works as expected...

**Comment by RobinBuschmann** [comment]
The find option `distinct: true` does not seem to work in general.

https://github.com/sequelize/sequelize/issues/6953
https://github.com/sequelize/sequelize/issues/2713

**Comment by RobinBuschmann** [comment]
@georgeedwards Is this working now for you?

**Comment by RobinBuschmann** [comment]
Issue is closed due to no response

**Comment by doovers** [comment]
@RobinBuschmann Same problem here
