### ISSUE TITLE
One-to-many association issues with postgres

### ISSUE THREAD

**Issue by georgeedwards** [RobinBuschmann/sequelize-typescript#144]
I have the following definitions, but when running with postgres I get the error:

> TypeError: Cannot read property 'jobId' of undefined

```
@Table
export class Job extends Model<Job> {

    @Column
    name: string;

    @HasMany(() => Result)
    results: Result[];
}

@Table
export class Result extends Model<Result> {
    @Column
    value: string;

    @Column
    downTime: string

    @ForeignKey(() => Job)
    @Column
    jobId: number;

    @BelongsTo(() => Job)
    job: Job;
}

```

I have followed the docs and cannot see wh this should be problematic?

**Comment by RobinBuschmann** [comment]
Hey @georgeedwards, thanks for reporting. When exactly does this happen? On loading the models or requesting data or ..?

**Comment by georgeedwards** [comment]
@RobinBuschmann On loading the models

**Comment by RobinBuschmann** [comment]
I cannot reproduce it. So it works very well for me. Can you provide a full example (a repo)?

**Comment by georgeedwards** [comment]
@RobinBuschmann Sure [here](https://github.com/georgeedwards/sequelize-ts-issue) you probably will want to set up the db creds in `src/sequelize.ts`, then yarn install and then `node src`. 

For me I then get:

```
the jobs service.
You are using the default filter for the results service.
C:\Users\George\Source\Repos\testRepo\node_modules\sequelize\lib\associations\has-many.js:75
    if (this.target.rawAttributes[this.foreignKey]) {
                                 ^

TypeError: Cannot read property 'jobId' of undefined
    at new HasMany (C:\Users\George\Source\Repos\testRepo\node_modules\sequelize\lib\associations\has-many.js:75:34)
    at Function.hasMany (C:\Users\George\Source\Repos\testRepo\node_modules\sequelize\lib\associations\mixin.js:26:25)
    at Function._target.(anonymous function) [as hasMany] (C:\Users\George\Source\Repos\testRepo\node_modules\sequelize-typescript\lib\models\BaseModel.js:35:41)
    at Object.processAssociation (C:\Users\George\Source\Repos\testRepo\node_modules\sequelize-typescript\lib\services\association.js:183:32)
```

**Comment by RobinBuschmann** [comment]
@georgeedwards There is a typo in your code
`import Result from './result';` => `import Result from './Result';` https://github.com/georgeedwards/sequelize-ts-issue/blob/master/src/models/Job.ts#L2

Here is an explanation: https://github.com/RobinBuschmann/sequelize-typescript/issues/72#issuecomment-319155934

**Comment by georgeedwards** [comment]
Aha! You've got it - thanks 👍 

Slightly unhelpful error message, but none the less - user error. No bug.
