### ISSUE TITLE
Support Alias?

### ISSUE THREAD

**Issue by georgeedwards** [RobinBuschmann/sequelize-typescript#145]
I can;t see any references in the docs (appologies if I have missed them), is there a way of doing something like:

    Contact.hasMany(PhoneNumber, {as: 'phoneNumbers'});

I can't see how you would alias an association?

**Comment by RobinBuschmann** [comment]
The alias is determined by the name of the property. So when defining a relation like `@HasMany(() => Person) persons: Person[]`, the property name `persons` will internally be set as `alias` in sequelize.

**Comment by georgeedwards** [comment]
Great, is that mentioned in the docs anywhere?

**Comment by RobinBuschmann** [comment]
No it is not
