### ISSUE TITLE
ORDER by a function

### ISSUE THREAD

**Issue by schmod** [RobinBuschmann/sequelize-typescript#146]
Currently, the typings do not us to construct `ORDER BY fn(col)` queries.

From the [sequelize docs](http://docs.sequelizejs.com/manual/tutorial/querying.html#ordering):

```ts
Subtask.findAll({
  order: [
    // Will order by max(age)
    sequelize.fn('max', sequelize.col('age')),
   ]
});
```

However, the current typings do not allow a `fn` to exist in the `order` array:

```ts
order?: string | col | literal | Array<string | number | typeof Model | {
        model: typeof Model;
        as?: string;
    }> | Array<string | col | literal | Array<string | number | typeof Model | {
        model: typeof Model;
        as?: string;
    }>>;
```

**Comment by RobinBuschmann** [comment]
Hey @schmod thanks for reporting. I will add them to the typings of `sequelize-typescript`. 

But they also seem to be missing on the typings of `sequelize` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L3249)

**Comment by schmod** [comment]
Ah, bummer.  I suppose we should PR that repository as well.  

Do you want me to make the changes, or do you want to handle this?

**Comment by RobinBuschmann** [comment]
If you like to.. :)

**Comment by schmod** [comment]
Thanks! Sorry for not getting around to submitting a PR.
