### ISSUE TITLE
I think there's a type definition problem in Model.d.ts

### ISSUE THREAD

**Issue by BruceHem** [RobinBuschmann/sequelize-typescript#149]
<img width="698" alt="screen shot 2017-09-27 at 8 36 54 pm" src="https://user-images.githubusercontent.com/15667259/30916449-a76b1f0a-a3c3-11e7-847f-547bc404c68c.png">

There's a sequelize property on this, but I have to tell it as any.

**Comment by RobinBuschmann** [comment]
Ah ok. Then we should add it to `Model.d.ts` :)

**Comment by BruceHem** [comment]
ok thanks

**Comment by RobinBuschmann** [comment]
It's better to let the issue open until it's done :)

**Comment by BruceHem** [comment]
BTW: to make the food? 😂

<img width="533" alt="screen shot 2017-09-30 at 8 34 33 pm" src="https://user-images.githubusercontent.com/15667259/31046203-e441f8ec-a61e-11e7-8aa2-e7867563f649.png">

**Comment by RobinBuschmann** [comment]
Ha, meaningful comment 😂
