### ISSUE TITLE
How to get underlying Sequelize / Config ?

### ISSUE THREAD

**Issue by vikrantpogula** [RobinBuschmann/sequelize-typescript#15]
Hey !

Great module.. been looking for this from a while.  Just wondering how to get underlying sequelize module, or how to configure additional config like `pool` etc.

**Comment by vikrantpogula** [comment]
Never mind i figured it out. ! very well written library this one. 👍

**Comment by RobinBuschmann** [comment]
@vikrantpogula thank you very much :)
