### ISSUE TITLE
Is mysql2 the only one that works with sequelize-typescript?

### ISSUE THREAD

**Issue by BruceHem** [RobinBuschmann/sequelize-typescript#151]
I tried with "mysql": "^2.14.1" and I got this Error: Please install mysql2 package manually.

Is this on purpose?

**Comment by snewell92** [comment]
I believe it is, but idk why, although @RobinBuschmann would likely know.

Does plain sequelize work with that mysql package?

**Comment by BruceHem** [comment]
@snewell92 yes plain sequelize works. 
I'm asking this because I think I have problem in production with mysql2 on another project

**Comment by RobinBuschmann** [comment]
I think `mysql` only works with older sequelize versions (<4) ... so the latest sequelize version requires `mysql2` as the docs say:   http://docs.sequelizejs.com/manual/installation/getting-started

So it has nothing to do with sequelize-typescript

**Comment by BruceHem** [comment]
I just confirmed it, `sequelize` v4 works only with `mysql2`.
