### ISSUE TITLE
Q: Does it validate types at runtime?

### ISSUE THREAD

**Issue by dragosbulugean** [RobinBuschmann/sequelize-typescript#152]
For example I have declared a date field.
Will validate() detect if the runtime type is wrong if I do something like Object.assign() from an object received from a request that has a string instead of a date?
I am using Joi for this currently, but I was wondering if I can skip it for the annotations this provides.
Awesome project, I will contribute if the occasion arises.
Thank you!

**Comment by RobinBuschmann** [comment]
Hey @dragosbulugean, validation requirements need to be set explicitly like `@IsDate` or `@Column({validate:{isDate:true}})`

**Comment by RobinBuschmann** [comment]
@dragosbulugean Does this work for you? If you're happy with my answer feel free to close this issue :)
