### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by csreid** [RobinBuschmann/sequelize-typescript#153]
I got the following output while trying to spin up a small demo of `sequelize-typescript`:

`sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13`

**Comment by BruceHem** [comment]
Yeah that’s the latest sequelize

**Comment by RobinBuschmann** [comment]
@csreid Does this happen while using operators like so `$like`, `$gt`, `$lt`, ...  or do you get this warning without using any operators in your query?

**Comment by mctep** [comment]
Deprecation happens by default.

See more: https://github.com/sequelize/sequelize/issues/8417#issuecomment-334056048

To disable this warning add `operatorsAliases: false` to your `Sequelize` config:

```diff
import { Sequelize } from 'sequelize-typescript';

const sequelize = new Sequelize({
+	operatorsAliases: false,
	host: MYSQL_HOST,
 	port: MYSQL_PORT,
	name: MYSQL_DATABASE,
	username: MYSQL_USER,
	// other options
- });
+ } as any);
```
@RobinBuschmann looks like there is no `operatorsAliases` in ` SequelizeConfig | ISequelizeValidationOnlyConfig` typings.

**Comment by BruceHem** [comment]
Yes, we need somebody to add typings for the operators.

**Comment by mctep** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20284

**Comment by RobinBuschmann** [comment]
Hey @mctep, what do you mean "by default"?

**Comment by mctep** [comment]
I mean that this warning happens always (by default 😄) despite string operators usage.
I think this issue should be closed because it is `sequelize` issue.

**Comment by csreid** [comment]
To be clear, I'm not actually using any operators. The following script gives me the warning:

```ts
import { Sequelize } from 'sequelize-typescript';

let seq = new Sequelize('postgres://localhost:5432/my-database');
```

**Comment by RobinBuschmann** [comment]
@csreid Ah ok, thanks for clearing this. On which sequelize version does this happen?

@mctep So this happens with sequelize only as well?

**Comment by csreid** [comment]
Sequelize is at `4.13.3`.


Whole `package.json` is here:

```json
{
  "name": "sequelize-typescript-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "reflect-metadata": "^0.1.10",
    "sequelize": "4.13.3",
    "sequelize-typescript": "0.5.0"
  } 
}   
```

**Comment by mctep** [comment]
@RobinBuschmann Yes. In `sequelize > 4.12.0`

**Comment by RobinBuschmann** [comment]
@mctep Thanks, then you're absolutely right: This is a sequelize issue.

**Comment by jazzfog** [comment]
I don't get it...
I am new to `sequelize-typescript`, just discovered it, installed and trying it out.
Right after connection attempt I get the error (as reported above). 
So it just doesn't work. Completely.
Looks like since October, so three months now.
I mean, I appreciate all the hard work that maintainer of this repository has done but it looks bit frustrating that package could stay broken for so long... I mean, I kinda understand that real problem could be in `sequelize`, not in `sequelize-typescript` but why nobody contacted `sequelize`'s maintainers or someone about it then...
Did I get something wrong?

**Comment by RobinBuschmann** [comment]
Hey @jazzfog thanks for reporting. Can you address your issue here: https://github.com/sequelize/sequelize/issues/8417 . Maybe you already find a solution in this issues comments :)
