### ISSUE TITLE
Using separate option

### ISSUE THREAD

**Issue by oscarcalvo** [RobinBuschmann/sequelize-typescript#155]
Hi, I have queries with several includes and has many relations of rows where at the end I am getting cartesian product and is slow. Looking for, I see that with Sequelize I can use separate:true in includes (https://github.com/sequelize/sequelize/pull/4177), but dont see it in your package. How can I use it?

Thanks

**Comment by RobinBuschmann** [comment]
Hey @oscarcalvo thanks for reporting this. `separate: boolean` needs to be added to the `IIncludeOptions`.

For now you can make the compiler happy with this:
```typescript
{
  include: [{
    ['separate' as any]: true,
  }]
}
```

(This seems to be missing on the sequelize typings as well)

**Comment by oscarcalvo** [comment]
ok thanks you

**Comment by OrenSchwartz** [comment]
why is this closed ? please re-open.
