### ISSUE TITLE
Consider removing createdAt, updatedAt, deletedAt from type definition file.

### ISSUE THREAD

**Issue by BruceHem** [RobinBuschmann/sequelize-typescript#158]
@RobinBuschmann I think we should remove them, and let users define themselves. Because let say I override the timestamps behaviour in the global define config to be created_date, updated_date, or deleted_date. In this case I would have these "createdAt, updatedAt, deletedAt" giving intellisense when they are not there. What do you think?

**Comment by RobinBuschmann** [comment]
@BruceHem I thought about it too. But someone how'd like to use `@Table({timestamps: true})` only, wouldn't get autocompletion at all anymore.

**Comment by ShaharHD** [comment]
An idea ... what if in addition to having `extends Model<classname>` it will be more like: `extends Model<classname>, TimeStampAttributes` - is it a possible solution?

**Comment by RobinBuschmann** [comment]
An interface would be an option instead. @ShaharHD Multiple inheritance is not supported :)

**Comment by ShaharHD** [comment]
I've meant `TimeStampAttributes` to be an interface

**Comment by BruceHem** [comment]
Then we would get something like:

```ts
class User extends Model<User> implements TimeStampAttributes {

}
```
a bit verbose IMHO

**Comment by RobinBuschmann** [comment]
`createdAt`, `updatedAt`, `deletedAt` are marked as optional in the `Model.d.ts`. Therefore I suggest to use `"strictNullChecks": true,` in `tsconfig.json`, so that people using `@Table({timestamps: true})` do have autocomplete and others using there own property names are aware of the case that `createdAt` and so on are probably undefined. :)

**Comment by BruceHem** [comment]
@RobinBuschmann Nice. Looking forward for 1.0
