### ISSUE TITLE
Sequelize Migrations

### ISSUE THREAD

**Issue by snewell92** [RobinBuschmann/sequelize-typescript#159]
This is probably beyond the scope of this package, but I'm interested in how other users approach and handle migrations. Since Sequelize has a CLI that can generate migration files, do y'all use that and copy the javascript file into your code bases?

Is there a way we could create a sequelize-typescript migration generator? (I don't really care about having the full sequelize cli, just migrations). Is there a way we could leverage the existing sequelize cli and just move a file over or rename it (bash scripting?) and then fix up the file (if doing code-first, we still have to edit the up/down functions anyways).

Thoughts?

**Comment by RobinBuschmann** [comment]
Hey @snewell92 currently I'm using the package `db-migrate` for my migrations.

I didn't use sequelize migrations yet. So I need to have a look into it before I can give any answers. I will give sequelize migrations a try...and come back with my thoughts about it.

**Comment by snewell92** [comment]
I was reading the `sequelize/cli` docs - apparently v4 support is still in progress - so I'm not sure if the v4 model definitions are even compatible with the cli.

If you use `db-migrate`, I'll probably end up doing that, it seems a lot simpler than sequelize. My only desire is to have the datatypes I use in my models' annotations to match what I use in the migrations.

I'm coming from a Code-First Entity Framework (.NET) mindset though, so maybe I need to change the way I think about migrations. Currently the way I want to be able to do migrations, is to make a code change in a typescript model, and then make a corresponding migration file that will do that change for me, hence why I'd like the datatypes to be the same, so that the model and the migrations 'speak the same language' - so to speak.

**Comment by RobinBuschmann** [comment]
Any ideas on how this could be achieved? I'm thinking of some kind of a snapshot file of the current state of the model, which is created beside each migration. When creating further migrations this snapshot will be used to compare the old state (from the snapshot file) with the current state of the model. Sounds like a very interesting project to me... but very complex as well 🙈

**Comment by bilby91** [comment]
Hey,

We have been using `sequelize-cli` for almose 3 month now. Running with v4 sequelize code without any issue. We come from a rails background and the similar approach to handler migrations is really nice. 

Are you experiencing any particular issue @snewell92  ?

**Comment by snewell92** [comment]
Neat! I was trying to use typescript files, so in my `src` dir a `migrations` folder with typescript files, and I wanted to compile them down to js files that sequelize could use. I opted to just have migrations in javascript.

**Comment by snewell92** [comment]
@RobinBuschmann It does sound interesting, but yes - complex. I'm going to drop it, as your solution, and @bilby91 's solution should work fine for most people. `sequelize-cli` has an open issue about typescript support I believe, and `db-migrate` can have plugins written to allow authoring of typescript migration files.

**Comment by leogoesger** [comment]
@RobinBuschmann could you provide an example of how you are using `db-migrate`? thanks

**Comment by RobinBuschmann** [comment]
@leogoesger Sure. Here we go https://github.com/ElisaBaum/maple-backend/tree/develop/migrations

https://github.com/ElisaBaum/maple-backend/blob/develop/package.json#L7

**Comment by dilizarov** [comment]
@snewell92 I really resonate with this post. What did you end up landing on? Do you happen to have an example of how you're managing migrations while using `sequelize-typescript`?

@bilby91 I also come from a rails background. Do you maybe have an example as well of your `sequelize-cli`? I'm on version 5 right now, but I imagine it might be similar?
