### ISSUE TITLE
Options is missing operatorsAliases

### ISSUE THREAD

**Issue by devuxer** [RobinBuschmann/sequelize-typescript#167]
Please add `operatorsAliases` to the Sequelize `Options` interface.

The type should `object | boolean`

This is needed to be able the follow the advice in [this issue](https://github.com/sequelize/sequelize/issues/8417) re: string-based operators.

**Comment by RobinBuschmann** [comment]
@devuxer thanks for reporting. This will be fixed with #166

**Comment by RobinBuschmann** [comment]
Already fixed and released

**Comment by devuxer** [comment]
Thanks, Robin. This finally allowed me to eliminate that warning about string-based operators.
