### ISSUE TITLE
Transaction type exported

### ISSUE THREAD

**Issue by ShaharHD** [RobinBuschmann/sequelize-typescript#168]
When using 
```
sequelize.transaction( (t) => { 
  somemethod(t)
})

someMethod(t?) {
   someModel.create<someModel>({}, { transaction: t }
}
``` 
the type of `t` is different than the one from Sequelize (which is fine IMHO) but the issue is that with TypeScript if I have methods which receives the Transaction for internal usage I can't specify the parameter type as it is not exposed by `sequelize-typescript` and I have to leave `t` in method as either `any` or typeless.

Before using `sequelize-typescript` I was using `import { Transaction } from 'sequelize'` for the return type of `sequelize.transaction`

Could it be the type definitions are out of date? which is what causing the issue?

**Comment by RobinBuschmann** [comment]
`import {Transaction} from "sequelize";` should be working for that. I cannot reproduce this issue. Can you provide an example repo? Thank you

**Comment by ShaharHD** [comment]
I think I might have found what causing the issue on my end:
Can please you try to include `@types/sequelize` in your test?

I have to use it - as without it my `tsc` just goes to 100% and doesn't finish the build it seems...

**Comment by RobinBuschmann** [comment]
`@types/sequelize` is installed automatically cause it is a dependency of `sequelize-typescript`

**Comment by RobinBuschmann** [comment]
@ShaharHD Do you still have issues with this? Or can this be closed?

**Comment by RobinBuschmann** [comment]
closing issue due to no response

**Comment by saachinsiva** [comment]
Sorry to bring this dead thread live again, but I am facing the same issue. When I do `import {Transaction} from "sequelize";` all I get is Cannot find module 'sequelize'.

do I need to install @types/sequelize as my own dependency?

Thanks
