### ISSUE TITLE
Sequelize class missing Op

### ISSUE THREAD

**Issue by ShaharHD** [RobinBuschmann/sequelize-typescript#169]
In Sequelize v4 Op `Sequelize.Op` became a recommended usage for building queries [operators-security](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-security)

Could it be the type definitions are out of date? which is why it's missing `Op`?

**Comment by RobinBuschmann** [comment]
@ShaharHD thanks for reporting. This will be fixed with #166

**Comment by RobinBuschmann** [comment]
Is fixed with `sequelize-typescript@0.6.0`
