### ISSUE TITLE
DataType.GEOMETRY not supported?

### ISSUE THREAD

**Issue by ShaharHD** [RobinBuschmann/sequelize-typescript#170]
Creating a model with `@Column(DataType.GEOMETRY('point'))` such as:

```
  @Column(DataType.GEOMETRY('point'))
  public geo_location: {
    type: string;
    coordinates: [number, number];
  };
```
or

```
  @Column(DataType.GEOMETRY('point'))
  public geo_location: any
```

Upon trying to create a new model record with the specific field:
```
      geo_location: {
        type: 'point',
        coordinates: [latitude, longitude],
      },
```

is always generating the following error:
`column "geo_location" is of type point but expression is of type geometry`

The field type is `point` (as it should be) ... but for some reason `sequelize-typescript` seems to not propagate correctly the `DataTypeGeometry` parameters (`type: string` and `srid?: number`)

I'm following the instructions from http://docs.sequelizejs.com/variable/index.html

**Comment by RobinBuschmann** [comment]
@ShaharHD Which sequelize version are you using?

With the following setup it is working well for me:

```typescript
@Table
export class Location extends Model<Location> {
    @Column(DataType.GEOMETRY('POINT'))
    point: any;
}
```

```typescript
Location.create<Location>({
            point: {
                type: 'Point',
                coordinates: [39.807222, -76.984722]
            }
        })
```

**Comment by ShaharHD** [comment]
All latest versions.

```
    "sequelize": "^4.14.0",
    "sequelize-typescript": "^0.5.0",
```

I also have the following (if it makes any difference)
```
    "@types/sequelize": "^4.0.76",
    "sequelize-noupdate-attributes": "^1.0.0",
```

The other difference might be that I'm using Postgres and you're testing with a different DB?
I'll create a test project repo - and will update.

**Comment by RobinBuschmann** [comment]
I've tested it on mysql and postgres. On both it is working. Can you provide a stack trace to your error as well?

**Comment by RobinBuschmann** [comment]
@ShaharHD Same here? Did you get it to work? Can this issue be closed?

**Comment by micksatana** [comment]
I confirmed @RobinBuschmann solution is working. The key is you need to use capital.
```
DataType.GEOMETRY('POINT')
```
Not
```
DataType.GEOMETRY('point')
```
The latter will cause error.

However, if the DataType.GEOMETRY() suppose to take case-insensitive. I think this considered a bug.

**Comment by RobinBuschmann** [comment]
@micksatana thanks

**Comment by bel-mont** [comment]
This appears to be broken in the later versions of MySQL. Using the following packages:
```
"@types/sequelize": "^4.28.9",
"sequelize": "^5.22.3",
"sequelize-typescript": "^1.1.0",
```

And the following property as specified above
```
@Column(DataType.GEOMETRY('POINT'))
point: any;

```

And assigning it a value like
```
entity.point = {
    type: 'Point',
    coordinates: [row.longitude, row.latitude],
};
```
Will result in
`
FUNCTION GeomFromText does not exist
`
This is because MySQL deprecated and later on got rid of that function. It should be using ST_GeomFromText now.

**Comment by Ibraheem-adeyemo** [comment]
Please am also getting this error and have looked for the solution everywhere and have not gotten any working solution. I created my table using

location: {
        type:DataTypes.GEOMETRY('POINT', 4326),
        allowNull:false
    }

an I now query the table using this 

 const nearestLocation = await Address.findAll({
            where: {
                location:[[sequelize.fn('ST_Distance_Sphere', sequelize.literal('geolocation'), location),'distance']],
                order: 'distance', 
                limit: 4
            }
        })

this is the location

const location = sequelize.literal(`ST_GeomFromText('POINT(${long} ${lat})', 4326)`);

but this is returning error

Error: GeometryType undefined not supported. Please I really need help to get this solved
