### ISSUE TITLE
 Property getFoo does not exist on type Bar

### ISSUE THREAD

**Issue by samanmohamadi** [RobinBuschmann/sequelize-typescript#175]
```
@Table()
class Bar extends Model<Bar> {
    @ForeignKey(() => Foo)
    @Column
    fooId: number;

    @BelongsTo(() => Foo)
    foo: Foo;
}
```
when I call `getFoo` on `Bar` instance I get this error:
**Property getFoo does not exist on type Bar**

how can I prevent this?

**Comment by RobinBuschmann** [comment]
Since typescript cannot know of these dynamically generated methods, `sequelize-typescript` provides additional methods like `$get`, `$add` and so on you need to do it like this: `instance.$get('foo')`

**Comment by samanmohamadi** [comment]
Thanks

**Comment by samanmohamadi** [comment]
How could I achieve this: `bar.getFoo(where{....});`

**Comment by RobinBuschmann** [comment]
As a second parameter you can add your options. Unfortunately they are only marked as `any`. But it should work: `instance.$get('foo', {where: {}})`;
