### ISSUE TITLE
Glob based model paths

### ISSUE THREAD

**Issue by onebesky** [RobinBuschmann/sequelize-typescript#177]
Some projects keep models within modules right next to controllers. Current implementation of sequelize-typescript allows to specify only path to folder with models.

What do you think about adding support for the following configuration:
```
modelPaths: [__dirname + '/**/*.model.ts']
```

**Comment by RobinBuschmann** [comment]
Sounds good. I think we should implement this next.

**Comment by RobinBuschmann** [comment]
#24

**Comment by victorivens05** [comment]
Hey guys. 
I made some simple changes and was about to make sure they worked, before I opened a PR, when I found this discussion. 
So, what will be done? Add the include option in the sequelize constructor or implement glob in the `modelPaths`?

**Comment by RobinBuschmann** [comment]
Using `modelPaths` for an additional globing functionality should be fine. So that using a path to a directory with `modelPaths` should continue working as well. 

@victorivens05 What is you suggestion?

**Comment by victorivens05** [comment]
@RobinBuschmann in my tests I managed to use glob and folder together.
Using glob, if you pass a folder: `c:\project\models` it doesn't return anything, but there's a method called `glob.hasMagic` with which we can detect if the user passed a folder or a glob.
If the user passed a folder, we concatenate with `\*` and get every file in the folder.

It should work, unless some user has a folder called `!(folder)`, `@(folder)` or `[folder]`

The problem right now is that I work alone, so I don't have much experience working with teams. The tests seems to not be working and I don't know if I should create a branch and submit a PR.

**Comment by RobinBuschmann** [comment]
@victorivens05 Sounds good! Don't worry. Create your PR and we will have a look :) If there is something that need to be adjusted we can discuss that in the context of your PR. If you have any questions don't hesitate to ask.

**Comment by victorivens05** [comment]
I just submitted the PR. I already think some stuff should be done differently. I didn't create a test, I'd like to create one, but I would need some help to figure out where and how it should be done.

**Comment by snewell92** [comment]
Worth mentioning from [this other issue thread](https://github.com/RobinBuschmann/sequelize-typescript/issues/24#issuecomment-308157677)

> I think it would be much clearer to use only paths for modelPaths option and no globs. Using globs in include, exclude with an absolute path should work.

It might be a good idea to leave `modelPaths` alone, and then add `include` and `exclude` options that do exactly what your PR is doing for `modelPaths`.

I'll defer to @RobinBuschmann - it will be super nice to have globs either which way imo. :D

**Comment by RobinBuschmann** [comment]
@snewell92 ha, maybe I'm right with that one. We could use an option called `models` for passing either an array of paths, of globs or of model references to simplify and mark `modelPaths` as deprecated... or `include` as initially intended. 

@victorivens05

**Comment by victorivens05** [comment]
In my opinion, a breaking change should only be made when there is a great benefit attached to it or there is no other way to solve a problem.

The way the PR was submitted, nothing will have to change and there will be a new (altough small) feature.

**Comment by victorivens05** [comment]
I think this PR #181 closes this issue.

**Comment by RobinBuschmann** [comment]
Closed due to #181
