### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature

### ISSUE THREAD

**Issue by notedit** [RobinBuschmann/sequelize-typescript#180]
typescript  2.5.3  

```
@Table({
    tableName:'class_room',
    indexes: [
        {
            unique:true,
            fields:['app_key','room_id']
        }
    ]
})
class ClassRoom extends Model<ClassRoom> 

// some other code 

```

file: 'file:///Users/xiang/Work/xiaobankets/src/models.ts'
severity: 'Error'
message: 'Unable to resolve signature of class decorator when called as an expression.
  Cannot invoke an expression whose type lacks a call signature.'
at: '28,1'
source: 'ts'

**Comment by RobinBuschmann** [comment]
Hey @notedit, did you solved your problem or are there any questions left? :)
