### ISSUE TITLE
how should i run sequelize-typescript example demo？

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#182]
I build typescript file to JavaScript file， and I execute  JavaScript file like below

![image](https://user-images.githubusercontent.com/17508916/32209898-a48445c2-be45-11e7-9741-899bdd7ec306.png)

it report error cannot find module， but I use npm install before build typescript file， please tell me how to do to run this example demo ；

**Comment by RobinBuschmann** [comment]
Hey @chaoxihailing did you compile the ts files in `lib` directory as well?

**Comment by chaoxihailing** [comment]
maybe, it is ok now， thanks。
