### ISSUE TITLE
create User but  not get deliver value to insert to database

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#184]
I define User model like below

    import { sequelize, Sequelize } from "../db";
    import { Instance, DataTypes } from "sequelize";
    import {Table, Model, PrimaryKey, Column, AutoIncrement, BelongsToMany,
        DefaultScope, Scopes, CreatedAt, UpdatedAt} from "sequelize-typescript";

    @Table
    export class User extends Model<User> {
        @PrimaryKey
        @AutoIncrement
        @Column
        public id: number;

        @Column
        public firstName: string;

        @Column
        public lastName: string;

        @CreatedAt
        public createdAt: Date;

        @UpdatedAt
        public updatedAt: Date;
    }

and Usercontroller

        public async createUser(ctx: any) {
        logger.info("Andrew - UserController.createUser()");
        const req = ctx.request.body;

        sequelize.addModels([User]);
        const user: User = new User();
        user.firstName = req.firstName;
        user.lastName = req.lastName;
        await userService.createUser(user);
        ctx.body = user;
    }

UserdbService
    
  public async createUser(user: User): Promise<void> {
        logger.info("-----------------------", JSON.stringify(user));
        await User.create<User>(user);
        await User.create({firstName: "Ye", lastName: "bob"});
    }

I use postman to deliver user value, but it create user without deliver value this like this, and second statament can execute. It is has value devliver from postman like below. I don't konw where is error.

 
![image](https://user-images.githubusercontent.com/17508916/32266847-fccc4a3e-bf23-11e7-8e72-bf118414c070.png)

**Comment by RobinBuschmann** [comment]
Hey @chaoxihailing, the data is stored correctly, right? The only issue is, that the data does not appear in the response? Which framework are you using for the http request handling? Do you have an example repo, where I can have a look at?
