### ISSUE TITLE
Index annotation 

### ISSUE THREAD

**Issue by rocky-bgta** [RobinBuschmann/sequelize-typescript#185]
How I can create Index on column by annotation

**Comment by RobinBuschmann** [comment]
This is the way to go :)

```typescript

@Table({
    indexes: [
        {
            unique: false,
            fields: ['column_name']
        },
    ]
})

```

**Comment by rocky-bgta** [comment]
CREATE UNIQUE INDEX lower_case_username ON users ((lower(username)));

**Comment by rocky-bgta** [comment]
Thanks for your replay.
But I to create insensitive unique index like this:
CREATE UNIQUE INDEX lower_case_username ON users ((lower(username)));

Please let me know how I can I implement this feature.

**Comment by RobinBuschmann** [comment]
@rocky-bgta sry for the late response: Can you address this question in the sequelize repo to clarify how `CREATE UNIQUE INDEX lower_case_username ON users ((lower(username)));` can be achieved with pure sequelize?

**Comment by RobinBuschmann** [comment]
@rocky-bgta any update on this ? :)

**Comment by RobinBuschmann** [comment]
Closing this issue due to no response
