### ISSUE TITLE
Join query Issue

### ISSUE THREAD

**Issue by rocky-bgta** [RobinBuschmann/sequelize-typescript#188]
I use this orm framework and done almost all task.
But I can't execute any **join query** using this orm feature, Also your documentation doesn't show
any join query example. 

I tried several time so make join query work, but I failed.
So will please give a example of join query using your orm.

**Comment by Tower450** [comment]
you can see with sequelize documentation 
http://docs.sequelizejs.com/manual/tutorial/querying.html
You can actually do some find function into find function.

**Comment by natesilva** [comment]
Keep in mind this is an ORM, not a SQL generator. It models things at a higher level than SQL. What matters is the association between the objects. Behind the scenes, that may or may not happen using a `JOIN`. (Some ORMs I have used, like Laravel’s, avoid `JOIN`s altogether…)

The `include` directive is typically used to do `JOIN`-like things. An example, but it really depends on how your models are set up:

```typescript
const usersWithPets = await User.findAll<User>({
  logging: console.log,   // optional: include this to see the generated query
  include: [
    {
      model: Pet,
      required: true      // true is similar to an INNER JOIN and false a LEFT JOIN
    }
  ]
});
```

**Comment by rocky-bgta** [comment]
Thank for your replay.

For this purpose I use Knex.js for query builder and execute that build raw
query through sequelize.

It will be better if your framework provide a query builder like Knex.js

Thanks again
Md. Rocky


Thanks
Software Engineer
Md. Nazmus Salahin Rocky

**Comment by RobinBuschmann** [comment]
@rocky-bgta Can this be closed now?
