### ISSUE TITLE
Typescript compiler output bunch of errors for version 0.6.0-beta.3 

### ISSUE THREAD

**Issue by bosunolanrewaju** [RobinBuschmann/sequelize-typescript#190]
Anybody familiar with this error when compiling a project running `sequelize-typescript v 0.6.0-beta.3`:

```
node_modules/sequelize-typescript/lib/models/Model.d.ts(133,129): error TS2693: 'T' only refers to a type, but is being used as a value here.

133   static scope<T extends Model<T>>(this: (new () => T), options?: string | string[] | ScopeOptions | WhereOptions<any>): typeof T;
```

Plus many others similar to this one.

Is there any settings or configuration setup that I am missing?

**Comment by RobinBuschmann** [comment]
@bosunolanrewaju Looks like a bug. `typeof T` is invalid imo. @schmod or am I wrong?

**Comment by schmod** [comment]
@bosunolanrewaju What version of typescript are you using?

**Comment by Tower450** [comment]
tsc -v 2.4.2 and the only solution is to copy the repository into 
```
node_modules\@types
```
By the way, here is my tsconfig.json

```
{
  "compilerOptions": {
    "strictNullChecks": true,
    "rootDir": "./src",
    "lib": ["es2017"],
    "target": "es6",
    "outDir": "dist",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "exclude":[
    "node_modules",
    "src/__test__"
  ]
}
```

**Comment by schmod** [comment]
@Tower540 @bosunolanrewaju can you try again with TS 2.5.3?  

That's what we use internally, and it seems to work.

**Comment by Tower450** [comment]
sorry i don't have this error, i was on the bad thread lol

**Comment by schmod** [comment]
Looks like you need `skipLibCheck": true` in your `.tsconfig`.

**Comment by Tower450** [comment]
alright thanks bro! :)

**Comment by RobinBuschmann** [comment]
@schmod According to this issue: https://github.com/Microsoft/TypeScript/issues/204 `typeof T` is not valid unfortunately

**Comment by bosunolanrewaju** [comment]
@schmod Typescript version is `2.6.1`

**Comment by RobinBuschmann** [comment]
`v0.6.0-beta.4` is released now
