### ISSUE TITLE
distinct property in IFindOptions

### ISSUE THREAD

**Issue by azalpacir** [RobinBuschmann/sequelize-typescript#193]
Hello, i'm trying to do a findAndCountAll on one of the models and i've added an include property however i'm getting an error from the typings that distinct is not part of the property.  

`BenefInsuranceTransaction.findAndCount({
            where: params,
            limit: take,
            offset: skip,
            attributes: ['Id','User','Ind','Stats'],
            include: [{model: BenefInsuranceDetail, required:true, where:{DeleteInd:0}, attributes:['BenefInsDetailID']}],
            distinct: true
        })`

I need to use distinct in order to get the correct count because it's the only solution that I've found to get the correct count for paging.

Thanks.

**Comment by RobinBuschmann** [comment]
@azalpacir Does [this](https://github.com/sequelize/sequelize/issues/2996#issuecomment-243636321) work for you?

**Comment by azalpacir** [comment]
hello,

Sorry, I'm not sure how I will be able to use the distinct function in the link you gave because i need to count only if it has the associated model. hope you can enlighten me.

thanks.

**Comment by RobinBuschmann** [comment]
Hey @azalpacir, sry for the late response. Can you tell me the exact SQL query you want to achieve?

**Comment by azalpacir** [comment]
Hello, 

I'm trying to use the findAndCountAll to be used for the pagination of the records. However when using the said function with the "include" property, I'm getting an incorrect count, which is an existing issue in sequelize. The solution was to add a "distinct" property to the main query in order to get the correct count but the sequelize-typescript model does not allow me to add the "distinct" property because it's not included in the IFindOptions interface. When I checked the sequelize library the "FindOptions" has the "distinct" property.

**Comment by RobinBuschmann** [comment]
Ah sry, I misinterpreted your code example. You‘re right it is missing. I will mark this issue as a bug.

For now you could use distinct like so `{['distinct']: true}` or `{['distinct' as any]: true}`

**Comment by brianschardt** [comment]
This still isnt working and the solution of using {['distinct']: true} or {['distinct' as any]: true}
does not work
