### ISSUE TITLE
Some functions in Sequelize instance not detected by TypeScript

### ISSUE THREAD

**Issue by micksatana** [RobinBuschmann/sequelize-typescript#196]
~~Not sure if this line extends the class wrongly.~~

https://github.com/RobinBuschmann/sequelize-typescript/blob/1fda92ac34460fbfa82758bd8e0c33bedd1bfad6/lib/models/Sequelize.d.ts#L7

~~I track the code, the line above `SequelizeOrigin` referred to `SequelizeStatic` in @types/sequelize at [DefinitelyTyped/types/sequelize/index.d.ts#L6540](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/08da8b8a66772b532fad923d9f2d30af88f5edc3/types/sequelize/index.d.ts#L6540)~~

~~The SequelizeStatic does not have declared functions like `close` or `transaction`, etc.~~

~~If an instance created from [Sequelize in sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript/blob/1fda92ac34460fbfa82758bd8e0c33bedd1bfad6/lib/models/Sequelize.d.ts#L7) is an extended version of [Sequelize in @types/sequelize](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts), then should this line changed to...~~

~~export declare class Sequelize extends SequelizeOrigin.Sequelize {~~

~~I tested working in my project.~~
The problem gone but don't know root cause yet.

**Comment by RobinBuschmann** [comment]
Hey @micksatana thank you for reporting. This should already work. I've tested it with the latest sequelize-typescript and typescript version - You're are absolutely right, it is not working :(

Probably it has to do with the new typescript version. Which typescript version are you using?

**Comment by RobinBuschmann** [comment]
> `export declare class Sequelize extends SequelizeOrigin.Sequelize {`

Unfortunately this solution will not work, cause `SequelizeOrigin.Sequelize` is an interface. It throws `error TS2689: Cannot extend an interface 'SequelizeOrigin.Sequelize'.`

**Comment by micksatana** [comment]
Could you try this? I cannot re-produce on my side already, the problem seems to occur only the first time setup project. Now, I suspect it's IDE bug. I'm using PHPStorm 2017.2.4

https://github.com/micksatana/sequelize-functions-undetected-when-use-sequelize-typescript

**Comment by RobinBuschmann** [comment]
Strange, autocomplete in your example project is working for me very well, too. Probably you're right and it is an IDE issue 🤔
