### ISSUE TITLE
Typesafe way of getting Associations

### ISSUE THREAD

**Issue by intellix** [RobinBuschmann/sequelize-typescript#199]
I'm looking at **graphql-sequelize** and trying to get things working with **graphql-typescript** here: https://github.com/mickhansen/graphql-sequelize/blob/master/docs/relay.md.

The example shows passing in an association like `User.Tasks` so the library can automatically fetch them. After reading through the documentation and debugging/profiling I've found thats a **HasMany** association object and was trying to achieve the same thing here.

I've got this:
```ts
@Table
export class Seed extends Model<Seed> {
  @PrimaryKey
  @AutoIncrement
  @Column
  id: number;
 
  @Column
  name: string;

  @BelongsTo(() => User)
  user: User;
}

@Table
export class User extends Model<User> {
  @PrimaryKey
  @AutoIncrement
  @Column
  id: number;

  @HasMany(() => Task)
  tasks: Task[];
}

...

sequelize.addModels([ User, Task ]);
```

It seems like a property called `associations` magically appears on my class after calling addModels but it's not safe to get without casting to `any` first like:
```ts
import { User } from '../models/User';

console.log((<any>User).associations.tasks);
```

Any ideas/thoughts on how I can PR an improvement for this?

**Comment by intellix** [comment]
Was just playing around with various ways to add that data within TS and I think having something like `ModelInitialised` might help which includes the extra properties added when addModels is called:
```ts
interface Model<T> { }

interface ModelInitialised<T> {
  associations: { [key: string]: any };
}

class Person implements Model<Person> {
  name = 'Dom';
}

function addModels(models: Array<Model<any>>): Array<ModelInitialised<any>> {
  return models.map(model => {
    // ...initialise
    return { ...model, associations: {...} };
  });
}

export addModels([Person]);
```

**Comment by RobinBuschmann** [comment]
Hey @intellix the reason why `associations` does not appear on the typings of `sequelize-typescript` is that it is not part of the `sequelize` typings. But I have nothing against adding them :) If you like to, you can open a PR for that.
The property need to be added to `Model.d.ts`: For example: `static associations?: any`

**Comment by intellix** [comment]
I guess it'd be good to type the associations as well at some point but this one will satisfy me :)
