### ISSUE TITLE
Running tests on windows

### ISSUE THREAD

**Issue by snewell92** [RobinBuschmann/sequelize-typescript#20]
This relates to a [previous discussion about the node environment variable](https://github.com/RobinBuschmann/sequelize-typescript/pull/19#issuecomment-306531655).

I've made some headway [on this branch](https://github.com/snewell92/sequelize-typescript/tree/updateNodeEnvInTravis) so that windows users can run `npm run exec-tests` and get all the mocha goodies (moved the environment variable into travis - local environments need to specify the variable themselves).

However, `nyc` still isn't returning successfully. Running `npm run cover` on a windows machine still generates errors. I'm investigating further... being able to run all the npm scripts without errors will help other people contribute.

I suspect it's the file glob pattern of the `--exclude` option for nyc. The [nyc README](https://www.npmjs.com/package/nyc) says it uses [micromatch](https://www.npmjs.com/package/micromatch) for file globbing, but perhaps specifying the excludes in the npm script like that is passing it to the shell to parse the file glob, which may or may not work on windows depending on the shell... I'll have to investigate this later (maybe tomorrow). As I thought the single quotes would pass the path string into nyc (so that it can use micromatch)... I'm not really sure, just guessing.

The error I'm currently running into is this:

```bash
$ npm run build
  ... output is good ...
$ npm run cover
  ... scripts, tests, etc ...
npm ERR! sequelize-typescript@0.3.1 cover-v4:
  `npm run prepare-test-v4 && nyc --exclude 'lib/models/v3/**/*.js' --all
    --require source-map-support/register mocha test/specs/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sequelize-typescript@0.3.1 cover-v4 script.
```

Installing `nyc` globally and running the nyc part of the command by itself worked fine. Frustrating!

Next thing I might try is messing with quotes/no quotes/other ways of passing options to nyc.

**Comment by RobinBuschmann** [comment]
@snewell92 Thank you for raising this. I will assign this issue to you, if it's OK for you.
