### ISSUE TITLE
`TypeError: model.init is not a function`

### ISSUE THREAD

**Issue by bradkovach** [RobinBuschmann/sequelize-typescript#207]
I have been battling this issue off and on for a few days now.

When you attempt to run your application, you will see `TypeError: model.init is not a function` in the console.

For me, the fix was to edit `tsconfig.json` and ensure that `target` was `es6` or higher.  TypeScript will default to `es3` if nothing is provided.  This causes the decorator feature to fail miserably.

I hope this helps someone.

**Comment by RobinBuschmann** [comment]
Hey @bradkovach, how did you compile the source files? With simply running `tsc`?

**Comment by bradkovach** [comment]
Yes, running `tsc --watch` and then using `nodemon` to reload the results as I work.

Project setup is pretty standard.  TypeScript sources are in the `src` directory, and then are compiled *over* to the `dist` directory.
```
server
- dist/
- src/
- package.json
- tsconfig.json
```

Here is my `tsconfig.json`

```json
{
    "compilerOptions": {
        "sourceMap": true,
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowJs": true
    },
    "exclude": [
        "node_modules",
        "dist",
        "test"
    ]
}
```

**Comment by RobinBuschmann** [comment]
Hmm, can't reproduce it. Does this work with `es5` for you as well?

**Comment by bradkovach** [comment]
It does not work with es5.  I'll push my repo later so you can see the setup.

**Comment by RobinBuschmann** [comment]
Thanks, would be nice to have a look at this setup :)

**Comment by RobinBuschmann** [comment]
Hey @bradkovach, is this issue still a problem?

**Comment by RobinBuschmann** [comment]
Closing this issue due to no response
