### ISSUE TITLE
Can timestamp fields be renamed?

### ISSUE THREAD

**Issue by mchencb** [RobinBuschmann/sequelize-typescript#208]
`@Column` can rename field using an option. Can we do the same for `@CreatedAt`, `@UpdatedAt` and `@DeletedAt`?

**Comment by RobinBuschmann** [comment]
Hey @mchencb you could achieve it like this:

```
  @UpdatedAt
  @Column({field: 'update_timestamp'})
  updateTimestamp: Date;
```

**Comment by mchencb** [comment]
OK. Great! Thank you!
