### ISSUE TITLE
@DefaultScope and @Scopes do not work w/ query symbols

### ISSUE THREAD

**Issue by Coksnuss** [RobinBuschmann/sequelize-typescript#209]
Minimal working example to reproduce the issue:

Model:
```ts
import { Table, Scopes, Model, PrimaryKey, Column } from 'sequelize-typescript';
import { Op } from 'sequelize';

@Table({
    tableName: 'MyTable',
    timestamps: true,
    paranoid: true,
})
@Scopes({myScope: {
    where: { deletedAt: {
        [Op.lte]: Date.now(),
    }},
}})
export class MyModel extends Model<MyModel> {
    @PrimaryKey
    @Column
    public id: number;
}
```

Code
```ts
const db = new Sequelize({
    dialect: 'mysql',
    host: 'localhost', database: '...', username: '...', password: '...',
    logging: false,
});

db.addModels([MyModel]);
const dbSync = db.sync({ force: true })
    .then(() => { console.log("Sync done!"); })
    .catch((e) => { console.log("Sync error", e); });

dbSync.then(() => {
    MyModel
        .scope('myScope')
        .findAll({
            logging:console.log,
            paranoid: false, // Just to keep the query as simple as possible
            // Where query, exactly as in @Scopes
            where: { createdAt: {
                [Op.lte]: Date.now(),
            }}
        });
})
```

Expected Query:
```sql
SELECT `id`, `createdAt`, `updatedAt`, `deletedAt`
FROM `MyTable` AS `MyModel`
WHERE `MyModel`.`createdAt` <= '2017-11-27 13:16:09'
  AND `MyModel`.`deletedAt` <= '2017-11-27 13:16:09'; -- THIS LINE IS WRONG BELOW!
```

Actual Query:
```sql
SELECT `id`, `createdAt`, `updatedAt`, `deletedAt`
FROM `MyTable` AS `MyModel`
WHERE `MyModel`.`createdAt` <= '2017-11-27 13:16:09'
  AND `MyModel`.`deletedAt` = '2017-11-27 13:16:09';
```

Please note that this does not only apply to `Op.lte`. Other complex where queries are not possible either (e.g. `where: { deletedAt: { [Op.ne]: null } }`)

**Comment by Coksnuss** [comment]
In addition, it would be nice to add the `paranoid?: boolean` option to `IScopeIncludeOptions` or `IBaseIncludeOptions`

**Comment by RobinBuschmann** [comment]
Hi @Coksnuss, thanks for reporting. So, it is "failing" silently for you, right? Actually I'm getting an error 😮

**Comment by Coksnuss** [comment]
Hi @RobinBuschmann ,

does it throw an error with the provided example?

It does throw an error for me too if I define a scope using query symbols on a regular column (i.e. not deletedAt, createdAt, updatedAt). I cant recall exactly but it said something like "unknown type {}".

**Comment by RobinBuschmann** [comment]
@Coksnuss Ah ok, so it is not throwing on deletedAt, updatedAt and so - strang. I tried on regular columns only. And yes, it is something like "unknown type {}" for me, too. 

But, good new, I already found out what causes the issue :)
