### ISSUE TITLE
Joining a table without defining an association

### ISSUE THREAD

**Issue by dlemburg** [RobinBuschmann/sequelize-typescript#212]
Quick note: if this question would be better served asked in the sequelize js issues, please tell me, and I'd be glad to move it there. It seems it spans both sequelize js and sequelize typescript. 

So far, I've been unsuccessful. Here is a quick example of what I'd like to do that I cannot get to work...

Given 3 tables: Company, Product, Lookup...

Company has many Products. Products have one Company. Lookup table serves as an enum/constant for hardcoded values. I.e. state/country names, application specific naming conventions, etc.

Here are the models in sequelize-typescript (though the question still fully relates to sequelize js):

    // COMPANY
    @Table
    export default class Company extends Model<Company> {
   
       @PrimaryKey    
       @Column
       Oid:number;
        

       @Column
       Name:string;
        

       @Column
       Address:string;

   
       @HasMany(() => Product)
       products: Product[];
    
    }

    // PRODUCT
    @Table
    export default class Product extends Model<Product>{

       @PrimaryKey    
       @Column
       Oid: number; 

       @ForeignKey(() => Company)
       @Column
       companyOid: number;
    
       @BelongsTo(() => Company)
       company: Company;

       @Column
       Price: number;   

       @Column
       Name: string;    
    
       //@ForeignKey(() => Lookup)    //attempt #1
       //@Column({references: {model: "Lookup", key: "Oid"}})   //attempt #2
       @Column
       LkpStateOid: number; 
    }

    // LOOKUP
    @Table
    export default class Lookup extends Model<Lookup> {

       @PrimaryKey
       //@BelongsTo(() => Product)  // do not want to hardcode Product, as it could be any table
       @Column
       Oid:number; 

       @Column
       Value:number;  // where the value represents the hardcoded state, county, etc., ie "CA"
        
    }

The issue here is that there is no "real" relationship between Product.lkpStateOid and Lookup.oid, except that one references the other in order to obtain the `Lookup.value`. In any sql variant, this is not an issue- just a simple join on the tables. In sequelize, however, the relationship between the tables must be known before I can get any of the associated data in a query. This is what I'd like to do:

     const companyInfo = await Db.Company.find({
                include: [{
                   model: Product, 
                   include: [{
                       model: Lookup, 
                       attributes: ["value"]
                   }]
                }]
            })
The first `include` is no problem. The second, nested `include` is not successful. I've tried a number of different annotations on the table, but the secondary issue (even if i could successfully "fake" a relationship in order to be able to associate the data) is that I do not want to hardcode which table the Lookup table `belongsTo` because the Lookup table could contain values that are needed in any number of other tables. Is there a way to accomplish this goal?

This link seems close to what I'd like (and is commented as an idea in the above table): [http://docs.sequelizejs.com/manual/tutorial/associations.html#enforcing-a-foreign-key-reference-without-constraints][1]
Any help would be appreciated. Thanks! 

  [1]: http://docs.sequelizejs.com/manual/tutorial/associations.html#enforcing-a-foreign-key-reference-without-constraints

**Comment by RobinBuschmann** [comment]
So as far as I understand you correctly, you want to set up a polymorphic association, while the LookUp keeps foreignkeys of different other Tables, right?
So that: LookUp.Oid --> Product or LookUp.Oid --> OtherTableY or LookUp.Oid --> OtherTableX

**Comment by dlemburg** [comment]
I think we are saying the same thing. To further clarify:


Company has a foreign key property LkpStateOid which refs Lookup.Oid;
Product has a foreign key property LkpProductTypeOid which refs Lookup.Oid

Lookup table is sort of a monolithic constant table, where "X" number of other tables in the database holds foreign key references to the Lookup table. An example sql query:

```
SELECT c.*, lkp.Value
FROM Company c
JOIN Product p ON p.CompanyOid = c.oid
JOIN Lookup lkp ON lkp.oid = p.lkpProductTypeOid
```

in this case, lkp.Value holds the constant value we want (i.e. some defined "productType" value), referenced by p.lkpProductTypeOid

the Lookup table could look like this:

OId           Value            Type

 1         someValue         Product Type

**Comment by dlemburg** [comment]
Figured it out. Solution:

` // Lookup Table
@Table
export default class Lookup extends Model<Lookup> {

    @PrimaryKey
    @Column
    Oid:number; 

    @Column
    Value:number;   
}`

`@Table
export default class Product extends Model<Product>{

    @PrimaryKey    
    @Column
    Oid: number; 

    @ForeignKey(() => Company)
    @Column
    companyOid: number;
    
    // sequelize association
    @BelongsTo(() => Company)
    company: Company;

    @Column
    Price: number;   

    @Column
    Name: string;    
    
    /* will come back as:     { state: {oid: 1, value: "CA"} }
    @BelongsTo(() => Lookup, 'LkpStateOid')    
    state: Lookup;

    @Column
    LkpStateOid: number; 
}`

I had the wrong impression that I needed to put an annotation on the Lookup table referencing Product. But only needed @BelongsTo(() => "LkpStateOid"), with `LkpStateOid` as the actual column name, and `state` as the alias. Very clean, and exactly what I need. 

Thanks for trying to problem solve with me!

**Comment by chirag2120787** [comment]
I want to do the exact same thing in JS but I am not able to find something like this in SequelizeJs. Can you help ?
