### ISSUE TITLE
rejectOnEmpty can be Boolean or Error

### ISSUE THREAD

**Issue by Diluka** [RobinBuschmann/sequelize-typescript#214]
see http://docs.sequelizejs.com/class/lib/model.js~Model.html

> options.rejectOnEmpty | Boolean \| Error | optionaldefault: false | Throws an error when no records > found
> -- | -- | -- | --

https://github.com/RobinBuschmann/sequelize-typescript/blob/59681a0a533f9104e0cdaa4508e980f554151f7f/lib/interfaces/IFindOptions.ts#L95

**Comment by RobinBuschmann** [comment]
@Diluka Thanks for reporting
