### ISSUE TITLE
Is there a changelog for 0.6?

### ISSUE THREAD

**Issue by natesilva** [RobinBuschmann/sequelize-typescript#216]
I noticed 0.6.1 was released and is no longer marked beta. Before upgrading, is there a changelog? Any known breaking changes?

Regards,
Nate

**Comment by RobinBuschmann** [comment]
Hey @natesilva, not yet. But I will add a changelog very soon. I let you know.

**Comment by RobinBuschmann** [comment]
Here we go: https://github.com/RobinBuschmann/sequelize-typescript/releases/tag/v0.6.0

**Comment by natesilva** [comment]
Thank you so much!
