### ISSUE TITLE
Issue with findCreateFind in v0.6.1 with Typescript 2.6.2

### ISSUE THREAD

**Issue by kingjerod** [RobinBuschmann/sequelize-typescript#217]
Versions:
```
sequelize-typescript: 0.6.1
sequelize: 4.4.3
typescript: 2.6.2
@types/sequelize: 4.0.79
```
It seems like it wants the "includes" key in the where object.

Code:
```
const [statModel, created] = await StatModel.findCreateFind<StatModel>({
   where: {id: id, statDate: date, statName: name},
   defaults: {statValue: value}
});
```

Getting this error:
```
error TS2345: Argument of type '{ where: { id: number; statDate: Date; statName: string; }; defaults: { statValue: number; ...' is not assignable to parameter of type 'IFindCreateFindOptions<any>'.

Types of property 'where' are incompatible.

Type '{ id: number; statDate: Date; statName: string; }' is not assignable to type 'WhereOptions<any> | fn | or | (string | or | col | and)[]'.

Type '{ id: number; statDate: Date; statName: string; }' is not assignable to type '(string | or | col | and)[]'.

Property 'includes' is missing in type '{ id: number; statDate: Date; statName: string; }'.
```

**Comment by RobinBuschmann** [comment]
@kingjerod thanks for reporting. Unfortunately I cannot reproduce it. Can you provide an example repo?

**Comment by kingjerod** [comment]
I noticed that when I switch the statDate to a string TypeScript has no problem with it. 

Here's the repo:
https://github.com/kingjerod/sequelize-typescript-fcf-test

This is the error you should see:
```
src/index.ts(4,68): error TS2345: Argument of type '{ where: { id: 1; statDate: Date; statName: "score"; }; defaults: { statValue: number; }; }' is not assignable to parameter of type 'IFindCreateFindOptions<any>'.
  Types of property 'where' are incompatible.
    Type '{ id: 1; statDate: Date; statName: "score"; }' is not assignable to type 'WhereOptions<any> | fn | or | (string | or | col | and)[]'.
      Type '{ id: 1; statDate: Date; statName: "score"; }' is not assignable to type '(string | or | col | and)[]'.
        Property 'includes' is missing in type '{ id: 1; statDate: Date; statName: "score"; }'.
```

**Comment by RobinBuschmann** [comment]
The problem is the `Date`, of course. See the sequelize typings here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L3112

It doesn't allow `Date`. Since you've passed only one generic type (`StatModel.findCreateFind<StatModel, IStatModel>` is also possible) the compiler cannot infer the `WhereOptions<T[P]>`.
However, it seems to be an issue with the sequelize typings. `Date` should be allowed here, I think.

But there is another way to get it working: Since `sequelize-typescript@0.6.0` you don't need to pass any generic type anymore and without any, it is working very well, too: `StatModel.findCreateFind({where: {statDate: new Date()}})`. 
(Actually this should be inferred to `StatModel.findCreateFind<StatModel>` as well - So it's strange that passing no generic type is working ... 🤔 )

**Comment by kingjerod** [comment]
If I delete the generic type, I get an error about the id:

```
src/index.ts(5,13): error TS2345: Argument of type '{ where: { id: number; statDate: Date; statName: string; }; defaults: { statValue: number; }; }' is not assignable to parameter of type 'IFindCreateFindOptions<{ statValue: number; }>'.
  Types of property 'where' are incompatible.
    Type '{ id: number; statDate: Date; statName: string; }' is not assignable to type 'fn | or | (string | or | col | and)[] | WhereOptions<{ statValue: number; }>'.
      Object literal may only specify known properties, and 'id' does not exist in type 'fn | or | (string | or | col | and)[] | WhereOptions<{ statValue: number; }>'.
```

Seems like it only works with a single value in the "where" clause, if I have just id it works fine.

**Comment by RobinBuschmann** [comment]
Ah, ok. I see. This is a bug then.

In the following line `TAttributes` need to be `Partial<TAttributes>` instead.
https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/interfaces/IFindCreateFindOptions.ts#L8

For now you need to pass both generic types unfortunately `StatModel.findCreateFind<StatModel, Partial<StatModel>>` or `StatModel.findCreateFind<StatModel, {}>`
