### ISSUE TITLE
TS errors when upgrading to latest versions "Error:(11, 68) TS2314: Generic type 'IFindOptions<T>' requires 1 type argument(s)."

### ISSUE THREAD

**Issue by jplusje** [RobinBuschmann/sequelize-typescript#218]
:
typescript 2.6.2
sequelize-typescript 0.6.1
@types/sequelize 4.0.79
sequelize 4.23.4

After updating relevant libraries to the latest versions I get an error which states:
`Error:(11, 68) TS2314: Generic type 'IFindOptions<T>' requires 1 type argument(s).`

```
const findOptions: database.IFindOptions = {
    where: {},
    attributes: ['type', 'shape', 'width', 'height', 'diameter', 'count', 'status', 'remarks']
};

findOptions.where.assignmentId = req.params.assignmentId;
```
I've tried to specify the type by providing the model database.IFindOptions<Throughput> but this doesn't resolve the issue. Which code change is necessary?

**Comment by RobinBuschmann** [comment]
Hey @jplusje, you need to pass the generic type to `IFindOptions`. For example: `IFindOptions<YourModel>`

**Comment by jplusje** [comment]
The solution is indeed to supply the model when setting these options.

For other users having the same issue, this is the full solution:
```
  const findOptions: FindOptions<Throughput> = {
    where: {},
    attributes: ['type', 'shape', 'width', 'height', 'diameter', 'count', 'status', 'remarks']
  };

  if(typeof findOptions.where !== 'undefined' && typeof req.params.assignmentId !== 'undefined') {
    (<WhereOptions<Throughput>>findOptions.where).assignmentId = req.params.assignmentId;
  }
```

The <T> is the actual model class which is being used to perform the search.
