### ISSUE TITLE
Usage with ts-node

### ISSUE THREAD

**Issue by blocka** [RobinBuschmann/sequelize-typescript#22]
The `getModels` function assumes the models are located in .js files. When using ts-node, nothing is compiled so it doesn't find anything. Would it work if that function looked for .ts files too?

**Comment by RobinBuschmann** [comment]
@blocka thanks for raising this. Yes, this will work. I'll put this in the next release.

**Comment by RobinBuschmann** [comment]
@blocka I've released a new version (`0.3.3`), which allows loading ts files now.

**Comment by snewell92** [comment]
@blocka did the new release (`0.3.3`) resolve your issue? It seems like we can close this issue now.

**Comment by blocka** [comment]
Yup. Works great!

**Comment by borislemke** [comment]
@blocka could you kindly share a portion of your setup? My models aren't loaded properly after moving to `ts-node`

**Comment by blocka** [comment]
What is the issue?

**Comment by borislemke** [comment]
@blocka it turned out to be a typo, had `ts` instead of `.ts` in my `readDirSync.filter` function 😅
