### ISSUE TITLE
Question: How to set polymorphic association

### ISSUE THREAD

**Issue by rasikas** [RobinBuschmann/sequelize-typescript#221]
I have following three main entities `User`, `Company`, `Address`. `User` can have many `Addresses` and `Company` can have many `Addresses` too. I managed to implement this using polymorphic many to many as given below.

I have intermediate entity (many to many table) called `EntityAddress` 

~~~
export const ENTITY_TYPE_USER = 1
@Table({
  tableName:  'EntityAddress',
  timestamps: false
})
export class EntityAddress extends Model<EntityAddress> {
  @Column
  entityId: number          // This can be either User.id or Company.id

  @ForeignKey(() => Address )
  @Column
  addressId: number

  @Column
  entityType: number       // This indicates whether this address is linked to a User or Company
}
~~~

and in my `User` model I can retrieve addresses belongs to user with following definition

~~~

@Table({
  tableName: 'Users,
  timestamps: true
})
export class User extends Model<User> {
 ...
 ...

  @BelongsToMany(() => Address, {
    through: {
      model: () => EntityAddress,
      scope: { entityType: ENTITY_TYPE_USER },
      unique: false
    },
    foreignKey: 'entityId'
  })
  addresses: Address[]
}
~~~

This works fine and I can retrieve address array with the given `User` (or with Company)

my question is how to insert data into this intermediate table `EntityAddress`
1. Manually add `entityId`, `addressId`, `entityType`
2. use $add, $set
~~~
const user = await User.findById(id)
const address = Address()
address.save()
user.$add('addresses', address, {
 // How to specify 'entityType' field value here to indicate this is address associated with a `User`
})
~~~
If I use option 2 how to specify `entityType` = 1 when setting the relationship.

Thank you

**Comment by RobinBuschmann** [comment]
Hey @rasikas the entityType should be inferred automatically. Did you try it with `user.$add('addresses', address)` ?

**Comment by rasikas** [comment]
Amazing, that worked without specifying anything additionally, I was thinking I may need to specify it specifically based on my experience with Laravel eloquent, where even though you specify the relationship in the models it applies for retrieval only, and when you attach many to many relationship you have to specify the other column values

ex: `User`
~~~
    ...
    ...
    public function addresses()
    {
        return $this->belongsToMany(Address::class, Address::TABLE_ENTITY_ADDRESS,
            Address::COL_ENTITY_ADDRESS_ENTITY_ID, Address::COL_ENTITY_ADDRESS_ADDRESS_ID)
            ->wherePivot(Address::COL_ENTITY_ADDRESS_ENTITY_TYPE, self::$entityType);
    }

    public function attachAddress($addressId)
    {
        $this->addresses()->attach($addressId,
            [Address::COL_ENTITY_ADDRESS_ENTITY_TYPE => self::$entityType]);
    }
~~~
**`attach($addressId, [Address::COL_ENTITY_ADDRESS_ENTITY_TYPE => self::$entityType]);`**

Here it is inferred automatically which is the proper way. Thank you very much

**Comment by RobinBuschmann** [comment]
@rasikas Same here, can we close this issue?

**Comment by rasikas** [comment]
yes please
