### ISSUE TITLE
"Class constructor [ClassName] cannot be invoked without 'new' " that cannot be solved by targeting es6 or above

### ISSUE THREAD

**Issue by Danlock** [RobinBuschmann/sequelize-typescript#222]
Hey, Ive been looking around for other people who have this issue, and it seems to be solved by setting the target version higher if you are using sequelize v4 but that isn't the case for me.

Here is my model:
```
import { AllowNull, Column, Model, PrimaryKey, Table } from 'sequelize-typescript';

@Table({ paranoid: false, timestamps: false, tableName: 'version' })
export default class Version extends Model<Version> {
  @PrimaryKey
  @Column
  public name: string;

  @AllowNull(false)
  @Column
  public version: string;
}

```

Here is my controller (using hapi.js)
```
  export const getAppVersion: RouteController = {
    pre: [
      {
        assign: 'getVersion',
        method: (request, reply) => {
          return reply(Version.findOne({ where: { name: 'app' } }));
        },
      },
    ],
    handler(request, reply) {
      const version: Version = request.pre.getVersion;
      return reply({ minimumVersion: version.version });
    },
  };

```

sample of package.json :
```
    "sequelize": "^4.20.1",
    "sequelize-typescript": "^0.6.1",
```
actual error message:
```
Class constructor Version cannot be invoked without 'new'
      at Array.reduce (<anonymous>)
      at new Promise (<anonymous>)
      at <anonymous>

````
my tsconfig.json:
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "lib": ["es2015","es2016","es2017"],
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "noImplicitReturns": false,
    "strictNullChecks": false,
    "traceResolution": false,
    "noImplicitAny": true,
    "noUnusedLocals": false,
    "alwaysStrict": true,
    "module": "commonjs",
    "outDir": "./build",
    "baseUrl": "./src",
    "target": "esnext",
    "sourceMap": true,
    "allowJs": true,
    "pretty": true
  },
  "include": [
    "./package.json",
    "./tsconfig.json",
    "./src/**/*"
  ],
  "paths": {
    "src/*" : ["./src/**/*"]
  }
}
```

I can't find any other guidance on this issue that isnt just "point your transpiler to es6 and above".
I am 100% sure my tsconfig.json is getting properly picked up by tsc.
Can anyone help, because im kind of stuck right now.

Looking at this projects tsconfig.json, i notice you guys are targeting es5. Could that be the issue?

**Comment by RobinBuschmann** [comment]
Hi @Danlock, can you provide the call stack to `Class constructor Version cannot be invoked without 'new'` as well? The compiled target of this project shouldn't be an issue, cause it is targeted to `es5` for sequelize <v4 and to `es6` for >v4.

**Comment by Danlock** [comment]
Sorry, this problem was entirely on my end. I had another sequelize instance that was importing the model and causing this issue. Not sure why it went with that error message, but ill close this issue now.

Thanks for the prompt reply anyway! I'm slowly transforming a project from sequelize to sequelize typescript so that I dont need to write my classes twice, and the library looks really nice to use so far.

**Comment by wagnxx** [comment]
> I've fixed the issue by setting
> 
> ```
>   "compilerOptions": {
>     "module": "commonjs",
>     "target": "es6",
>     "moduleResolution": "node",
>     "lib": ["es5", "dom"],
>     ...
>   }
> ```

thank u,my problem was fixed
