### ISSUE TITLE
Usage with Jest

### ISSUE THREAD

**Issue by mikew** [RobinBuschmann/sequelize-typescript#223]
I can get sequelize-typescript working when using Mocha to run our tests, but when trying to use Jest I'm seeing:

```
Model not initialized: "<Model>" needs to be added to a Sequelize instance before "inspect" can be called.
```

I can most likely get you an example repository to reproduce it in a couple of hours.

**Comment by RobinBuschmann** [comment]
Hey @mikew, do you initialized the Models via `const sequelize = new Sequelize({modelPaths: ['path/to/model']})` or `sequelize.addModels(['path/to/models'])`/`sequelize.addModels([YourModel])`?

**Comment by mikew** [comment]
Sorry, I thought that would be important and forgot to mention it.

This is with the `addModels` method.

**Comment by RobinBuschmann** [comment]
Ah ok, an example repo would be helpful then :)

**Comment by mikew** [comment]
The good (???) news is that it doesn't work with `modelPaths` either.

Here is an example repository: https://github.com/mikew/sequelize-typescript-jest

**Comment by RobinBuschmann** [comment]
Are you sure, that your typescript-preprocessor for jest is using the `tsconfig.json`? Your passing null for the compiler options (https://github.com/mikew/sequelize-typescript-jest/blob/master/jest.typescript-preprocessor.js#L8) I don't know if typescript is using the `tsconfig.json` then - probably not.

**Comment by mikew** [comment]
Hm I'm pretty sure I verified that null would mean that `tsc` uses the default tsconfig.json. I will verify later.

Thanks for looking into this.

**Comment by RobinBuschmann** [comment]
Hey @mikew any update on this? :)

**Comment by mikew** [comment]
Yep, it was the preprocessor. Everything works when using ts-jest. Sorry for the delay!
