### ISSUE TITLE
modelPaths will not import a single file without glob 'magic'

### ISSUE THREAD

**Issue by Danlock** [RobinBuschmann/sequelize-typescript#224]
Because of line

https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/services/models.ts#L185 

you cannot import a single model, because it appends /* to something like 
```
modelsPath: [ __dirname + 'models/version.ts' ]
``` 

A quick workaround is to artifically insert glob syntax into the path (instead of version.ts use ?ersion.ts). This skips over the problematic if statement, although it obviously wont work if you have version.ts and Version.ts in the same directory.

**Comment by RobinBuschmann** [comment]
Hi @Danlock, thanks for reporting. `modelPaths` wasn't intent to be used for targeting a single file. Use `addModels` of the `Sequelize` instance instead. Here you can pass the reference of the class:

```typescript
import {Sequelize} from 'sequelize-typescript';

const sequelize = new Sequelize({...});

seqeuelize.addModels([Version]);
```

Probably it makes sense to allow passing model references in the options in the future as well 🤔

**Comment by Danlock** [comment]
even if it isnt valid for a single file, this issue blocks users from passing in multiple single files as well, a common use case. I think you should at least document the glob workaround for users just passing in a few models files so they wont get confused like i did.

**Comment by RobinBuschmann** [comment]
@Danlock sry for the late response: Can you give me an example of passing in multiple single files via paths? I do not really understand your point here

**Comment by Danlock** [comment]
When I initially made this issue I was incrementally implementing this library with my models to see if it would work, so instead of pointing it to every model in my models folder I only wanted to point to one model, then 2, then three etc.

Because of my configuration file being a JSON object it was much easier to pass in an array of filenames to import than entire javascript object reference.

The way it behaves now is not really intuitive, it really is modelDirectories instead of modelPaths if it doesn't allow single files without workarounds.

But because of the other issue of this library not working across multiple sequelize instances, theres another use case for importing multiple single model files so that the right models are attached to the right instances, and therefore the right database connections.

I didn't find using the workaround to be a major pain so documenting that instead of fixing it would probably be fine.
