### ISSUE TITLE
Does this work on electron app?

### ISSUE THREAD

**Issue by mojtababaghban** [RobinBuschmann/sequelize-typescript#225]
Does this work on electron app?

**Comment by snewell92** [comment]
I would think so.

[Try it out](https://electronjs.org/docs/tutorial/quick-start) by [using the electron starter repo](https://github.com/electron/electron-quick-start) and installing typescript, sequelize, and sequelize-typescript and using a SQLite database or something.

If sequelize works, sequelize-typescript will work.

**Comment by bilby91** [comment]
I agree with @snewell92 . As long as you use `sequelize-typescript` in the main process (https://github.com/electron/electron/blob/master/docs/glossary.md#main-process) you __should__ be good to go. You won't be able to use it in the renderer process.

**Comment by RobinBuschmann** [comment]
Hey @mojtababaghban did you get it to work with electron?

**Comment by RobinBuschmann** [comment]
Closing this issue due to no reply

**Comment by chscott** [comment]
> I agree with @snewell92 . As long as you use `sequelize-typescript` in the main process (https://github.com/electron/electron/blob/master/docs/glossary.md#main-process) you **should** be good to go. You won't be able to use it in the renderer process.

Could you elaborate on why sequelize-typescript cannot be used in the renderer? Thanks!
