### ISSUE TITLE
Real field names

### ISSUE THREAD

**Issue by LogansUA** [RobinBuschmann/sequelize-typescript#233]
Hello.

I have model Device
```javascript
import { Model, DataType, Table, Column, PrimaryKey, AutoIncrement, AllowNull, Default, HasMany } from 'sequelize-typescript';
import { Session } from './Session';

enum DeviceType {
    ANDROID = 'android',
    IOS = 'ios',
    BROWSER = 'browser',
}

@Table({
    tableName: 'device',
    underscored: true,
})
export class Device extends Model<Device> {
    @PrimaryKey
    @AutoIncrement
    @AllowNull(false)
    @Column(DataType.INTEGER)
    id: number;

    @Default(DeviceType.ANDROID)
    @AllowNull(false)
    @Column({
        type: DataType.ENUM(DeviceType.ANDROID, DeviceType.IOS, DeviceType.BROWSER),
        field: 'platform_type',
    })
    platformType: string;

    @AllowNull(false)
    @Column(DataType.TEXT)
    uuid: string;

    @Default(null)
    @Column({
        type: DataType.TEXT,
        field: 'notification_token',
    })
    notificationToken: string;

    @HasMany(() => Session)
    sessions: Session[];
}
```

How can i get real field names by querying data?
**Query**:
```javascript
Device.findOne().then((device: Device) => console.log(device.get({ plain: true }))
```
**Expected result**:
```javascript
{ id: 1,
  platform_type: 'android',
  uuid: 'SOME_UUID_NEW',
  notification_token: null,
  sessions: [] }
```
**Given result**:
```javascript
{ id: 1,
  platformType: 'android',
  uuid: 'SOME_UUID_NEW',
  notificationToken: null,
  sessions: [] }
```

I.e. i want to retrieve object with keys as real field name (as they named in database)

Thank you

**Comment by RobinBuschmann** [comment]
Hey @LogansUA the docs say `If set to true, included instances will be returned as plain objects` (http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-get) So this doesn't seem to be the way to do it. But I don't know if it is working at all. Can you address this to the sequelize team instead?

If you always need to use the field names as property names, why not using the same name for the properties? But I assume, you already thought about it? ;)

**Comment by LogansUA** [comment]
@RobinBuschmann Ok, what about another solution, like i have now in my sequelize configuration: use hook `beforeDefine` to create instance method for each model which will return plain object where all properties mapped to their field names (if field parameters is not defined then use their property name).
For now it's solves my problems, but when i started to implement it using sequelize-typescript i found one problem **how to define global hook for sequelize instance**
Previously i could do it like that
```javascript
const sequelize = new Sequelize(
    'DATABASE_NAME',
    'DATABASE_USERNAME',
    'DATABASE_PASSWORD',
    {
        dialect: 'DATABASE_DIALECT',
        host: 'DATABASE_HOST',
        port: 'DATABASE_PORT',
        hooks: {
            beforeDefine: (model, options) => {
                if (typeof options.instanceMethods === 'undefined') {
                    options.instanceMethods = {};
                }

                // Add method which helps to retrieve model objects with underscored fields
                options.instanceMethods.getPlainWithDatabaseFieldNames = db.getPlainWithDatabaseFieldNames;
            },
        },
    },
);
```

**Comment by LogansUA** [comment]
@RobinBuschmann any thoughts?

**Comment by RobinBuschmann** [comment]
Sry for the late response: `new Sequelize({..., hooks: {...}})` isn't working?

Another way of encapsulating this, is creating your own model base class, which inherits from `Model` like

```ts
class BaseModel<T> extends Model<T> {
  getPlainWithDatabaseFieldNames() {...}
}
```

**Comment by LogansUA** [comment]
@RobinBuschmann Ok, will try it, thank you.

**Comment by LogansUA** [comment]
Here's solution that works for me:
```javascript
import { Model, Table } from 'sequelize-typescript';

@Table({})
export class BaseModel<T> extends Model<T> {
    getPlainWithDatabaseFieldNames() {...}
}
```
