### ISSUE TITLE
Where object type is not match

### ISSUE THREAD

**Issue by Diluka** [RobinBuschmann/sequelize-typescript#234]
```ts
       {
            where: {
                parentId: id,
                isEnabled: true,
                "$parent.isEnabled$": {
                    $or: [true, null]
                }
            }
        }
```

`"$parent.isEnabled$"` this key means lookup into the relation table. It's worked. But the type definition says it is not right.

It generate sql like this ```(`parent`.`isEnabled` = true OR `parent`.`isEnabled` IS NULL)```

**Comment by RobinBuschmann** [comment]
Hey @Diluka , thanks for reporting. Can you provide a link to the docs of sequelize defining this? Thank you :)

**Comment by Diluka** [comment]
I can't find any docs about this feature either.
But they've already implemented this according to sequelize/sequelize#3095

**Comment by bosunolanrewaju** [comment]
@Diluka Did you try without the `$` like `parent.isEnabled`? I was able to sort records by a related table using just `table.column`.

**Comment by RobinBuschmann** [comment]
@bosunolanrewaju I think Diluka addresses the typings here. `$parent.isEnabled$` is working for Diluka, but the typescript compiler is throwing.

@Diluka I think, the best option to achieve this is the following: `where: { ['$parent.isEnabled$' as any] }`. Otherwise we need to add `any` to the typings of `WhereOptions` which would destroy type safety here. What do you think?

**Comment by bosunolanrewaju** [comment]
Oh, I see. I found out that the typings for `where: sequelize.where()` is not in `ICountOptions` too. 
Not sure it would work for `WhereOptions` either.

@Diluka  can you try something in the line of 
`where: sequelize.where(sequelize.col("$parent.isEnabled$"), "OR", [true, null])`?

**Comment by Diluka** [comment]
@RobinBuschmann `as any` is a good solution. I often use it to resolve the typings mismatch issue in each package.

@bosunolanrewaju I think it is too complicated. I prefer to using `as any`.

**Comment by RobinBuschmann** [comment]
OK, then I close this issue now. @Diluka Feel free to reopen it, if it is still an issue for you
