### ISSUE TITLE
Add excludes / includes option

### ISSUE THREAD

**Issue by snewell92** [RobinBuschmann/sequelize-typescript#24]
Based on the discussion within #23 we can add a feature in the `ISequelizeOptions` for support of `includes/excludes` options. To fully support this, we should add support for [globs](https://www.npmjs.com/package/glob).

Still a bit of discussion as to whether or not `modelPaths` should only be paths - since it would be easier to implement if we could just concatenate both the `includes` array and `modelPaths` array together and have logic in the reduce loop to discriminate between directories, files, or a glob pattern. Or possibly use the reduce loop to pass through the array once to expand all glob patterns/directories, building an array of only files, then after the reduce loop map over them with `require` - although this would require first pulling out all passed in `Models` from the array so we just get an array of models and an array of strings. Meh, maybe not worth the effort.

The excludes option seems far easier to grapple with. We already have a filter in `models.ts -> getModels` function so we just add that in.

**Comment by RobinBuschmann** [comment]
Yeah, I think it would be much clearer to use only paths for `modelPaths` option and no globs. Using globs in `include`, `exclude` with an absolute path should work.

**Comment by snewell92** [comment]
:+1: Sound great.

**Comment by RobinBuschmann** [comment]
I think this can be closed, since globs are solving this mostly.
