### ISSUE TITLE
DataType.GEOGRAPHY not supported?

### ISSUE THREAD

**Issue by localnet** [RobinBuschmann/sequelize-typescript#240]
I can see the data type GEOGRAPHY in the documentation: 
 - http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

But when I try use it:
```
    @Column(DataType.GEOGRAPHY)
    public geolocation: any;
```
I gets the following error:
> La propiedad 'GEOGRAPHY' no existe en el tipo 'DataTypes'.
> (Translated: The property 'GEOGRAPHY' do not exist in the type 'DataTypes'.)

I am newbie with geolocation and PostGIS, but this data type seems better than GEOMETRY for geolocation.

**Comment by RobinBuschmann** [comment]
Hey @localnet, which sequelize version are you using?

**Comment by localnet** [comment]
Hi @RobinBuschmann, the sequelize version I am using:
```
$ npm ls sequelize | grep sequelize
└── sequelize@4.28.5
```

But after to think on it I think the issue is of "types/sequelize":
```
$ cat node_modules/\@types/sequelize/index.d.ts | grep GEOGRAPHY
$ cat node_modules/\@types/sequelize/index.d.ts | grep GEOMETRY
        GEOMETRY: DataTypeGeometry;
```

**Comment by RobinBuschmann** [comment]
@localnet Ah yes, it is missing on the sequelize typings... Thank you! Probably it is part of a newer version and a dependency update for sequelize-typescript would help.

**Comment by localnet** [comment]
@RobinBuschmann if you want close the issue, do it. After read a little more about geolocation, I am using GEOMETRY because it have better performance when is not necessary take in account the earth curvature.

Thanks so much and great work!
