### ISSUE TITLE
Sequelize - Use paranoid in include in findAll

### ISSUE THREAD

**Issue by pirmax** [RobinBuschmann/sequelize-typescript#241]
I use **Sequelize** to fetch all data with somes parameters.

I want display all data and data removed with **paranoid = false**.

**PhpStorm** give me an error when I use paranoid in **include[]**.

If I remove the second line **paranoid = false**, the third line give me an error too.

[![enter image description here][1]][1]
[![enter image description here][2]][2]

I know I can't use **paranoid** in **include[]** because it's not defined in **IIncludeOptions** interface but I want use **paranoid** in cascade :)

The query work, but I have this error in **PhpStorm**, and I can't leave it like that for replaying my code.

I have tried this code:

    return await AggregatedNotificationBySegment.findAll<AggregatedNotificationBySegment>({
        where: {
            aggregatedDate: {[Sequelize.Op.between]: [dateBegin, dateEnd]},
        },
        include: [{
            model: Segment,
            required: true,
            where: {
                deletedAt: {
                    $or: [ null, {  $not: null } ]
                }
            },
            include: [{
                model: Database,
                required: true,
                where: {
                    uuid: databaseUuid,
                    deletedAt: {
                        $or: [ null, {  $not: null } ]
                    }
                }
            }]
        }],
        order: [["aggregatedDate", "ASC"]]
    });

But, Sequelize add automaticaly this condition in SQL query:

> (`segment->database`.`deletedAt` > '2017-12-18 08:46:56' OR
> `segment->database`.`deletedAt` IS NULL) AND

One **AND** before the other condition... It's block the query...

  [1]: https://i.stack.imgur.com/cUpnc.png
  [2]: https://i.stack.imgur.com/I2zhe.png

**Comment by pirmax** [comment]
@andrewlababies say https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15670

The paranoid key is missing in IncludeOption interface...

**Comment by RobinBuschmann** [comment]
closes by #242

**Comment by royalpinto** [comment]
@pirmax , @RobinBuschmann  Which version of `sequelize` has this fix? I tried with the latest version v4.39.0 but issue exists there as well. If it is not part of the core `sequelize`, could you provide some patch to apply?

Thanks

**Comment by RobinBuschmann** [comment]
Hey @royalpinto this was fixed in sequelize-typescript - so the latest version `0.6.6` has the fix

**Comment by royalpinto** [comment]
@RobinBuschmann Thanks
