### ISSUE TITLE
Sequelize Typings DT @types vs types/sequelize

### ISSUE THREAD

**Issue by snewell92** [RobinBuschmann/sequelize-typescript#246]
So I was reading [the other sequelize typings](https://github.com/types/sequelize) and saw that it is consistently given more attention than the DT monorepo typings (the one that gets installed with `@types/sequelize`).

@RobinBuschmann have you looked at that repo? What are your thoughts?

**Comment by RobinBuschmann** [comment]
@snewell92  Thanks for the hint. I will look at it.

**Comment by RobinBuschmann** [comment]
The maintenance of @types/sequelize typings seems to be much better now. So I will stick with these.
