### ISSUE TITLE
$count helper return type

### ISSUE THREAD

**Issue by imposibrus** [RobinBuschmann/sequelize-typescript#247]
https://github.com/RobinBuschmann/sequelize-typescript/blob/ddc0608c902c42b496c6c213d7178007ab610669/lib/models/BaseModel.ts#L149

Shouldn't return type be `Promise<number>` here?

**Comment by DG-Wangtao** [comment]
Hi, is there a same issue? @RobinBuschmann 
[model.count doesn't always return a Promise\<number\>](https://github.com/sequelize/sequelize/issues/10757)
And a PR to fix this issue in sequelize:
https://github.com/sequelize/sequelize/pull/10763

**Comment by DG-Wangtao** [comment]
> Hi, is there a same issue? @RobinBuschmann
> [model.count doesn't always return a Promise<number>](https://github.com/sequelize/sequelize/issues/10757)
> And a PR to fix this issue in sequelize:
> [sequelize/sequelize#10763](https://github.com/sequelize/sequelize/pull/10763)

It works fine when I upgrade my `sequelize` to version `5.6.0`

**Comment by RobinBuschmann** [comment]
Hey @DG-Wangtao, thanks for bringing this up. Do you really mean `$count` of a model instance or `count` of the model reference?

**Comment by DG-Wangtao** [comment]
Paste my code below:
```
// app/model/access.ts
import { Table, Column, Model, PrimaryKey, Length, DefaultScope } from 'sequelize-typescript';
@Table({
  underscored: false,
  tableName: 'accesses',
})
export default class Access extends Model<Access> {

  @PrimaryKey
  @Length({ max: 36, min: 1 })
  @Column({ field: 'person_id' })

  personId: string;
  @Column({ field: 'image_url' })
  imageUrl: string;
}
```

```
// app/service/access.ts
import Access from '../model/access';
 const results = await Access.count({
        col: 'person_id',
        distinct: true,
        attributes: [ 'access.image_url' ],
        group: 'access.area_id',
       },
      );
```

You will see the returns type of `Access.count` will be `Promise<{ [key: string]: number }>` in `sequlize:5.6.0` and it is `Promise< number >` in `sequlize` before `5.6.0`.
Maybe is an issue of `sequlize` , not in this project.
