### ISSUE TITLE
Error with a simple find

### ISSUE THREAD

**Issue by Rioos** [RobinBuschmann/sequelize-typescript#250]
So im trying authenticating a User with passport:

<img width="664" alt="captura de tela 2017-12-22 as 14 51 42" src="https://user-images.githubusercontent.com/4395602/34306013-224dbc8a-e728-11e7-8f67-89124b3dd87b.png">

When checking the logs it seems that the Query is working but that Data is not being returned:

<img width="922" alt="captura de tela 2017-12-22 as 14 52 48" src="https://user-images.githubusercontent.com/4395602/34305997-0f54be08-e728-11e7-9217-944c258ec885.png">

**Comment by RobinBuschmann** [comment]
Hey @Rioos, can you provide an example repo, which reproduces the issue?

**Comment by Rioos** [comment]
<img width="395" alt="captura de tela 2017-12-22 as 15 08 56" src="https://user-images.githubusercontent.com/4395602/34306404-14fcd99c-e72a-11e7-9348-f2a1dcd3fbf2.png">

**Comment by RobinBuschmann** [comment]
Hey, I mean a git repository :) Thank you

**Comment by Rioos** [comment]
Actually cant, its a private repo, anything else that might help ?

**Comment by RobinBuschmann** [comment]
Ok, here we go then: https://github.com/RobinBuschmann/st-issue-250 Works very well here. So feel free to fork and try to reproduce your issue :)

**Comment by Rioos** [comment]
Testing right now, posting results soon! Thanks mate!

**Comment by Rioos** [comment]
It worked just fine =( 

So its nothing about the environment, i'm looking deep into code, trying to find something. 

If i realize what is the error i'll send it here.

**Comment by RobinBuschmann** [comment]
Great! Thanks

**Comment by Rioos** [comment]
Found the problem! It was the constructor i setted in the Model class. Since i migrated from typeorm it was present and i didnt remove it.

Maybe it'd  be nice to have support for that. =)

**Comment by RobinBuschmann** [comment]
Can you show me how the constructor did look like?

**Comment by RobinBuschmann** [comment]
..so what actually caused the issue?

**Comment by Rioos** [comment]
It was just a simple

    `constructor() {
        super();
    }`

**Comment by RobinBuschmann** [comment]
Ah ok, the retrieved values from db get passed through the constructor. So internally something like `new User(data)` happens. Due to your empty `super` call data couldn’t been set.

**Comment by Rioos** [comment]
So maybe something like 

`
  constructor(data: User) {
    super(data);
  }
`

Might work, right ?

**Comment by RobinBuschmann** [comment]
Yes, indeed :)

**Comment by RobinBuschmann** [comment]
Hey @Rioos, can this be closed now?

**Comment by Rioos** [comment]
Sure =)
