### ISSUE TITLE
Question: How to remove polymorphic association $remove

### ISSUE THREAD

**Issue by rasikas** [RobinBuschmann/sequelize-typescript#251]
This is related to the question #221 

example Model names are bit different since I've taken it directly from my current code. But the concept is very much same with the #221 

**Property Model** 
```
export class Property extends Model<Property> {
...
...
  @BelongsToMany(() => Address, {
    through: {
      model: () => EntityAddress,
      scope: { entityType: 1 },
      unique: false
    },
    foreignKey: 'entityId'
  })
  addresses: Address[
```

**Address Model**
```
export class Address extends Model<Address>
```

Property's addresses (in this case usually one but design is so that I can have many to many with entities such as User, Property etc) 
So I have a table called `EntityAddress` with following columns
`entityId` - (can be either `propertyId`, `userId` etc)
`addressId` - FK to Address table
`entityType` - (indicates the entity type ex: 1 - `Property`, 2 - `User` etc)

```
export class EntityAddress extends Model<EntityAddress> {
  @Column
  entityId: number

  @ForeignKey(() => Address )
  @Column
  addressId: number

  @Column
  entityType: number
}
```

I can associate `Address` with `Property` without any issue and it automatically inserts entityType = 1 to the intermediate table (`EntityAddress` as well
```
const property = await this.propertyRepository.findById(id)   // id = 1
await address.save() // addressId = 8
property.$add('addresses', address)
```
**Sql output**
```
Executing (default): INSERT INTO `EntityAddress` (`entityId`,`addressId`,`entityType`) VALUES (1,8,1);
```

But now when I try to remove the association
```
    const property = await this.propertyRepository.findById(id, {include: [
    {
      model: Address,
      as: 'addresses'
    }]})
    const address = property.addresses[0]  // for testing i takes the first address and remove
    property.$remove('addresses', address);
```
**Sql output**
```
Executing (default): DELETE FROM `EntityAddress` WHERE `entityId` = 1 AND `addressId` IN (8)
```
Now the problem here is it doesn't use the `entityType` in the delete query as in insert query. which could cause it to delete other entity type associations. ex: if there is a `User` with id = 1 and has address association to address id 8.

I'm not sure this is an inherent sequelize issue or something you can help with.

**In addtion another question on the definition of $remove**
```
$remove<R extends Model<R>>(propertyKey: string, instances: R|R[], options?: any): Promise<this>;
```
only accepts instance(s) in the second parameter but in the sequelize documentation it says you can [pass id(s) or string(s) as well](http://docs.sequelizejs.com/class/lib/associations/has-many.js~HasMany.html#instance-method-remove)

**Comment by rasikas** [comment]
I tried the $get() as follows and it also works fine by automatically including the `entityType`
```
const addresses = await property.$get('addresses', {where: {id: addressId}}) as Address[]
```

**Sql output**
```
SELECT 
    `Address`.`id`,
    `Address`.`unitNumber`,
    ...
    `EntityAddress`.`entityId` AS `EntityAddress.entityId`,
    `EntityAddress`.`addressId` AS `EntityAddress.addressId`,
    `EntityAddress`.`entityType` AS `EntityAddress.entityType`
FROM
    `Addresses` AS `Address`
        INNER JOIN
    `EntityAddress` AS `EntityAddress` ON `Address`.`id` = `EntityAddress`.`addressId`
        AND `EntityAddress`.`entityId` = 1
        AND `EntityAddress`.`entityType` = 1
WHERE
    (`Address`.`id` = '9');
```

So I'm wondering why it doesn't include the `entityType = 1` scope condition in `$remove`

**Comment by RobinBuschmann** [comment]
@rasikas Sry for the late response. Did you already get it to work now? Otherwise looks like a sequelize issue to me. Did you tried it with pure sequelize (`removeAdresses` or `removeAdress`)?

Regarding your other question: Yes, this seems to be a bug in sequelize-typescript typings

**Comment by rasikas** [comment]
Yep I've already raised the issue with sequelize and they also confirmed it is a bug
[Here is the link to the issue](https://github.com/sequelize/sequelize/issues/8890)
