### ISSUE TITLE
missing dataValues property in Modal.d.ts

### ISSUE THREAD

**Issue by santiagodoldan** [RobinBuschmann/sequelize-typescript#252]
Just wanted to know if there's a reason or if it is ok to add the missing `dataValues` property, I'd love to add it as we're using it to get the plain object of a model instance.

https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/models/Model.d.ts

**Comment by RobinBuschmann** [comment]
@santiagodoldan Sounds good. I have nothing against it :)
