### ISSUE TITLE
Accessing model property names dynamically

### ISSUE THREAD

**Issue by ali-web** [RobinBuschmann/sequelize-typescript#265]
Is there a built-in way to access model property names dynamically without having to hard code them as strings when writing a query?
So instead of:
`User.findOne({ where: {'userId': userId} })`

we could writing something like:
`User.findOne({ where: {User.propertyNames.userId: userId} })`

**Comment by RobinBuschmann** [comment]
Hey @ali-web, in the next release there will be type checking available for model properties in where options - which also means that auto complete will work. Will this fit your needs?

**Comment by ali-web** [comment]
Hey @RobinBuschmann , certainly, thanks!

**Comment by RobinBuschmann** [comment]
This feature is part of the latest version
