### ISSUE TITLE
$get Generic Type is incorrectly returning <R, R[]>

### ISSUE THREAD

**Issue by intellix** [RobinBuschmann/sequelize-typescript#267]
$get is Type Annotated to return either an instance or an array of instances: https://github.com/RobinBuschmann/sequelize-typescript/blob/f54231ede75a9d6ab0acd6c2ca018dfb60911dc4/lib/models/Model.d.ts#L447

## Currently
```ts
// Model.d.ts
$get<R extends Model<R>>(propertyKey: string, options?: any): Promise<R|R[]>;
```

Is problematic for fetching an array of things:
```ts
const posts = user.$get<Post>('posts');
posts.forEach(p => console.log(p)); // Property 'forEach' does not exist on type 'Post | Post[]'.
```

## Expected

```ts
// Model.d.ts
$get<R extends Model<R>>(propertyKey: string, options?: any): Promise<R>;
```

Would allow us to specify exactly the type and use it appropriately:
```ts
const posts = await user.$get<Post[]>('posts');
posts.forEach(p => console.log(p));
```

## Temporary workaround

```ts
const posts = await user.$get<Post>('posts') as Post[];
posts.forEach(p => console.log(p));
```

**Comment by RobinBuschmann** [comment]
Hey @intellix that sounds reasonable. Thanks for implementing!
