### ISSUE TITLE
hasTrigger option in @Table

### ISSUE THREAD

**Issue by blocka** [RobinBuschmann/sequelize-typescript#27]
I'm trying to set this option, but it seems typescript doesn't think it exists. It is definitely in the d.ts file under DefineOptions. Do you have any insights (or workarounds?)

**Comment by blocka** [comment]
Actually, forget that. It appears that you don't have the latest type definitions for sequelize.

**Comment by RobinBuschmann** [comment]
@blocka I will update the typings with the next release. Thanks for raising this issue.

**Comment by snewell92** [comment]
Dang, the types just recently updated to `4.0.60` - I had just submitted a PR last week to update the typings to `4.0.59`.

@RobinBuschmann Is there a reason we need to pin the version of the typings package? Can we do `~4.0.60` or `^4.0.60`? If not that's okay, you'll just need to re-release `sequelize-typescript` to update typings whenever you run into something that's missing ;). (I could see how being loose with the version of `@types/sequelize` might cause problems if upstream changes rearrange/restructure types, but the `~` prefix should ensure only non breaking changes I think).

**Comment by RobinBuschmann** [comment]
@snewell92 Yeah, I think all dependencies should been locked to a fix version to ensure nothing breaks with an Update of a dependency.

**Comment by RobinBuschmann** [comment]
@snewell92 dies this mean we already using the latest typings?

**Comment by RobinBuschmann** [comment]
closed due to 42f19a912578304bf0ee41695c75cc9d8b79d2ba

**Comment by RobinBuschmann** [comment]
@blocka  `sequelize-typescript@0.3.5` now uses the latest sequelize typings

**Comment by snewell92** [comment]
re: @RobinBuschmann  about your question, as you saw, nope. We were a version behind.

Good job being on top of this! :+1:  If I had cryptocurrency I'd tip you.
