### ISSUE TITLE
Static increment method is missing from Model

### ISSUE THREAD

**Issue by intellix** [RobinBuschmann/sequelize-typescript#276]
Currently doing:
```ts
const await user = User.findById(1);
user.increment({ amount });
```

Would be nice to not need to do the first query. Looked through the documentation/code and found that there's actually a static increment as well

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-increment
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2929

**Comment by RobinBuschmann** [comment]
Thanks for reporting. Any PRs to fix this are welcome :)
