### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#277]
I defined User like this
![image](https://user-images.githubusercontent.com/17508916/35191735-8b9e2f42-febd-11e7-89b4-c30b3f0b9537.png)

I use sequelize.addModels([User]), but it occur error like below
![image](https://user-images.githubusercontent.com/17508916/35191761-5179dbc6-febe-11e7-8d92-3f40bbeb131b.png)

how to it happen?

**Comment by RobinBuschmann** [comment]
Hey @chaoxihailing, this is because `addModels()` tries to resolve all relations of `User`.  Therefore the related models (`Role` and `UserRole`) need to be added to the Sequelize instance as well:
```ts
addModels([User, UserRole, Role]);
```

But yes, the error message is not very meaningful :/ I will fix this.

**Comment by chaoxihailing** [comment]
I try to do it, but it also occur the same error, but if I comment `@BelongsToMany(()=>Role, ()=> UserRole) public roles: Role[]`，it can work normal.

**Comment by chaoxihailing** [comment]
I have  add extra  models (`Permission` and `RolePermission`) to the Sequelize instance, so it can work again.
