### ISSUE TITLE
bulkCreate not work normal

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#279]
I try to use `bulkCreate` to create user, code like
![image](https://user-images.githubusercontent.com/17508916/35208568-1301a218-ff84-11e7-8255-3e07f79a08f7.png)
it is error
![image](https://user-images.githubusercontent.com/17508916/35208832-3d9e3774-ff85-11e7-9137-5dbf9633ea73.png)

but if not use `bulkCreate`, and save user like `user.save()`, it is work.

**Comment by RobinBuschmann** [comment]
Hey @chaoxihailing, can you provide your create table query of your `User` table? Looks like you have an unique constraint on one of your columns, which prevents you from inserting the data you want.

**Comment by chaoxihailing** [comment]
`@Table({
    freezeTableName: true,
    paranoid: true,
    timestamps: true,
})
export class User extends Model<User> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @Unique
    @Column
    public policeNumber: string;

    @Column
    public name: string;

    @Column
    public identityCard: string;

    @Column
    public duty: string;

    @Column
    public mobile: string;

    @Column
    public department: string;

    @Column
    public password: string;

    @BelongsToMany(() => Role, () => UserRole)
    public roles: Role[];

    // @BelongsToMany(() => Organization, () => UserOrganizationRelation)
    // public organization: Organization[];

    @CreatedAt
    public createdAt: Date;

    @UpdatedAt
    public updatedAt: Date;

    @DeletedAt
    public deletedAt: Date;
}
`

**Comment by RobinBuschmann** [comment]
There are 2 issues I've noticed:
1. `user.save()` is already storing data and it returns a `Promise`
2. `bulkCreate` is for creating User instances by passing in raw object literals instead of instances

So you either use `save` OR `bulkCreate`:

`save`:

```ts
await data.reduce((promise, item) => promise.then(() => {

  if(YOUR_CONDITION) {
    const user = new User();
    user.name = item.YOUR_PROPERTY;
    // and so on for all other properties
    return user.save();
  }
}), Promise.resolve());
```

or

`bulkCreate`:

```ts
const userData = data
  .filter(item => YOUR_CONDITION)
  .map(item => ({
    name: item.YOUR_PROPERTY,
    // and so on for all other properties
  }));

await User.bulkCreate(userData);
```

**Comment by chaoxihailing** [comment]
thanks
