### ISSUE TITLE
Question: If you guys use vscode, is it possible to get intellisense in create, update or build functions?

### ISSUE THREAD

**Issue by BruceHem** [RobinBuschmann/sequelize-typescript#28]
```ts
const user = await User.build<User>(
    {
      email: 'bruce.hem@pathmazing.com', // <--- it would be so cool if i can get intellisense on which fields are available here.
      password: '123456',
      todos: [{ title: 'Do home work!' }, { title: 'Watch TV!' }]
    },
    {
      include: [Todo]
    }
  );
```

**Comment by RobinBuschmann** [comment]
Hey @BruceHem, `build` can be called with a second generic:

````typescript
interface IUser {
   email: string;
   // ...
}

User.build<User, IUser>({
   email: ''
})
````

Or if you only need auto completion and don't care about what's optional or required, you can use typescripts build in mapped type `Partial`. With this approach you don't need to defined an additional interface:

````typescript
User.build<User, Partial<User>>({
   email: ''
})
````
The problem with this approach is, that you will get auto completion for all your members within `User` - Which means function members as well. Thats why `build<User, User>` is not a good idea.

**Comment by BruceHem** [comment]
Hey man thanks, this lib is freaking awesome. Waiting to see it reached v1 soon.

**Comment by RobinBuschmann** [comment]
@BruceHem thank you very much :)
