### ISSUE TITLE
Raw queries

### ISSUE THREAD

**Issue by ClueGuy** [RobinBuschmann/sequelize-typescript#281]
There's a typing issue when trying to use raw queries with Sequelize-Typescript:

```
sequelize.query(query, {
            replacements: [this.user.id],
            model: MyModel
        });
```

The above generates the following TypeScript error:

```
Error:(25, 32) TS2345: Argument of type '{ replacements: any[]; model: typeof MyModel; }' is not assignable to parameter of type 'QueryOptions'.
  Types of property 'model' are incompatible.
    Type 'typeof MyModel' is not assignable to type 'Model<any, any>'.
      Property 'Instance' is missing in type 'typeof MyModel'.
```

**Comment by RobinBuschmann** [comment]
Hey @ClueGuy, thanks for reporting

**Comment by TalissonJunior** [comment]
Any updates ?

**Comment by RobinBuschmann** [comment]
@TalissonJunior This will be part of `sequelize-typescript@1.0.0` - I'm working on it

**Comment by TalissonJunior** [comment]
@RobinBuschmann  Awesome, i´m excited to see that new version.

**Comment by Romstar** [comment]
how are you even able to access the sequelize object?  Why am I not able to do this?  I can't run raw queries, change the default timeout from 15 seconds to longer, or even called stored procedures.  How do I do that?

**Comment by TalissonJunior** [comment]
@Romstar  you need to get the instance of your sequelize connection, then you can run raw queries here is an example:

```js
var mySequelize = new Sequelize({
            host: 'host',
            database: 'database',
            dialect: 'dialect',
            username: 'username',
            password: 'password',
            modelPaths: [__dirname + '/Models/**/**']
        });

// Here you can you use your sequelize instance to run raw queries.
mySquelize.query(query, {
            replacements: [this.user.id],
            model: MyModel
        });
```

Hope it helps.

**Comment by TalissonJunior** [comment]
@Romstar can you provide a minimal code or a repository that i can access to check out this issue?

**Comment by Romstar** [comment]
@TalissonJunior  I can, I'll just create a new repository with the same package json and a single index.ts file creating a new sequelize instance and failing to have a query accessible as well as the config being limited.  I'll link you here when I do it.

**Comment by Rodrigo54** [comment]
This works for me.

```typescript
var mySequelize = new Sequelize({
  host: 'host',
  database: 'database',
  dialect: 'dialect',
  username: 'username',
  password: 'password',
  modelPaths: [__dirname + '/Models/**/**']
});

mySequelize.query(query, {
  replacements: [this.user.id],
  model: mySequelize.models.MyModel // <-- This works for me.
});
```

**Comment by BenjaminDish** [comment]
Nice workaround @Rodrigo54, waiting for the v1.0.0 fix.

**Comment by RobinBuschmann** [comment]
Fixed on branch `1.0.0` and is released with `sequelize-typescript@1.0.0-alpha.8`

**Comment by vipulpatel1994** [comment]
How should i do in my repo

**Comment by RobinBuschmann** [comment]
@vipulpatel1994, if you use `sequelize-typescript@1.0.0`, this should do the trick:
```ts
sequelize.query('SELECT ...', {model: YourModel });
```

**Comment by RoelRoel** [comment]
> This works for me.
> 
> ```ts
> var mySequelize = new Sequelize({
>   host: 'host',
>   database: 'database',
>   dialect: 'dialect',
>   username: 'username',
>   password: 'password',
>   modelPaths: [__dirname + '/Models/**/**']
> });
> 
> mySequelize.query(query, {
>   replacements: [this.user.id],
>   model: mySequelize.models.MyModel // <-- This works for me.
> });
> ```

Warning: This will not include computed properties added to your models

**Comment by srkimir** [comment]
How this would work if you are using `group by` raw query?
