### ISSUE TITLE
Table decorator overloaded returning incorrect void type

### ISSUE THREAD

**Issue by Danlock** [RobinBuschmann/sequelize-typescript#282]
So first of all, if a decorator returns void instead of Function on strict mode typescript throws an error because of this, and it can't really be worked around., or used as a decorator in strict mode. So the type is wrong because of that. 

https://github.com/Microsoft/TypeScript/issues/4534
https://stackoverflow.com/questions/36446480/typescript-decorator-reports-unable-to-resolve-signature-of-class-decorator-whe

The way I found it is that IDefineOptions is incorrect, in that it doesn't allow indexes with where conditions. This type definition is hosted outside the library, so it isn't as relevant but it causes making a table with decorators with partial indexes throw errors on typescript strict mode.

The quick workaround is to just set the where key under indexes as an any key on the object so typescript cant detect it. such as 

` ['where' as any] `

**Comment by Danlock** [comment]
I tried to solve the issue by returning void or void|Function, but neither passes the tests. 
Ill take another look when I have more time, typecasting it to any isn't really a solution.

**Comment by RobinBuschmann** [comment]
Hey @Danlock which exact strict option do you mean?

**Comment by Danlock** [comment]
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "lib": ["es2015","es2016","es2017"],
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "noImplicitReturns": false,
    "noEmitOnError": true,
    "strictNullChecks": true,
    "traceResolution": false,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "noImplicitAny": true,
    "alwaysStrict": true,
    "strict": true,
    "module": "commonjs",
    "outDir": "./build",
    "baseUrl": "./src",
    "target": "es2017",
    "inlineSourceMap": true,
    "allowJs": true,
    "pretty": true
  },
  "include": [
    "./package.json",
    "./tsconfig.json",
    "./src/**/*"
  ],
  "paths": {
    "src/*" : ["./src/**/*"]
  }
}
```

Posted is my tsconfig.json

**Comment by mxs42** [comment]
Any updates on this? Examples from readme simply don't compile in strict mode.

**Comment by RobinBuschmann** [comment]
Sry completely overseen this issue. But `where` seems to work perfectly well in `@Table({indexes: [{where: {bla: 'sdfdsf'}}]})`

@mxs42 What's your issue here? :)

**Comment by mxs42** [comment]
@RobinBuschmann well, it turns out that I messed with types while hot-fixing an issue with AnyWhereOptions and broke some code accidentally 😆
No issues on my sides anymore, I should be more careful I guess.

**Comment by RobinBuschmann** [comment]
@Danlock @mxs42 Is this still an issue? I couldn't reproduce it.

**Comment by Danlock** [comment]
I also don't use typescript anymore, so If you can't reproduce it, that's good enough for me.
