### ISSUE TITLE
ISequelizeConfig

### ISSUE THREAD

**Issue by dkuida** [RobinBuschmann/sequelize-typescript#284]
Hey
First of all - great job, really love the library - spent with it the whole day and it is really saving time.

now to the issue

in Interface ISequelizeConfig there is a definition that goes this way
```javascript
/**
     * Path to models, which should be loaded
     */
    modelPaths?: string[];
```
but that means that a definition in the form of 

```javascript
const configDb: SequelizeConfig = {
    dialect: 'postgres',
    modelPaths: [Country], ...config.countriesDb
};
```
throws an error TS2322 = because clearly `Country` is a model and not a string

what do you I miss here?

**Comment by RobinBuschmann** [comment]
Hey @dkuida, thank you :)

This is currently not possible via the config. You need to create an instance of `import {Sequelize} from 'sequelize-typesctipt';` and then you can call `addModels` like

```ts
const sequelize = new Sequelize({...});
sequelize.addModels([Country]);
```

But yes, it would make sense to enable adding models to the configuration like:
```ts
const configDb: SequelizeConfig = {
    dialect: 'postgres',
    models: [Country], ...config.countriesDb
};
```
Any PRs are welcome :)
