### ISSUE TITLE
Missing sourceKey in AssociationOptionsHasMany.

### ISSUE THREAD

**Issue by operandom** [RobinBuschmann/sequelize-typescript#287]
Hi !
Is it possible to update @types/sequelize to remove the problem ?
Thx !

**Comment by RobinBuschmann** [comment]
Hey @operandom thanks for reporting. 

We need to update `@types/sequelize` dependency to fix this

**Comment by RobinBuschmann** [comment]
Fixed with latest sequelize-typescript version
