### ISSUE TITLE
how can I association corss_model with unique key

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#289]
I have three model `User` , `UserOrganization`, `Organization`.  and I want to `manytomany` association , but not use `Primary Key` instead using `unique Key` , these model defind like 
```
-- user model
class User extends Model<User> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @Unique
    @Column
    public policeNumber: string;

    @BelongsToMany(() => Organization, () => UserOrganization, "code")
    public organization: Organization[];
}

-- Organization model
class Organization extends Model<Organization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @Unique
    @Column
    public code: string;

    @BelongsToMany(() => User, () => UserOrganization, "policeNumber")
    public users: User[];
}

-- UserOrganization model
class UserOrganization extends Model<UserOrganization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @ForeignKey(() => User)
    @Column
    public policeNumber: string;

    @Column
    public name: string;

    @ForeignKey(() => Organization)
    @Column
    public code: string;
}
```
I insert data, error like this 
![image](https://user-images.githubusercontent.com/17508916/35554109-80981bc0-05d5-11e8-9358-6cb74c737105.png)

How can I defined  `manytomany` association with unique key

**Comment by RobinBuschmann** [comment]
Hey @chaoxihailing I will come back to you as soon as possible. But unfortunately I have no time until the end of the week.

**Comment by chaoxihailing** [comment]
@RobinBuschmann hey，are you have time to continue answer my question  ?

**Comment by RobinBuschmann** [comment]
@chaoxihailing I've looked into it, but couldn't find a solution. Can you address your issue with a native sequelize example to the sequelize team instead?

**Comment by chaoxihailing** [comment]
I sorry about this problem that I used not mapping data in userOrganization.
