### ISSUE TITLE
Extending Model's static methods

### ISSUE THREAD

**Issue by alonewarrior** [RobinBuschmann/sequelize-typescript#291]
Hey, I'm new to using this library and am converting over my codebase to typescript. In an effort to implement caching, I'm trying to find the most viable solution possible without having to rewrite and introduce a ton of additional logic throughout the application to support it. 

What I'm hoping to do is write a class that extends Model and subsequently extends certain static find methods to add a layer for checking the cache before going onward. As of right now, Typescript throws errors when I attempt to do this, stating that I cannot assign an abstract constructor to a non-abstract constructor. Are there any recommendations to circumvent this, or allow it to occur with a simple extension? Any help would be much appreciated!

Currently, my error: 
````The 'this' context of of type 'typeof Model' is not assignable to methid's 'this' of type 'new () => T'. Cannot assign an abstract constructor type to a non-abstract constructor type.````

**Comment by RobinBuschmann** [comment]
Hey @alonewarrior, can you provide a specific example?

**Comment by alonewarrior** [comment]
Sure! I'm creating a BaseModel that I'm extending from to provide pre-defined columns for each table that exists (not sure how well this is going to work yet):

````
@Table({
    paranoid: true,
    freezeTableName: true,
    timestamps: true,
    underscored: true
})
export class BaseModel<E> extends Model<BaseModel<E>> {
    @Column(DataType.STRING(2048))
    notes: string;
    
    @Column(DataType.STRING)
    add_user_id: string;
    
    @Column(DataType.STRING)
    change_user_id: string;
    
    @CreatedAt
    add_date: Date;
    
    @UpdatedAt
    change_date: Date;
    
    @DeletedAt
    delete_date: Date;
    
    static findAll<T extends Model<T>>(this: (new () => T), options?: IFindOptions<T>): Promise<T[]> {
        return super.findAll<T>(options);
    }
}
````

I'd like to extend findAll (and a few others), and I've tried putting in many different combinations for the findAll type and none have worked.

**Comment by RobinBuschmann** [comment]
Unfortunately I can only provide a workaround for that: Using `call` omits the error:
```ts
return super.findAll.call(this, options);
```
There seems to be an issue with `this` in static functions (https://github.com/Microsoft/TypeScript/issues/20264 this was closed and labelled with `Design Limitation`)

**Comment by alonewarrior** [comment]
@RobinBuschmann This will work! Thanks so much!!

**Comment by ostar0816** [comment]
@alonewarrior how did you get it work?
I am getting this error when I try `return super.findAll.call(this, options);
 `
Class static side 'typeof ParentModel' incorrectly extends base class static side 'typeof Model'.
  The types returned by 'findOne(...)' are incompatible between these types.
    Type 'Bluebird<Model<any>>' is not assignable to type 'Bluebird<T>'.
      Type 'Model<any>' is not assignable to type 'T'.
        'Model<any>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Model<T>'.
