### ISSUE TITLE
Need to disable 'strictPropertyInitialization' in TS 2.7 or later

### ISSUE THREAD

**Issue by vichyssoise** [RobinBuschmann/sequelize-typescript#292]
Or you get `
Property '' has no initializer and is not definitely assigned in the constructor.` error.

Add below to your tsconfig.json
```js
{
  "compilerOptions": {
    ...
    "strictPropertyInitialization": false
  }
}
```

**Comment by RobinBuschmann** [comment]
@vichyssoise thanks for posting this. So you mean it is enough to set this property to the main app which uses `sequelize-typescript` or is it also necessary to add `"strictPropertyInitialization": false` to the tsconfig.json of `sequelize-typescript`?

**Comment by vichyssoise** [comment]
@RobinBuschmann 
The former is required it for creating new Model like

```ts
@Table
class User extends Model<User> {
  @Column
  username: string  // Property '' has no initializer and is not definitely assigned in the constructor.
}
```

and also tsconfig.json at`/test` in this repository might be required.

**Comment by manV** [comment]
Would "definite assignment assertion modifiers " help? See "Definite Assignment Assertions" section on [this page](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html)

**Comment by Darkseal** [comment]
Other than setting the `strictPropertyInitialization` flag to `false`, you can also change your TS code and use the new _definite assignment assertion_ modifiers for the affected properties.

For additional info on that (and other workarounds/fixes), [read this post](https://www.ryadel.com/en/ts2564-ts-property-has-no-initializer-typescript-error-fix-visual-studio-2017-vs2017/).

**Comment by aasmm7x** [comment]
Using the `!` modifier solved my problem without disable the property initialization rule!

Thanks @Darkseal

**Comment by RobinBuschmann** [comment]
What @Darkseal stated, using`!` is the way to go. Closing this issue now

**Comment by unflores** [comment]
This is kind of a bummer, it means that whenever I get something from the database and do manipulations on it, I have to then cast it to the value of the attribute.

```
const appIds: string[] = apps.slice(1, -1).map(app => <string>app.id)
```
In this example the compiler complains about `appIds` being `undefined | string`. :(

**Comment by RobinBuschmann** [comment]
Hey @unflores, can you open a new issue for that? Best with more information about you model?

**Comment by unflores** [comment]
@RobinBuschmann Sorry for the noise, I didn't properly understand what `strictPropertyInitialization` was doing. That will be fine for my needs.

**Comment by mathemaudio** [comment]
Let me clarify about the _!_ sign - you should put it after the class member name, like this:
`class Foo{  bar!:Node  }`
instead of 
`class Foo{  bar:Node  }`

**Comment by Alejandro742** [comment]
![Screen Shot 2021-11-18 at 12 14 21](https://user-images.githubusercontent.com/56900549/142472989-8e91c5b9-159e-4688-b9dd-d6fefccadf24.png)
If your are using VsCode just reload the window

**Comment by Alejandro742** [comment]
> > Or you get ` Property '' has no initializer and is not definitely assigned in the constructor.` error.
> > Add below to your tsconfig.json
> > ```js
> > {
> >   "compilerOptions": {
> >     ...
> >     "strictPropertyInitialization": false
> >   }
> > }
> > ```
> 
> I have used `"strictPropertyInitialization": false` and the project is running perfectly. But in the editor (VSCode), there is a red indicator is still appearing. Would you like to give me any solution to this problem?

![Screen Shot 2021-11-18 at 12 14 21](https://user-images.githubusercontent.com/56900549/142472989-8e91c5b9-159e-4688-b9dd-d6fefccadf24.png)

Just reload the window

**Comment by ashraful-talukder** [comment]
> > > Or you get ` Property '' has no initializer and is not definitely assigned in the constructor.` error.
> > > Add below to your tsconfig.json
> > > ```js
> > > {
> > >   "compilerOptions": {
> > >     ...
> > >     "strictPropertyInitialization": false
> > >   }
> > > }
> > > ```
> > 
> > 
> > I have used `"strictPropertyInitialization": false` and the project is running perfectly. But in the editor (VSCode), there is a red indicator is still appearing. Would you like to give me any solution to this problem?
> 
> ![Screen Shot 2021-11-18 at 12 14 21](https://user-images.githubusercontent.com/56900549/142472989-8e91c5b9-159e-4688-b9dd-d6fefccadf24.png)
> 
> Just reload the window

Thank you so much for your response. I had applied your suggestion and still, my problem exists.
