### ISSUE TITLE
Incomplete types for QueryInterface

### ISSUE THREAD

**Issue by jaydp17** [RobinBuschmann/sequelize-typescript#294]
I was working with `QueryInterface` and `constraints` where I noticed there are some types missing.

### For example:
[showConstraint(..)](https://github.com/sequelize/sequelize/blob/a4a0f883bdb48e9d5092fa8fd750b880ef8ffbe2/lib/query-interface.js#L865)

The return type of that function i.e. `Constraint`

**Comment by RobinBuschmann** [comment]
Hi @jaydp17, thanks for reporting, but these typings need to be added to the sequelize type definitions instead. So it is not part of sequelize-typescript https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts :)
