### ISSUE TITLE
Multiple relation to the same model problem

### ISSUE THREAD

**Issue by kjamrog** [RobinBuschmann/sequelize-typescript#295]
In Project model I have two relations to User model. One of them is M:N realized by ProjectsUsers model:

  `// Project model`
 `@ForeignKey(() => User)`
 `@Column`
  `created_by_id: number;`

  `@BelongsTo(() => User, 'created_by_id')`
  `created_by: User;`

  `@BelongsToMany(() => User, () => ProjectsUsers)`
  `users: User[];`

  `// User model`
  `@BelongsToMany(() => Project, () => ProjectsUsers)`
  `projects: Project[];`

 `// ProjectsUsers model`
  `@ForeignKey(() => Project)`
  `@Column`
  `project_id: number;`

  `@ForeignKey(() => User)`
  `@Column`
  `user_id: number;`

While creating models I get following error:
`Error: Alias cannot be inferred: "Project" has multiple relations with "User"`

Could you please help me to resolve this issue?
Thanks in advance

**Comment by RobinBuschmann** [comment]
Hey @kjamrog, can you provide the code of the creation call?

**Comment by kjamrog** [comment]
Hey, thanks for quick reply.
I'm just creating Sequelize object and calling sync() method. Everything works fine when I remove one of the relations from Project model.

**Comment by kjamrog** [comment]
I double checked now and the error appears when creating Sequelize object, even before calling sync() method

**Comment by RobinBuschmann** [comment]
Hmm, I cannot reproduce it. Can you provide an example repository so that I can have a look at?

**Comment by kjamrog** [comment]
When trying to create some minimal code snippet to reproduce it, I found out what is the problem. In Project model I had defined scope in which I included User model without 'as' keyword. Something like that:

```
@Scopes({
  withUser: {
   include: [() => User]
  }
})
@Table({tableName: 'projects'})
export default class Project extends Model<Project> {...}
```

After adding 'as' keyword it works as expected.

Anyway, thank you very much for your time!

**Comment by RobinBuschmann** [comment]
You're welcome :)
