### ISSUE TITLE
Unique index on 2 or more fields

### ISSUE THREAD

**Issue by Djay77** [RobinBuschmann/sequelize-typescript#298]
Hello,

Is it possible to index 2 (or more) fields as unique like in the official documentation  ? : http://docs.sequelizejs.com/manual/tutorial/models-definition.html#indexes

`indexes: [
    {
      unique: true,
      fields: ['yyy', 'xxx']
    }]`

Thanks you

**Comment by RobinBuschmann** [comment]
Hey, sure, try it like so:

```ts
@Table({
  indexes: [
    {
      unique: true,
      fields: ['yyy', 'xxx']
    }
  ]
})
export class YourModel extends Model<YourModel> {

}

```

**Comment by Djay77** [comment]
Damn, I tried with :

`indexes: {
        unique: true,
        fields: ['scope', 'path']
    }`

Thanks you 👍
