### ISSUE TITLE
Specifying string length does not appear to generate proper schema (sqlite3)

### ISSUE THREAD

**Issue by taicho** [RobinBuschmann/sequelize-typescript#3]
If using the "@Column" attribute with DataType.String(someLength) the model does not appear to generate the correct schema and instead generates a column in the sqlite database with an incorrect "[object Object]" column type, very bizarre. I've tried using @Column({type: DataType.String(someLength)}) and have used the raw Sequelize.STRING type as well. With no arguments the column generates properly with a VARCHAR(255) data type but when length is specified it does not appear to work. Thoughts?

**Comment by RobinBuschmann** [comment]
This is a bug, thank you for reporting. I will solve this tomorrow morning.

**Comment by RobinBuschmann** [comment]
@taicho It should work now. I published a new version to npm: `sequelize-typescript@0.2.1`.

**Comment by taicho** [comment]
@RobinBuschmann can confirm works like a charm now! Thanks for such a quick fix.
