### ISSUE TITLE
how to use unique key  instead of primary key in one-to-one assoction

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#305]
I have two model `AdminUser`, `Organization`, and I want to use `unique key` `Organzation.code` assoction `AdminUser.organizationCode` instead of primary key `id`
```

export class AdminUser extends Model<AdminUser> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

   @ForeignKey(() => Organization)
    public organizationCode: string;

    @BelongsTo(() => Organization, "organizationCode")
    public organization: Organization;
}

export class Organization extends Model<Organization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @Unique
    @Column
    public code: string;

    @HasOne(() => AdminUser)
    public adminUser: AdminUser;
}

```
but sql query is still use `organization.id` associate
![image](https://user-images.githubusercontent.com/17508916/36138300-d191f204-10d3-11e8-98dc-2d26a11af3ce.png)

how to make right associate like ``AdminUser`.`organizationCode` = `organization`.`code``

**Comment by RobinBuschmann** [comment]
Hey @chaoxihailing, actually you need to use `targetKey` like so:

```ts
@BelongsTo(() => Organization, {targetKey: 'code'})
```

⚠️But this doesn't seem to work with `HasOne`.  Regarding (this)[https://github.com/sequelize/sequelize/issues/8105] this is an issue with sequelize.

So you could use `@HasMany` as a workaround :/

**Comment by chaoxihailing** [comment]
thanks，it can work normally
