### ISSUE TITLE
Multiple tables of same Model

### ISSUE THREAD

**Issue by jtrujillo7** [RobinBuschmann/sequelize-typescript#306]
Hi,

Is there a way to have multiple tables (different table names) in the same database using a single model definition?

Hacking around I found, given a Model Customer
```
    class Customer2 extends Customer{
    }
    Customer2.tableName="alternateTable";
```
And from here I could sync() and save() to the alternate table name. Maybe there's a more standard way...
Thanks!

**Comment by RobinBuschmann** [comment]
Hey @jtrujillo7 you could use inheritance to achieve this. So, no, you will need separate models, but you could define one model from which other models will inherit:

```ts
class BaseCustomer<T> extends Model<T> {

  /* your identical columns goes here */

}

@Table({tableName: 'customer1'})
class Customer1 extends BaseCustomer {}


@Table({tableName: 'customer2'})
class Customer" extends BaseCustomer {}

```

What do you think?

**Comment by jtrujillo7** [comment]
It's a beautiful solution.
Just one detail that I am confused with, indexes.
Here is an attempt to create two tables with the same model and index structure:

```
class BaseCustomer extends Model<BaseCustomer> {
    @PrimaryKey @AutoIncrement
    @Column(DataType.INTEGER)
    id:number;
    @Column(DataType.STRING)
    name:string;
    @Column(DataType.INTEGER)
    age:number;
  
  }
  let indexCustomer=[{fields:["id"]},{fields:["name"]}];    // Common indexes
  
 @Table({tableName: 'customer1',indexes:indexCustomer})  //ts: Unable to resolve signature of class decorator when called as an expression. Cannot invoke an expression whose type lacks a call signature. Type 'void' has no compatible call signatures.
  class Customer1 extends BaseCustomer {}
  
  
  @Table({tableName: 'customer2'})
  class Customer2 extends BaseCustomer {}

```
Trying to add the index in the `@Table` decorator give that ts error that, frankly, I don't understand.
The only way I've found would be adding the indexes after the tables are created with

`sequelize.queryInterface.addIndex('Customer1',indexCustomer[0]);
`
etc.
Is there a better way to specify common indexes?

Thanks!

**Comment by RobinBuschmann** [comment]
Indeed, that's strange. tsc doesn't seem to be able to infer the type correctly. But annotating indexCustomer with the actual type `DefineIndexesOptions ` fixes this:

```ts
const indexCustomer: DefineIndexesOptions[] = [
  {fields: ["id"]},
  {fields: ["name"]}
  ];

```

**Comment by jtrujillo7** [comment]
Perfect, thanks so much!

**Comment by ermamud** [comment]
HI, I tried the same example above, and I am getting this error:
`@Table annotation is missing on class BaseCustomer `

Any ideas?
