### ISSUE TITLE
Error in use operator aliases

### ISSUE THREAD

**Issue by leonetosoft** [RobinBuschmann/sequelize-typescript#308]
I am not able to use operators like $ or, $ and ... is accusing error
```
searchUserInCompany(busines_id, userLogin) {
        return DbConnection.Instance.entities.user.findAll({
            attributes: ['id', 'nickname', 'email'],
            where: {
                
                $or: [{ email: { $like: userLogin + '%' } },
                { nickname: { $like: userLogin + '%' } }],
                busines_id: busines_id
            },
            raw: true
        });
    }
```

**Comment by RobinBuschmann** [comment]
Hey @leonetosoft can you provide the actual error?

**Comment by CFCSystem** [comment]
Hello!
Utilizando o operador $or está dando erro de compilação typescript:

Script: `user.findAll({
            attributes: ['id', 'nickname', 'email'],
            where: {
                $or: [{ email: { $like: userLogin + '%' } },
                { nickname: { $like: userLogin + '%' } }],
                busines_id: busines_id
            },
            raw: true
        });`

`TSError: ⨯ Unable to compile TypeScript
src/managers/users/UserManager.ts (16,17): Argument of type '{ attributes: string[]; where: { $or: ({ email: { $like: string; }; } | { nickname: { $like: stri...' is not assignable to parameter of type 'FindOptions<userAttribute>'.
  Types of property 'where' are incompatible.
    Type '{ $or: ({ email: { $like: string; }; } | { nickname: { $like: string; }; })[]; busines_id: any; }' is not assignable to type 'fn | where | (string | col | and | or)[] | WhereOptions<userAttribute>'.
      Object literal may only specify known properties, and '$or' does not exist in type 'fn | where | (string | col | and | or)[] | WhereOptions<userAttribute>'. (2345)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:307:15)
    at /usr/lib/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)`

**Comment by CFCSystem** [comment]
I had to use it this way:

`entities.user.findAll({
            attributes: ['id', 'nickname', 'email'],
            where: {
                [Sequelize.Op.or]: [{ email: { $like: userLogin + '%' } },
                { nickname: { $like: userLogin + '%' } }],
                busines_id: busines_id
            },
            raw: true
        });`

**Comment by leonetosoft** [comment]
@RobinBuschmann 
Hello!
Utilizando o operador $or está dando erro de compilação typescript:

Script: `user.findAll({
            attributes: ['id', 'nickname', 'email'],
            where: {
                $or: [{ email: { $like: userLogin + '%' } },
                { nickname: { $like: userLogin + '%' } }],
                busines_id: busines_id
            },
            raw: true
        });`

`TSError: ⨯ Unable to compile TypeScript
src/managers/users/UserManager.ts (16,17): Argument of type '{ attributes: string[]; where: { $or: ({ email: { $like: string; }; } | { nickname: { $like: stri...' is not assignable to parameter of type 'FindOptions<userAttribute>'.
  Types of property 'where' are incompatible.
    Type '{ $or: ({ email: { $like: string; }; } | { nickname: { $like: string; }; })[]; busines_id: any; }' is not assignable to type 'fn | where | (string | col | and | or)[] | WhereOptions<userAttribute>'.
      Object literal may only specify known properties, and '$or' does not exist in type 'fn | where | (string | col | and | or)[] | WhereOptions<userAttribute>'. (2345)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:307:15)
    at /usr/lib/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)`

I had to use it this way:

`entities.user.findAll({
            attributes: ['id', 'nickname', 'email'],
            where: {
                [Sequelize.Op.or]: [{ email: { $like: userLogin + '%' } },
                { nickname: { $like: userLogin + '%' } }],
                busines_id: busines_id
            },
            raw: true
        });`

**Comment by RobinBuschmann** [comment]
@leonetosoft sorry, I have completely overseen your answer. Yeah I see, seems to be an issue with the sequelize typings. But since the usage of `$or`, `$in` and so on is deprecated in favor of using symbols instead, I wouldn't investigate this anymore. So I will close this issue, if it is ok for you?

**Comment by leonetosoft** [comment]
@RobinBuschmann By min is okay, it works normal the way I demonstrated. Thank you for your work!

**Comment by ningacoding** [comment]
still a sequelize typings issue, because is not totally deprecated, you even can pass custom operator names by aliases:

http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-aliases

wich should be supported by sequelize-typescript, since is a current and available option.

**Comment by RobinBuschmann** [comment]
hey @ningacoding, yeah, you're right, but this need to be partially fixed here  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize
since {where: {someProperty: {$or: [...]}}} is part of the native sequelize typings

I also noticed that sequelize-typescript need to be adjusted to support: `{where: {$or: ..., $and: ...}}`
