### ISSUE TITLE
How to share models between server and browser

### ISSUE THREAD

**Issue by Toxicable** [RobinBuschmann/sequelize-typescript#310]
I'd like to share my models between front and backend so I only have one definition, but that currently appear to be possible since importing any class with the annotations in them brings in all the Nodejs binaries such as `dns` which cannot be used on the browser

**Comment by RobinBuschmann** [comment]
Hey @Toxicable, i think this won't be possible without installing `sequelize` and `sequelize-typescript` on the frontend as well, which won't work in a browser.

What about using interfaces instead? These interfaces can then be implemented by your backend- and frontend classes or  maybe you can use interfaces only on frontend?

**Comment by Toxicable** [comment]
Yup I'm doing the Interface approach at the moment. Like so
```
interface Person {
name: string;
}

@Table
class Person implements Person extends Model<Person> {
  @Colunm
  name: string
}
```
Just would be nice if we could just use the same class on the frontend instead.
Maybe providing a shim for the decorators that can be resolved by the frontend would resolve the `sequelize` dependency?

**Comment by RobinBuschmann** [comment]
Yeah, this would work. But it seems to me that it is not so easy to achieve and I would say it wouldn't be part of this project. But if you want to give it a try, I'm happy if you'll come back with your knowledge :)

**Comment by Toxicable** [comment]
fixed by https://github.com/RobinBuschmann/sequelize-typescript/pull/574
