### ISSUE TITLE
findAll does not populate dataValues in Model instance

### ISSUE THREAD

**Issue by saachinsiva** [RobinBuschmann/sequelize-typescript#311]
We are facing issue with very basic model where findAll methods returns all the value as null except for the primary key in the dataValues but however we find that all the values are populated in previousDataValues butif we use raw=true, we can get the actual value but not as Model instance. Please see below the code. Please let me know what are we doing wrong here.

Note : The data already exists in the table.

`	

    import { Table, Column, Model, HasMany, DataType, PrimaryKey } from 'sequelize-typescript';

	@Table({
		tableName: 'ADDRESS_TYPE'
	})
	export class AddressTypeSeq extends Model<AddressTypeSeq> {
		@PrimaryKey
		@Column({
			type: DataType.STRING,
			field: 'Address_Type_Code'
		})
		code: string = null;

		@Column({
			type: DataType.STRING,
			field: 'Name'
		})
		name: string = null;

		@Column({
			type: DataType.INTEGER,
			field: 'Input_User_ID'
		})
		createdBy: string = null;

		@Column({
			type: DataType.DATE,
			field: 'Input_TS'
		})
		createdOn: string = null;

		@Column({
			type: DataType.INTEGER,
			field: 'Audit_User_ID'
		})
		updatedBy: string = null;

		@Column({
			type: DataType.DATE,
			field: 'Audit_TS'
		})
		updatedOn: string = null;

		@Column({
			type: DataType.DATEONLY,
			field: 'Effective_Date'
		})
		effectiveDate: string = null;

		@Column({
			type: DataType.DATEONLY,
			field: 'Expiration_Date'
		})
		expirationDate: string = null;
	}

DAO Class

    export class AddressTypeDAO {
		static async getAll(): Promise<AddressTypeSeq[]> {
			const res1: AddressTypeSeq[] = await AddressTypeSeq.findAll<AddressTypeSeq>();
			console.log(res1[0])
			return res1;
		}
	}

Output
	
     AddressTypeSeq {
	  dataValues:
	   { code: 'M',
		 name: null,
		 createdBy: null,
		 createdOn: null,
		 updatedBy: null,
		 updatedOn: null,
		 effectiveDate: null,
		 expirationDate: null },
	  _previousDataValues:
	   { code: 'M',
		 name: 'Mailing Address',
		 createdBy: 0,
		 createdOn: 2017-08-06T12:32:01.877Z,
		 updatedBy: 0,
		 updatedOn: 2017-08-06T12:32:01.877Z,
		 effectiveDate: 2017-08-17T00:00:00.000Z,
		 expirationDate: 9999-12-31T00:00:00.000Z },
	  _changed:
	   { name: true,
		 createdBy: true,
		 createdOn: true,
		 updatedBy: true,
		 updatedOn: true,
		 effectiveDate: true,
		 expirationDate: true },
	  _modelOptions:
	   { timestamps: false,
		 validate: {},
		 freezeTableName: true,
		 underscored: false,
		 underscoredAll: false,
		 paranoid: false,
		 rejectOnEmpty: false,
		 whereCollection: null,
		 schema: null,
		 schemaDelimiter: '',
		 defaultScope: {},
		 scopes: [],
		 indexes: [],
		 name: { plural: 'AddressTypeSeqs', singular: 'AddressTypeSeq' },
		 omitNull: false,
		 tableName: 'ADDRESS_TYPE',
		 instanceMethods:
		  AddressTypeSeq {
			_customGetters: {},
			_customSetters: {},
			validators: {},
			_hasCustomGetters: 0,
			_hasCustomSetters: 0,
			rawAttributes: [Object],
			attributes: [Array],
			_isAttribute: [Object] },
		 classMethods: AddressTypeSeq,
		 sequelize:
		  Sequelize {
			options: [Object],
			config: [Object],
			dialect: [Object],
			queryInterface: [Object],
			models: [Object],
			modelManager: [Object],
			connectionManager: [Object],
			importCache: {},
			test: [Object],
			throughMap: {},
			_: [Object] },
		 hooks: {},
		 uniqueKeys: {} },
	  _options:
	   { isNewRecord: false,
		 _schema: null,
		 _schemaDelimiter: '',
		 raw: true,
		 attributes:
		  [ 'code',
			'name',
			'createdBy',
			'createdOn',
			'updatedBy',
			'updatedOn',
			'effectiveDate',
			'expirationDate' ],
		 includeNames: [] },
	  __eagerlyLoadedAssociations: [],
	  isNewRecord: false }

`

**Comment by RobinBuschmann** [comment]
Hey @saachinsiva this is because you're setting them `null`. If you think about how an object is instantiated: The values which get mapped from the database will be initialized in the super call - your `= null` initialization will happen afterwards. So you can imagine it like:

```ts
class AddressTypeSeq extends Model< AddressTypeSeq> {
  constructor(values) {
    super(values); // 'code' and so on is initialized here
    this.code = null; // ... and you overriding it here with null after the proper values are set
    ...
  }
}
```

So you need to omit the `null` initialization and everything should work very well 😊

**Comment by saachinsiva** [comment]
@RobinBuschmann 

Thanks for the information. I just figured it myself and about to reply.  Everything is working fine now after I removed the initialization.
