### ISSUE TITLE
Association "HasOne" & scope

### ISSUE THREAD

**Issue by Relik77** [RobinBuschmann/sequelize-typescript#312]
Hi,

With sequelize it's possible to use "scope" with "hasOne" relation.
For exemple for :
```ts
@Table
class WebSite extends Model<WebSite> {
    @PrimaryKey
    @AutoIncrement
    @Column(DataType.INTEGER)
    id: number;
    
    @HasMany(() => Page, {
    })
    Pages: Page[];
    
    @HasOne(() => Page, {
         scope: {
             type: "home"
         }
    })
    HomePage: Page;
}

@Table
class Page extends Model<Page> {
    @PrimaryKey
    @AutoIncrement
    @Column(DataType.INTEGER)
    id: number;
    
    @AllowNull(false)
    @ForeignKey(() => WebSite)
    @Column(DataType.INTEGER)
    website_id: number;
    
    @BelongsTo(() => WebSite, {
        onUpdate: "CASCADE",
        onDelete: "CASCADE"
    })
    WebSite: WebSite;
    
    @AllowNull(false)
    @Column(DataType.STRING)
    type: string;
}
```

it works, but it would be necessary to update ```AssociationOptionsHasOne``` interface to avoid a typescript error :

```ts
interface AssociationOptionsHasOne extends AssociationOptions {
    scope?: AssociationScope; // here
    keyType?: DataTypeAbstract;
}
```

**Comment by RobinBuschmann** [comment]
Thank you for reporting!

**Comment by firou1925** [comment]
Any updates on this?

**Comment by RobinBuschmann** [comment]
I didn't realized in the first place, but this is an issue in the sequelize typings, not in the sequelize-typescript ones. So  one need to update the sequelize typings in order to fix this.

**Comment by dancrumb** [comment]
I have created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35420 to address the typings issue in sequelize

**Comment by dancrumb** [comment]
FWIW: You could address this with declaration merging, in the interim: http://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by dancrumb** [comment]
Perhaps #312 is a better solution for this - make the DefinitelyTyped types a peer dependency and allow the users of `sequelize-typescript` to handle this with declaration merging?

**Comment by jpollard-cs** [comment]
assuming we now need to update the typings that ship with sequelize to get this to work?

**Comment by RobinBuschmann** [comment]
Since sequelize ships typings (where the assoication types are fixed) since version 5, this isn't an issue anymore
