### ISSUE TITLE
how to use unique key instead of primary key in many-to-many assoction

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#317]
I have three model User, Organization, UserOrganization   and I want to use unique key Organzation.code assoction UserOrganization.organizationCode instead of primary key id

    ---User
    Class User extends Model<User> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @Unique
    @Column
    public policeNumber: string; 

    @BelongsToMany(() => Organization, () => UserOrganization)
    public organizations: Organization[];
    }

    ---UserOrganization
    Class UserOrganization extends Model<UserOrganization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @ForeignKey(() => User)
    @Column
    public userId: number;

    @ForeignKey(() => Organization)
    @Column
    public organizationCode: string;
    }

    ---Organization
    Class Organization extends Model<Organization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @Unique
    @Column
    public code: string;

    @BelongsToMany(() => User, () => UserOrganization)
    public users: User[];
    }
but it error `UserOrganization is not associated to User`, How does I write right assoction?

**Comment by RobinBuschmann** [comment]
`targetKey` would be the proper option for that. Unfortunately this is only supported for `BelongsTo` associations, not for `BelongsToMany` in sequelize. But there is an open PR for that feature https://github.com/sequelize/sequelize/pull/8143
