### ISSUE TITLE
 SequelizeEagerLoadingError

### ISSUE THREAD

**Issue by chaoxihailing** [RobinBuschmann/sequelize-typescript#318]
It is normal `manyTomany` association example,and I did `sequelize.addModels([User,Organiztion,UserOrganization]);`

    class User extends Model<User> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;
    }

    class Organization extends Model<Organization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;
    }

    class UserOrganization extends Model<UserOrganization> {
    @PrimaryKey
    @AutoIncrement
    @Column
    public id: number;

    @ForeignKey(() => User)
    @Column
    public userId: number;

    @ForeignKey(() => Organization)
    @Column
    public organizationId: number;
    }
   
and I query data like blow

    let result = await User.findAll({
            where: {
                policeNumber: { $in: userCodes },
            },
            include: [{
                model: UserOrganization,
                include: [{
                    model: Organization,
                }],
            }],
        });
but it error 
![image](https://user-images.githubusercontent.com/17508916/36962714-95f0fef8-208b-11e8-899f-8176b0349816.png)
it does happen ?

**Comment by chaoxihailing** [comment]
I find it can work like below

    let result = await User.findAll({
        where: {
            policeNumber: { $in: userCodes },
        },
        include: [{ model: Organization }],
    });

**Comment by CindyBoy** [comment]
I meet the same question, had you soved?

**Comment by chaoxihailing** [comment]
yes, you have to add mapping variable just like in User model
```
    @BelongsToMany(() => Organization, () => UserOrganization)
    public organizations: Organization[];
```
and query like
```
	let result = await User.findAll({
        where: {
            policeNumber: { $in: userCodes },
        },
        include: [{
                model: Organization,
        }],
    });
```

**Comment by chaoxihailing** [comment]
@CindyBoy
