### ISSUE TITLE
disregard definition files

### ISSUE THREAD

**Issue by agalazis** [RobinBuschmann/sequelize-typescript#32]
I am using using node v 7.10 with typescript 2.3.3 and sequelize-typescript 0.3.3.
.d.ts files in the model directory should be disregarded. instead I am getting:
`Cannot find module '../some-model.d' `
`(which is not even a thing because it's a d.ts and not d.js)`. Either consider only .js files or disregard .d.ts files.

**Comment by RobinBuschmann** [comment]
Hi @agalazis , this was fixed with `sequelize-typescript@0.3.5`. So update to `0.3.5` and it should work very well :)

**Comment by snewell92** [comment]
@agalazis Have you tried updating to `sequelize-typescript@0.3.5`, and has that resolved the error?

**Comment by RobinBuschmann** [comment]
Closing due to no answer

**Comment by agalazis** [comment]
(yes it works sorry for not coming back)
