### ISSUE TITLE
Uncaught ReferenceError: Model is not defined

### ISSUE THREAD

**Issue by maloy1984** [RobinBuschmann/sequelize-typescript#320]
Hello.
Can anybody help?
I have error with relations.
I have two models

`import {Column, DataType, HasMany, Model, Table} from 'sequelize-typescript';
import {Barcode} from './Barcode';

@Table({
    tableName: 'nomenclature'
})
export class Nomenclature extends Model<Nomenclature> {
    @Column({
        allowNull : false,
        primaryKey: true,
        type      : DataType.BIGINT
    })
    id: number;

    @Column({
        allowNull: false
    })
    name: string;

    @Column({
        allowNull: false,
        type     : DataType.FLOAT
    })
    price: string;

    @HasMany(() => Barcode)
    barcodes: Barcode[];
}

import {BelongsTo, Column, DataType, ForeignKey, HasOne, Model, Table} from 'sequelize-typescript';
import {Nomenclature} from './Nomenclature';

@Table({
    tableName: 'barcode'
})
export class Barcode extends Model<Barcode> {
    @Column({
        allowNull : false,
        primaryKey: true,
        type      : DataType.BIGINT
    })
    id: number;

    @Column
    barcode: string;

    @ForeignKey(() => Nomenclature)
    @Column({
        allowNull: false,
        type     : DataType.BIGINT
    })
    nomenclature_id: number;

    @BelongsTo(() => Nomenclature)
    nomenclature: Nomenclature;
}
`

and I have error Uncaught ReferenceError: Nomenclature is not defined.

If I comment relation 'barcodes' in Nomenclature model, or  'nomenclature' in Barcode model, everything works fine.
All Models in different files.

**Comment by RobinBuschmann** [comment]
Hey @maloy1984, I've tried your example - everything works very well for me. Can you provide a github repository with your example, which reproduces the issue?

**Comment by RobinBuschmann** [comment]
Hey @maloy1984 is this still an issue for you or can this be closed?

**Comment by RobinBuschmann** [comment]
Closed due to no reply
