### ISSUE TITLE
defined models: modelPaths fail

### ISSUE THREAD

**Issue by frankyjquintero** [RobinBuschmann/sequelize-typescript#321]
Configuration
To make the defined models available, you have to configure a Sequelize instance from sequelize-typescript(!).

import {Sequelize} from 'sequelize-typescript';

const sequelize =  new Sequelize({
        database: 'some_db',
        dialect: 'sqlite',
        username: 'root',
        password: '',
        storage: ':memory:',
        modelPaths: [__dirname + '/models']
});
Before you can use your models you have to tell sequelize where they can be found. So either set modelPaths in the sequelize config or add the required models later on by calling sequelize.addModels([Person]) or sequelize.addModels([__dirname + '/models']):

sequelize.addModels([Person]);
sequelize.addModels(['path/to/models']);

basandome en las opciones que brindan la opcion de:

sequelize.addModels(['path/to/models']);

 no funciona me ha tocado usar la opcion
sequelize.addModels([Person]);

**Comment by RobinBuschmann** [comment]
Hey @frankyjquintero can you describe your issue in english, please? :) If this is not so easy for you, you could provide a link to your github repository, in which this issue is demonstrated. Then I can have a look at this :)

**Comment by RobinBuschmann** [comment]
Is this still an issue for you or can this be closed?
