### ISSUE TITLE
create / alter database from models 

### ISSUE THREAD

**Issue by mossaabzaroui** [RobinBuschmann/sequelize-typescript#323]
Hello,

What is the best way to update the database when adding or modifying a model. Without using sync ({force: true}) that makes a Drop. We want to update our development and production environments automatically.

Thank you.

**Comment by RobinBuschmann** [comment]
Hey @mossaabzaroui , see https://github.com/RobinBuschmann/sequelize-typescript/issues/274

**Comment by mossaabzaroui** [comment]
Thank you @RobinBuschmann
