### ISSUE TITLE
module.js:538 error

### ISSUE THREAD

**Issue by damavarunkumar** [RobinBuschmann/sequelize-typescript#324]
when i am run npm -v i am getting

 module.js:538 error

error: cannot find module 'ini'
at function.module._resolveFilename <module.js:536:15>

**Comment by RobinBuschmann** [comment]
Hey @damavarunkumar you've run `npm -v` and got  `module.js:538 error`, right? This sounds like an npm issue in general to me - not related to sequelize-typescript. Have you tried to reinstall npm?

**Comment by damavarunkumar** [comment]
@RobinBuschmann :- I have re install npm but still error remains same do we nee to change proxy settings.

**Comment by RobinBuschmann** [comment]
Hey could you get it working now?

**Comment by RobinBuschmann** [comment]
Closed due to no answer
