### ISSUE TITLE
Error while debugging

### ISSUE THREAD

**Issue by saachinsiva** [RobinBuschmann/sequelize-typescript#326]
Hi

We are developing our node app in Typescript using VSCode. We start our application using ts-node-dev E.g. (ts-node-dev ./src-ts/start.ts) which works fine but when we try to debug the application, it fails with the below error.

`
TypeError: Class constructor Model cannot be invoked without 'new'
    at new AddressTypeSqlz (C:\server\src-ts\standard\address\dao\sqlz\AddressTypeSqlz.ts:31:42)
    at Function.build (C:\server\node_modules\sequelize\lib\model.js:1974:12)
    at Function._target.(anonymous function) [as build] `

Our VSCode debug configuration:
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Current TS File",
            "type": "node",
            "request": "launch",
            "args": [
                "./server/src-ts/start.ts"
            ],
            "runtimeArgs": [
                "-r",
                "./server/node_modules/ts-node/register"
            ],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
`

which basically converts into below command

`node -r ./server/node_modules/ts-node/register --inspect-brk=20251 ./server/src-ts/start.ts `

Our tsconfig.json

`{
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "moduleResolution": "node",
        "outDir": "dist",
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "watch": true,
        "lib": [
            "es2017"
        ]
    },
    "include": [
        "src-ts/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}`

**Comment by RobinBuschmann** [comment]
Seems like the `compilerOptions` are ignored in your second case. Are you sure, that the `compilerOptions` from the `tsconfig.json` are used?

**Comment by saachinsiva** [comment]
Can you please let me know how can I verify that? Also , wanted to let you know that if I remove all of my Sequelize classes, the debugger works fine, its failing as soon as I add annotation. 

I am now able to debug the app with the below configuration. Created tsc tasks and then using launch program pointing to the generated file.However I would prefer to use ts-node if possible.

Task definition :
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "server\\tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}`

Debug config:

`{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/server/src-ts/start.ts",
            "outFiles": [
                "${workspaceRoot}/server/dist/*.js"
            ]
        },`

Thanks for your help

**Comment by RobinBuschmann** [comment]
The only way I found to verify this is using the debugger and the help of my IDE (webstorm):
If the compilerOptions aren't used, the compiled output of es6 classes will be functions (cause the default target will be used, which es `es3`), in case of es2017 the output of these classes will be classes of course. So I stopped the debugger after a test class and  the IDE shows the difference between both:
with `es2017`
<img width="409" alt="bildschirmfoto 2018-03-08 um 19 44 01" src="https://user-images.githubusercontent.com/5270739/37169852-6851afd0-2309-11e8-9717-bf46aaf94833.png">

without compilerOptions:
<img width="358" alt="bildschirmfoto 2018-03-08 um 19 43 41" src="https://user-images.githubusercontent.com/5270739/37169857-6c1e7544-2309-11e8-9a0e-961244f8e669.png">

**Comment by JiamingLinn** [comment]
I notice that it happens when the `target` option set to lower than `es6`. Could it fixed to surpport `es5`?

**Comment by RobinBuschmann** [comment]
Since sequelize 4.X es6 classes are used. So if it is a requirement for you to compile to es5, you need to install sequelize 3.X
