### ISSUE TITLE
Alias cannot be inferred

### ISSUE THREAD

**Issue by doovers** [RobinBuschmann/sequelize-typescript#327]
Given the following models, each of the associations work fine in isolation but not if used together. I'm getting:

> Error: Alias cannot be inferred: "Estimate" has multiple relations with "Employee"

What am I doing wrong?

```typescript
@Table()
export default class Estimate extends Model<Estimate> {

  // Fields....

  @ForeignKey(() => Employee) @Column estimatorId: number;
  @BelongsTo(() => Employee) estimator: Employee;

  @ForeignKey(() => Employee) @Column foremanId: number;
  @BelongsTo(() => Employee) foreman: Employee;

  @BelongsToMany(() => Employee, () => Crew) crew: Employee[];
}
```

```typescript
@Table()
export default class Employee extends Model<Employee> {

  // Fields....

  @HasMany(() => Estimate, 'estimatorId') estimatesAsEstimator: Estimate[];
  @HasMany(() => Estimate, 'foremanId') estimatesAsForeman: Estimate[];

  @BelongsToMany(() => Estimate, () => Crew) estimatesAsCrew: Estimate[];
}
```

```typescript
@Table()
export default class Crew extends Model<Crew> {

  @ForeignKey(() => Employee) @Column employeeId: number;
  @ForeignKey(() => Estimate) @Column estimateId: number;

}
```

**Comment by RobinBuschmann** [comment]
Hey @doovers see this https://github.com/RobinBuschmann/sequelize-typescript#multiple-relations-of-same-models

**Comment by doovers** [comment]
@RobinBuschmann That's exactly the resource I used to try to do this. I'm doing what it says to do there but I'm still getting an error.

I've tried all of the following variants with the same result:

```typescript
  @ForeignKey(() => Employee) @Column estimatorId: number;
  @BelongsTo(() => Employee) estimator: Employee;
```
```typescript
  @ForeignKey(() => Employee) @Column estimatorId: number;
  @BelongsTo(() => Employee, 'estimatorId') estimator: Employee;
```
```typescript
  @BelongsTo(() => Employee, 'estimatorId') estimator: Employee;
```

**Comment by RobinBuschmann** [comment]
Sry, I have overseen that.

You need to do it for both directions. So for the `BelongsTo` and the `HasMany` annotations. In your first post you only did it for `HasMany `.

**Comment by doovers** [comment]
@RobinBuschmann Is this what you mean? I've tried this and it doesn't work either... Apologies if I don't understand you correctly.

```typescript
@Table()
export default class Estimate extends Model<Estimate> {

  // Fields....

  @BelongsTo(() => Employee, 'estimatorId') estimator: Employee;
  @BelongsTo(() => Employee, 'foremanId') foreman: Employee;

  @BelongsToMany(() => Employee, () => Crew) crew: Employee[];
}
```

```typescript
@Table()
export default class Employee extends Model<Employee> {

  // Fields....

  @HasMany(() => Estimate, 'estimatorId') estimatesAsEstimator: Estimate[];
  @HasMany(() => Estimate, 'foremanId') estimatesAsForeman: Estimate[];

  @BelongsToMany(() => Estimate, () => Crew) estimatesAsCrew: Estimate[];
}
```

```typescript
@Table()
export default class Crew extends Model<Crew> {

  @ForeignKey(() => Employee) @Column employeeId: number;
  @ForeignKey(() => Estimate) @Column estimateId: number;

}
```

**Comment by RobinBuschmann** [comment]
@doovers Does the error happen while initializing these models or when trying to retrieve data?
If it happens when retrieving data, you also need to define what exact `include` do you want to use. Therefor you have to set `as` explicitly like:

```ts
Employee.findAll({
  include: [{model: Estimate, as: 'estimatesAsEstimator'}]
})
```

**Comment by doovers** [comment]
@RobinBuschmann That was the problem! Thanks for the help!

**Comment by doovers** [comment]
@RobinBuschmann I'm having a little more trouble with this because I'm trying to do the include in the default scope of the model. How can I do this? 

I tried with:
```typescript
@DefaultScope({
  include: [{ all: true }]
})
```
But got:
> Cannot read property 'getTableName' of undefined

I can't seem to figure out how to define the include in the default scope:
```typescript
@DefaultScope({
  include: [
    { model: () => Employee, association: ?? },
  ]
})
```

**Comment by RobinBuschmann** [comment]
@doovers when do you the error? While initializing the models or when trying to retrieve data?

I couldn't reproduce it at all :/. Can you provide a full example?

**Comment by doovers** [comment]
@RobinBuschmann Apologies for the late reply! I had another look at this and it happens when I call `create` on a model that `BelongsTo` a model with `include: [{ all: true }]`

Logging `include` at `/node_modules/sequelize/lib/model.js:465:29` yields:

```javascript
  static _validateIncludedElement(include, tableNames, options) {
    console.log(include);
    tableNames[include.model.getTableName()] = true; // Fails here
```

```json
{
    "all": true,
    "parent": {
        "model": "Employee",
        "as": "estimator",
        "association": "estimator",
	...
    }
}
```

Note that the model attribute is missing where `all: true` but in the parent it is present.

**Comment by lookapanda** [comment]
Is there something new to this? @RobinBuschmann

**Comment by RobinBuschmann** [comment]
@lookapanda I've completely overseen this one. I looked into it now and getting an error as well, but a different one: `Unhandled rejection TypeError: val.replace is not a function`. Which error do you receive here?

**Comment by lookapanda** [comment]
I get the same error as @doovers (with different type names, obviously)

**Comment by RobinBuschmann** [comment]
@lookapanda So 
> Cannot read property 'getTableName' of undefined

as well?

**Comment by lookapanda** [comment]
Hm, no, not in my implementation. What do you do to get that error?

**Comment by lookapanda** [comment]
I "fixed" it by using `include: all` but ofc, I don' want to include everything, I only need 3 attributes

**Comment by jefersonmombach** [comment]
Hi @RobinBuschmann I'm faced this error now, I'm using the version 0.6.6 of sequelize-typescript and 4.38.0 of sequelize.

The error occurs on retrieving data.

My code:

```
@Table({ tableName: 'dom_domain' })
export class Domain extends BaseModel<Domain> {
  @Column({ field: 'dom_id', autoIncrement: false, primaryKey: true, type: DataType.UUID })
  id: string;

  @HasMany(() => Document, 'domIdType')
  documentTypes: Document[];

  @HasMany(() => Document, 'domIdEmitter')
  documentEmitter: Document[];
}

@Table({ tableName: 'doc_document' })
export class Document extends BaseModel<Document> {
  @Column({ field: 'doc_id', autoIncrement: false, primaryKey: true, type: DataType.UUID })
  id: string;

  @ForeignKey(() => Domain)
  @Column({ field: 'dom_id_type', type: DataType.UUID })
  domIdType: string;

  @ForeignKey(() => Domain)
  @Column({ field: 'dom_id_emitter', type: DataType.UUID })
  domIdEmitter: string;

  @BelongsTo(() => Domain, 'domIdType')
  type: Domain;

  @BelongsTo(() => Domain, 'domIdEmitter')
  emitter: Domain;
}

@Injectable()
export class DocumentService {
  private readonly db: Sequelize;
  private readonly logger: Logger;

  constructor(
    @Inject('DocumentRepository')
    private readonly documentRepository: typeof Document,
    @Inject('DatabaseService')
    private readonly databaseService: DatabaseService,
  ) {
    this.db = databaseService.getInstance();
    this.db.addModels([Document, Domain]);
  }
}
```

And the error:
Error: Alias cannot be inferred: "Document" has multiple relations with "Domain"


I've tried put the @Scope and @DefaultScope, but didn't work.
Can you help me?

**Comment by jefersonmombach** [comment]
Hi @RobinBuschmann tks for answer.

I omitted the `ForeingKey` annotation but didn't work, below the stacktrace

`Alias cannot be inferred: "DocumentoAmbiental" has multiple relations with "Dominio"
    at inferAliasForInclude (/home/volumes/p/sigabem/siga/packages/server/siga-backend/node_modules/sequelize-typescript/lib/services/models.js:258:23)
    at /home/volumes/p/sigabem/siga/packages/server/siga-backend/node_modules/sequelize-typescript/lib/services/models.js:236:19
    at Array.map (<anonymous>)
    at Object.inferAlias (/home/volumes/p/sigabem/siga/packages/server/siga-backend/node_modules/sequelize-typescript/lib/services/models.js:235:39)
    at tryPrepareOptions (/home/volumes/p/sigabem/siga/packages/server/siga-backend/node_modules/sequelize-typescript/lib/models/BaseModel.js:76:50)
    at Function._target.(anonymous function) [as findAndCount] (/home/volumes/p/sigabem/siga/packages/server/siga-backend/node_modules/sequelize-typescript/lib/models/BaseModel.js:35:21)
    at DocumentService.<anonymous> (/home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.service.ts:96:52)
    at Generator.next (<anonymous>)
    at /home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.service.ts:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.service.ts:15:12)
    at DocumentService.list (/home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.service.ts:85:16)
    at DocumentController.<anonymous> (/home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.controller.ts:96:46)
    at Generator.next (<anonymous>)
    at /home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.controller.ts:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.controller.ts:15:12)
    at DocumentController.list (/home/volumes/p/sigabem/siga/packages/server/siga-backend/src/api/v1/sewer/document/document.controller.ts:59:16)
    at /home/volumes/p/sigabem/siga/packages/server/siga-backend/node_modules/@nestjs/core/router/router-execution-context.js:42:29
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
`

I did a little look in the `inferAliasForInclude`, `getAssociationsByRelation` and `getAssociations` functions and seems that they work just with prototype, they doesn't look the foreign key attribute to associate the models.

Can you help me?

**Comment by RobinBuschmann** [comment]
Hey @jefersonmombach, the error doesn't seem to occur on loading the models (For me it is working well). Are you facing this issue while retrieving data?

**Comment by matheushf** [comment]
With me the problem is that I wasn't calling `as: 'modelCustomName'` two times.

```
include: [{
      model: usuario,
      as: 'user',
      attributes: [
        ['usua_id', 'id'],
        ['usua_username', 'username'],
      ],
    },
    {
      model: usuario,
      as: 'userSeguindo',
      attributes: [
        ['usua_id', 'id'],
        ['usua_username', 'username'],
      ],
    },
```

So, if you have defined more than one relation in your model, you need to use `as` for all includes

**Comment by sakthissnite** [comment]
Hi @RobinBuschmann I'm faced this error now, 

The error occurs on when loading model.

My code:

```
@Table()
export default class PwtAnswer extends Model<PwtAnswer> {

   /**
     * Selected id of the AC Charger
     */
    @Column({
        field: 'ac_charger_id'
    })
    @ForeignKey(() => PwtrepoCharger)
    public acchargerId: number;

    @BelongsTo(() => PwtrepoCharger , { as: 'ac_charger', foreignKey: 'acchargerId' })
    public ac_charger: PwtrepoCharger;

 /**
     * Selected id of the DC Charger
     */
    @Column({
        field: 'dc_charger_id'
    })
    @ForeignKey(() => PwtrepoCharger)
    public dcchargerId: number;

    @BelongsTo(() => PwtrepoCharger, { as: 'dc_charger', foreignKey: 'dcchargerId' })
    public dc_charger: PwtrepoCharger;

}

@Table()
export default class PwtrepoCharger extends Model<PwtrepoCharger> {

  @HasMany(() => PwtAnswer , { as: 'ac_charger', foreignKey: 'acchargerId' })
        public ac_charge: PwtAnswer[];
    
        @HasMany(() => PwtAnswer, { as: 'dc_charger', foreignKey: 'dcchargerId' })
        public dc_charger: PwtAnswer[];

}
```
And the error:
Error: Alias cannot be inferred: "PwtAnswer" has multiple relations with "PwtrepoCharger"

can you help me?

**Comment by HexM7** [comment]
Facing the same error:

Follower model: 

```ts
  ...
  @ForeignKey(() => User)
  @AllowNull(false)
  @Column({
    type: DataType.BIGINT,
  })
  public followee_id: string;

  @ForeignKey(() => User)
  @AllowNull(false)
  @Column({
    type: DataType.BIGINT,
  })
  public follower_id: string;

  @BelongsTo(() => User, 'followee_id')
  public followee: User;

  @BelongsTo(() => User, 'follower_id')
  public follower: User;
  ...
```

User model:

```ts
  ...
    @HasMany(() => Relation, {
    as: 'followers',
    foreignKey: 'followee_id',
    hooks: true,
    onDelete: 'CASCADE',
  })
  public followers: Relation[];

  @HasMany(() => Relation, {
    as: 'followees',
    foreignKey: 'follower_id',
    hooks: true,
    onDelete: 'CASCADE',
  })
  public followees: Relation[];
  ...
  ```
  
  Error:
  ```
  Error: Alias cannot be inferred: "Relation" has multiple relations with "User"
  ```
