### ISSUE TITLE
Load models from path issue

### ISSUE THREAD

**Issue by MikeDabrowski** [RobinBuschmann/sequelize-typescript#329]
Hi, past two weeks I tried to create sequelize many to many associations and failed again and again. Then I tried your library and it worked almost out of the box.

But I encountered an issue with loading models to instance. 
I am using latest everything, I am developing on windows but target is linux. 

Here's the directory structure:
```
node-backend:
    config
    migrations
    node_modules
    seeders
    src:
        instances:
            sequelize.ts <- new Sequelize....
        models:
            Role.ts
            User.ts
            UserRole.ts
        controllers:
            user.ctrl.ts
        services:
            user.service.ts
       ....
....
```
For example Role.ts is exporting default class Role.
```
import { BelongsToMany, Column, Model, Table } from 'sequelize-typescript';
import User from './User';
import UserRole from './UserRole';

@Table({
  tableName: 'roles'
})
export default class Role extends Model<Role> {
  @Column
  roleName: string;

  @BelongsToMany(() => User, () => UserRole)
  users: User[];
}
```
Given this dir structure I tried:

`modelPaths: [__dirname + '\\**\\*.ts']` <- ends within instances dir
`modelPaths: [__dirname + '\\models\\*.ts']`<- ends within instances dir
`modelPaths: [__dirname.split('\\').slice(0, -1).join('\\') + '\\models\\*.ts']` <- should work but it doesn't

and some other variations. I also tried them from controller - same result
`Error: Model not initialized: "User" needs to be added to a Sequelize instance before "findAll" can be called.`

How to properly load those files? I tried to stick to docs.

Thank you for this awesome library, it will simplify my code 😄

**Comment by MikeDabrowski** [comment]
I can move sequelize config to index.ts and it works fine there. Seems like it has wrong path or ignores it when defined in other place.

**Comment by MikeDabrowski** [comment]
I realized it works by normal sql rules from join table.

**Comment by RobinBuschmann** [comment]
Hey @MikeDabrowski, thanks for your feedback :) So you already solved your issue now?

**Comment by MikeDabrowski** [comment]
No, still can't auto load models. I edited the issue because I realized the answer to the other question :)

**Comment by RobinBuschmann** [comment]
Are you using tsnode or do you compile the ts files first? Regarding the last option: Did you define a different directory for the output?

**Comment by MikeDabrowski** [comment]
I use tsnode, my run conf: `nodemon --exec ./node_modules/.bin/ts-node -- ./src/index.ts`
Output dir is `dist` but i haven't tried to build it yet.

I also use swaggerUi which loads apis like this `[__dirname + '\\controllers\\*.ts']` which works. It also uses `__dirname` so might give us some clue. I think it is a matter of proper paths.

I also console.logged sequelize instance to look for any paths. If instance is defined in its file in instances directory - no paths in the output. But if instance is in index.ts, everything works. Technically this solves issue but I'm curious why it didn't work in previous configuration.

**Comment by RobinBuschmann** [comment]
Ok. But wouldn't be the correct path from `instances/sequelize.ts` to the models `__dirname + '/../models'` or `__dirname + '/../models/*.ts'`. So you need to go one directory up.

**Comment by MikeDabrowski** [comment]
Yeah I thought about it too, `__dirname` already points to instances and `+` just concatenates the rest. 
Effect: 
`Error: Model not initialized: "Role" needs to be added to a Sequelize instance before "findAll" can be called.`

Noob question: does it matter at what point `new Sequelize` runs?

**Comment by RobinBuschmann** [comment]
Can provide an example project, which reproduces the issue?

**Comment by MikeDabrowski** [comment]
Sure, https://github.com/MikeDabrowski/sequelize-ts-example

**Comment by RobinBuschmann** [comment]
Seems like you're never importing `instances/sequelize.ts`, so that the models never getting added before they get used in your controllers.

**Comment by MikeDabrowski** [comment]
Wow, so simple mistake... I don't know I somehow assumed it would by picked up by something along the way. Thank you for your help and time.

**Comment by RobinBuschmann** [comment]
You‘re welcome :)
