### ISSUE TITLE
usage with async, await

### ISSUE THREAD

**Issue by xkguq007** [RobinBuschmann/sequelize-typescript#33]
error appeared code.
```
  const foundUser: Model<User> = await User.findOne(
        {
          where: { email },
          include: [
            { model: UserAvatarImage, as: 'avatarImage' }
          ]
        }
      );
  if (!foundUser) {
    const err = new Room36Error('cannot find user.');
    err.status = 404;
    return next(err);
  }
  foundUser.comparePassword(password);
```

Problem scenario is.

when i use promise, i use like
```
User.fineOne({}).then((foundUser: User) => {})
```
like this. This way is not occured error.
However, when i use like this
```
const foundUser: User = await User.fineOne({})
```
It error occured, 

> Type 'Model<{}>' is not assignable to type 'User'.
>   Property 'id' is optional in type 'Model<{}>' but required in type 'User'.

So I did is
```
const foundUser: Model<User> = await User.fineOne({})
```
and error is disappeared.
However, now i must use instance method (comparePassword in this scenario), so I did
```
foundUser.comparePassword(password);
```

then, boom! error appeared.

> [ts] Property 'comparePassword' does not exist on type 'Model<User>'.

How can i fix this?
I'm stucked.

p.s sorry for bad english, I hope you can understand.

**Comment by RobinBuschmann** [comment]
@xkguq007 You need to pass the type as a generic to all static functions. No matter if you are using async/await or pure promises. So when using `User.findOne<User>(...)` instead of `User.findOne(...)` it should work:
```typescript
const foundUser: User = await User.findOne<User>({});

User
  .findOne<User>({})
  .then(foundUser => foundUser.comparePassword(password)) // <-- should work as well, without annotating the type again
```

**Comment by xkguq007** [comment]
Oh, I see. Thanks!
I should check static functions more.
closed!
