### ISSUE TITLE
Primary key

### ISSUE THREAD

**Issue by sant123** [RobinBuschmann/sequelize-typescript#331]
> A primary key (id) will be inherited from base class Model. This primary key is by default an INTEGER and has autoIncrement=true (This behaviour is a native sequelize thing).

This text is from sequelize v3? Because I'm working in version 4 and with this config... 

``` ts
@Table({ tableName: "roles" })
export default class Role extends Model<Role> {
  @PrimaryKey
  @Column(DataType.INTEGER)
  public id: number;
}
```

I'm getting this response after `.save()` method:

![image](https://user-images.githubusercontent.com/7959437/37630288-bcbd59ce-2bb1-11e8-919d-be534e917890.png)

You can see `id` is null and a property named `null` is created, I tested in Sequelize and this happens when you forget to put autoIncrement=true. To solve this is just simply add the decorator `@AutoIncrement` but this contradicts the text below. 

The result will be this:

![image](https://user-images.githubusercontent.com/7959437/37630357-282c5a3e-2bb2-11e8-8b3c-6883e8ae5ac5.png)

So the question is, on decorator `@PrimaryKey` should we guarantee `@AutoIncrement` is added under the hood? Or specify in the docs when a primary key is used, also needs to use the `AutoIncrement` decorator.

Thank you and good job in this library!

**Comment by RobinBuschmann** [comment]
Hi @sant123 as the docs say, the id is already inherited from the base model. So when defining your own primary key(which is achieved with the `PrimaryKey` Decorator), it is up to you how this key will behave. That‘s why I would prefer the explicit solution: Adding `Autoincrement` manually. However if you want to have the default behaviour, just don‘t create your own primary key and use the inherited one. What‘s your opinion on that?

**Comment by sant123** [comment]
Ohhhhh understood. Thank you!
