### ISSUE TITLE
<Model>.create or .update ... not showing in vscode intellisense?

### ISSUE THREAD

**Issue by chanlito** [RobinBuschmann/sequelize-typescript#333]
@RobinBuschmann but click to go to definition works. What could be the issue here?

**Comment by RobinBuschmann** [comment]
Which sequelize-typescript version are you using and which of vscode?

**Comment by chanlito** [comment]
It seems that it doesn't show with typescript@2.7.+, but shows on 2.6.2

**Comment by sant123** [comment]
Yes, it's a Typescript issue that will be resolved in version 2.8. You can get more information here https://github.com/Microsoft/TypeScript/issues/21711

**Comment by RobinBuschmann** [comment]
@sant123 Thanks for linking this with the actual ts issue :)

**Comment by sant123** [comment]
Happy to help @RobinBuschmann 😄

**Comment by chanlito** [comment]
Seems ok now with 2.8

**Comment by sitexw** [comment]
Is it me, or the bug is back ?
![image](https://user-images.githubusercontent.com/2950561/71018440-c78b6100-20f8-11ea-9a70-66f134e50eb0.png)

- typescript: 3.7.2
- VSCode: 1.4.;2

**Comment by libvirtadept** [comment]
Got the same thing
vscode: 1.41.1

**Comment by Divlo** [comment]
Yeah I don't have the autocompletion too. 🤔
