### ISSUE TITLE
AllowNull(false) on foreign key

### ISSUE THREAD

**Issue by dkuida** [RobinBuschmann/sequelize-typescript#335]
Hi
if I have two models
```typescript
@Table({timestamps: true, tableName: 'patient'})
export class Patient extends Model<Patient> {
    @PrimaryKey
    @AutoIncrement
    @Column({primaryKey: true})
    public patientId: number;
    @AllowNull(false)
    @Column
    public firstName: string;
    @AllowNull(false)
    @Column({type: DataType.ENUM, values: ['id', 'passport']})
    public idType: string;
    @AllowNull(false)
    @Column
    public id: string;
    @Column
    public lastName: string;
    @ForeignKey(() => Clinic)
    public clinicId: Clinic;
}

@Table({timestamps: true, tableName: 'clinic'})
export class Clinic extends Model<Clinic> {
    @PrimaryKey
    @AutoIncrement
    @ForeignKey(() => Patient)
    @Column({primaryKey: true})
    public clinicId: number;
    @Column
    public name: string;
    @Column
    public phone: string;
    @BelongsToMany(() => Doctor, () => DoctorClinic)
    public doctors: Doctor[];
    @HasMany(() => Patient)
    public patients?: Patient[];

}


```
if I try to set @AllowNull(false) on  
```
@ForeignKey(() => Clinic)
    public clinicId: Clinic;
```

in order to constraint the creation of a Patient only wiht clinic I get
        throw new Error("@Column annotation is missing for \"" + propertyName + "\" of class \"" + target.constructor.name + "\"" +
        ^

Error: @Column annotation is missing for "clinicId" of class "Patient" or annotation order is wrong.

in sequalize I could set {allowNull: false} on the foreign key itself - what is the correct way to do it in Sequalize-Typescript?

**Comment by RobinBuschmann** [comment]
Hey @dkuida, to achieve this, you either need to use `Column` annotation on your foreign key like:
```ts
  @AllowNull(false)
  @ForeignKey(() => Clinic)
  @Column
  public clinicId: number;
```
or set `allowNull: false` on the relation annotation
```ts
  @HasMany(() => Patient, {
    foreignKey: {
      allowNull: false
    }
  })
  public patients?: Patient[];
```

**Comment by dkuida** [comment]
well the first approach is the one I tried fro the start but it returns
`@Column annotation is missing for "clinicId" of class "Patient" or annotation order is wrong.`
but the second one worked like a charm

thank you
