### ISSUE TITLE
Provide association options

### ISSUE THREAD

**Issue by HackedByChinese** [RobinBuschmann/sequelize-typescript#34]
I'm trying to set some association options. For example, I have a `HasMany` where I want to disallow null in the FK and cascade on delete.

In Sequelize, I'd do something like:

```
childModel.belongsTo(parentModel, {
   foreignKey: {
      allowNull: false
   },
  onDelete: 'CASCADE'
});
```

I don't see any place in the association attributes or `ForeignKey` to pass in those options. See [foreign keys](http://docs.sequelizejs.com/manual/tutorial/associations.html#foreign-keys) (Their documentation on this subject is a bit messy).

I'd like to be able to do the following, using BelongsTo as an example:
```
export class Child extends Model<Child> {
   @BelongsTo(() => Parent, { foreignKey: { allowNull: false }, onDelete: 'CASCADE'})
    public parent: Parent;
}
```
I'm using Sequelize 4, but I think the issue is the same for 3.

**Comment by BruceHem** [comment]
Yeah i been reading the doc, but don't see any where to set 'CASCADE'. @RobinBuschmann can u shed some light here?

**Comment by RobinBuschmann** [comment]
Unfortunately this is currently not possible with the available decorators. So at the moment you have to rely on the automatically set configuration by sequelize.

But this should be supported by sequelize-typescript. I will look into this and start implementing this feature as soon as possible.

**Comment by zuhair-naqvi** [comment]
+1

**Comment by RobinBuschmann** [comment]
This feature is now part of the 0.4.0-beta release (`sequelize-typescript@0.4.0-beta`) @HackedByChinese thanks again for implementing.

**Comment by BruceHem** [comment]
should this be mentioned in the doc? it took me quite some time

**Comment by RobinBuschmann** [comment]
@BruceHem this can already be found here: https://github.com/RobinBuschmann/sequelize-typescript#foreignkey-belongsto-hasmany-hasone-belongstomany-api

..or do you think that an example would be a good idea?

**Comment by BruceHem** [comment]
An example would be nice. And also I think we should show that this feature is available after 0.4.0-beta too.

**Comment by BruceHem** [comment]
@RobinBuschmann do we have a sequelize-typescript chat group?

**Comment by RobinBuschmann** [comment]
@BruceHem You mean a chat like https://gitter.im/ ? What to you intend to achieve with a group chat? Should it be for questions, bugs, ...?

**Comment by BruceHem** [comment]
Yes!

**Comment by RobinBuschmann** [comment]
@BruceHem I think it is better to keep one communication channel for now: github. A chat needs moderation and is much harder to be moderated than the github issues.
