### ISSUE TITLE
Fill model instance with object literal?

### ISSUE THREAD

**Issue by jtrujillo7** [RobinBuschmann/sequelize-typescript#344]
I must be missing something elemental :

```
class Book extends Model<Book>{
     @Column(DataType.STRING)
     title:string;
}
let book=new Book;

book={title:"somethig"};  /* Error Type '{ title: string; }' is not assignable to type 'Book'.
  Property '$add' is missing in type '{ title: string; } */

```
What I want to do is to fill the instance with the raw values but keeping the validations of typescript.

With

`let book:Partial<Book>=new Book;`

ts validates that field names are in Book but you can omit some non-optional field.

Is there a better approach to this?

**Comment by RobinBuschmann** [comment]
Hey @jtrujillo7, with `book={title:"somethig"};` you're referencing a completely new object to your variable `book`. What do you want is assigning values to your existing object (which is an instance of `Book`), right? You can do so while initializing a model instance with 
```ts
const book = new Book({title: 'Crime and Punishment'});
await book.save(); // to store data in to your database
// or both at once
const book = await Book.create({title: 'Crime and Punishment'}); // creates a new object and stores it into the db
``` 
or if your model was already created:
```ts
await book.updateAttributes({title: 'The Brothers Karamazov'})
```

**Comment by jtrujillo7** [comment]
Hi Robin,

Yeah, thanks for your reply, I needed that clarification. Anyway what I was looking for was essentially object type checking of the properties passed to a model.

`new Book({titXXle:"sdf", price:34})`

Passes without error. I can not find a way to "secure" the assignments to a model.
thanks!

**Comment by RobinBuschmann** [comment]
@jtrujillo7 Which sequelize-typescript version are you using?

**Comment by jtrujillo7** [comment]
Hi, 
I had 0.6.2. Upgraded to 0.6.3 and now it does the checks. Thanks!
