### ISSUE TITLE
Composite Foreign Keys

### ISSUE THREAD

**Issue by euler2718** [RobinBuschmann/sequelize-typescript#347]
I am trying to create a relationship with composite foreign keys (mssql).  I don't think this is supported, so I have tried to used a scope.
The resulting query is correct, but my sequelize model is only populating a single instance, not many.

Both Tables have 3 Fields with identical names (above as Q_ID, G_Code, T_Code) which determines the relationship:

**TableB.Q_ID** _REFERENCES_ **TableA.Q_ID**
**TableB.G_Code** _REFERENCES_ **TableA.G_Code**
**TableB.T_Code** _REFERENCES_ **TableA.T_Code**

I've written the relationship FROM **TableA** as:

```
    @HasMany(() => SqlzForTableB, {
      foreignKey: 'Q_ID', 
      scope: {
             G_Code: { [Sequelize.Op.col]: 'AliasForTableOfThisSqlzModel.G_Code' },
             T_Code: { [Sequelize.Op.col]: 'AliasForTableOfThisSqlzModel.T_Code' }
         }
     })
```
Do you have any suggestions on handling a composite foreign key relationship?

Thanks

**Comment by RobinBuschmann** [comment]
Hey @euler2718, sry for the late response. Unfortunately I don't fully get your issue. Can you provide a more advanced example? In which exact case only a single instance is populated instead of many?

**Comment by RobinBuschmann** [comment]
@euler2718 Do you solved your issue?

**Comment by euler2718** [comment]
We solved the issue by creating Association Tables on the DB side manually...
So the main issue I was trying to solve, is what if I have something like BelongsToMany relationship with 3 keys instead of 2?

ALSO - this is more generally a sequelize question, but its about updated Association Tables:

    @BelongsToMany(() => SqlzModel1, { through: 'ASSN_TABLE', foreignKey: 'code1', otherKey: 'code2' })
    modelArray: SqlzModel1[];
When I run an update, it doesn't seem to update the ASSN_TABLE.

I tried getting away from using the Table Names directly and created another model hoping it would update:
    @BelongsToMany(() => SqlzModel1, { through: 'AssnSqlzModel', foreignKey: 'code1OnSqlz', otherKey: 'code2OnSqlz' })
    modelArray: SqlzModel1[];

but in this case,
I get the error: SequelizeDatabaseError: Invalid object name 'AssnSqlzModel'

I've also tried:
    @BelongsToMany(() => SqlzModel1, { through: {model: 'AssnSqlzModel'}, foreignKey: 'code1OnSqlz', otherKey: 'code2OnSqlz' })
    modelArray: SqlzModel1[];

I do have ways of solving this, but it would be nice if I didn't have to go another route.

Let me know if I should make another discussion for this.

Thanks.

**Comment by RobinBuschmann** [comment]
@euler2718 Did you try to use the reference instead of a string: `{through: () => AssnSqlzModel}`?

**Comment by euler2718** [comment]
yes I did that too, and it works fine to read the table, but doesn't help on an update / create

**Comment by RobinBuschmann** [comment]
Hey @euler2718 do you managed to get this working?

**Comment by RobinBuschmann** [comment]
@blankstar85 Thanks for your input on this. So, your example works, right? There is no difference between your example and the formerly one provided by euler2718 or have I overseen something? Thanks in advance

**Comment by blankstar85** [comment]
Yes my example is identical, it works fine so far with everything that i need. I didn't have a need for three keys though. So not sure if mine applies to the original, I handle all database (initial) manually, then use migrations to adjust. So I don't use sync or rely on sequelize to create the database for me.

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity of reporter.

**Comment by harpsdev** [comment]
@blankstar85 probably too late for you..
import { Op } from 'sequelize';
And replace Sequelize.Op by Op

**Comment by blankstar85** [comment]
@harpsdev thanks for the comment, but if you look at the comment at the bottom i had already figured it out and updated it. I left the top to not completely change everything in the comment, i guess I should have. Thanks for the help tho..
