### ISSUE TITLE
Webpack problem, how to solve it?

### ISSUE THREAD

**Issue by aa6my** [RobinBuschmann/sequelize-typescript#348]
`Field 'browser' doesn't contain a valid alias configuration`

The error shows like this. Try to googling still cannot find right answer

**Comment by chanlito** [comment]
We need more information.

**Comment by RobinBuschmann** [comment]
@aa6my Is this still an issue for you?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity

**Comment by Toxicable** [comment]
fixed up https://github.com/RobinBuschmann/sequelize-typescript/pull/574
