### ISSUE TITLE
Will sequelize-typescript work with sequelize v5?

### ISSUE THREAD

**Issue by chanlito** [RobinBuschmann/sequelize-typescript#350]
@RobinBuschmann , so Sequelize recently released https://github.com/sequelize/sequelize/releases/tag/v5.0.0-beta.2 with various breaking changes, so I wonder how will this affect sequelize-typescript v1 in the near future?

**Comment by RobinBuschmann** [comment]
@chanlito Yes it should work. I've tested it a bit with https://github.com/RobinBuschmann/sequelize-typescript-example and it worked very well with v5.

**Comment by alexey-pelykh** [comment]
Odd, I get
```
Cannot find module './v5/Model'
```
in `node_modules/sequelize-typescript/lib/models/Model.js:6:13` with
```
"sequelize": "^5.0.0-beta.5",
"sequelize-typescript": "^0.6.5-beta.0",
```

**Comment by RobinBuschmann** [comment]
Hey @alexey-pelykh thanks for bringing this up. `sequelize@5` will currently only work with `sequelize-typescript@canary` hope this helps

**Comment by alexey-pelykh** [comment]
Thanks for explanation!

**Comment by RobinBuschmann** [comment]
With the latest beta release it should work with `sequelize@5` as well: `sequelize-tyescript@next`

**Comment by intellix** [comment]
Isn't the plan for them to release official TypeScript typings with the original library? 
https://github.com/sequelize/sequelize/milestone/18
https://github.com/sequelize/sequelize/issues/9285

**Comment by RobinBuschmann** [comment]
Hey @intellix, thanks for bringing this up. So those typings may conflict with @types/sequelize... 🤔

**Comment by KillWolfVlad** [comment]
@RobinBuschmann sequelize v5.0.0-beta.16 have official typescript typings sequelize/sequelize#10287

**Comment by ricklancee** [comment]
@RobinBuschmann will sequelize typescript move to the official typings? I tried them out with `@canary` but got alot of conflicts in typing.

**Comment by RobinBuschmann** [comment]
@ricklancee Thanks for asking: I've just created an issue for that #529

**Comment by RobinBuschmann** [comment]
Close this issue due to initial question is answered
