### ISSUE TITLE
Problems with Model.bulkCreate()

### ISSUE THREAD

**Issue by dlemburg** [RobinBuschmann/sequelize-typescript#352]
I'm trying to execute the following bulk create as follows:

 ```
          const results = await Entity2LocationContactMap.bulkCreate([
                new Entity2LocationContactMap({ entityOid: 1, locationOid: 10, entityOid_LocationContact: 2}),
                new Entity2LocationContactMap({ entityOid: 1, locationOid: 15, entityOid_LocationContact: 3}),
            ]);
            console.log("results: ", results);
```

This call does not break, but it does not insert new records. Here is a screenshot of the logged out results array- as you can see. all pertinent values are `undefined`:

![bulkcreate-bug](https://user-images.githubusercontent.com/17346002/38600220-40ddedfa-3d18-11e8-8b82-00e15046144b.PNG)

I have tried not instantiating new Entity2LocationContactMap objects and instead just passing a raw object, but that breaks. I've also tried chaining .save() to each instantiated object similar to using `Promise.all([])` (which I am using as a workaround currently), but no luck there either. I am using Sql Server, by the way.

Any idea what is going on? Thanks in advance.

**Comment by RobinBuschmann** [comment]
Hey @dlemburg `bulkCreate`, `create` and so on are expecting plain objects. Try it like so:
```ts
await Entity2LocationContactMap.bulkCreate([
               { entityOid: 1, locationOid: 10, entityOid_LocationContact: 2},
               { entityOid: 1, locationOid: 15, entityOid_LocationContact: 3},
           ]);
```

**Comment by dlemburg** [comment]
Great, thanks. That worked. Some of my earlier tests on different models did not work doing that same thing. So if anyone stumbles upon this, my suspicion is that it was breaking because the primary key column hadn't been properly assigned, or auto-increment hadn't been marked.

Thanks for the help!

**Comment by Swadish** [comment]
Sorry for ressurrecting an old thread, but I was able to bulkInsert models using a map with destructuring:

```typescript
  createBulkCreditors(users: User[], transaction?: Transaction): Promise<User[]> {
    const mappedUsers = users.map(
      ({ someAttribute1, someAttribute2, someAttribute3 }) => ({
        someAttribute1,
        someAttribute2,
        someAttribute3,
      }),
    );

    return User.bulkCreate(mappedUsers, {
      ignoreDuplicates: true,
      transaction,
    }).catch(e => {
      throw new DefaultException(e);
    });
  }
```

Yes, in this case you have to iterate the array again.
