### ISSUE TITLE
Create an association without a foreign key

### ISSUE THREAD

**Issue by alfaproject** [RobinBuschmann/sequelize-typescript#355]
I was trying to create an association without creating a foreign key constraint for a particular use case, but it doesn't look like it's possible.

I actually thought the issue was in Sequelize and reported there: https://github.com/sequelize/sequelize/issues/9303

As you can see in that issue, the reduced test case actually achieves what I want, but I don't seem able to do the exact same using `sequelize-typescript`. ):

My equivalent annotated model looks like this:
```ts
@Table
export class Transaction extends Model<Transaction> {
  @PrimaryKey
  @Column
  public id: number;

  @ForeignKey(() => User)
  @Column(DataType.INTEGER.UNSIGNED)
  public userId: number;

  @BelongsTo(() => User, {
    constraints: false,
  })
  public user: User;
}
```

If I remove the `@ForeignKey` annotation then an error is thrown:
`Foreign key for "User" is missing on "Transaction".`

I've tried a bunch of other combinations, but I'm out of ideas. I think it's just not possible or I'm missing something.

**Comment by alfaproject** [comment]
@RobinBuschmann that seems to be the missing piece. Thank you for helping! (:

**Comment by soldevfa** [comment]
xdgvr
