### ISSUE TITLE
Type issue when passing string key to where clause

### ISSUE THREAD

**Issue by ekscentrysytet** [RobinBuschmann/sequelize-typescript#359]
Typescript compiler complains when I put query association syntax to where clause.

Here's the query:
```javascript
Client.findAll({
      where: {
        source: sourceName,
        accountId: accountId,
        '$matchedClients.id$': null,
      },
      attributes: ATTRIBUTES_ALIASES.CLIENT.listAttributes,
      include: [
        model: Client,
        as: 'matchedClients',
        attributes: ['id'],
        where: { source },
        required: false,
      ],
    })
```
I get error:
```
error TS2345: Argument of type '{ where: { source: string; accountId: string; '$matchedClients.id$': null; }; attributes: string[...' is not assignable to parameter of type 'IFindOptions<Client>'.
  Types of property 'where' are incompatible.
```

It's actullay acceptable by sequelize and works as expected but not documented in the docs. See discussions here: [#3095](https://github.com/sequelize/sequelize/issues/3095).

**Comment by RobinBuschmann** [comment]
Hey @ekscentrysytet, thanks for reporting. 

You need to use `['$matchedClients.id$' as any]: null`. There is currently no way to have type safety with the `$<property_name>$` syntax.

See this issue: https://github.com/RobinBuschmann/sequelize-typescript/issues/234#issuecomment-355820615 

Hope this helps

**Comment by ekscentrysytet** [comment]
@RobinBuschmann Ok, thank you!
