### ISSUE TITLE
Behaviour with auto-pluralization of tables differs from sequelize

### ISSUE THREAD

**Issue by johannes-scharlach** [RobinBuschmann/sequelize-typescript#361]
Typically sequelize pluralises the model name to create tables, so that the table is called `Users` and the model is called `User`. That always made sense to me, since the table does contain multiple users.

By setting `freezeTableName` to `true` by default, `sequelize-typescript` behaves differently from `sequelize` in regards to the table names that are created. I tried to read up on https://github.com/RobinBuschmann/sequelize-typescript/issues/154 and https://github.com/RobinBuschmann/sequelize-typescript/pull/148 to understand why this was required, but I don't think I understand... From the [sequelize docs](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init)

About `freezeTableName`:
> If freezeTableName is true, sequelize will not try to alter the model name to get the table name. Otherwise, the model name will be pluralized

About `underscoredAll`:
> Converts camelCased model names to underscored table names if true. Will not change model name if freezeTableName is set to true

In particular I don't understand what problem you're referring to in [this comment](https://github.com/RobinBuschmann/sequelize-typescript/pull/148#issuecomment-333040736). I've just set `freezeTableName` to `false` in my own repository and so far things seem to work well. Was it that this would be a breaking change for `sequelize-typescript`?

Would you consider such a breaking change (which will match the behaviour of sequelize more closely) for v1.0.0?

**Comment by RobinBuschmann** [comment]
Hey @johannes-scharlach, initially I decided at one point that I want to use the exact class name as table name. Simply because I prefer using it like that. To achieve this behaviour the `tableName`  option was set to the name of the class.
Since this decision was made and sequelize-typescript was alive for some time as #148 came up, switching to the default behaviour had mean a breaking change. So to fix #148 I removed the default initializing of `tableName` and to keep the singular name `freezeTableName` was set to true instead.

But yes, we should definitely consider making this change for `1.0.0`. Thanks for bringing this up :)

**Comment by johannes-scharlach** [comment]
Thanks for the clarification! This project is really cool and I hope I can help move it forward ;)

What I'd have in mind for making such a change is to set the default behaviour to be the same as in `sequelize`, but add a config option when you run `new Sequelize`, where you can define `defaultFreezeTableName`. That will make a migration to v1.0.0 simple for existing projects while having the default closer to sequelize.

Other solutions I could think of (e.g. providing two different decorators like `Table` and `PluralisedTable`) seems just as much work as setting the option manually everywhere...

**Comment by RobinBuschmann** [comment]
It is already possible to set default define options for all tables like so 
```ts
new Sequelize({
  define: {/* Default options goes here */}
})
```
Nevertheless, `freezeTableName` is currently set while passing options via `@Table` annotation instead of using the global default options 🙈My fault..

**Comment by C45tr0** [comment]
Looks like in v1.0.0-alpha.7 the default for freezeTableName is still set to true. Are you still expecting to change this behavior? @RobinBuschmann

**Comment by RobinBuschmann** [comment]
@C45tr0 Good point! What’s your opinion on that?

**Comment by C45tr0** [comment]
I agree with the above thread and think the default should match Sequelize.

**Comment by C45tr0** [comment]
@RobinBuschmann Let me know if it you would like me to submit a PR for this. Willing to help.

**Comment by RobinBuschmann** [comment]
@C45tr0 If you like to - Any help is appreciated
