### ISSUE TITLE
Create arguments don't require non-null fields

### ISSUE THREAD

**Issue by wbobeirne** [RobinBuschmann/sequelize-typescript#367]
Using version `1.0.0-alpha.3`, when I define a model like so:

```.ts
@Table
export default class User extends Model<User> {
  @Column({ allowNull: false })
  name: string;
}
```

I would expect calling

```.ts
User.create({})
```

to give me an error letting me know that name is required. But the TypeScript def doesn't stop me. Obviously this causes the following runtime error:

> Unhandled rejection SequelizeValidationError: notNull Violation: User.name cannot be null

Is there something I'm missing in the model definition or the create call that would prevent this? Or is this not supported?

**Comment by RobinBuschmann** [comment]
Hey @wbobeirne, unfortunately there is no way to connect the configuration `{allowNull: false}` with the interface used in the `create` method. So it's up to you defining your requirements on `create`. You can achieve this like so:

```ts
interface CreateUserDTO {
    name: string;
}

@Table
export default class User extends Model<User> {

    @Column({ allowNull: false })
    name: string

    static create(values: CreateUserDTO, options?: ICreateOptions) {
        return super.create.call(this, values, options);
    }
}
```

**Comment by RobinBuschmann** [comment]
@wbobeirne Does my suggestion solve the issue for you? Can we close this issue then?

**Comment by wbobeirne** [comment]
Yep, that's a totally reasonable solution. Sorry for leaving this stale so long.
