### ISSUE TITLE
update with returning: true option not returning updated object

### ISSUE THREAD

**Issue by 620eli** [RobinBuschmann/sequelize-typescript#369]
I was able to do this in the default version of sequelize and it returned me the updated user:
`User.update({ ... }, { where: { id }, returning: true }).then(
(updatedUsers, [user]) => res.json(user),
error => res.send(error)
);`
I wanted to do this with the sequelize-typescript version but I'm not able to get the user. When I try to do this, I get an 'Unhandled rejection TypeError: undefined is not a function' error:
`User.update({ ... }, { where: { id }, returning: true }).then(
([updatedUsers, [user]]) => res.json(user),
(error: Error) => res.send(error)
);`

Is it a bug or am I doing something wrong?
Any suggestions?

**Comment by RobinBuschmann** [comment]
Hey @620eli, thanks for reporting. Since I cannot reproduce your issue, can you provide an example repository which represents the actual issue?

**Comment by 620eli** [comment]
[https://github.com/620eli/example](url)
After starting the server, try to do a PUT on localhost:9090/api/users/1 with the properties email, firstname, lastname, photoURL set in the request body. The error should now show up in the server output.

**Comment by RobinBuschmann** [comment]
Hey @620eli, thanks. But this isn't working with native sequelize as well. This is because you're using `{returning: true}` with `sqlite`, which is not supported. The `returning` option is only available for postgres as stated [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L3041) as well.

**Comment by 620eli** [comment]
Well, I am pretty sure that this worked with native sequelize and sqlite. Unfortunately I changed the project so I couldn't reproduce it anymore. I tried to rebuild it with native sequelize but it didn't work, too. Anyways, thanks for your help!
