### ISSUE TITLE
[Question] Updating schema

### ISSUE THREAD

**Issue by tomeram** [RobinBuschmann/sequelize-typescript#373]
I am trying to update schema if it's different on load and I am not sure how to do it.
I tried adding a column to a table and I am getting a missing column error:
```
SequelizeDatabaseError: SQLITE_ERROR: no such column: date
```

Is there an option I can pass?
Tried : `validateOnly` and `sync: { force: true }` without success...

**Comment by RobinBuschmann** [comment]
Hey @tomeram , `validateOnly: true` is a hidden feature. It makes it possible to use the validation of sequelize without the actual ORM.

**Comment by tomeram** [comment]
@RobinBuschmann Thanks,
I found my answer anyway 😄
