### ISSUE TITLE
Constructor (uri: string, options?: Options) not supported

### ISSUE THREAD

**Issue by alex-friedl** [RobinBuschmann/sequelize-typescript#375]
Hello,

First of all: thank you for this awesome library! :)

I was wondering if you could add support for the new `(uri: string, options?: Options): Sequelize;` constructor?

I find it quite convenient to use URIs for connection information and still have the possibility to configure things like SQL logging

```
const sequelize = new Sequelize(env.DB_URL, {
  logging: false
});
```

**Comment by RobinBuschmann** [comment]
Hey @alex-friedl, thanks for the hint. I will implement this when `1.0.0` is released :)

**Comment by alex-friedl** [comment]
Sounds good! :)

Do you have a rough estimate for the release date of 1.0.0 ?

**Comment by RobinBuschmann** [comment]
Unfortunately I cannot give you any estimation here. When I have the chance to upgrade to 1.0.0 on any of our productive projects and everything works well, I will feel more comfortable with it and will publish 1.0.0. Until then, you can use an alpha version of 1.0.0: Install it with the canary tag: `sequelize-typescript@canary`

**Comment by bosunolanrewaju** [comment]
Using this method works for me:
```
const sequelize = new Sequelize({
  url: env.DB_URL, 
  logging: false
});
```

**Comment by petrogad** [comment]
First off, thank you @RobinBuschmann for all the great work here!

I'm curious how close you are to supporting url in version 1.0.0. 

Thank you

**Comment by RobinBuschmann** [comment]
Closing this, since `1.0.0` is released
