### ISSUE TITLE
build fails with latest typescript version

### ISSUE THREAD

**Issue by MaxBinnewies** [RobinBuschmann/sequelize-typescript#379]
Hello,

Our build fails on Kubernetes, but not locally, with the following error:
Step #0: node_modules/sequelize-typescript/lib/utils/types.d.ts(9,16): error TS2344: Type ‘keyof T’ does not satisfy the constraint ‘string’.
Step #0: Type ‘string | number | symbol’ is not assignable to type ‘string’.
Step #0: Type ‘number’ is not assignable to type ‘string’.

Turns out Kubernetes pulled the latest typescript version from 9 hours ago: 2.9.1
We set typescript to the previous version (2.8.4) and the build works.

Is this a bug with sequelize-typescript, typescript, or something else entirely?

Thanks,
Max

**Comment by andys8** [comment]
Can confirm the issue.

**Comment by RobinBuschmann** [comment]
@MaxBinnewies Thanks for reporting. @andys8 Thanks for providing more details :)

For now you can also set `skipLibCheck` `true` in your tsconfig to omit the error.

**Comment by andys8** [comment]
Thanks @RobinBuschmann for the quick fix. When is the next release planned to make this fix available?
