### ISSUE TITLE
options.include[].on not supported in query

### ISSUE THREAD

**Issue by Cyberuben** [RobinBuschmann/sequelize-typescript#381]
I'm currently using the following query:

```
let [respondent] = await RespondentRelational.findOrCreate({
	where: {
		mongoId: this._id.toString()
	},
	include: [{
		model: RespondentAttribute,
		include: [{
			model: AttributeOption,
			// @ts-ignore: Not supported by sequelize-typescript
			on: {
				"$attributes.attributeId$": { $col: "attributes->option.attributeId" },
				"$attributes.optionId$": { $col: "attributes->option.optionId"}
			}
		}, {
			model: Attribute,
			where: demographicsFilter
		}]
	}]
});
```

The following code won't compile without the `// @ts-ignore` line because of missing types. It would be nice if you could add support for that.

**Comment by Cyberuben** [comment]
Unfortunately it doesn't seem to be mentioned anywhere in the docs. Although, it is mentioned in the reference, but no examples or proper types have been given.

http://docs.sequelizejs.com/class/lib/model.js~Model.html

Search using your browser for `options.include[].on`.

**Comment by RobinBuschmann** [comment]
Ok, then I'll simply add it with `on: any`
