### ISSUE TITLE
FilteredModuleAttributes in 1.0

### ISSUE THREAD

**Issue by lookapanda** [RobinBuschmann/sequelize-typescript#384]
Is there a reason the arguments for `getDataValue()` are restricted to those few in https://github.com/RobinBuschmann/sequelize-typescript/blob/1.0.0/lib/model/types/FilteredModelAttributes.ts#L4 ?

I can no longer use `this.getDataValue('somethingElese')` because of this and sadly, I cannot find any changelog that explains this breaking change.

**Comment by lookapanda** [comment]
Hello,

I have this case, for example:

```typescript
@Column({
        type: DataType.STRING(2),
        defaultValue: DEFAULT_LANGUAGE,
        get() {
            const language = this.getDataValue('language');
            if (!language) {
                return DEFAULT_LANGUAGE;
            }
            
            return language;
        },
    })
    public language: string;
```

But  `this.getDataValue('language')` is not allowed by the compiler now because of `FilteredModuleAttributes`.

It is very much a valid use case here though, because I want that getter to return the default value and not `null` if there's no entry in the database.

**Comment by lookapanda** [comment]
<img width="877" alt="bildschirmfoto 2018-06-06 um 13 41 39" src="https://user-images.githubusercontent.com/770632/41036142-5e80053e-698f-11e8-8f53-51f13043a7f4.png">

**Comment by RobinBuschmann** [comment]
Ah ok, I see. Either do
```ts
@Column({
  get(this: YourModel) { /* ... */ }
})
```
or
```ts
@Column
get language(): string {
   /* ... */
}
```

Hope this helps

**Comment by lookapanda** [comment]
I'm still relatively new to TypeScript, I somehow have the feeling that it has to do with the generics, but I'm not quite sure how to fix it

**Comment by RobinBuschmann** [comment]
Hey @lookapanda what error message are you getting here?

**Comment by lookapanda** [comment]
It says that `language` does not exist on that type. I started another attempt similar to https://github.com/RobinBuschmann/sequelize-typescript/issues/291

I extend the Model class now directly and override the needed functions like `findById`

**Comment by RobinBuschmann** [comment]
@lookapanda Sry for the delayed reply: So it throws here:
```ts
  @Column({
        type: DataType.STRING(2),
        defaultValue: DEFAULT_LANGUAGE,
        get(this: UserSetting) {
            const language = this.getDataValue('language'); // <---- throws here?
            if (!language) {
                return DEFAULT_LANGUAGE;
            }

            return language;
        },
    })
```
?

**Comment by lookapanda** [comment]
It did, but as I said, I'm doing it in another way and it works fine now!

**Comment by lewispham** [comment]
Any plans to fix this issue @RobinBuschmann ?
I've just encountered this issue on `v4.27.20`.
@lookapanda Can you help share your workarounds?
