### ISSUE TITLE
modelPaths in 1.0

### ISSUE THREAD

**Issue by lookapanda** [RobinBuschmann/sequelize-typescript#386]
I see that they've been deprecated:

```typescript
    /**
     * Path to models, which should be loaded
     * @deprecated
     */
    modelPaths?: string[];
```

Why is that and what's the replacement?

**Comment by RobinBuschmann** [comment]
@lookapanda  Just `models` is the replacement. Since it now also takes references instead of only paths.

**Comment by lookapanda** [comment]
Thanks!
