### ISSUE TITLE
Invalid scope called

### ISSUE THREAD

**Issue by Aleksaas** [RobinBuschmann/sequelize-typescript#388]
```
SequelizeScopeError: Invalid scope dto called.
    at Function.scope (C:\MacGregor\BackEnd\node_modules\sequelize\lib\model.js:1422:15)
```

I have this error message which happens sometimes for some entities although the specified scope exists. Example: 
```
@Scopes({
    dto: {
        attributes: ['id', 'name', 'description', 'position', 'serialNumber', 'runningHours', 'isActive', 'criticality', 'equipmentTypeId'],
        include: [() => EquipmentType.scope("dto")]
    },
})
```

```
@Scopes({
    dto: {
        attributes: ['id', 'name', 'description']
    },
})
@Table({
    tableName: 'equipmentType'
})
export class EquipmentType extends BaseModel<EquipmentType> {
```

In 90% of the code something like this work, but in some places it doesn't for some reason. Anyone had this issue?

**Comment by RobinBuschmann** [comment]
Hey @Aleksaas, can you confirm, that is only happens for entities where you've defined an include like `include: [() => EquipmentType.scope("dto")]`? That's at least what I guess causing the issue 🤔If so this is definitely a bug

**Comment by 620eli** [comment]
A can confirm this issue.

**Comment by sahilchaddha** [comment]
I have reproduced this issue and found a workaround solution.I suppose this is because how sequelize inits models from the folder. This can be fixed if EquipmentType is initialized before the calling model is. You can try changing fileName with prefix `a` like `aequipmentType.ts`. This will make sequalize to init EquipmentType model with scopes first.

**Comment by Aleksaas** [comment]
I realized that it actually depends on the order of model includes in `this._sequelize.addModels([` method, so when I moved model `EquipmentType` to be before the model that includes it, it worked. That's why it seemed like random behavior and worked for some models and for some not.

**Comment by sahilchaddha** [comment]
Yes. I am not sure how we can set order of models during init method. But renaming for now is a valid working work-around solution to this problem.

**Comment by Aleksaas** [comment]
But you don't have to rename. I just did this: `        this._sequelize.addModels([
            EquipmentType,
            Equipment
        ])`
instead of this: `        this._sequelize.addModels([
            Equipment,
            EquipmentType
        ])`
and it worked. `Equipment` includes `EquipmentType`.

**Comment by sahilchaddha** [comment]
Yes. This also works. For me, i am providing directory path for all the models. Hence renaming works for me. `modelPaths: "/models/*.model"`

**Comment by RobinBuschmann** [comment]
@Aleksaas @sahilchaddha Maybe I misunderstood something, but when using `addModels` it is important to add all models, which have relations between each other, at once(!). So if you have an association between `User` and `UserAddress`, you need to `addModels([User, UserAddress])`

**Comment by Aleksaas** [comment]
@RobinBuschmann Yes, but if u do something like this in `User` model: `include: [() => UserAddress.scope("dto")]` it will throw an error if u define `UserAddress` after `User`  like this: `addModels([User, UserAddress])`. But if u define like this `addModels([UserAddress, User])` it will work. That was the problem in my case. The order was important.

**Comment by RobinBuschmann** [comment]
@Aleksaas Thanks for clarifying that :)

**Comment by tdiam** [comment]
Is there any workaround for cases where both models need to use a scope of the other.

Example:
```TypeScript
// User.ts
@Scopes({
    someScope1: { ... },
    withAddress: {
        include: [{
            model: () => UserAddress.scope("someScope2"),
            as: "address"
        }]
    }
})
class User extends Model<User> { ... }
```
and
```TypeScript
// UserAddress.ts
@Scopes({
    someScope2: { ... },
    withUsers: {
        include: [{
            model: () => User.scope("someScope1"),
            as: "user"
        }]
    }
})
class UserAddress extends Model<UserAddress> { ... }
```

No order in `addModels` can fix this kind of circularity and Sequelize will always fail with `Invalid scope [...] called`. Any help appreciated.

**Comment by tdiam** [comment]
I solved this by adding the scopes dynamically where needed, as per [sequelize#9864](https://github.com/sequelize/sequelize/issues/9864). I used the [addScope](http://docs.sequelizejs.com/class/lib/model.js%7EModel.html#static-method-addScope), since the solution with functional scopes from sushantdhiman did not work.

```typescript
UserAddress.addScope("withUsers", {
    withUsers: {
        include: [{
            model: () => User.scope("someScope1"),
            as: "user"
        }]
    }
})
```

**Comment by flogvit** [comment]
Didn't find any way to do this with sequelize-typescript, so this is how I solved it:

I added <model>.scopes.ts files in the same folders as the <model>.model.ts files. The <model>.scopes.ts files looks something like:

```javascript
UserAddress.addScope("withUsers", {
  include: [
    {
      model: User.scope("someScope1"),
      as: "user"
    }
  ]
}
```

Then I load everything like:

```javascript
  const path = require('path');
  const glob = require('glob');

  sequelize.addModels([__dirname + "/../**/*.model.ts"]);
  glob.sync( __dirname + "/../**/*.scopes.ts" ).forEach( function( file ) {
    require(path.resolve(file);
  }
```

**Comment by RobinBuschmann** [comment]
I came to the conclusion that there is no way to solve this. It makes perfectly sense, that the order matters here. Since you can't add a scope which depends on another which isn't resolved at the time of adding the former scope. So I think the only solution is - as @tdiam already pointed out - to add the scope dynamically.

**Comment by dever23b** [comment]
Is there any chance this could be revisited?

It seems like this issue shouldn't need to exist.  In the Sequelize code, they use Toposort after initialization of the models to sort them by dependencies (associations) prior to executing tasks that require the proper order of models loading.  It seems like a simple sort after defining the models, before associating them, could fix this issue.

https://github.com/sequelize/sequelize-typescript/blob/9baa5845123ff14ae641892d8d8cdebeb7612cf2/src/sequelize/sequelize/sequelize.ts#L52-L53
