### ISSUE TITLE
How to Resolve TS2339: Property 'length' does not exist on type 'Model<{}> | Model<{}>[]'.

### ISSUE THREAD

**Issue by nevyen** [RobinBuschmann/sequelize-typescript#389]
Hey guys, 

I have created a many to many association. And it all works fine. My Models are:

```
@Table
export class Role extends Model<Role> {

    public static PROPERTY_KEY_USER: string = "permissions";

    @Column
    name: string;

    @BelongsToMany(() => User, () => UserRole)
    permissions: User[];
}
```
```
@Table
export class User extends Model<User> {

    public static PROPERTY_KEY_ROLE: string = "role";

    @Unique
    @AllowNull(false)
    @Column
    username: string;

    @Unique
    @IsEmail
    @Column
    email: string;

    @AllowNull(false)
    @Column
    password: string;

    @AllowNull(false)
    @Column
    name: string;

    @BelongsToMany(() => Role, () => UserRole)
    role: Role[];

    @BeforeCreate
    @BeforeUpdate
    static hashPassword(instance: User) {
        if (instance.changed("password")) {
            let hash = bcrypt.hashSync(instance.password, config.get("app.security.saltRounds"));
            instance.password = hash;
        }
    }

    comparePasswords(password: string): Promise<boolean> {
        return bcrypt.compare(password, this.password);
    }
}
```
```
@Table
export class UserRole extends Model<UserRole> {

    @ForeignKey(() => User)
    @Column
    userId: number;

    @ForeignKey(() => Role)
    @Column
    roleId: number;
}
```
Now I am trying to get all Roles of an User. So I can check if my user ist allowed to access the data. 
The method I'm trying to do this looks so: 

```
    // return a middleware
    return (req: Request, res: Response, next: NextFunction) => {
        User.findById(req.params.userId).then(user => {
           return user.$get(User.PROPERTY_KEY_ROLE).then(roles => {
               console.log("Roles: " + prettyjson.renderString( JSON.stringify(roles)));
                 for (let i: number = 0; i < roles.length; i++) {
                     if (req.params.userId && isAllowed(roles[i].name)) {
                         return next();
                     } //role is allowed, so continue on the next middleware
                 }
            }).catch(err => {
                    console.log(err);
                }
            );

        }).catch(err => (
            res.status(403).json({message: "Forbidden"})
        ));
        //res.status(403).json({message: "Forbidden"}); // user is forbidden
    };
```
Now my problem is that typescript complains about "roles.length". It seems the promise doesn't be an array. So how can I avoid this?

**Comment by jeremyhon** [comment]
I have a similar situation where I'm retrieving an array of associations via the `$get` method
```
// Imagine Post hasMany Comments
Post.getComments = () => {
  const comments: Comments[] = await this.$get('Comments')
}
```
TS won't let me add the type annotation because "includes" doesn't exist on Model<{}>, which is the singular form of the Model. However I'm trying to retrieve an array of said models (Model<{}>[]) which _should_ have the `includes` method. 

Any ideas for workarounds or solutions? This is a great library by the way.

**Comment by RobinBuschmann** [comment]
@nevyen Since typescript cannot infer the type automatically here, you have to explicitly set the type like:
```ts
user.$get(User.PROPERTY_KEY_ROLE).then((roles: Role[]) => /* ... */ );
```
or in @jeremyhon case, when using `async/await` the type need to be casted:
```ts
const comments = (await this.$get('Comments') as Comments[])
```

**Comment by nevyen** [comment]
Thanks for your help. Maybe you can add this to your example. If your are new to typscript it's a little complicated. 

Closed for me. Whats about @jeremyhon ?

**Comment by jeremyhon** [comment]
Awesome. I originally used a type cast function but your solution is more concise. Thanks for the fast response.

**Comment by praveenfzs** [comment]
hello, I am import type jquery in ionic 4 project.
To count remaining character in input field, i had attach error below.
![Ionic App](https://user-images.githubusercontent.com/39900321/61368487-912c8a00-a8ab-11e9-8786-49005e285895.png)
