### ISSUE TITLE
AnyWhereOptions don't allow NULL

### ISSUE THREAD

**Issue by mxs42** [RobinBuschmann/sequelize-typescript#391]
Consider having this code:
```
        MyModel.update({
            field: "field_value",
        }, {
            where: {
                field: null
            }
        });
```
Sequelize supports this code, where clause is `WHERE field IS NULL` in this case.  
Type definitions don't allow NULL:
```
    /**
     * A hash of attributes to describe your search, accepting any field names. See `WhereOptions` for details.
     */
    interface AnyWhereOptions {
        [field: string]: WhereOptions<any>[] | Object;
    }
```

Why can't we have `WhereOptions<any>[] | Object | null` there?

**Comment by RobinBuschmann** [comment]
Hey @mxs42, thanks for reporting, but this is an `@types/sequelize` issue (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L3188). Can you report it there or create a PR fixing this issue?

**Comment by mxs42** [comment]
Sorry, completely misunderstood this thing about relationships between sequelize-typescript and types, I will create a PR in their repo later.
