### ISSUE TITLE
Different scopes for WHERE and SELECT

### ISSUE THREAD

**Issue by Aleksaas** [RobinBuschmann/sequelize-typescript#396]
This is not a bug reporting, it is only a question, and if it is not possible currently maybe it can become feature.
When I get `Users` from DB I have something like this in my `where` clause `'$customer.name$'` where `customer` is property on `User`.
Because of that I need to put this in `User` scope: `include: [() => Customer]`. If I don't do that I would get error: `missing from-clause entry for table`.
So far so good, but the problem is that doing so it will also return `Customer` inside `User` as a response, and I don't want that, I only included it so `where` clause doesn't throw an error.
Is there a way to use one scope to support `where` clause and another scope as a result of query? Because what you need in `WHERE` is not the same as what you want in `SELECT`.
If this is not possible, is there any other approach to solve this problem?

**Comment by Aleksaas** [comment]
I found solution, if u want something to be available for `where` and not appear in `select` this is how it should be included: `include: [{ model: User, attributes: []}]`. Don't know why this is not documented, it is important feature.

**Comment by RobinBuschmann** [comment]
@Aleksaas You're right, but this should be part of the sequelize docs - not the sequelize-typscript ones.
