### ISSUE TITLE
Many to Many relationship issue

### ISSUE THREAD

**Issue by michalejoye** [RobinBuschmann/sequelize-typescript#398]
I am having an issue with mapping the many to many when self ref. In my case, I have a User class which has a array of Users called friends. However I try to map the data, the array is always undefined.
I have a class called User which is like:
```
@Table
export class User extends Model<User> {

    @Column({
        autoIncrement:true,
        primaryKey:true
    })
    UserId:number;

    @Column({
        unique:true
    })
    UserName: string;
  
    @Column
    Banned: boolean;

    @BelongsToMany(() => User, () => FriendList)
    friends: User[];

}
```
and the FriendList class is
```
@Table
export class FriendList extends Model<FriendList> {

  @ForeignKey(() => User)
  @Column
  UserId: number;

  @ForeignKey(() => User)
  @Column
  FriendId: number;
}
```

**Comment by RobinBuschmann** [comment]
Hey @michalejoye, since both `ForeignKey` annotations are referencing the same model (`User`), sequelize-typscript cannot know which foreign key is the "own" ID and which one is the ID of the users friend. So you need to tell it explicitly like:

```ts
@Table
export class User extends Model<User> {
    ...
    @BelongsToMany(() => User, () => FriendList, 'UserId', 'FriendId')
    friends: User[];
}
```
If you do so, you can omit the ForeignKey annotation in your `FiendList` model
```ts
@Table
export class FriendList extends Model<FriendList> {

  @Column
  UserId: number;

  @Column
  FriendId: number;
}
```

An error message would be good here 🤔

**Comment by RobinBuschmann** [comment]
#401

**Comment by michalejoye** [comment]
So i tired those changes but it does not seem to work. User.friends is always returning null


'''
@Table
export class FriendList extends Model<FriendList> {

  @Column
  UserId: number;


  @Column
  FriendId: number;
}
'''
'''
@Table
export class User extends Model<User> {

    @Column({
        autoIncrement:true,
        primaryKey:true
    })
    UserId:number;

    @Column({
        unique:true
    })
    UserName: string;
  
    @Column
    Banned: boolean;

    @BelongsToMany(() => User, () => FriendList, 'UserId', 'FriendId')
    friends: User[];

}

'''

**Comment by RobinBuschmann** [comment]
Hey @michalejoye, I've completely overseen this one. Sorry for that. When querying data including related models, you have to say sequelize that you also want to retrieve this associated data:
```ts
User.findOne({
  where: {...},
  include: [User] // <---
});
```

**Comment by RobinBuschmann** [comment]
@michalejoye Can we close this issue now or do you still have an issue with that?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
