### ISSUE TITLE
Transactions in hooks

### ISSUE THREAD

**Issue by torkelrogstad** [RobinBuschmann/sequelize-typescript#404]
Is it possible to get access to the (possibly undefined) Transaction object in hooks defined on our models?

Like in [this](https://stackoverflow.com/questions/35014679/sequelize-hook-depending-on-transaction) SO question.

**Comment by RobinBuschmann** [comment]
@torkelrogstad Yes, sure:

```ts
class YourModel extends Model<YourModel> {
  @BeforeCreate
  static doSomething(instance, options) {
    // options.transaction
  }
}
```

**Comment by torkelrogstad** [comment]
Thank you! Does types exist for these options? I solved by problem by simply doing `{...options}` in all my queries within a hook, but that's a completely untyped solution.

**Comment by RobinBuschmann** [comment]
Hey @torkelrogstad sry for the late reply. Unfortunately there aren't any typings for that at the moment. But since the original issue was solved, I close this issue now.
