### ISSUE TITLE
Custom filename -> model matching

### ISSUE THREAD

**Issue by MatthiasKunnen** [RobinBuschmann/sequelize-typescript#405]
Would it be possible to allow a custom matcher instead of matching the filename directly to the model? I use `person.model.ts` as filename and `export class Person extends Model<Person>`. I don't want to use default exports because of reasons mentioned here: https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html.

I would suggest adding an optional modelMatch property to the Sequelize constructor. This property would be given a function which would be supplied with the filename (without extension) of a module that matches the modelPath and its exported members. The function should for each exported member decide (true or false) whether it is a model. 

**example**

```TypeScript
// person.model.ts

export interface PersonResponse {
}

export class Person extends Model<Person> {
}
```

```TypeScript
const sequelize = new Sequelize({
    modelPaths: [path.join(__dirname, 'api/**/*.model.ts')],
    modelMatch: (filename, member) => filename.startsWith(member.toLowerCase())
});
```

In this case, the modelMatch function would be called twice, one with `('person.model.ts', 'PersonResponse')` and once with `('person.model.ts', 'Person')`. As soon as this function return true, the matched exported member should be added as model.

Consumers of this library can then use any desired approach to matching, be it regexes, a predefined dictionary, ...

The default for this function would be `(filename, member) => filename === member`.

If you're interested in this proposal, I can make a PR.

**Comment by RobinBuschmann** [comment]
@MatthiasKunnen This sounds like a great idea to me. 👍Lets implement this

**Comment by MatthiasKunnen** [comment]
I assume based on the following that it is not: 
> One model class per file
This is not only good practice regarding design, but also matters for the order of execution. Since Typescript creates a __metadata("design:type", SomeModel) call due to emitDecoratorMetadata compile option, in some cases SomeModel is probably not defined(not undefined!) and would throw a ReferenceError. When putting SomeModel in a separate file, it would look like __metadata("design:type", SomeModel_1.SomeModel), which does not throw an error.
