### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by xlxAciDxlx** [RobinBuschmann/sequelize-typescript#406]
I just have a few questions that I feel like for some reason I'm struggling to wrap my head around.

### Scope Inclusions/Exclusions
For fetching the results of a `User`, I have the default scope set to _exclude_ the `password` field (because, duh). However, I can't seem to find any way to include the `role` field (linked to `UserRole` class).

### Table/Column Linking
For assigning a `User` a role (`UserRole`), I have the following code:
```ts
// Role Value
@BelongsTo(() => UserRole)
role: UserRole[];

// Role ID
@ForeignKey(() => UserRole)
@Default(1)
@Column
userRoleIds: number;
```
This works all fine and dandy, but is there any way for me to have it so I can define _multiple_ role IDs (i.e 1 - admin, 2 - developer) and get the role data for both of those records in the response?

**Comment by tzellman** [comment]
Not sure if this is what you are asking, but you could use a Virtual Column, which plucks out and maps the role(s) you care about.

e.g.
```
@Column({
    type: DataType.VIRTUAL,
    get(this: User) {
        return this.getDataValue('role').find((r) => r.id === 2);
    }
})
public adminRole: UserRole;
```

**Comment by xlxAciDxlx** [comment]
Thanks, @tzellman , I'll give that a shot! Also, has anyone found any good ways of automatically generating migrations? I get that's a big ask, but it seems tedious and rather time wasting to have to modify the `sequelize-typescript` model file (when you make changes to columns, etc) as well as to have to also type out a migration up/down.

**Comment by RobinBuschmann** [comment]
Hey @xlxAciDxlx, to include associated models in your queries you need to include the model like so. Nevertheless I see some issues in your setup. You expect your `User` model to have multiple roles, right? And a role can belong to multiple `User`? This seems to be a `many-to-many` relation to me:

```ts
@Table
class User extends Model<User> {
  @BelongsToMany(() => Role, () => UserRole)
  roles: Role[];
}
```
```ts
@Table
class Role extends Model<Role> {
  @BelongsToMany(() => User, () => UserRole)
  users: User[];
}
```
The "through" table:
```ts
@Table
class UserRole extends Model<UserRole> {
  @ForeignKey(() => User)
  userId: number;

  @ForeignKey(() => Role)
  roleId: number;
}
```
When querying data:
```ts
User.findAll({
  include: [Role]
});
```
or when using scopes:
```ts
@DefaultScope({
  include: [() => Role],
})
```

Hope this helps :)

**Comment by xlxAciDxlx** [comment]
Thanks, @RobinBuschmann, that's what I was looking for! :D Any answer on the migrations? :D

**Comment by xlxAciDxlx** [comment]
Any suggestions in regards to migrations?

**Comment by RobinBuschmann** [comment]
@xlxAciDxlx sry for the delayed reply. Currently I‘m using no sequelize integrated implementation for my migrations. I‘m happy with 
https://github.com/db-migrate/node-db-migrate - with dB-migrate i‘m writing raw migration queries in order to have full control over my database.

**Comment by xlxAciDxlx** [comment]
I'll give that a shot, thank you!

**Comment by xlxAciDxlx** [comment]
Yes, that's what I'm referring to. Would you mind providing a quick example? I'm not entirely sure I'm grasping how I'd go about this.

**Comment by RobinBuschmann** [comment]
Unfortunately not :/ I've never used the sequelize integrated data migrations. So I have no clue how to configure them. If you find out, I would appreciate it if you'd come back with your knowledge :)

**Comment by xlxAciDxlx** [comment]
Would you mind outlining your current method for me? Maybe I'd be able to wrap my head around it. I'm just super paranoid (at least on the production side of things) about messing up a live database that's actually used to power services. Haha And if I figure anything out, I definitely will share my knowledge!

**Comment by RobinBuschmann** [comment]
@xlxAciDxlx probably an example helps: https://github.com/ElisaBaum/maple-backend/tree/develop/migrations https://github.com/ElisaBaum/maple-backend/blob/develop/package.json#L7

With `db-migrate-plugin-typescript` you can also write your migrations in ts.

**Comment by awilkinsx** [comment]
@RobinBuschmann  & @xlxAciDxlx , If either of you are still interested in sequelize migration files let me know. I have some examples ranging from adding tables, columns and through tables.

**Comment by RobinBuschmann** [comment]
@awilkinsx Yes, I am interested :) Can you provide an example repo?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
