### ISSUE TITLE
reflect-metadata dependency

### ISSUE THREAD

**Issue by MatthiasKunnen** [RobinBuschmann/sequelize-typescript#407]
This library states in the README that it requires [reflect-metadata](https://www.npmjs.com/package/reflect-metadata). The consumer has to install this package manually. Why is this dependency not in the dependency list of `package.json` so that it is automatically installed along with `sequelize-typescript`?

**Comment by RobinBuschmann** [comment]
Hey @MatthiasKunnen, this is to prevent that multiple reflect-metadata packages get installed. Why? Each reflect-metadata installation has its own metadata storage, from which it reads and writes from. 
So if you had a project with multiple reflect-metadata packages, it could happen that in one file you write metadata in one reflect-metadata package and  in another file you’re trying to retrieve this metadata accidently from the other reflect-metadata package, which of course doesn’t exist there.

The only way is to list reflect-metadata in peerDependencies, but you would need to install it manually anyway.

**Comment by eddiemonge** [comment]
That sounds like a bad reason. Do you have a link to the docs that shows this happening? I don't understand how installing this as a peer prevents that. If anything, it just shifts the blame
