### ISSUE TITLE
"duplicating" property in "include" options

### ISSUE THREAD

**Issue by francisvalois** [RobinBuschmann/sequelize-typescript#408]
Hello, 

I'm using the "duplicating" property of the "include" options to get around a limitation with inner join where condition and limit select under the Sequelize library. I've found that the actual IBaseIncludeOptions does not include this property so i get many error from the TypeScript compiler.

The property is not shown into the documentation but is used in the actual code of Sequelize as shown here and is recommended for my type of query.

Obtained from Model.js, line 487 [(model.js)](https://github.com/sequelize/sequelize/blob/master/lib/model.js)
```
options.include = options.include.map(include => {
      include = this._conformInclude(include);
      include.parent = options;
      include.topLimit = options.topLimit;

      this._validateIncludedElement.call(options.model, include, tableNames, options);

      if (include.duplicating === undefined) {
        include.duplicating = include.association.isMultiAssociation;
      }

      include.hasDuplicating = include.hasDuplicating || include.duplicating;
      include.hasRequired = include.hasRequired || include.required;

      options.hasDuplicating = options.hasDuplicating || include.hasDuplicating;
      options.hasRequired = options.hasRequired || include.required;

      options.hasWhere = options.hasWhere || include.hasWhere || !!include.where;
      return include;
    });
```
I created a PR #409 to correct that.

**Comment by RobinBuschmann** [comment]
Can be closed due to #409
