### ISSUE TITLE
missing property in IFindOptions<F> 

### ISSUE THREAD

**Issue by b051** [RobinBuschmann/sequelize-typescript#410]
should have `includeIgnoreAttributes?: boolean` property

https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1451

**Comment by RobinBuschmann** [comment]
Thanks for reporting !

**Comment by RobinBuschmann** [comment]
According to one of the main maintainers of sequelize `includeIgnoreAttributes` isn't part of the public API.

https://github.com/sequelize/sequelize/issues/8670#issuecomment-346096561
