### ISSUE TITLE
Initialize object after loading from database

### ISSUE THREAD

**Issue by Mc128k** [RobinBuschmann/sequelize-typescript#411]
Hi
This is not a bug, but a question I could not find the answer for. I am trying to initialise an object after loading it from the database, so it creates an internal state before being usable. Normally you would do these things from the constructor, but apparently the data is still not defined when it's being called.

So I thought about hooks, but it didn't work. Basically I want the object to be initialised every time an instance of it is created, wether new, loaded or whatever.

I'm new to ORMs, and I'm even considering that the pattern I'm using could be bad. Basically I'm using the models as full classes with instance variables (not stored) and internal state. Is it ok or I should separate the models from the classes?

The use case for this is to instantiate a chat bot object from the database (loads the configuration and state) and while it's created it instantiates an internal library for communicating with the server.

Thanks

**Comment by RobinBuschmann** [comment]
Hey @Mc128k, can you provide some code snippets/examples so that we can get a better idea of what you want to achieve please? :)

**Comment by Mc128k** [comment]
It's a simple matter of calling some code whenever a new instance is created. Like using a constructor, I would like to be able to initialize some stuff when the class is created (after the instance variables are populated with the database data).

So when I create / update / load an instance it always perform some stuff immediately after the object is created.

**Comment by RobinBuschmann** [comment]
Sounds totally like hooks are the solution for that - what issues did you faced with hooks?

**Comment by Mc128k** [comment]
The fact that apparently there is no hook that covers the "load" operation. Or maybe I could not find it. I tried some hooks but they weren't fired at the right moment

**Comment by RobinBuschmann** [comment]
@Mc128k If you don't want to do async stuff, you could use the `constructor`. After the `super` call the instance variables should be fully initialized:
```ts
constructor(values?: FilteredModelAttributes<T>, options?: IBuildOptions) {
  super(values, options);
  // ...
}
```

If you want to use hooks, you'd need to combine hooks. Something like:
```ts
@AfterCreate
@AfterFind
//...
static processRecord(record) {
}

@AfterBulkCreate
//...
static processRecords(records) {
  records.map(record => this.processRecord(record))
}
```

**Comment by Mc128k** [comment]
I was missing the constructor arguments, I think that's more than ok.

Thanks a lot
