### ISSUE TITLE
ignoreDuplicates not working when individualHooks is true

### ISSUE THREAD

**Issue by Diluka** [RobinBuschmann/sequelize-typescript#415]
### VERSIONS
 - `sequelize`: `4.38.0` 
 - `sequelize-typescript`: `0.6.5`

### PROBLEMS
Only `ignoreDuplicates: true` it will generate `INSERT IGNORE ...` statements. If both `ignoreDuplicates: true` and `individualHooks: true` it generates `INSERT ...` statements only.

P.S. I'm not sure this issue is belongs to `sequelize-typescript` or `sequelize`.

**Comment by RobinBuschmann** [comment]
Sounds like a `sequelize` issue. Can you verify by reproducing it with sequelize only?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
