### ISSUE TITLE
Question : Use Abstract Class in associations

### ISSUE THREAD

**Issue by BenjaminDish** [RobinBuschmann/sequelize-typescript#418]
Hello,

It is an issue but a true question. Here is my use case :

I have a generic class CompteSpecial
```typescript
@Table
export class CompteSpecial<T> extends BaseModel<CompteSpecial<T>> {

    @Column(DataType.STRING)
    public urlCompte: string;
    
    @Column(DataType.ENUM(listEnumMemberNames(CompteSpecialType)))
    public typeCompteSpecial: string;
}
```

implemented by 2 classes : CompteSpecialPresta and CompteSpecialRZ

```typescript
@Table({ tableName: 'compte_special_presta' })
export class CompteSpecialPresta extends CompteSpecial<CompteSpecialPresta> {

    @Column(DataType.STRING)
    public societe: string;

    @Column(DataType.STRING)
    public mailsANotifier: string;

    @Column(DataType.ARRAY(DataType.BIGINT))
    public lotsAccessiblesId: Array<number>;
    
}
```

```typescript
@Table({ tableName: 'compte_special_rz' })
export class CompteSpecialRZ extends CompteSpecial<CompteSpecialRZ> {

    @Column(DataType.STRING)
    public zone: string;

}
```
and in a Compte Class, I need to build a @BelongToMany Association with theses classes like :

```typescript
@Table({ tableName: 'compte' })
export class Compte extends BaseModel<Compte> {

    @BelongsToMany(() => CompteSpecial, () => CompteComptesSpeciaux)
    public comptesSpeciaux: CompteSpecial[];
}
```

So as you can see, I need the comptesSpeciaux attribute to refer to an array of CompteSpecial, which can be CompteSpecialPresta or CompteSpecialRZ. The above Compte.ts code doesn't compile as CompteSpecial is a generic type an needs to be specified. 

Do you know a way to implement such a use case ?

**Comment by RobinBuschmann** [comment]
Hey @BenjaminDish, association scopes are the right way to do this. Look at the sequelize docs here: http://docs.sequelizejs.com/manual/tutorial/associations.html#scopes

If you still have questions, don't hesitate to ask ;)

**Comment by RobinBuschmann** [comment]
Hey @BenjaminDish, sry for the late reply. Completely overseen this one. Is this still an issue for you? How do you want to retrieve the data for `CompteSpecialPresta`, `CompteSpecialRZ`, ...?

**Comment by BenjaminDish** [comment]
@RobinBuschmann I finally decided to work diferently and not trying to do this (which was quite strange actually). So problem not solved but the problem is not a problem anymore ^^.

Thanks. I close the issue
