### ISSUE TITLE
hooks option in @Table decorator is broken

### ISSUE THREAD

**Issue by wbk** [RobinBuschmann/sequelize-typescript#421]
Given a model `foo.ts`

```
@Table({hooks: {
    beforeCreate: (instance, options) => {}
}})
export default class Foo extends Model<Foo> {}
```

An attempt to load this model will throw `Error: Model not initialized: "Foo" needs to be added to a Sequelize instance before "addHook" can be called.` during the model's own initialization process.

Sequelize ultimately calls `this.Addhook()` for every item specified in a Table's `hooks` options property, but the options are processed by sequelize before a model's `isInitialized` property is set to `true` by sequelize-typescript.

Either the `hooks` property should be removed from typings or `overrideStaticFunctions` should not apply to `addHook`, so that sequelize's built-in `hooks` option can be used as designed.  I suggest the latter.

**Comment by wbk** [comment]
I'm a fan of the latter, selfishly, because it makes a use case of mine slightly cleaner :)

In my opinion, the error-message-displaying override breaks Sequelize.  Sequelize internally calls this function, ultimately within `sequelize.define`, which as far as things go is pretty important.  Sequelize would run as expected if this override were not in place and Sequelize could call its own implementation.  For those who would rely on the usefulness of a `Model not initialized` warning, I would hope anyone who attempts to use an uninitialized model should find a useful error message scrolling across their screen well before they start tacking hooks onto its instance. 

Additionally, I'd advocate against removing `hooks` from typings.  I feel the `hooks` option is the most convenient way of applying helper methods which are defined elsewhere.  The project of mine which brought this issue to light, for example, relies on a snowflake-like service for primary key generation within a particular table.  I've found it convenient to be able to pass a hook function by reference:

```
import { baz } from '../helpers/baz'

@Table({hooks: {
    beforeCreate: baz // I can pass a reference to the hook function
}})
export default class Foo extends Model<Foo> {}
```

Rather than have to wrap it, using sequelize-typescript's decorators:

```
import { baz } from '../helpers/baz'

@Table
export default class Foo extends Model<Foo> {
    @BeforeCreate
    static doBaz(instance, options) {
        baz(instance, options); // This feels unnecessarily verbose
    } 
}
```

This could also be solved by calling addHook directly on an initialized model instance, but I'd consider it even worse because it would decouple a model's hooks from its definition.

Thoughts?

**Comment by wbk** [comment]
@RobinBuschmann that makes perfect sense to me.  Want a PR?

**Comment by RobinBuschmann** [comment]
@wbk PRs are welcome 👍
