### ISSUE TITLE
 SQL syntax error. findAndCountAll with scopes

### ISSUE THREAD

**Issue by ALjean** [RobinBuschmann/sequelize-typescript#427]
When a use Model.scope(['scope1']).findAndCountAll({distinct: true})

I get an SQL sql syntax error.
SELECT DISTINCT('id') FROM .....   // some joins with aliases
Expected result:

DISTINCT('id') =>  DISTINCT('aliasName.id')

It's happend because scope adds empty array``` include: [] ```.
And sequelize.count() add alias to query DISTINCT('aliasName.id').

sequelize-typescript/services/models.js
method inferAlias() remove options.include if length is 0.

**Comment by RobinBuschmann** [comment]
@ALjean thanks for reporting. So with pure sequelize this is working. Do I understand you properly here?

**Comment by ALjean** [comment]
@RobinBuschmann Yes.

**Comment by RobinBuschmann** [comment]
Fixed with #450
