### ISSUE TITLE
Provide "schema" in the Sequelize constructor parameter

### ISSUE THREAD

**Issue by aviranco** [RobinBuschmann/sequelize-typescript#429]
I am using PostgreSQL, and I would like to pass the "schema" of PostgerSQL (to put the tables in) in the Sequelize ctor options and it seems it doesn't exist.

I know there is a @table decorator on each model, but I want to define it once when I define the specific connection instead of define every time in every model declaration. 

I did it in the Sequelize ctor like this:
```
      sequelize = new Sequelize({database: databaseConfig.database,
      username: databaseConfig.username,
      password: databaseConfig.password,
      options: {
        host: host,
        port: port,
        dialect: 'postgres',
        schema: 'SCHEMA NAME"
      }
```

Thanks

**Comment by RobinBuschmann** [comment]
@aviranco Try this
```ts
new Sequelize({
  ...,
  define: {
    schema: 'SCHEMA NAME'
  }
})
```

**Comment by RobinBuschmann** [comment]
@aviranco does the suggested solution work for you. Can we close this issue?

**Comment by RobinBuschmann** [comment]
Close this issue due to no further information was given.

**Comment by aviranco** [comment]
yes thanks

**Comment by dibyendumca** [comment]
Hello,
How can I pass the schema name as a parameter to the model class, during the runtime?
