### ISSUE TITLE
Add options on BelongsToMany

### ISSUE THREAD

**Issue by AamuLumi** [RobinBuschmann/sequelize-typescript#431]
Hi !

Is there a way to add options on a `BelongsToMany` relation as mentioned in [Sequelize doc](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-belongsToMany) ?
I read in the doc that `@BelongsToMany(relatedModelGetter: () => typeof Model, through: string, options: AssociationOptionsBelongsToMany)` exists, but it doesn't seem to work (typescript error).

And is there a way to add this kind of function ? : `@BelongsToMany(relatedModelGetter: () => typeof Model, through: (() => typeof Model), options: AssociationOptionsBelongsToMany)`

Thanks for all the work you already achieved ! :)

**Comment by RobinBuschmann** [comment]
Hey @AamuLumi, the docs are wrong here - It rather should be:
```ts
@BelongsToMany(relatedModelGetter: () => typeof Model, options: AssociationOptionsBelongsToMany)
```

Hope this helps.

**Comment by RobinBuschmann** [comment]
#432

**Comment by AamuLumi** [comment]
Okay thanks !

I tested this function (with the `through` field in option), and got this : 
```Foreign key for "SourceModel" is missing on "MiddleTable".```
But I don't have this error when using the `@BelongsToMany(relatedModelGetter: () => typeof Model, through: (() => typeof Model))` signature. Seems there's a bug too on the `through` string value which is not resolved correctly. That's why I asked if this signature with an `options` field could be a good idea. :)

**Comment by RobinBuschmann** [comment]
@AamuLumi Can you show me how your MiddleTable class look like?

**Comment by AamuLumi** [comment]
```
@Table({ tableName: 'MiddleTable' })
class MiddleTable extends Model<MiddleTable> {
	@Column description!: string;

	@ForeignKey(() => SourceModel)
	@Column
	SourceModelId!: number;

	@ForeignKey(() => SecondModel)
	@Column
	SecondModelId!: number;
}
```

**Comment by RobinBuschmann** [comment]
Looks good so far. Can you provide an example repo which reproduces the issue?

**Comment by AamuLumi** [comment]
Here's a fork of seqyelize-typescript-example with the problem. I updated `Actor` with the code which isn't working (l.30->35) : https://github.com/AamuLumi/sequelize-typescript-example

**Comment by AamuLumi** [comment]
I found this way works : 
```
@BelongsToMany(() => Movie, {
    onUpdate: "CASCADE",
    onDelete: "CASCADE",
    through: () => MovieActor,
  })
  movies?: Movie[];
```

So it seems that there's only the string `through` option which doesn't work.

**Comment by RobinBuschmann** [comment]
Hey @AamuLumi,

you have to use either the model getter (`() => ThroughModel`) or the string representation of the through table in both(!) models (`Movie` and `Actor` in case of the example).

Yep, this way `through: () => MovieActor` is supported as well :) If you're fine with your posted solution, can we close this issue then?

**Comment by AamuLumi** [comment]
Oh okay ! Thanks a lot for the clarification ! :)

Issue resolved ! And another thanks for this amazing library.
