### ISSUE TITLE
IsEmail options

### ISSUE THREAD

**Issue by Pritilender** [RobinBuschmann/sequelize-typescript#434]
I've got a model that has `IsEmail` decorator for email validation, but I want to pass in `required_tld: false` option to validator.js ([more options are listed under `isEmail`)](https://github.com/chriso/validator.js#validators), but I don't know how. I've tried with `@Is('email)`, but turns out that it's not the proper way. Even tried stupid things like attaching object as `@IsEmail({...})`.

So, is there a way to pass options for `isEmail` validator using `IsEmail` decorator?

**Comment by RobinBuschmann** [comment]
Hey @Pritilender this isn't possible with sequelize-typescript's `IsEmail` annotation for now and I don't know if it is with pure sequelize. The docs are not 100 percent clear here.

You could try to find out with `@Column({validate: {isEmail: ...}})`. Pass your options and see if it works

**Comment by Pritilender** [comment]
@RobinBuschmann yup, it works, but typings do not support passing object as a parameter for `isEmail` validator. I guess I'll have to make a PR for @types/sequelize then.
