### ISSUE TITLE
Foreign Keys cannot be nullable

### ISSUE THREAD

**Issue by patrickatkeylogic** [RobinBuschmann/sequelize-typescript#436]
My model requires an optional reference to my User table through the User table's `id` primary key but when the table is created the `userId` field is always not nullable. Is this possible through the library? I hope I'm just missing something.

Here's my column definition:
```  
  @ForeignKey(() => User)
  @AllowNull(true)
  @Column(DataType.INTEGER)
  userId: number;
```

Thanks!

**Comment by RobinBuschmann** [comment]
Hey @patrickatkeylogic, you need to define this in your association decorators (`@BelongsTo`, `@HasOne`, ...) for example:

```ts
@BelongsTo(() => User, {
    foreignKey: {
      allowNull: true
    }
})
```

**Comment by RobinBuschmann** [comment]
@patrickatkeylogic Does the suggested solution work for you? Can we close this issue?

**Comment by patrickatkeylogic** [comment]
I didn't end up using it so I can't confirm, sorry!
