### ISSUE TITLE
Typing of $set and $get

### ISSUE THREAD

**Issue by iRath96** [RobinBuschmann/sequelize-typescript#437]
Is there a specific reason why these methods do not make use of `keyof`?
For example, 

`$set<R extends Model<R>>(propertyKey: string, instances: R | R[] | string[] | string | number[] | number, options?: IAssociationActionOptions): Promise<this>;`

could instead be defined as:

`$set<T extends keyof this>(propertyKey: T, instances: this[T], options?: IAssociationActionOptions): Promise<this>;`

Thus rendering it type-safe.

**Comment by RobinBuschmann** [comment]
Hey @iRath96, I thought about it, too. But sequelize supports singular and plural values, which wouldn't be covered by `keyof` unfortunately.

**Comment by iRath96** [comment]
Hey @RobinBuschmann, I don't see the issue with this right now. Can you elaborate a bit more on this, please?

In my codebase, I've got a situation like this:
```typescript
@BelongsTo(() => Group)
parent: Group;

@HasMany(() => User)
users: User[];
```

and for both cases (singular + plural), using the `keyof` approach works fine here.

**Comment by RobinBuschmann** [comment]
You could write `someInstance.$add('user', ...)` which would cause an compiler error, since `user` is not a known property of your model

**Comment by iRath96** [comment]
Ah, I get your point. I see why it's hard to make `$add` (as well as `$del` etc.) type-safe, but this does not affect `$set` and `$get`, right?

**Comment by RobinBuschmann** [comment]
I‘ll have to check that but I think you are right - we should use keyof for get and set

**Comment by nickbclifford** [comment]
Additionally, would it be realistic to change the API of `$add` to take in a plural instead of a singular? This would allow for maximum type safety, and you could just use the [`inflection`](https://www.npmjs.com/package/inflection) library that Sequelize internally uses to make the key singular and call the Sequelize method from there.

```typescript
// Add a new type for the string and number case
type ModelLike<R extends Model<R>> = R | string | number;

type ArrayPropertyKeys<T, R extends ModelLike<R>> = {
	[K in keyof T]: T[K] extends Array<R> ? K : never;
}[keyof T];
abstract class Model<T extends Model<T>> {
    // - snip -
    $add<R extends ModelLike<R>>(propertyKey: ArrayPropertyKeys<T, R>, instances: R | R[], options?: IAssociationActionOptions): Promise<this>;
}

// inside the implementation
return this['add' + capitalize(inflection.singularize(propertyKey))](instances, options);
```
I realize that modifying the consumer API would be a fairly major change, but considering that it's in the interest of maximum type safety, it might be worth considering.

**Comment by RobinBuschmann** [comment]
@nickbclifford Thanks for bringing this up and sorry for the late reply. Restricting the type to arrays only, won't work for has-one relations. Since there the `get`/`set` methods are used as well.
