### ISSUE TITLE
How to get random records from db?

### ISSUE THREAD

**Issue by Doraemon2010** [RobinBuschmann/sequelize-typescript#441]
public async GenRandAdsByType(type: number): Promise<Ads | null> {
           let queryCondition = { where: { ad_type: type }, order: "rand()"     };
           return await this.adsRepository.findOne<Ads>(queryCondition);
}
I want to set order by  rand(),  but get   Ads.rand()  not found ..

how can I set raw  sql to  mysql ?

or Maybe I can use QueryBuilder  build raw sql ?

Thx.

**Comment by RobinBuschmann** [comment]
Hey @Doraemon2010 see this example: https://github.com/sequelize/sequelize/issues/3156#issuecomment-74792600

**Comment by Doraemon2010** [comment]
Thx.
