### ISSUE TITLE
Association reference 

### ISSUE THREAD

**Issue by JulianMined** [RobinBuschmann/sequelize-typescript#442]
Hello,

how can i get reference of my association like this:
`const UserTasks = User.hasMany(Task, {as: 'tasks'});
`
I need it for the "resolver" method of the package "graphql-sequelize" and i couldn't found a way...

Thanks, Julian

**Comment by brianalois** [comment]
I am also looking for this. Do you have a solution?

**Comment by JulianMined** [comment]
Yes, this is working.

`export default class User extends Model {
    static init(sequelize){
        return super.init({
            id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
            name: Sequelize.STRING,
            email: Sequelize.STRING,
            password: Sequelize.STRING,
        },{
            sequelize,
            tableName: 'users'
        })
    }

    static associate(models) {
        this.Channels = this.belongsTo(models.Channel)
    }
}`

`resolver(User.Channels)`

**Comment by brianalois** [comment]
where is assiciate called?

**Comment by brianalois** [comment]
Here is a issue that had a solution: https://github.com/RobinBuschmann/sequelize-typescript/issues/199

resolver(User.associations.channel) would have worked for you
