### ISSUE TITLE
Still creating invalid Postgres/MySQL queries

### ISSUE THREAD

**Issue by TimMensch** [RobinBuschmann/sequelize-typescript#446]
Bug #135 was closed for "no followup", but is being ignored even though another person posted that he was having the same issue.

Well, now I'M having this issue, and I tracked it down to a bug in `sequelize-typescript`. Rather that post it on the closed bug, where based on the history it may be ignored, I'm filing a new bug.

It's a combination of three things:

* sequelize-typescript sets `distinct:true` as a default.
* sequelize-typescript deletes an empty `include:[]` array from settings.
* sequelize-typescript then calls `count()` on the model, which causes Sequelize to generate bad SQL.

Leaving an empty `include` array fixes the problem. This can be fixed by deleting a single line from `/lib/services/models.js`:

```javascript
/**
 * Pre conform includes, so that "as" value can be inferred from source
 */
function inferAlias(options, source) {
    options = __assign({}, options);
    if (!options.include) {
        return options;
    }
    // if include is not an array, wrap in an array
    if (!Array.isArray(options.include)) {
        options.include = [options.include];
    }
    else if (!options.include.length) {
//        delete options.include; // *** Removing this line fixes the issue, and it seems redundant anyway
        return options;
    }
    // convert all included elements to { model: Model } form
    options.include = options.include.map(function (include) {
        include = inferAliasForInclude(include, source);
        return include;
    });
    return options;
}
```

To repro the bug, you should be able to create any table with sequelize-typescript, and then share the service with pagination enabled (using `feathers-sequelize`):

```javascript
    const userService = service({ Model: User, paginate: { max: 50, default: 50 } });
    app.use("users", userService);    
```

`feathers-sequelize` calls findAndCountAll() on the model. `feathers-sequelize` defaults the `distinct` to true, and while there's a workaround that involves adding a hook to every service, it would be nice if this combination didn't crash at the `sequelize-typescript` layer.

I'm currently not set up to perform pull requests on sequelize-typescript; please let me know if you can apply this fix ASAP so that we don't need to continue work around this bug.

**Comment by TimMensch** [comment]
(Updated the bug report to clarify that I was using `sequelize-typescript` with `feathers-sequelize`.)

**Comment by RobinBuschmann** [comment]
@TimMensch Thanks for reporting. Can you create a PR for that?

**Comment by TimMensch** [comment]
OK, PR is done.

**Comment by TimMensch** [comment]
Any chance you can publish a new build with this fix? I'm now running into a conflict where I _need_ `distinct` to be enabled, but I can't enable it because of the bug.

**Comment by RobinBuschmann** [comment]
Hey @TimMensch, it should already be part of `sequelize-typescript@0.6.7-beta.0`

**Comment by TimMensch** [comment]
AND I'm using a new version of Sequelize-TypeScript, and this bug _has returned_.

Can you please fix ASAP _again_? Sent another PR: https://github.com/RobinBuschmann/sequelize-typescript/pull/736
