### ISSUE TITLE
Is it possible to pass multiple model paths to sequelize.addModels() ?

### ISSUE THREAD

**Issue by byebyebears** [RobinBuschmann/sequelize-typescript#451]
I have several sub-apps and want to have my models organized per sub-app instead of in one models directory. Like, app1/models, app2/models, etc. The models are in the same database, but I just want to organize them with their related app. I tried,

`sequelize.addModels(__dirname + 'path/to/app1/models/');`
`sequelize.addModels(__dirname + 'path/to/app2/models/');`

and I get,

`Error: Model not initialized: "Example" needs to be added to a Sequelize instance before association can be resolved.`

There is an association between two models, but they happen to be in separate directories.

**Comment by RobinBuschmann** [comment]
Hey @byebyebears, yes this is possible. Either with separate `addModels` calls like you did in your example or  
```ts
sequelize.addModels([__dirname + 'path/to/app1/models/', __dirname + 'path/to/app2/models/']);
``` 
You can also use globs like `sequelize.addModels([__dirname + 'path/to/*/models/*']);`

Please note that models, which are related to each other, have to be added at once! For example if `User` is related to `Group` you cannot add them separately like `sequelize.addModels([User]);`
`sequelize.addModels([Group]`);` but `sequelize.addModels([User, Group]`) would do the job

Hope this helps

**Comment by RobinBuschmann** [comment]
@byebyebears Can we close this issue now?

**Comment by Mosouley** [comment]
That was a key answer, since my dirname could not add the related models
i finally got it done, by adding each of the models once, because they were related
You can also use globs like sequelize.addModels([__dirname + 'path/to/*/models/*']);

sequelize.addModels([Model1, Model2, Model3]) and it did the job!
