### ISSUE TITLE
How to use underlying Sequelize classes

### ISSUE THREAD

**Issue by saachinsiva** [RobinBuschmann/sequelize-typescript#453]
Hi

I would like to use many of the underlying classes from Sequeseliz e.g. Transaction etc as a param of our functions and I could not do it unless I install @types/sequelize project or I will have to reference the sequelize installed as part of this package using relative path which I think is not a good idea.

So far we install both @types/sequelize and @types/sequelize-typescript and then import Transaction from sequelize but as soon as I upgrade the version to 0.6.6, I get this error in VSCode and I am not even sure if it is a bug in vs code.

> Type 'import("c:/proj/server/node_modules/@types/sequelize/index").Transaction' is not assignable to type 'import("c:/proj/server/node_modules/sequelize-typescript/node_modules/@types/sequelize/index").Transaction'.

Please advise.

**Comment by RobinBuschmann** [comment]
@saachinsiva Just use the `Sequelize` reference from `sequelize-typescript`
```ts
import {Sequelize} from 'sequelize-typescript';

Sequelize.Transaction
```

**Comment by saachinsiva** [comment]
Hi

Thanks for looking in to this issue. I tried that before and was getting an error as below

> [ts] Cannot access 'Sequelize.Transaction' because 'Sequelize' is a type, but not a namespace. Did you mean to retrieve the type of the property 'Transaction' in 'Sequelize' with 'Sequelize["Transaction"]'?

**Comment by RobinBuschmann** [comment]
Hey @saachinsiva, I have no issues using `Transaction` like I did in my example. So I'm getting no errors. Can you provide an example repo which reproduces the issue?

**Comment by saachinsiva** [comment]
Thanks for your time. I am not sure if I can share the code due to company copyright policy. I will try to mimic something and share it once available.

**Comment by RobinBuschmann** [comment]
Hey @saachinsiva are you still on this issue? Will you have time to provide an example repo in the near future?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
