### ISSUE TITLE
Example of Bridge Tables

### ISSUE THREAD

**Issue by kferrone** [RobinBuschmann/sequelize-typescript#454]
Would be nice to see an example of how to make a proper bridge table relationship (aka Many to Many) using `sequelize-typescript`.  Since no examples, I must trial and error till I figure it out. Wish me luck . . .

**Comment by RobinBuschmann** [comment]
Hey @kferrone, What about https://github.com/RobinBuschmann/sequelize-typescript#many-to-many? :)

**Comment by RobinBuschmann** [comment]
Hey @kferrone, can you share your repo with me, so that I can check?

**Comment by kferrone** [comment]
OK so I can't give the full project I'm on at work but I did simplify what I'm doing down to just using `sequelize-typescript`. 

Here is the repo I made real quick this morning: [kferrone/sequel_fun](https://github.com/kferrone/sequel_fun)

The repo shows off perfectly my issue if you were to un-comment the lines at the bottom of the `ability.model.ts` where you see the `@BelongsToMany` above `contacts`.

**Comment by kferrone** [comment]
OK .... Your assumption about where I was importing from is correct, i.e. import { . . . } from './'. Why the heck would that be an issue??? All I did was export the default classes in the index like below. 

`src/models/index.ts`
```
export {default as Contact} from './contact.model';
export {default as Key} from './key.model';
export {default as Ability} from './ability.model';
export {default as ContactAbility} from './contactAbility.model';
export {default as Guild} from './guild.model';
```

Is this an issue because they become an `alias` when I export an import and sequelize doesn't like that?

**Comment by RobinBuschmann** [comment]
For instance if you define a relation between two models with `BelongsTo` and `HasMany`, you will result in a circular dependency between both models. In general node can handle this, as long as the circular references aren't resolved immediately like
```ts
// a.model.ts
import {B} from './b.model.ts';
new B();
```
```ts
// b.model.ts
import {A} from './a.model.ts';
new A();
```
This example throws an error. That's why sequelize-typescript uses arrow functions to reference the dependencies “later”. With your index.ts a similar thing happens. I need some time to check what the exact issue.

**Comment by RobinBuschmann** [comment]
@kferrone Does my suggestion already helped you?

**Comment by kferrone** [comment]
Oh yeah everything worked fine. My issue was indeed how I was importing. You do have to import the referenced entities directly from their files, i.e. no redirecting through index.js. Thank you very much.
