### ISSUE TITLE
Include all not working when creating object

### ISSUE THREAD

**Issue by theGlenn** [RobinBuschmann/sequelize-typescript#457]
I have the following model:
```ts
@Table
export default class Manager extends Model<Manager> {
  @Column
  name: string;

  @BelongsToMany(() => Event, () => EventManagers)
  events?: Event[];
}
```

- When using findById with `include`, I get the the corresponding result:
```ts
Manager.findById(id, {
  include: [{ all: true }],
})
```
Result : `{"name": "Maya", "events": [], "id": 2}`
 
- But when I create an object with the same options, it doesn't return the result with the included associations
```ts
new Manager({ name: 'Maya' }, {
  include: [{ all: true }],
})
.save();
```

Result: `{"name": "Maya", "id": 2}`

**Comment by RobinBuschmann** [comment]
Hey @theGlenn, `new Manager({ name: 'Maya' }, {  include: [{ all: true }]}).save();` doesn't execute a search query. It only returns an instance of `Manager` with the initialized values. So if you would pass an event like `new Manager({ name: 'Maya', {events: [{someValue: 'test'}]} }, {  include: [{ all: true }]}).save();`, it will store the event beside the manager value and will return the manager instance with its previously created event.

Hope this helps!

**Comment by theGlenn** [comment]
Hey @RobinBuschmann helps a lot thank you. So I have another question kinda related to the previous one. What if I want to create a Manager and associate it with a an event but using it's id

**Comment by RobinBuschmann** [comment]
You're welcome!

```ts
const manager = new Manager({...});
const someEvent = await Event.findOne();

manager.$add('event', someEvent);
```
It shouldn't matter if you call `save` before or after `$add` on `manager`.

**Comment by theGlenn** [comment]
Cheers @RobinBuschmann
