### ISSUE TITLE
Problems with multiple relationships

### ISSUE THREAD

**Issue by Dragons0458** [RobinBuschmann/sequelize-typescript#458]
Hi!, in my project I'm getting the following error:

```
UnhandledPromiseRejectionWarning: Error: Alias cannot be inferred: "ProjectRecurrence" has multiple relations with "Projects"
```

My code is:

```
export default class ProjectRecurrence extends Model<ProjectRecurrence> {

    ...

    @ForeignKey(() => Projects)
    @IsInt
    @Column
    project_id: number;

    @BelongsTo(() => Projects, 'project_id')
    projectIdObject: Projects;

    ...

    @HasMany(() => Projects, 'project_recurrence_id')
    projects: Projects[];

}
```

is a bug? thank you!

**Comment by RobinBuschmann** [comment]
Hey @Dragons0458, can you provide the query which causes this error?

**Comment by Dragons0458** [comment]
Hello! is when starting the server

**Comment by mk4arts** [comment]
Hi,

i have a similar error... I'm trying to attach a user as an author and as an assignee of a task.

Tried two approaches:
`
*User.ts*
@ForeignKey(() => User)
@Column
authorId: string;

@BelongsTo(() => User, "authorId")
author: User;


@ForeignKey(() => User)
@Column
assigneeId: string;

@BelongsTo(() => User, "assigneeId")
assignee: User;
`

and

`
*User.ts*
@BelongsTo(() => User, "authorId")
author: User;

@BelongsTo(() => User, "assigneeId")
assignee: User;
`

combined with this (and without any mention in task.ts:

`
*task.ts*
@HasMany(() => Issue, "authorId")
authoredIssues: Issue[];

@HasMany(() => Issue, "assigneeId")
assignedIssues: Issue[];
`

The result was always the same:
`Error: Alias cannot be inferred: "Task" has multiple relations with "User"
    at inferAliasForInclude...`

Any help here? Its crashing on startup, just like the error of @Dragons0458

**Comment by mk4arts** [comment]
Got it to work... I missed my defined scope to have an `as` in the includes. Now it works like a charm, maybe its the same problem @Dragons0458 ?

**Comment by RobinBuschmann** [comment]
@Dragons0458 The foreign key decorator is just a helper to  infer the foreign keys automatically. If you have multiple relations of the same model (which is `Project` in your case) the foreign keys need to be set explicitly - like you did. So no need to the foreign key annodation - Just omit it and it should work!

**Comment by RobinBuschmann** [comment]
@Dragons0458 Do you still have any issues with this? Can we close this issue then?

**Comment by Dragons0458** [comment]
ok, ok, I just tried version 0.6.6 of this library and I no longer get the error, sorry for not looking before, thank you very much for the solution to this! :D

**Comment by Dragons0458** [comment]
Sorry to reopen the thread after so much time, but I have returned to get the same error and I do not know why, the models and classes are the following:

`
export default class ProjectRecurrence extends Model<ProjectRecurrence> {

    ...

    @ForeignKey(() => Projects)
    @IsInt
    @Column
    project_id: number;

    @BelongsTo(() => Projects, 'project_id')
    projectIdObject: Projects;

    ...

    @HasMany(() => Projects, 'project_recurrence_id')
    projects: Projects[];

}
`

and

`export default class Projects extends Model<Projects> {

    ...

    @IsInt
    @Column
    project_recurrence_id: number;

    @BelongsTo(() => ProjectRecurrence, 'project_recurrence_id')
    projectRecurrenceIdObject: ProjectRecurrence;

    ...

    @HasMany(() => ProjectRecurrence, 'project_id')
    projectsRecurrences: ProjectRecurrence[];

   ...

}`

and this is the model:

![imagen](https://user-images.githubusercontent.com/3160847/59059500-fa07f780-8853-11e9-9df3-e0055abb9be7.png)

any solution?

Thank you very much! :D

**Comment by RobinBuschmann** [comment]
@Dragons0458 can you provide an example repo, which reproduces the issue?

**Comment by Dragons0458** [comment]
Hi! this is the repository: https://github.com/Dragons0458/AliasCannotBeInferred thank you!

**Comment by RobinBuschmann** [comment]
Hey @Dragons0458, your setup is totally fine. The issue is the query itself. You have to tell sequelize-typescript which relation to `ProjectRecurrence` you want to use:

```ts
Projects.findAll({
    include: [{
        model: ProjectRecurrence,
        as: 'projectRecurrenceIdObject' // <---
    }]
})
```

Hope this helps. Feel free to close this issue if my answer solves your problem

**Comment by Dragons0458** [comment]
Hello! My apologies for the delay in responding.

The query that shows me works for me, but when I do the opposite it does not work, what could it be? Thank you!

```
ProjectRecurrence.findAll({
    include: [{
        model: Projects,
        as: 'projectIdObject'
    }]
}).then(console.log).catch(console.error);
```

**Comment by RobinBuschmann** [comment]
@Dragons0458 Do you receive the same error? I don't get any - It's working very well for me.

**Comment by Dragons0458** [comment]
I just checked and if it works correctly, sorry for the inconvenience, for now it was all good, thank you very much for your help! I will close the issue: D
