### ISSUE TITLE
Use sequelize-typescript with SQLite

### ISSUE THREAD

**Issue by fschuetz04** [RobinBuschmann/sequelize-typescript#460]
If I want to use sequelize-typescript with SQLite, it will make sense to allow configuration in the form of `{ storage: 'data', dialect: 'sqlite' }`, but this is currently not possible.
Shall I open a pull request or am I supposed to use a URI in this case?

**Comment by RobinBuschmann** [comment]
Hey @fschuetz04, it should already possible to pass those options:
```ts
const sequelize = new Sequelize({
  ...
  storage: ':memory:', 
  dialect: 'sqlite',
});
```

**Comment by fschuetz04** [comment]
I'm getting the error that the types aren't compatible because I **only** pass the parameters `storage` and `dialect,` which makes sense for SQLite.
According to `lib/types/SequelizeConfig.d.ts`, I have to pass `database` + `username` + `password`, `url` or `name` + `username` + `password`. So that doesn't fit my use case.

**Comment by RobinBuschmann** [comment]
Ah now I understand. So sequelize-typescript prevents you from passing only these options. If sequelize is happy with only those ones, it would be great if you could create a PR for that 👍

**Comment by fschuetz04** [comment]
Okay, I opened the pull request #461.

**Comment by kkmoslehpour** [comment]
I'm having an issue when exporting the SQLite config from another model. So the following gives me a typescript error:

database:
```
export const sqliteConfig = {
  production:{
    database: 'sqlite_db',
    dialect: 'sqlite',
    storage: 'mystorage.sqlite',
    host: '127.0.0.1',
    logging: GLOBAL_CONFIG.somepath
  }
};
```



```
import { sqliteConfig } from '../config/database';

const sequelize = new Sequelize(sqliteConfig.production);
```

``` 
Argument of type '{ database: string; dialect: string; storage: string; host: string; logging: any; }' is not assignable to parameter of type 'SequelizeOptions'.
      Types of property 'dialect' are incompatible.
        Type 'string' is not assignable to type '"sqlite" | "mysql" | "postgres" | "mariadb" | "mssql" | undefined'.
  Overload 2 of 4, '(uri: string, options?: SequelizeOptions | undefined): Sequelize', gave the following error.
    Argument of type '{ database: string; dialect: string; storage: string; host: string; logging: any; }' is not assignable to parameter of type 'string'.ts(2769)
```

However, when I copy the entire object into the `Sequelize()` it doesn't complain. 

```
const sequelize = new Sequelize({
  database: 'sqlite_db',
  dialect: 'sqlite',
  storage: 'mystorage.sqlite',
  host: '127.0.0.1',
  logging: GLOBAL_CONFIG.somepath
});
```

**Comment by fschuetz04** [comment]
```ts
export const sqliteConfig = {
  production:{
    database: 'sqlite_db',
    dialect: 'sqlite' as 'sqlite',
    storage: 'mystorage.sqlite',
    host: '127.0.0.1',
    logging: GLOBAL_CONFIG.somepath
  }
};
```

Does it work like that?

**Comment by kkmoslehpour** [comment]
Yes, that fixed the error, but why do we need to cast the type here? It seems a bit misleading for people trying to follow what the docs.

**Comment by fschuetz04** [comment]
The type of the dialect field is defined as `'mysql' | 'postgres' | 'sqlite' | 'mariadb' | 'mssql'` to enable TypeScript to check whether you pass in a valid value (https://github.com/types/sequelize/blob/c628e47acd0cb073b69d06b38ff3fd3ce3f47dbc/lib/sequelize.d.ts#L156). This is a good thing, I guess, but TypeScript does not infer the type of the sqliteConfig object you import by its usage. Not knowing much, TypeScript only infers that the dialect field is a string, which does not match the required type of the dialect field (as a string might be any string). I can see why that leads to confusion. Maybe that should be explained in https://github.com/RobinBuschmann/sequelize-typescript#configuration, @RobinBuschmann ?

**Comment by RobinBuschmann** [comment]
I wouldn't add this to the README of this project because it is common typescript behaviour.
