### ISSUE TITLE
Accessing column attributes

### ISSUE THREAD

**Issue by PatrickGeyer** [RobinBuschmann/sequelize-typescript#462]
Hi there,

I'm wondering how to access the name of the primary key column for a given model.
My issue is that I have a base class, the extended models of which have differently names primary ID's. (UID, and ID)
At the moment I'm running a "describe" query of the model, but of course that adds overhead.
Before switching to the typescript version of sequelize I used model.primaryKeyAttributes..

Many thanks!

**Comment by RobinBuschmann** [comment]
Hey @PatrickGeyer did you manage to get it working?

**Comment by RobinBuschmann** [comment]
@PatrickGeyer So you've got your base service `class BaseService<Repo extends Model < Repo > >` and your Repo class defined like so `class Repo extends Model<Repo> {}` - Is this correct?

**Comment by PatrickGeyer** [comment]
@RobinBuschmann yes that's correct.

**Comment by RobinBuschmann** [comment]
Ah `Repo` is a generic... completely overseen this one.

Can you provide an example repo, which reproduces the issue?
