### ISSUE TITLE
Infinite loop using recursive models

### ISSUE THREAD

**Issue by BenjaminDish** [RobinBuschmann/sequelize-typescript#466]
Hello,

I'm using Sequelize (version -m5.0.0-beta.9) + Postgresql

I'm having trouble with recursive models. I have the Commentaire model which could have children of the same type.

Code:

```
@DefaultScope({
    include: [
        { model: () => Commentaire, as: 'children' },
    ]
})
export class Commentaire extends Model<Commentaire> {

    @ForeignKey(() => Commentaire)
    @Column
    public commentaireParentId: number;

    @HasMany(() => Commentaire, 'commentaireParentId')
    public children: Array<Commentaire>;

}
```
When trying to make a findAll request on this model, I get an infinite loop error :

`RangeError: Maximum call stack size exceeded`

For information, it is not due to some data referencing itself. I tested a find request supposed to return [] and the problem is the same.

If I don't add the default scope, it does work. The children are not loaded but it works. So I suspect the scope + include to be the source of the problem.

How to avoid infinite loop in this case ?

**Comment by RobinBuschmann** [comment]
@BenjaminDish Does my answer helped you? Can we close this issue then?

**Comment by BenjaminDish** [comment]
Sorry @RobinBuschmann, I forgot to give feedback. Actually, yes, you're right, it is due to sequelize itself. Sequelize doesn't manage recursive models natively. So I decided to rename my second level Model (it was a 2 level structure).

Thanks ! So I close the issue
