### ISSUE TITLE
Store nested object without using chaining promises 

### ISSUE THREAD

**Issue by theothirteen** [RobinBuschmann/sequelize-typescript#467]
I would like to store the following object without using chaining promises 

For example, if I store B it will be chaining the store process and store all the associated objects.

Is there any option available in the library?

```
export class A extends Model<A> {

  @PrimaryKey
  @Column({ autoIncrement: true })
  Id: number;

  @Column(DataType.JSON)
  WelcomeMessage;

  @Column
  Name: string;
 }
```

```
export class B extends Model<B> {
  @PrimaryKey
  @Column({ autoIncrement: true })
  Id: number;

  @ForeignKey(() => A)
  @Column
  AId: number;

  @BelongsTo(() => A)
  A: A;

  @Column
  Name: string;
}
```

**Comment by RobinBuschmann** [comment]
Hey @theothirteen, you are able to create an entry with its associations like so:

```ts
const b = await B.create({
  Name: 'B',
  A: {
    WelcomeMessage: 'Hello World'
  }
}, include: [A])
```

Hope this helps

**Comment by RobinBuschmann** [comment]
@theothirteen Does this answer your question? Can we close this issue then?

**Comment by theothirteen** [comment]
@RobinBuschmann 

Thanks for the help.
