### ISSUE TITLE
Stubbing model methods

### ISSUE THREAD

**Issue by bschulte** [RobinBuschmann/sequelize-typescript#469]
What would be the best way to go about stubbing methods (via something like sinon) on models (such as create)? I've tried stubbing on the model's class prototype, but when I try that I get an error saying:

> Argument of type '"create"' is not assignable to parameter of type '"dataValues" | "$add" | "$set" | "$get" | "$count" | "$create" | "$has" | "$remove" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "isNewRecord" | "Model" | "sequelize" | ... 28 more ... | "books"'.

My attempt at stubbing is:

```
const userCreateStub = sinon.stub(User.prototype, "create").throws();
```

The model looks like:

```
import {
  Column,
  CreatedAt,
  Default,
  Model,
  Table,
  UpdatedAt,
  HasMany
} from "sequelize-typescript";

import Book from "./book.model";

@Table
export default class User extends Model<User> {
  @Column
  public username!: string;

  @Column
  public email!: string;

  @Column
  public password!: string;

  @CreatedAt
  public createdAt!: Date;

  @UpdatedAt
  public updatedAt!: Date;

  @Column
  public lastLogin!: Date;

  @Default(0)
  @Column
  public loginAttempts!: number;

  @Default(false)
  @Column
  public locked!: boolean;

  @Column
  public apiKey!: string;

  @Default(0)
  @Column
  public isAdmin!: number;

  @HasMany(() => Book)
  public books: Book[];
}
```

**Comment by RobinBuschmann** [comment]
Hey @bschulte, since `create` is a static method, you need to pass `User` as the target: `stub(User, 'create')`

**Comment by RobinBuschmann** [comment]
Does this solve your problem? Can we close this issue then?

**Comment by bschulte** [comment]
Yes, thank you!
