### ISSUE TITLE
Passing host/port instead of url in Sequelize constructor

### ISSUE THREAD

**Issue by intellix** [RobinBuschmann/sequelize-typescript#470]
Currently using a URI and trying to switch to host/port/username/password due to username/password being embedded within a Kubernetes secret.

Adding host/port gives me:
```
[ts] Argument of type '{ host: string; port: string; username: string; password: string; dialect: string; storage: string; }' is not assignable to parameter of type 'string'.
```

**Comment by RobinBuschmann** [comment]
Hey @intellix, looks like you’re missing the `database` property in order to name the database(?)

**Comment by intellix** [comment]
Ahah you're right. I guess it's just the TypeScript error kind of sucks. Get the same error if you make port a string rather than number
