### ISSUE TITLE
Auto generate class

### ISSUE THREAD

**Issue by shishir28** [RobinBuschmann/sequelize-typescript#477]
Hi ,
I was just wondering if we could generate model class for existing table in SQL server something like sequelize-auto-ts ? 

Thanks 
Shishir

**Comment by RobinBuschmann** [comment]
Hey @shishir28, currently there is no feature like this implemented with sequelize-typescript.

**Comment by shishir28** [comment]
@RobinBuschmann  Sorry for late response. That's okay . 
I wrote small SQL scripts which does lot of work for me . It is not perfect  but  it saves my  time  significantly :-) 
I am closing  it but may be we can add this  as request for future release?

**Comment by RobinBuschmann** [comment]
@shishir28 yes, we either could include this feature in sequelize-typescript or provide it as a separate package (as a plug-in). What do you think?

**Comment by shishir28** [comment]
I guess it should be plugin if your original vision of creating sequelize-typescript was to create ORM in typescript . 
My $0.02.  

Let me know if you need any assistance on it.
