### ISSUE TITLE
Model not initialized

### ISSUE THREAD

**Issue by LeandroDoldan** [RobinBuschmann/sequelize-typescript#485]
Hello Robin!

I've been having for a while an issue when importing models. I've found the solution after a few weeks, and I'd like to share my solution. I'm sorry if this is not the place to post it.

My project structure is the following:
```
models/                               
  |--index.ts                     // This file contains the sequelize instance
    |--models/                             
       |--author/                 // Every model has it's own folder 
         |--controller.ts              
         |--facade.ts                  
         |--routes.ts                    
         |--schemas/              // Folder for models definitions
            |--author.model.ts    // Model definition
```
As you can see, every model has it's own folder, and the model definition is inside a 'schemas' folder inside that folder.

In order to make it work, each class must to be exported as default.

The sequelize instance is declared in the index.ts file:

```
export const sequelize = new Sequelize(
  {
    name: secrets.dbName,
    dialect: config.common.database.dialect,
    host: secrets.dbHost,
    username: secrets.dbUsername,
    password: secrets.dbPassword,
    logging: false,
    modelMatch: (filename, member) =>
    {
      return filename.substring(0, filename.indexOf('.model')) === member.toLowerCase();
    }
  });
```

The modelMatch setting was added because of the project structure, but none of the settings are mandatory.

Now, let's see how the models were added. This piece of code is placed next to the sequelize definition:

```
const models = [];

// This piece of code imports EVERY model declared with the chosen project structure
fs.readdirSync(__dirname + '/models')
  .filter(file =>
  {
    return fs.lstatSync(`${ __dirname }/models/${ file }`).isDirectory();
  })
  .forEach(file =>
  {
    fs.readdirSync(path.join(__dirname, 'models', file, 'schemas'))
      .forEach(schema =>
      {
        if (schema.endsWith('.model.js')) //This is needed to aviod model.js.map files
        {
          const schemaPath = path.join(__dirname, 'models', file, 'schemas', schema);
          let model = require(schemaPath)
          models.push(model.default)
        }
      });
  });

sequelize.addModels(models);
``` 

Hope it will be useful for someone in a similar situation!

Thank you Robin for your hard work!

**Comment by RobinBuschmann** [comment]
Hey @LeandroDoldan, thanks for sharing your solution. Since `modelMatch` only works together with `modelPaths`, have you tried using `modelPaths`?  I assume for your setup the following config should work as well:

```
new Sequelize({
    modelPaths: [__dirname + '/relative/path/**/*.model.ts'], // or `.js` depending on whether you're using ts-node or not
    modelMatch: (filename, member) => filename.substring(0, filename.indexOf('.model')) === member.toLowerCase()
  });
```
(Don't forget adjusting `/relative/path`)

Hope this helps as well :)

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity

**Comment by Taqiarzoo** [comment]
> Hello Robin!
> 
> I've been having for a while an issue when importing models. I've found the solution after a few weeks, and I'd like to share my solution. I'm sorry if this is not the place to post it.
> 
> My project structure is the following:
> 
> ```
> models/                               
>   |--index.ts                     // This file contains the sequelize instance
>     |--models/                             
>        |--author/                 // Every model has it's own folder 
>          |--controller.ts              
>          |--facade.ts                  
>          |--routes.ts                    
>          |--schemas/              // Folder for models definitions
>             |--author.model.ts    // Model definition
> ```
> 
> As you can see, every model has it's own folder, and the model definition is inside a 'schemas' folder inside that folder.
> 
> In order to make it work, each class must to be exported as default.
> 
> The sequelize instance is declared in the index.ts file:
> 
> ```
> export const sequelize = new Sequelize(
>   {
>     name: secrets.dbName,
>     dialect: config.common.database.dialect,
>     host: secrets.dbHost,
>     username: secrets.dbUsername,
>     password: secrets.dbPassword,
>     logging: false,
>     modelMatch: (filename, member) =>
>     {
>       return filename.substring(0, filename.indexOf('.model')) === member.toLowerCase();
>     }
>   });
> ```
> 
> The modelMatch setting was added because of the project structure, but none of the settings are mandatory.
> 
> Now, let's see how the models were added. This piece of code is placed next to the sequelize definition:
> 
> ```
> const models = [];
> 
> // This piece of code imports EVERY model declared with the chosen project structure
> fs.readdirSync(__dirname + '/models')
>   .filter(file =>
>   {
>     return fs.lstatSync(`${ __dirname }/models/${ file }`).isDirectory();
>   })
>   .forEach(file =>
>   {
>     fs.readdirSync(path.join(__dirname, 'models', file, 'schemas'))
>       .forEach(schema =>
>       {
>         if (schema.endsWith('.model.js')) //This is needed to aviod model.js.map files
>         {
>           const schemaPath = path.join(__dirname, 'models', file, 'schemas', schema);
>           let model = require(schemaPath)
>           models.push(model.default)
>         }
>       });
>   });
> 
> sequelize.addModels(models);
> ```
> 
> Hope it will be useful for someone in a similar situation!
> 
> Thank you Robin for your hard work!

thank you 
Leandro Doldan
