### ISSUE TITLE
Cannot find module './lib/annotations/association/BelongsTo'

### ISSUE THREAD

**Issue by bananabr** [RobinBuschmann/sequelize-typescript#49]
Install 0.3.5 through npm and /lib/annotations/association/BelongsTo.js will be missing.

**Comment by RobinBuschmann** [comment]
Hey @bananabr thanks for reporting. Can you provide an example project, which demonstrates the issue. I can't reproduce it - It's working fine for me. Thank you.

**Comment by bananabr** [comment]
@RobinBuschmann, it was probabbly some npm issue ...
Although, I noticed that this kind of signature is missing @BelongsTo(relatedModelGetter: () => typeof Model, options: AssociationOptionsBelongsTo), only @BelongsTo(relatedModelGetter: () => typeof Model, foreignKey: string) is availble. Is this right?

**Comment by RobinBuschmann** [comment]
@bananabr This is correct - The readme on github comes from the master branch. This version is not released yet.
