### ISSUE TITLE
Extend DataTypes to Handle Postgis Raster Type

### ISSUE THREAD

**Issue by nodejayes** [RobinBuschmann/sequelize-typescript#490]
Hello,

in our Project we use the sequelize-typescript package to get our Business Objects aut of the Database. Some of theese uses the Raster Type of Postgres and some other Custom Types.

How i can extends the DataTypes so that sequelize-typescript knows what he have to do with this Type?

**Comment by RobinBuschmann** [comment]
Hey @nodejayes, check these issues: [github](https://github.com/sequelize/sequelize/issues/8533) and [stackoverflow](https://stackoverflow.com/questions/34584080/how-to-add-a-custom-datatype-in-sequelize-orm). If you have any further questions, don't hesitate to ask!

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
