### ISSUE TITLE
Can't access Model from an instance

### ISSUE THREAD

**Issue by steven-ferguson** [RobinBuschmann/sequelize-typescript#492]
The [sequelize docs](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html) say that I should be able to access the Model from an instance using `instance.constructor`, but I am getting a type error.

```javascript
import {Book} from "../models/Book";

Book.findOne()
  .then(book => {
    console.log(book.constructor.getTableName());
  });
```

This gives the following typing error: `Property 'getTableName' does not exist on type 'Function'.`

**Comment by RobinBuschmann** [comment]
Hey @steven-ferguson , this is because `constructor` is of type `Function`: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L122. But you don't to do it like this (`book.constructor`), just use the class reference like `Book.getTableName`.

Hope this helps!

**Comment by RobinBuschmann** [comment]
@steven-ferguson Does this help? Can we close this issue now?

**Comment by steven-ferguson** [comment]
The [sequelize docs](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html) say that the `instance.constructor` should be the Model not type `Function`:

> To access the Model from an instance, simply use instance.constructor

I have a function where I have an instance and don't know the Model, so the solution you suggested will not work:

```javascript
function foo(instance) {
  conosle.log(instance.constructor.getTableName());
}
```

**Comment by RobinBuschmann** [comment]
@steven-ferguson You're absolutely right - `instance.constructor` always points to the class reference, no matter whether we are in the sequelize context or not. See this:
```ts
class User {}

const user = new User();
console.log(user.constructor === User); // true
```
The thing is, that the typings for the `constructor` reference are coming from typescript itself. I wouldn't like to overwrite them. So I can only recommend casting the type for your use case like so:
```ts
(book.constructor as typeof Model).getTableName()
```
Hope this helps!

**Comment by RobinBuschmann** [comment]
@steven-ferguson Does this help? Can we close this issue now?
