### ISSUE TITLE
How to I get deleted flag in destroy() method ?

### ISSUE THREAD

**Issue by NoMoreViolence** [RobinBuschmann/sequelize-typescript#495]
SomeModel.findOne({ where: { id: `SomeID` } }).then(res => res ? res.destroy({}).then(res => { `res type is void` }) : console.log('There is no value'))

Even if the model successfully deleted, I could not check the value is deleted or not.
How can I get delete flag ?

**Comment by RobinBuschmann** [comment]
Hey @NoMoreViolence, I think this is a matter of how you design your application. Do you want to remove the record from the database or just set mark it as "deleted"? If you like to implement the last strategy, you can use the `paranoid` flag like so:

```ts
@Table({
  paranoid: true,
})
class SomeModel extends Model<SomeModel> {...}
```

This will add  a `deletedAt` column to your model. Use sequelize this way and you get what you wanted to achieve.

Hope this helps. If you have any further questions, don't hesitate to ask!
