### ISSUE TITLE
Model not initialized - addModels

### ISSUE THREAD

**Issue by kamilkisiela** [RobinBuschmann/sequelize-typescript#496]
Here's a reproduction: https://github.com/kamilkisiela/sequelize-init

---

I have two models, a oneToMany relation. I read #366 and what I get is:
> Model not initialized: "Message" needs to be added to a Sequelize instance before association can be resolved

```ts
import { Message } from './models/message';
import { User } from './models/user';
import { Sequelize } from 'sequelize-typescript';

const sequelize = new Sequelize({...});

sequelize.addModels([User, Message]);
```

```ts
// Message.ts

@Table
export class Message extends Model<Message> {
  @BelongsTo(() => User, {
    foreignKey: 'senderId',
    targetKey: 'id',
  })
  sender: User;

  @Column
  content: string;
}
```

```ts
// User.ts
@Table
export class User extends Model<User> {
  @Column
  username: string;

  @HasMany(() => Message, {
    foreignKey: 'senderId',
    sourceKey: 'id',
  })
  senderMessages: Message[];
}
```

**Comment by RobinBuschmann** [comment]
@kamilkisiela can we close this issue now?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity

**Comment by adminparry** [comment]
i`m also this question 

@Table
class Book extends Model<Book> { 
  @BelongsToMany(() => Author, () => BookAuthor)
  authors: Author[];
}
 
@Table
class Author extends Model<Author> {
 
  @BelongsToMany(() => Book, () => BookAuthor)
  books: Book[];
}
 
@Table
class BookAuthor extends Model<BookAuthor> {
 
  @ForeignKey(() => Book)
  @Column
  bookId: number;
 
  @ForeignKey(() => Author)
  @Column
  authorId: number;
}

**Comment by adminparry** [comment]
Error: Model not initialized: "Author" needs to be added to a Sequelize instance before association can be resolved.

**Comment by adminparry** [comment]
can i understand each ref problem

**Comment by RobinBuschmann** [comment]
Hey @adminparry, thanks for reporting. Can you submit a new issue for that? An example repo would be great as well. Thanks!

**Comment by curmichris** [comment]
Hey Guys, was getting this issue as well recently and managed to get the Model by passing an instance of the connection to my Repository and get the model from the Sequelize instance.
This is how I tackled it and it works. 

`private async GetModel(): Promise<T> {
        const connection = await this.db.Connection(). //Returns my sequelize instance
        return connection.model('MODEL_NAME') //can also pass the type of the model required.
   }`
   
   Hope this helps
