### ISSUE TITLE
Please add this note to the configuration sections

### ISSUE THREAD

**Issue by rationalthinker1** [RobinBuschmann/sequelize-typescript#497]
Hello,
I literally spend a whole day trying to get this to work, I finally solved it. I don't want others to waste their time with it also. I wanted to do a pull request to add this line in the README.md, but since I'm a noob to JS frameworks and Github, I don't know how to do that.

Can someone please add this to the configurations sections?

> Depending on how the `tsconfig.json` is configured, the location of `modelPaths` may be different. If the `outDir` location was defined in the tsconfig.json, make sure that `modelPaths` is pointed somewhere in that location. For example, if the `outDir` was set to `./dist`, the `modelPaths` should be set to `[ ${appRoot}/dist/models ]` , `appRoot` being the root of your application. Also, if you are using wildcards for the `modelPaths`, make note that the files will not have `ts` extensions, but rather `js` extensions, e.g. `${appRoot}/dist/**/*.model.js`

**Comment by RobinBuschmann** [comment]
Hey @rationalthinker1, thanks for sharing this with us. You could create a PR if you like. A new section in the README like _Common pitfalls_  would make sense. What do you think?
