### ISSUE TITLE
How to replace Bluebird with Native Promise?

### ISSUE THREAD

**Issue by negezor** [RobinBuschmann/sequelize-typescript#501]
I do not use the capabilities of Bluebird. But because of him, I have mixed the types of Native Promise (async/await) and Bluebird. In Sequelize, you can [replace ](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1202 )the library.

**Comment by RobinBuschmann** [comment]
Hey @negezor, [Sequelize.Promise](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1202) is a way to access the bluebird promise object, but is this intended to be overridden? I don't know. Is there any recommendation from sequelize regarding replacing bluebird with native promises? If this is possible with pure sequelize it should be also possible with sequelize-typescript. Hope this helps!

**Comment by negezor** [comment]
Just noticed that this is only a link. Writing code every night is not the best 😅
