### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by okarlsson** [RobinBuschmann/sequelize-typescript#503]
I'm trying to use sequelize-typescript with `serverless`, `aws-lambda` and `webpack` and have a question regarding the initialization of sequelize.

I have my sequelize config in `sequelize.ts`
```
import { Sequelize } from 'sequelize-typescript';

const sequelize = new Sequelize({
  database: process.env.DB_NAME,
  dialect: 'postgres',
  host: process.env.DB_HOST,
  password: process.env.DB_PASSWORD,
  port: parseInt(process.env.DB_PORT, 10),
  username: process.env.DB_USER,
  modelPaths: [__dirname + '/models/**/*.model.ts'],
});

const db = {
  Sequelize: Sequelize,
  sequelize: sequelize,
};

export default db;
```

and `profileService.ts` like this
```
import Profile from '../models/profile.model';

export class ProfileService {
  public create(profile: Profile) {}

  public async listProfiles(): Promise<Profile[]> {
    return Profile.findAll();
  }
}
```

When calling the `listProfiles()` funciton I get the following error message. This is because the exported module from `sequelize.ts` is never imported anywhere from the entrypoint in webpack and is because of the never bundled. 
```
Model not initialized: \"Profile\" needs to be added to a Sequelize instance before \"findAll\" can be called.
```

If I import it in my handler like this, everything works as expected:
```
import { ApolloServer } from 'apollo-server-lambda';
import { schema } from '../graphql/schema';

import db from '../sequelize';
const x = db;

const server = new ApolloServer({
  schema: schema,
});

exports.handler = server.createHandler();
````

What would be a good way to going about this without having to import the sequelize module without using it?

**Comment by okarlsson** [comment]
Thanks for the fast reply @RobinBuschmann .

It just feels a bit awkward to have to import it at all without using it. But I guess I'll go with that approach for now until I think of something better.

Maybe something like this will work:

```
// service.ts
import '../sequelize';

export default class Service{}
```
```
// profileService.ts
import Service from './service';
import Profile from '../models/profile.model';

export class ProfileService extends Service {
  public create(profile: Profile) {}

  public async listProfiles(): Promise<Profile[]> {
    return Profile.findAll();
  }
}
```

**Comment by RobinBuschmann** [comment]
Hey @okarlsson, if you never load your `sequelize.ts` file, the sequelize instance won't get created and your models won't be initialized. So you have no choice to import it at some point. 
Do you have any further questions or can we close this issue now?

**Comment by okarlsson** [comment]
Alright! Sure, we can close it.
