### ISSUE TITLE
TypeError: Class constructor Model cannot be invoked without 'new'

### ISSUE THREAD

**Issue by azaeng04** [RobinBuschmann/sequelize-typescript#504]
Hi @RobinBuschmann 

I have been receiving this exact same issue with Wallaby js.

The `ExpenseGroup.model.ts`

```'use strict';

import { Table, Model, Column, DataType, CreatedAt, UpdatedAt, DeletedAt } from 'sequelize-typescript';

@Table
export class ExpenseGroup extends Model<ExpenseGroup>{

  @Column({ type: DataType.STRING, allowNull: false })
  public name: string;

  @Column({ type: DataType.STRING, allowNull: false })
  public description: string;

  @CreatedAt
  public createdAt: Date;

  @UpdatedAt
  public updatedAt: Date;

  @DeletedAt
  public deletedAt: Date;
};
```

The test:

```
describe('Expense Group CRUD', () => {
    beforeAll(async () => {
        await sequelize.sync({ force: true });
    })
    test.only('can create an Expense Group', async () => {
        const _expenseGroup = await ExpenseGroup.create(expenseGroup);

        // expect(_expenseGroup).toHaveProperty('id');
        // expect(_expenseGroup).toMatchObject(expenseGroup);
    });
....
```

The error that Wallaby js is throwing.

```​​​​​1 failing test, 0 passing (only executed src/tests/integration/models/expenseGroupCrud.test.ts)​​​​​
  
  ​​​​Expense Group CRUD can create an Expense Group​​​​ ​​​[34 ms]​​​​
    ​​​​
    ​​TypeError: Class constructor Model cannot be invoked without 'new'​​
      at new apply ​src/models/ExpenseGroup.model.ts:6​
      at Object.create ​src/tests/integration/models/expenseGroupCrud.test.ts:12:8​
      at Object.__awaiter ​src/tests/integration/models/expenseGroupCrud.test.ts:11:4​
```

`My tsconfig`
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "esnext",
        "allowJs": true,
        "noImplicitAny": true,
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

I have noticed that this error only pops up when I call the function to create the object. `ExpenseGroup.create()`

Help would be much appreciated.

**Comment by RobinBuschmann** [comment]
@azaeng04 Are you really, really sure, that `es6+` is used? I see your tsconfig looks correct (`"target": "esnext",`), but probably it is ignored for compilation somehow. Otherwise, can you provide an example repo which reproduces the issue, so that I can have a look at it?

**Comment by azaeng04** [comment]
Hi @RobinBuschmann thank you soo much for getting back to me.
What is really strange is that I just extracted the bits I needed to make use of the functionality and I got it working successfully. So no, I am not sure how the error came about. Even with the exact same node_modules installed. Just done on a clean instance of the project.

**Comment by RobinBuschmann** [comment]
@azaeng04 So you get the whole thing working or just a smaller setup?

**Comment by azaeng04** [comment]
@RobinBuschmann yep. That is correct. So I then merged the smaller setup onto the actual project and it worked fine. I did however revert every change I made on the project and started over.

**Comment by RobinBuschmann** [comment]
Good to here. If you find out what caused the issue it would be cool to here from you :)

**Comment by RobinBuschmann** [comment]
Since the problem was solved, this issue is closed. @azaeng04 If you still have any questions, just reopen the issue

**Comment by xuchaoying** [comment]
Same here in my unittest, did you find out why?  @azaeng04
