### ISSUE TITLE
Can't SELECT/find from Model

### ISSUE THREAD

**Issue by omariosouto** [RobinBuschmann/sequelize-typescript#509]
## Description

Hi! Your project is amazing, is the exact solution that I was looking for. But I'm trying to make a select query and I by some reason I can't do that

Link to project: https://github.com/omariosouto/sequelize-typescript-test

## Screenshots

I can create my project and create an user:
![image](https://user-images.githubusercontent.com/13791385/51006400-254b1c80-152a-11e9-865f-a09ca8462a1f.png)

But when I try to select:

![image](https://user-images.githubusercontent.com/13791385/51006811-106f8880-152c-11e9-8d9e-849ce8a1f2e4.png)

**Comment by RobinBuschmann** [comment]
Hey @omariosouto, thanks for reporting. Your example project is empty (or probably I don't have rights to read?)

**Comment by omariosouto** [comment]
Sorry, was to late when I was trying haha

Now the code is there :)

**Comment by RobinBuschmann** [comment]
@omariosouto No problem ;) 

The compiler option `strictFunctionTypes`(which is also enabled with `strict`) causes the error. For now I can only recommend to turn this off. But I will check whether I can get type inference running with `strictFunctionTypes: true`

**Comment by RobinBuschmann** [comment]
Close this issue in favor of #392
