### ISSUE TITLE
Multiple many-to-many relationships always failing with 'multiple relations' error

### ISSUE THREAD

**Issue by livanov** [RobinBuschmann/sequelize-typescript#511]
I read quite a number of issues/articles/docs of which [this](https://github.com/RobinBuschmann/sequelize-typescript/issues/398), [this](https://github.com/RobinBuschmann/sequelize-typescript/issues/295), [this](https://github.com/RobinBuschmann/sequelize-typescript#multiple-relations-of-same-models) and [this](https://www.npmjs.com/package/sequelize-typescript#many-to-many) but I can't get my use case working. Here it is:

I have `Movie`s and `Artist`s. A movie has director**s** and actor**s**, which are artists. An artist has movies he starred in and movies he directed (the reverse relationship). My tables are `movies`, `artists`, `movies_artists`, `movies_directors`, where the first two hold entities with no foreign keys, and the last two hold the many-to-many relationships. 

Application starts OK, but when fetching any movie or artist I get the `Unhandled rejection Error: Alias cannot be inferred: "Artist" has multiple relations with "Movie"`

### Movie
```typescript
@Table({tableName: 'movies'})
export class Movie extends Model<Movie> {

    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;

    @Column
    name: string;

    @BelongsToMany(() => Artist, () => MoviesActors, 'actor_id')
    artists: Artist[];

    @BelongsToMany(() => Artist, () => MoviesDirectors, 'director_id')
    directors: Artist[];
}
```

### Artist
```typescript
@Table({tableName: 'artists'})
export class Artist extends Model<Artist> {

    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;

    @Column
    name: string;

    @BelongsToMany(() => Movie, () => MoviesActors, 'movie_id')
    starred: Movie[];

    @BelongsToMany(() => Movie, () => MoviesDirectors, 'movie_id') // also tried changing the foreign_key column name so that they do not match (even though they are in two different sql tables)
    directed: Movie[];
}
```

### MoviesActors
```typescript
@Table({tableName: 'movies_actors'})
export class MoviesActors extends Model<MoviesActors> {

    @ForeignKey(() => Artist)
    @Column({field: 'actor_id'})
    actorId: number;

    @BelongsTo(() => Artist, 'actor_id')  // tried with and without alias, with @HasMany instead of @BelongsTo
    actor: Artist;  // tried with and without this field

    @ForeignKey(() => Movie)
    @Column({field: 'movie_id'})
    movieId: number; 

    @BelongsTo(() => Movie, 'movie_id')   // tried with and without alias, with @HasMany instead of @BelongsTo
    movie: Movie;  // tried with and without this field
}
```

### MoviesDirectors
```typescript
@Table({tableName: 'movies_directors'})
export class MoviesDirectors extends Model<MoviesDirectors> {

    @ForeignKey(() => Artist)
    @Column({field: 'director_id'})
    directorId: number;

    @BelongsTo(() => Artist, 'director_id') // tried with and without alias, with @HasMany instead of @BelongsTo
    director: Artist;  // tried with and without this field

    @ForeignKey(() => Movie)
    @Column({field: 'movie_id'})
    movieId: number;

    @BelongsTo(() => Movie, 'movie_id') // tried with and without alias, with @HasMany instead of @BelongsTo
    movie: Movie;  // tried with and without this field
}
```

**Comment by RobinBuschmann** [comment]
@livanov How does your `find` options look like? Like so: `Artist.find({include: [Movie]})`? When including `Movie`, you need to tell sequelize which relation you mean with this `starred ` or `directed`:
```ts
Artist.find({include: [
  {model: Movie, as: 'directed'},
]})
```
Hope this helps!

**Comment by livanov** [comment]
Thanks, that worked out! However just 1 more thing - when I fetch an Artist object with the query you provided I get an extra field called `MoviesDirectors` and I get the SQL reference there `SqlMovieDirector: {movieId: 1,directorId: 3}`. How can I get rid of that?

**Comment by RobinBuschmann** [comment]
Sry for the late reply: With the following options you get rid of the through object:
```ts
Artist.find({
 include: [
   {
    model: Movie, 
    as: 'directed',
    through: {attributes: []},
   }
 ]
})
```
