### ISSUE TITLE
No creation of tables

### ISSUE THREAD

**Issue by josecolella** [RobinBuschmann/sequelize-typescript#512]
Hello,
I'm trying to use sequelize-typescript to connect to my mysql instance.

With the following, No tables are being created by Sequelize, even though the sync is set to true.

`const sequelize = new Sequelize({
  host: "localhost",
  database: "tmpservice",
  username: "root",
  password: "somepassword",
  dialect: "mysql",
  sync: { force: true },
  operatorsAliases: false
});

sequelize.addModels([Account, UserFavorite]);`

Anything I'm missing here?

**Comment by RobinBuschmann** [comment]
Hey @josecolella, as stated [here](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html) `{...sync: {...}}` only sets the default options for `sync`. You still need to run `sequelize.sync` in order to create tables. Hope this helps!

**Comment by josecolella** [comment]
@RobinBuschmann Thanks. Can't believe I missed that. Appreciate your help

**Comment by vikasmaurya0864** [comment]
I am doing it but it is not creating tables.
