### ISSUE TITLE
Many-to-many models has missing properties in typings

### ISSUE THREAD

**Issue by Cyberuben** [RobinBuschmann/sequelize-typescript#513]
If I have a table called `users`, a table called `roles`, and a table called `userRoles` (with the fields `userId`, `roleId`, `givenAt`), I'm able to set up a many-to-many relation there, no problem.

However, `sequelize-typescript` then sets up the right associations and makes sure the models work. When querying and including the relation, the result is something like:

```
{
  "id": 2,
  "name": "test user",
  "roles": [{
    "id": 1,
    "name": "example",
    "UserRole": {
      "userId": 2,
      "roleId": 1,
      "givenAt": "2019-01-17T18:07:00"
    }
  }
}
```

When trying to access this info, like `user.roles[0].UserRole` to print the `givenAt` value, I get type errors. Currently I'm working on a rather large project that relies a lot of `// @ts-ignore` to support getting values from the join table, but I don't think this is the right solution.

Could there be done something to the typings of this library to make accessing these values work?

**Comment by RobinBuschmann** [comment]
Hey @Cyberuben, thanks for bringing this up. Unfortunately there is no way to add those typings dynamically. So you'll need to do it manually either like so

```ts
class User extends Model<User> {
  @BelongsToMany(() => Role, () => UserRole) 
  roles!: Role[];
}
class Role extends Model<Role> {
  UserRole!: UserRole;
}
```
or like this
```ts
class User extends Model<User>{
  @BelongsToMany(() => Role, () => UserRole) 
  roles!: Array<Role & {UserRole: UserRole}>;
}
```

Hope this helps!

**Comment by Cyberuben** [comment]
Thanks for the quick response.

This might be something useful to mention in the documentation, as I'd guess it would confuse quite a lot of people.

**Comment by RobinBuschmann** [comment]
@Cyberuben You're right. Can you create a PR for that?
