### ISSUE TITLE
Integration with Inversify

### ISSUE THREAD

**Issue by josecolella** [RobinBuschmann/sequelize-typescript#522]
Hey @RobinBuschmann ,
One quick question, I'm using your module in conjunction with inversify. Would you know how to bind the Model to the constructor of a class that is reading from DB?

**Comment by josecolella** [comment]
I'm thinking something where you can inject a Model into the class.

```typescript
@injectable
class SomeService {
       constructor(@inject(ACCOUNT_REPOSITORY) private accountRepository: Account) {}
```

```
bind<Model<Account>>(ACCOUNT_REPOSITORY).to(Account)
```

The problem is that I'm using `findAll`  which is a static method.

Any thoughts?

**Comment by RobinBuschmann** [comment]
Hey @josecolella, with your bind configuration (`bind(..).to(..)`) you're getting an instance of `Account` instead of the reference to the class itself. You need to use `toConstantValue`. See full setup:

```ts
const ACCOUNT_REPOSITORY = Symbol('AccountRepository');
type AccountRepository = typeof Account;

container
    .bind<UserRepository>(ACCOUNT_REPOSITORY)
    .toConstantValue(Account);
```

```ts
@injectable
class SomeService {
       constructor(@inject(ACCOUNT_REPOSITORY) private accountRepository: AccountRepository) {}
```

Hope this helps!

**Comment by josecolella** [comment]
@RobinBuschmann Thank you so much for your help. 👍
