### ISSUE TITLE
How to running default set of queries in sequelize-typescript after node server starts.

### ISSUE THREAD

**Issue by VishalUZ** [RobinBuschmann/sequelize-typescript#524]
For a NodeJS project using Sequelize-Typescript there is a requirement in which I have to execute a set of queries stored in a file (abc.sql). The SQL file should execute after Node server has started and all Model files are executed. This SQL file contains DDL and DML statements. How to make this work as I searched on many forums but didn’t find any solution? Thanks in advance.

**Comment by RobinBuschmann** [comment]
@VishalUZ Sounds like database migrations are what you're looking for. See this issue #274 for details.

**Comment by RobinBuschmann** [comment]
@VishalUZ Did it help? Can we close this issue now?

**Comment by VishalUZ** [comment]
Yes sure..
Thank you..
