### ISSUE TITLE
No default export defined for file "Xxxx"or export does not satisfy filename.

### ISSUE THREAD

**Issue by wildcookie007** [RobinBuschmann/sequelize-typescript#525]
Ran into this issue when trying to set up sequelize typescript:

> Error: No default export defined for file "Bet" or export does not satisfy filename.
Error: No default export defined for file "Bet" or export does not satisfy filename.
    at glob.sync.filter.map.filter.map.fullPath (/Users/king/Documents/Development/JS/api/node_modules/sequelize-typescript/dist/model/shared/model-service.js:95:27)

My code for initializing Sequelize:

```
import { Sequelize } from 'sequelize-typescript';
import config from 'config';
import path from 'path';
import fs from 'fs';

export const sql = new Sequelize({
	database: config.get('db.name') as string,
	username: config.get('db.username') as string,
	password: config.get('db.password') as string,
	dialect: config.get('db.options.dialect') as string,
	modelPaths: [path.join(__dirname, 'models')],
	operatorsAliases: Sequelize.Op as any
});
```

And the file that is related to the error is the first model in directory:

```
'use strict';

import {
	Model, Table, Column, AllowNull, AutoIncrement, PrimaryKey,
	ForeignKey, CreatedAt, UpdatedAt, HasMany, BelongsTo
} from 'sequelize-typescript';
import { User } from './User';
import { Like } from './Like';
import { Comment } from './Comment';

@Table
export class Bet extends Model<Bet> {
	@AllowNull(false)
	@AutoIncrement
	@PrimaryKey
	@Column
	id!: number;

	@ForeignKey(() => User)
	@Column
	user_id!: number;

	@ForeignKey(() => User)
	@Column
	opponent_id!: number;

	@AllowNull(true)
	@ForeignKey(() => Bet)
	@Column
	parent_id!: number; // def null todo

	@AllowNull(false)
	@Column
	reward!: string;

	@AllowNull(false)
	@Column
	state!: string; // def request todo

	@Column
	description!: string;

	@Column
	winnerType!: number;

	@AllowNull(false)
	@Column
	dueDate!: Date;

	@CreatedAt
	@Column
	createdAt!: Date;

	@UpdatedAt
	@Column
	updatedAt!: Date;

	@HasMany(() => Bet, 'parent_id')
	challengers!: Bet[];

	@HasMany(() => Like)
	likes!: Like[];

	@HasMany(() => Comment)
	comments!: Bet[];

	@BelongsTo(() => User, 'user_id')
	user!: User;

	@BelongsTo(() => User, 'opponent_id')
	opponent!: User;
}
```

Any ideas on how to get this resolved please? Tried exporting default, using `.addModels` yet still no luck. All of the files in models directory are of type `.ts` and only import `sequelize-typescript` or models.

```
"sequelize": "^4.42.0",
"sequelize-cli": "^5.4.0",
"sequelize-typescript": "^1.0.0-alpha.7"
```

**Comment by wildcookie007** [comment]
Resolved. Appearently having an `index.ts` for convenient exporting of models was interfering with models and I couldn't get sequelize to exclude so I just had to delete it.

**Comment by wildcookie007** [comment]
`await sql.sync({force: true});` must be present in my initial app file in order for the error to disappear, is there any way I could not sync upon start?

**Comment by RobinBuschmann** [comment]
@wildcookie007 Regarding your initial problem, you can use `modelMatch` or globs in `modelPath` to narrow down what should be loaded by sequelize-typescript. See https://github.com/RobinBuschmann/sequelize-typescript#model-path-resolving for details.

Regarding your necessity of using `sync`: Are you sure, you're receiving the same error as before? I assume that's not the `sync` call which fixes the issue but rather the fact that you've imported the file where you've created the sequelize instance (which is required, since otherwise your models aren't initialized)

**Comment by wildcookie007** [comment]
Yeah, the necessity of sync also initializes the models as the function was in the same file, had a hard time understanding that. Thanks.

**Comment by ricktjwong** [comment]
Using an `index.ts` file for exporting models work, just add this to your sequelize initiation:

`import * as models from './models'`

```
export const sequelize = new Sequelize(
  dbConfig.database,
  dbConfig.user,
  dbConfig.password,
  {
    dialect: 'postgres',
    port: parseInt(dbConfig.port, 10),
    host: dbConfig.host,
    models: Object.values(models),
    logging: dbConfig.logging,
  })
```
