### ISSUE TITLE
Is the .sync({force: true}) synchronous data model feature now supported?

### ISSUE THREAD

**Issue by ZQun** [RobinBuschmann/sequelize-typescript#527]
Is the .sync({force: true}) synchronous data model feature now supported?

Used to synchronizing data structures with sequelize
``` typescript
await User.sync({force: true}).then((result) => {
    // success
})
```
sequelize-typescript how do I need to use it?

**Comment by RobinBuschmann** [comment]
@ZQun It should be supported, since the beginning. Do you get an error when using this feature?

**Comment by RobinBuschmann** [comment]
Close this issue due to inactivity
