### ISSUE TITLE
AssociationGetOptions type problem in 1.0

### ISSUE THREAD

**Issue by qsona** [RobinBuschmann/sequelize-typescript#528]
Hi, I'm trying to use sequelize-typescript@1.0.0-alpha.7 .
It seems that `AssociationGetOptions` type is too strict.
```ts
@Table
class A extends Model<A>
  @hasMany(() => B)
  bs: B[]
end

// a is an instance of A
a.$get('bs', { order: ['c'] }) // ts error: Argument of type '{ order: string[]; }' is not assignable to parameter of type 'AssociationGetOptions<B>'
```

I checked this file:
https://github.com/RobinBuschmann/sequelize-typescript/blob/1.0.0/src/model/model/association/association-get-options.ts

https://github.com/sequelize/sequelize/blob/891de8e1014ee266c736817e96686c808c21936e/lib/associations/has-many.js#L162-L164
The documented fields are same as AssociationGetOptions, but
https://github.com/sequelize/sequelize/blob/891de8e1014ee266c736817e96686c808c21936e/lib/associations/has-many.js#L225
actually this options is passed to findAll, so other fields (order, limit, etc) are also needed.

( I know that `sequelize-typescript does not provide typings for sequelize` so I'm not sure which approach is the best. At this time I just report and don't send a PR. 🙇 )

**Comment by RobinBuschmann** [comment]
@qsona Thanks for bringing this up. Looks like you are right. There are types missing within `AssociationGetOptions`. For now `sequelize-typescript` is the right place to fix it. So PRs are very welcome :)
