### ISSUE TITLE
Docs: TypeScript typings missing in examples

### ISSUE THREAD

**Issue by eddiemonge** [RobinBuschmann/sequelize-typescript#531]
https://github.com/RobinBuschmann/sequelize-typescript#build-and-create and similar examples are missing all the TypeScript parts like what the variable and return types should be. Something like:

```
import {Person} from '../models/person'

export function newPerson (name: string, age: string): Promise<Person> {
  const person: Person = new Person({name: 'bob', age: 99});
  person.save();
  return person;
}

export function updateAge (): Promise<Person> {
  return Person
   .findOne()
   .then((person: Person) => {
     person.age = 100;
     return person.save();
   });
}
```

Something like that. These examples aren't correct I don't think (don't know for sure since I'm still new to TypeScript) and without examples showing best practices, it's hard to know

**Comment by RobinBuschmann** [comment]
Hey @eddiemonge, I'm not quite sure if I'm getting you right. You want [those](https://github.com/RobinBuschmann/sequelize-typescript#build-and-create) examples to have type annotations like in your example (`const person: Person /* <- here */ = new Person({name: 'bob', age: 99});`)? 
IDEs like WebStorm, VisualStudio Code or Atom should give you type information without explicitly annotating everything. So I see no need for this.

**Comment by eddiemonge** [comment]
If that was the case then TypeScript wouldn't exist.

**Comment by devoto13** [comment]
@eddiemonge TypeScript can infer types in many cases, so you don't have to specify them explicitly. This is one of such cases. Check out [documentation](http://www.typescriptlang.org/docs/handbook/type-inference.html) for more information. It is good practice to rely on type inference to make your code more readable.
