### ISSUE TITLE
@babel/preset-typescript not finding models

### ISSUE THREAD

**Issue by EnriqueVidal** [RobinBuschmann/sequelize-typescript#532]
Hi,

First of all this library looks amazing, I have been using typescript (via `@babel/preset-typescript`) using `sequelize.define` but I've had a couple of issues just using that by itself, like not being able to add Model static functions without setting them as optional or not being able to inherit from `Sequelize.Model`, so this library looks like next logical step.

My current problem is that I can't get this to work with babel 7, here's my babelrc:

```json
{
  "presets": [
    "@babel/env",
    "@babel/typescript"
  ],
  "plugins": [
    ["@babel/proposal-decorators", { "legacy": true }],
    ["@babel/proposal-class-properties", { "loose": true }],
    "@babel/proposal-async-generator-functions",
    "@babel/proposal-object-rest-spread",
    "@babel/plugin-transform-runtime"
  ]
}
```

And here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "lib": [ "es2015" ],
  },
  "exclude": [
    "node_modules",
    "test"    
  ],
  "include": [
    "src/**/*",
  ],
}
```

before completely moving to this library I wanted to try moving a single (my simplest model first), this is what my connection looks like:

```typescript
import { get } from 'helpers/env';
import { Sequelize } from 'sequelize-typescript';
import config from '../config/sequelize';

interface Credentials {
  database: string;
  dialect: string;
  host: string;
  password: null | string;
  username: string;
}

const credentials: Credentials = config[get('NODE_ENV', 'development')];

export const sequelize = new SequelizeT({
  ...credentials,
  modelPaths: [__dirname + '/new-models'],
});
```

And here's my model:

```typescript
// NTag.ts
import { Column, DataType, Model, Table } from 'sequelize-typescript';

@Table({ tableName: 'Tags' })
export class NTag extends Model<NTag> {
  public static async findOrCreateMany(names: string[]): Promise<NTag[]> {
    const promises = names.map((name) => (
      NTag.findOrCreate({
        where: NTag.sequelize.where(
          NTag.sequelize.fn('LOWER', 'name'),
          NTag.sequelize.fn('LOWER', name),
        ),
        defaults: { name },
      })));

    const tags = await Promise.all(promises);
    return tags.map(([ tag, _ ]) => tag);
  }

  @Column(DataType.STRING)
  public name: string;
}
```

So, `sequelize.syc()` works I can see the `CREATE TABLE` statement and all, and if I do something like `sequelize.sync().then(() => console.log(sequelize.models))` I can see that `NTag` is in there, but if I try doing something like say `NTag.findAll()` I get this error:

`Unhandled rejection Error: Model not initialized: "Model" needs to be added to a Sequelize instance before "call" can be called.`

Not to mention that if I write my column like:

```typescript
@Column
public name: string;
```

I get this error:

```
Error: Specified type of property 'name' cannot be automatically resolved to a sequelize data type. Please define the data type manually
```

I assume these errors are related to my configuration and not the library itself but at this point I'm pretty lost and google results for something this specific are very minimal.

Thanks in advance for your kind response any nudge in the right direction is greatly appreciated.

**Comment by EnriqueVidal** [comment]
@RobinBuschmann Hi, thanks for your quick response, it is a private repo at the moment, but I can try and fork it and make a public one, in the mean time, could the way I'm starting the app have anything to do with it? in development I start  it like this:

`cross-env NODE_PATH=./src nodemon -e js,ts ./src --exec babel-node --extensions ".js,.ts"`

Perhaps this is a source of my troubles. Thanks in advance.

**Comment by RobinBuschmann** [comment]
@EnriqueVidal You're welcome and thanks for keeping me up to date. I never faced this issue and I only found this package: https://www.npmjs.com/package/babel-plugin-decorator-metadata - maybe it helps

**Comment by EnriqueVidal** [comment]
Final question, I'm using this library in a GraphQL endpoint, and I can call models directly and query with no issues, but when I call my resolvers I get:

> "Model not initialized: "Model" needs to be added to a Sequelize instance before "call" can be called."

Perhaps I am missing something?

Thanks in advance

**Comment by EnriqueVidal** [comment]
Ugh, as I started moving my code to the newly created models I found that if I call them `Model.findAll()` from where `sequelize.sync` ran it works perfectly but I can't seem to do this from other files that import these classes, what am I missing?

**Comment by EnriqueVidal** [comment]
After all the work I've put into this I decided to move on and just switch to `ts-node` and a typescript loader instead. Thanks

**Comment by wyqydsyq** [comment]
I've also ran into similar issues using Babel to compile a project using `sequelize-typescript`. It seems that Babel's compilation breaks references to the Model classes entirely, as the error below also seems to occur when your Model is not added to the Sequelize instance, or you [try importing the model from a non-matching path](https://github.com/RobinBuschmann/sequelize-typescript/issues/366#issuecomment-389778844):
```
Unhandled rejection Error: Model not initialized: "Model" needs to be added to a Sequelize instance before "call" can be called.
```

I am 100% certain the Model is being added to the instance prior to using it, using the following code in my project throws the above error internally when calling `User.findOrCreate`:
```ts
  connection.addModels([User]);
  const [user, created] = await User.findOrCreate({
    where: { identity: email },
    defaults: newUserDefaults,
  });
```

I've tried setting the `type` for each column, and the `modelName` on all my `@Table()` annotations without any luck.

I'm also now looking at running my project directly via `ts-node` rather than transpiling with `babel` to work around this

**Comment by EnriqueVidal** [comment]
@wyqydsyq Yes, I ended up doing this to get it to work myself, moved to typescript and it worked.

**Comment by petrovi4** [comment]
It seems that this issue must be reopened. 
The decision to "abandon the babel-node" does not fix problem.

Even if specify all DataType for all Columns with the babel-node, I get 

> Unhandled rejection Error: Model not initialized: Member "call" cannot be called. "Model" needs to be added to a Sequelize instance.

Does anyone have a solution how to make sequelize-typescript work with babel-node? I really liked this library, but I will choose Babel without it and without TypeScript, than losing all the features of Babel.

And this is very sad (

**Comment by EnriqueVidal** [comment]
@petrovi4 The problem here is not a limitation with this library, but a limitation in babel, you could do what I did [here](https://github.com/RobinBuschmann/sequelize-typescript/issues/532#issuecomment-459152477) and ignore the type infers, and you could load your models like this:

```typescript
// src/index.ts

import { sequelize } from 'path/to/your/config';
import * as express from 'express';

const port = parseInt(process.env.PORT, 10) || 8080;
const app = express();

const server = app.listen(port, asyc (err) => {
  await sequelize.sync();

  // import your route initializers
  const { initializeTestRoutes } = require('routes/test');
  
  intializeTestRoutes(app);
});

export default server;
```
```typescript
// routes/test.ts

import { SomeModel } from 'models/SomeModel';
import { Express, Request, Response, Router } from 'express';

export const initalizeTestRoutes = (app: Express) => {
  const router = Router();

  router.get('/', async (req: Request, res: Response) => {
     const record = await SomeModel.findOne({ 
                                        where: { someField: someField },
                                        raw: true,
                                      });

    if (!record) return res.status(404);

    return res
                 .status(200)
                 .json(record);     
  };

  app.use('/test', router);
};
```

This would load the config allowing the models to be added before your endpoints (which I assume are calling said models) and then you can import your routes inside the `app.listen` call and finish setting up.

This should work as I do something similar with my graphql endpoints that depend on sequelize models, let me know either way.
