### ISSUE TITLE
Error TS2321 when defining relations with scopes using Typescript v. 3.2.4 (doesn't occur with TS 3.1.x)

### ISSUE THREAD

**Issue by IgorSzymanski** [RobinBuschmann/sequelize-typescript#533]
TS throws an error
`error TS2321: Excessive stack depth comparing types '() => NonAbstractTypeOfModel<Post>' and 'ModelClassGetter'.`

when defining relations using scopes:

```ts
@Table({})
export default class User extends Model<User>
{ 
    @HasMany(() => Post) // this is not causing the issue
    allPosts: Post[]

    @HasMany(() => Post.scope('visibleOnly')) // if commented, the error is gone.
    posts: Post[]
}
```

For some reason TS cannot associate `NonAbstractTypeOfModel<T>` with `typeof Model`.

TypeScript: 3.2.4

**Comment by RobinBuschmann** [comment]
Hey @IgorSzymanski, besides the type issue, is this technically working? My assumption is that defining relations with scoped models like you did won't.

**Comment by IgorSzymanski** [comment]
Yes, it did work (meaning, the scope was applied correctly to the relation and no error was thrown) with TS 3.1.x.
I found one example in the docs of a relation defined as such, and that is:
http://docs.sequelizejs.com/manual/tutorial/scopes.html

The last line of:
```ts
const Post = sequelize.define('post', attributes, {
  defaultScope: {
    where: {
      active: true
    }
  },
  scopes: {
    deleted: {
      where: {
        deleted: true
      }
    }
  }
});

User.hasMany(Post); // regular getPosts association
User.hasMany(Post.scope('deleted'), { as: 'deletedPosts' });
```
So I guess it's intended to work.

**Comment by IgorSzymanski** [comment]
I think I might have found the solution and it's passing all the tests.
Basically, defining `types/ModelClassGetter.ts` as:
```ts
import {Model, NonAbstractTypeOfModel} from "../models/Model";

export type ModelClassGetter<T = Model<any>> = (returns?: void) => NonAbstractTypeOfModel<T>;
```
and exporting `NonAbstractTypeOfModel` from `models/Model.d.ts'

```ts
/* ... */
// line 26
export type NonAbstractTypeOfModel<T> = (new () => T) & NonAbstract<typeof Model>;
/* ... */
```

Even though it's passing the tests and I could do a PR, I am not sure if it can affect development experience.

**Comment by RobinBuschmann** [comment]
Looks good 👍
