### ISSUE TITLE
Issue with Jest: Unable to run tests

### ISSUE THREAD

**Issue by josecolella** [RobinBuschmann/sequelize-typescript#535]
Hello @RobinBuschmann ,

I receive the following error message when I try running tests that have sequelize-typescript:
```
Test suite failed to run

    TypeError: Class extends value [object Object] is not a constructor or null

      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/v4/sequelize.js:15:25)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/v4/Sequelize.js:10:25)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/sequelize.js:6:17)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/BaseModel.js:3:19)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/Model.js:3:17)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/services/models.js:14:15)
```
Do you know what might be causing this? I'm currently using ts-jest.

**Comment by josecolella** [comment]
@RobinBuschmann I think I tracked this down. I basically ended up substituting any reference to the Model with interfaces and the issues stopped. It would be nice to understand why jest and sequelize-typescript aren't playing nice :(

**Comment by RobinBuschmann** [comment]
Hey @josecolella, can you provide an example repo, which reproduces the issue?

**Comment by josecolella** [comment]
@RobinBuschmann sure. I'm putting it together for you.

**Comment by josecolella** [comment]
@RobinBuschmann I have the repository showing the issue: https://github.com/josecolella/sequelize-typescript-jest-issue.

Steps to reproduce:

```sh
git clone https://github.com/josecolella/sequelize-typescript-jest-issue.git
cd sequelize-typescript-jest-issue/
npm i
npm test
```

You should receive the following message:

```
 FAIL  src/components/healthCheck/healthCheck.controller.spec.ts
  ● Test suite failed to run

    TypeError: Class extends value [object Object] is not a constructor or null

      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/v4/sequelize.js:15:25)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/v4/Sequelize.js:10:25)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/sequelize.js:6:17)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/BaseModel.js:3:19)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/models/Model.js:3:17)
      at Object.<anonymous> (node_modules/sequelize-typescript/lib/services/models.js:14:15)
```

Please let me know if you have any further questions

**Comment by josecolella** [comment]
@RobinBuschmann Any idea on this one?

**Comment by RobinBuschmann** [comment]
@josecolella `OriginSequelize = require('sequelize')` is an empty object during jest test run. This happens when a circular dependency appears. Unfortunately I have no idea why 🤔Especially because this doesn't happen if the app server is started, right?

**Comment by josecolella** [comment]
Correct. When the application is started the error is not seen, only when jest test runner is initiated

**Comment by josecolella** [comment]
@RobinBuschmann any suggestions for this. Currently I'm not able to use jest in any code that uses sequelize-typescript

**Comment by RobinBuschmann** [comment]
@josecolella With the following jest config the problem disappears:

```js
module.exports = {
  collectCoverage: true,
  moduleFileExtensions: [
    'ts',
    'tsx',
    'js'
  ],
  collectCoverageFrom: [
    'src/**/*.ts',
    'src/**/*.tsx'
  ],
  transform: {
    '\\.(ts|tsx)$': 'ts-jest'
  },
  testRegex: '.*\\.spec\\.(ts|tsx)$'
};
```
I don't know what exact setting causes the issue.

**Comment by josecolella** [comment]
Thanks @RobinBuschmann , I'll continue investigating which is the option that causes the issue, and report back

**Comment by RobinBuschmann** [comment]
Hey @josecolella , did you find something out? If there still are any issues with sequelize-typescript, just reopen the issue!

**Comment by PatrickGeyer** [comment]
@josecolella did you ever find out what exactly was causing the issue?

**Comment by PatrickGeyer** [comment]
For me it was the ``` "moduleDirectories": [
      ".",
      "src",
      "node_modules"
    ],``` option. When I removed the ```".",``` from ```moduleDirectories``` it was able to load the models correctly.

**Comment by josecolella** [comment]
@PatrickGeyer It works without the `.`. Thanks. I don't really understand why it has issues with the models with `.`, but anyways thanks again,
