### ISSUE TITLE
Type not enforced on .update({})

### ISSUE THREAD

**Issue by djvs** [RobinBuschmann/sequelize-typescript#536]
Just updated to 0.6.7, was also experiencing on 0.6.6.  

```
export type TMyStatusType = 'foo' | 'bar'
  @Sequelize.Column({
    allowNull: false,
    type: Sequelize.DataType.STRING,
    defaultValue: 'initial',
  })
  status: TMyStatusType
```

then elsewhere in the model class, or any other file with an instance of the class:
```
this.update({ 
  status: 'thisisntright'
})
```

Will not throw up any issues.  However:

```
this.status = 'thisisntright'
```

will.

**Comment by djvs** [comment]
This seems to only be happening with one model, which is especially confusing.

**Comment by edhedges** [comment]
I think it stems from this:

```
/**
   * This is the same as calling `set` and then calling `save`.
   */
  update(key: string, value: any, options?: InstanceUpdateOptions): Promise<this>;
  update(keys: Object, options?: InstanceUpdateOptions): Promise<this>;
```
Not being typed to the generic like this
```
/**
   * Update multiple instances that match the where options. The promise returns an array with one or two
   * elements. The first element is always the number of affected rows, while the second element is the actual
   * affected rows (only supported in postgres with `options.returning` true.)
   */
  static update<T extends Model<T>>(this: (new () => T), values: FilteredModelAttributes<T>, options: UpdateOptions): Promise<[number, Array<T>]>;
  static update<T extends Model<T>, A>(this: (new () => T), values: A, options: UpdateOptions): Promise<[number, Array<T>]>;
```

Would it be possible to have the non-static functions use the generic types?

**Comment by RobinBuschmann** [comment]
Hey @djvs, thanks for reporting. @edhedges is right, it is because `update` is not as strict typed as `static update` is. I'm going to change this for `sequelize-typescript@0.6.X`. 

(Please note, that `sequelize-typescript@1.0.0` will use the typings provided by sequelize itself, where most of the typings aren't as strict as they are now.)

**Comment by RobinBuschmann** [comment]
I'm going not to change this as discussed [here](#553). It would also mean a breaking change.

**Comment by djvs** [comment]
@RobinBuschmann  as discussed where?  Broken link?

**Comment by djvs** [comment]
#553 Fixed link
