### ISSUE TITLE
Ability to "Hydrate" Model from JSON String.

### ISSUE THREAD

**Issue by piyushkantm** [RobinBuschmann/sequelize-typescript#543]
This is more of a question rather than an issue... I have this specific use-case where we need to cache data. I just wanted to check if the following is possible.

1. We can get the whole DB Model from cache as **string**.
2. We want to parse the string and then instantiate the JSON object as Sequelize Model..

e.g.

```
const userJSON = `{"id":1,"name":"Piyush"}`; // Assume It's from cache...
const user = JSON.parse(userJSON);

const userModel = User.hydrate(user); // Searching for something like this...

userModel.update({
    "name": "Updated Name here"
}).then(...);
```

**Comment by piyushkantm** [comment]
Actually coming from Laravel background, i was searching for "hydrate" while the solution was under my nose the whole time... I just created this issue to post the answer if it servers any purpose to other users:


```
User.build(user, {
    isNewRecord: false
}).then((userModel) => {
// Do Crazy Stuff here...
});
```

**Comment by RobinBuschmann** [comment]
Thanks @piyushkantm for coming up with the actual solution. Since this is solved I close this one. If you still have any issues, just reopen it
