### ISSUE TITLE
Allow full support of mysql timestamps

### ISSUE THREAD

**Issue by thomasmikava** [RobinBuschmann/sequelize-typescript#544]
When I want some column to be of type nullable TIMESTAMP in mysql, with default value NULL, I can't do this in sequelize-typescript. 
```ts
@Column({
	type: "TIMESTAMP",
	defaultValue: NULL,
	allowNull: true,
})
```
This is not possible in current version.
Furthermore (though not related to nullability), if I want to create column updated_at with type TIMESTAMP in mysql, currently I write:
```ts
@Column({
	type: "TIMESTAMP",
	defaultValue: Sequelize.literal("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
})
```
Which is causing sql errors during insertion, since "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" is not valid value, and I'm forced to create static method for fixing this.
```ts
@BeforeCreate
static defaultUpdatedAt(instance: SMSGroup) {
	instance.updated_at = this.sequelize.literal("CURRENT_TIMESTAMP") as any; // or new Date()
}
```

**Comment by RobinBuschmann** [comment]
@thomasmikava As stated [here](https://github.com/sequelize/sequelize/issues/4896#issuecomment-396636594) remove `ON UPDATE CURRENT_TIMESTAMP` from you literal. Then it should work.

**Comment by thomasmikava** [comment]
If I try
```ts
@thomasmikava Column({
	type: "TIMESTAMP",
	defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
})
```
or 
```ts
@Column({
	type: "TIMESTAMP",
	defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
	onUpdate : Sequelize.literal("CURRENT_TIMESTAMP") as any,
})
```
This will create the following schema:
![image](https://user-images.githubusercontent.com/11869300/53228450-b3becc00-369a-11e9-883c-c67757de8b24.png)
while I want this:
![image](https://user-images.githubusercontent.com/11869300/53228515-dbae2f80-369a-11e9-8b3d-03a02a9d8a6f.png)

**Comment by RobinBuschmann** [comment]
@thomasmikava You're using `sequelize.sync` in order to create the database tables, right? I would recommend using migrations instead. There you could set up what you want and you could omit setting `defaultValue`.

**Comment by thomasmikava** [comment]
Yes, I do. Thank you! Do you still suggest db-migrate package for migrations or something else?

**Comment by RobinBuschmann** [comment]
Yes, if you are fine with writing the sql statements by yourself it is definitely the right tool for you

**Comment by thomasmikava** [comment]
Thanks!
