### ISSUE TITLE
define pseudo properties

### ISSUE THREAD

**Issue by fareshan** [RobinBuschmann/sequelize-typescript#545]
Is it possible to define [pseudo properties](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#defining-as-part-of-the-model-options) (getterMethods and setterMethods) in sequelize-typescript?

**Comment by RobinBuschmann** [comment]
@fareshan [This](https://github.com/RobinBuschmann/sequelize-typescript#accessors) should do the job

**Comment by fareshan** [comment]
as I needed a property without creating a column, i solved my issue by setting type DataType.VIRTUAL:
`
  @Column(DataType.VIRTUAL)
  get amount(): number {
    ...
  }
`

**Comment by RobinBuschmann** [comment]
@fareshan so if this is solved for you, can we close this issue then?

**Comment by fareshan** [comment]
@RobinBuschmann yes, i close it
