### ISSUE TITLE
insertOrUpdate throws Model not initialized: "State" needs to be added to a Sequelize instance before "getTableName" can be called.

### ISSUE THREAD

**Issue by nicolarichli** [RobinBuschmann/sequelize-typescript#547]
Hi @RobinBuschmann 
I have searched for this issue, but didn't find any solution on the issue tracker.

My Config:
```ts
export const dbConfig = {
    host: 'host',
    database: 'ECAT_test',
    username: 'username',
    password: 'password',
    dialect: 'mssql',
    modelPaths: [
        __dirname + '/../models/db/*.ts'
    ]
}
```
My Cluster Model:
```ts
import { Table, Column, Model, ForeignKey, PrimaryKey, BelongsTo, HasOne, HasMany } from 'sequelize-typescript'; 
import { State } from './State';
import { Blade } from './Blade';
import { DistributedSwitch } from './DistributedSwitch';
import { Folder } from './Folder';

@Table
export class Cluster extends Model<Cluster> {

    @Column({primaryKey: true})
    id: number;

    @Column
    name: string;

    @ForeignKey(() => Folder)
    @Column
    folderId: number;
    @BelongsTo(() => Folder)
    folder: Folder;

    @ForeignKey(() => DistributedSwitch)
    @Column
    distributedSwitchId: number

    @Column
    licenseKey: string;

    @Column
    datastoreClusterName: string;

    @ForeignKey(() => State)
    @Column
    installationState: number;
    @BelongsTo(() => State)
    state: State;

    @HasMany(() => Blade)
    blades: Blade[];
}
```

My State Model:
```ts
import { Table, Column, Model, ForeignKey, PrimaryKey, BelongsTo, HasOne, HasMany } from 'sequelize-typescript'; 
import { RunnedScript } from './RunnedScript';
import { Blade } from './Blade';
import { Cluster } from './Cluster';

@Table
export class State extends Model<State> {
    
    @Column({primaryKey: true})
    id: number;

    @Column
    name: string;

    @HasMany(() => Cluster)
    clusters: Cluster[]

    @HasMany(() => RunnedScript)
    runnedScripts: RunnedScript[];

    @HasMany(() => Blade)
    blades: Blade[];
}
```

Now I have a function, which should insert or update the state of the cluster:
```ts
addOrUpdateCluster(cluster: Cluster, callback: (error: any) => void): void {
    Cluster.insertOrUpdate({
      where: {
        name: cluster.name        
      },
      defaults: cluster
    }).then((res) => {
      return callback(null);
    }).catch((err) => {
      return callback(err);
    });
  }
```

I call the function like:
```ts
const cluster = Cluster.create({
      name: scriptData.clustername,
      state: {
        name: 'running'
      }
    }, {
      include: [ State ]
    });

    this._msSqlService.addOrUpdateCluster(cluster.value(), (err) => {
      if (err) {
        return new Response(500, 'Server error');
      }
    });
```

The error 'Model not initialized: "State" needs to be added to a Sequelize instance before "getTableName" can be called.' is shown.

Do you know, why this happens?
>

**Comment by RobinBuschmann** [comment]
@nicolarichli Looks like the models aren't loaded properly. Are you using ts-node or do you precompiling your ts code?

**Comment by nicolarichli** [comment]
I precompile the code

**Comment by RobinBuschmann** [comment]
Since the models are loaded during runtime, you should change your model paths so that they point to `js` files instead of `ts` ones

**Comment by nicolarichli** [comment]
All right, thanks a lot. But then I get following error:
`Error: No default export defined for file "blade" or export does not satisfy filename.`

**Comment by nicolarichli** [comment]
ah.. the file names are not in capital letters anymore in the compiled JS files

**Comment by RobinBuschmann** [comment]
If the filename doesn't match the class name you either have to use default exports or `modelMatch`. See [this](https://github.com/RobinBuschmann/sequelize-typescript#model-path-resolving)

**Comment by nicolarichli** [comment]
I did it about one hour ago.. Since then I experience an other error:
`No default export defined for file "bladeRunsScript" or export does not satisfy filename.`

My model looks like this (it's called bladeRunsScript.ts):
`import { Model, Table, ForeignKey, Column } from 'sequelize-typescript';
import { RunnedScript } from './runnedScript';
import { Blade } from './blade';

@Table
export class BladeRunsScript extends Model<BladeRunsScript> {
    @ForeignKey(() => Blade)
    @Column
    blade: number;

    @ForeignKey(() => RunnedScript)
    @Column
    runnedScript: number;
}`

**Comment by RobinBuschmann** [comment]
@nicolarichli So you either have to use default exports like:
```ts
...
export default BladeRunsScript;
```
or `modelMatch` like
```ts
const sequelize = new Sequelize({
  ...,
  modelMatch: (filename, member) => filename.toLowerCase() === member.toLowerCase()
})
```

**Comment by nicolarichli** [comment]
thanks man, it worked!! 
you can be proud of the work you do and I'm extremly impressed!! You volunteer for people and make the life easier of them.
Thanks a lot!!!

**Comment by RobinBuschmann** [comment]
You're welcome :)
