### ISSUE TITLE
foreign key issue

### ISSUE THREAD

**Issue by siddisking** [RobinBuschmann/sequelize-typescript#549]
Hi I am new to orm's and typescript.

I have been trying to figure out how to define foreign key relationship b/w 2 tables

here is the schema:

table 1 schema: **campaign**:

```
+---------------------+--------------+------+-----+---------+-------+
| Field               | Type         | Null | Key | Default | Extra |
+---------------------+--------------+------+-----+---------+-------+
| campaign_id         | varchar(50)  | NO   |     | NULL    |       |
| campaign_title      | varchar(50)  | NO   |     | NULL    |       |
| start_date          | date         | NO   |     | NULL    |       |
| end_date            | date         | NO   |     | NULL    |       |
| ad_id               | varchar(100) | NO   |     | NULL    |       |
| currency_unit       | varchar(100) | NO   |     | NULL    |       |
| total_budget        | int(11)      | NO   |     | NULL    |       |
| display_unit_id     | varchar(20)  | YES  |     | NULL    |       |
| cost_per_footfall   | int(11)      | NO   |     | NULL    |       |
| cost_per_impression | int(11)      | NO   |     | NULL    |       |
| id                  | varchar(40)  | YES  |     | NULL    |       |
+---------------------+--------------+------+-----+---------+-------+

```

table 2 schema: **campaign_display_units**:

```
+-----------------+-------------+------+-----+---------+-------+
| Field           | Type        | Null | Key | Default | Extra |
+-----------------+-------------+------+-----+---------+-------+
| campaign_id     | varchar(50) | NO   |     | NULL    |       |
| display_unit_id | varchar(50) | NO   |     | NULL    |       |
| id              | int(11)     | YES  |     | NULL    |       |
+-----------------+-------------+------+-----+---------+-------+

```

here are my models:

Campaign.ts

```
import {Table, Column, Model, HasMany} from 'sequelize-typescript'; 
import { CampaignDisplayUnits } from './CampaignDisplayUnits';
/**
 * Details of a campaign
 *
 */
@Table ({
  tableName:"campaign"
})
export class Campaign extends Model<Campaign> {

  @Column
  campaign_id: string

  @Column
  campaign_title: string

  @Column
  start_date: Date

  @Column
  end_date: Date

  @Column
  ad_id: string

  @Column
  currency_unit: string

  @Column
  total_budget: string

  @Column
  cost_per_impression: string

  @Column
  cost_per_footfall: string

  @HasMany(() => CampaignDisplayUnits,{constraints: false})
  campaign_display_units:CampaignDisplayUnits[];

}
```

and CampaignDisplayUnits.ts
```

import {Table, Column, Model, BelongsTo, ForeignKey} from 'sequelize-typescript'; 
import { Campaign } from "./Campaign";
/**
 * screens which are being used in a campaign
 *
 */
@Table ({
  tableName:"campaign_display_units"
})
export class CampaignDisplayUnits extends Model<CampaignDisplayUnits> {
  
  @Column
  display_unit_id: string;

  @ForeignKey(() => Campaign)
  @Column
  campaign_id: string;

  @BelongsTo(() => Campaign)
  campaign: Campaign;
  
  

}
```

I simple want to run `Campaign.findAll({include:[CampaignDisplayUnits]});`and get a output like this:

```
[
{
"id": "1",
"campaign_id": "campaign_00001",
"campaign_title": "Test Campaign",
"start_date": "2019-02-21",
"end_date": "2019-03-04",
"ad_id": "ad_000001",
"currency_unit": "INR",
"total_budget": 20000,
"cost_per_impression": 3,
"cost_per_footfall": 10,
"campaign_display_units": [aabcbc334,9909xx9aodf,....]
},{
...
}
]
```

Whenever I run the above code it shows this query

`Executing (default): SELECT Campaign.id, Campaign.campaign_id, Campaign.campaign_title, Campaign.start_date, Campaign.end_date, Campaign.ad_id, Campaign.currency_unit, Campaign.total_budget, Campaign.cost_per_impression, Campaign.cost_per_footfall, campaign_display_units.id AS campaign_display_units.id, campaign_display_units.display_unit_id AS campaign_display_units.display_unit_id, campaign_display_units.campaign_id AS campaign_display_units.campaign_id FROM campaign AS Campaign LEFT OUTER JOIN campaign_display_units AS campaign_display_units ON Campaign.id = campaign_display_units.campaign_id;
`
1. it takes the wrong table name
2. it does the LOJ on Campaign.id instead of campaign_id

What's the issue ?

Any help will be appreciated

-Thanks

**Comment by RobinBuschmann** [comment]
Hey @siddisking, it looks right to me. 

Regarding 1. the table name is correct. Just look at the `FROM` part of the query: `FROM campaign AS Campaign`. The referred table name is indeed `campaign`

Regarding 2. The join is done via the primary key of `Campaign`/`campaign`, which is `id` and the foreign key of table `campaign_display_units`, which is `campaign_id` as you've defined in your model.

What's your actual issue with the result?

**Comment by siddisking** [comment]
Hey,

Thanks for replying quickly.

Regarding 2 can I change the column on which it performs the join?

I am getting this result:

```
[
{
"id": "1",
"campaign_id": "campaign_00001",
"campaign_title": "Test Campaign",
"start_date": "2019-02-21",
"end_date": "2019-03-04",
"ad_id": "ad_000001",
"currency_unit": "INR",
"total_budget": 20000,
"cost_per_impression": 3,
"cost_per_footfall": 10,
"campaign_display_units": []
},
{
"id": "2",
"campaign_id": "campaign_00002",
"campaign_title": "Test Campaign 2 (Old)",
"start_date": "2019-02-11",
"end_date": "2019-02-16",
"ad_id": "ad_000002",
"currency_unit": "INR",
"total_budget": 20000,
"cost_per_impression": 3,
"cost_per_footfall": 10,
"campaign_display_units": []
},
{
"id": "3",
"campaign_id": "campaign_00003",
"campaign_title": "campaign expired",
"start_date": "2019-02-18",
"end_date": "2019-03-03",
"ad_id": "ad_000001",
"currency_unit": "INR",
"total_budget": 10000,
"cost_per_impression": 3,
"cost_per_footfall": 10,
"campaign_display_units": []
}
]
``` 


I am expecting that I will get a list of campaign_display_units with each campaign... to achieve this should I be doing something different?

**Comment by RobinBuschmann** [comment]
Ah now I see it. You've defined `campaign_id` in your `Campaign` model. Do you want this to be the primary key? If so, you have to tell sequelize:

```ts
@PrimaryKey
@Column
campaign_id: string;
``` 
or
```ts
@Column({primaryKey: true})
campaign_id: string;
```

**Comment by siddisking** [comment]
> Ah now I see it. You've defined `campaign_id` in your `Campaign` model. Do you want this to be the primary key? If so, you have to tell sequelize:
> 
> ```ts
> @PrimaryKey
> @Column
> campaign_id: string;
> ```
> 
> or
> 
> ```ts
> @Column({primaryKey: true})
> campaign_id: string;
> ```

Yep, this works! 

Thanks for your great insight.
