### ISSUE TITLE
Make a relation: add a foreign key

### ISSUE THREAD

**Issue by Chnapy** [RobinBuschmann/sequelize-typescript#55]
Hi
I made two Model and I search to add a relation between them, simply a foreign key.

Password.ts
```TypeScript
@Table
export default class Password extends Model<Password> {

    @PrimaryKey
    @AutoIncrement
    @Column(DataType.BIGINT)
    readonly id_password: number;

    @AllowNull(false)
    @Column
    value: string;

    @AllowNull(false)
    @Column(DataType.ARRAY(DataType.INTEGER))
    salt: Array<number>;

}
```

User.ts
```TypeScript
@Table
export default class User extends Model<User> {

    @PrimaryKey
    @AutoIncrement
    @Column(DataType.BIGINT)
    readonly id_user: number;

    @Length({min: 3, max: 16})
    @AllowNull(false)
    @Column
    readonly username: string;

    @BelongsTo(() => Password, 'id_password')
    password: Password;

    @IsEmail
    @AllowNull(false)
    @Column
    email: string;

    @CreatedAt
    @AllowNull(false)
    @Column
    readonly date_register: Date;

    @UpdatedAt
    @AllowNull(false)
    @Column
    date_last_activity: Date;

}
```

And I test that :
```TypeScript
this.sequelize.sync({force: true}).then(err => {

            const password = new Password({
                id_password: 2,
                value: 'test_pwd',
                salt: [21, 34, 56]
            });

            const user = new User({
                username: "Chnapy",
                password: password,
                email: "toto@aaa.com",
                date_register: new Date(),
                date_last_activity: new Date()
            });

            password.save();
            user.save();

        });
```

The database result is :
* For Password table:
![image](https://user-images.githubusercontent.com/7474483/28250219-cc253504-6a63-11e7-952d-ccdc024ecb06.png)
* For User table:
![image](https://user-images.githubusercontent.com/7474483/28250233-f0b7d39a-6a63-11e7-945c-0abc733212d8.png)
**You can see that `id_password` is empty, and there is no constraint on this field.** :confused:

I tried to use `@ForeignKey` or `@HasOne` in User.ts instead of `@BelongsTo` without success.

Thank you for your help, i'm still new to this framework :simple_smile:

**Comment by RobinBuschmann** [comment]
@Chnapy Hey, your model definitions are looking good so far.

When storing the data including the relations, you either need to create or build it like this:

```typescript
User.create({
    name: 'bob',
    password: {
      value: 'secret'
    }
  }, {include: [Password]}).then(() => ...);
```
or
```typescript
const user = new User({
    name: 'bob2',
    password: {value: 'secret2'}
  }, {include: [Password]});

user.save().then(() => ...);
```

**Comment by Chnapy** [comment]
Thanks !
But it doesn't work :(

I tried one and the other, but Typescript refuse to compile: `Argument of type '{ include: typeof Password[]; }' is not assignable to parameter of type 'IBuildOptions'.`

**Comment by RobinBuschmann** [comment]
Ah, I see. This seems to be a bug in the declaration files unfortunately :/ 

Try `include: [{model: Password}]` - This should work.

I will fix this. So that `include: [Password]` will work. Thanks for reporting

**Comment by Chnapy** [comment]
Thank you it works like a charm now :smile:
