### ISSUE TITLE
Argument of type '{ fields: string[]; }' is not assignable to parameter of type '{ skip?: string[]; }'.

### ISSUE THREAD

**Issue by someApprentice** [RobinBuschmann/sequelize-typescript#554]
When method `.validate` is used on the instance with option `{ fields: ['...'] }` application throw error

```
Argument of type '{ fields: string[]; }' is not assignable to parameter of type '{ skip?: string[]; }'.
Object literal may only specify known properties, and 'fields' does not exist in type '{ skip?: string[]; }'.
```

To work around this issue need manually write this [line](https://github.com/sequelize/sequelize/blob/master/lib/instance-validator.js#L24)

`entity.validate({ skip: _.difference(Object.keys(Entity.rawAttributes), ['foo']) })`

# Version
```
"sequelize": "^4.42.0",
"sequelize-typescript": "^0.6.6",
```

# Steps to reproduce

```
import { Sequelize, Model, Column } from 'sequelize-typescript';

const sequelize =  new Sequelize({
  //configs
});

class Entity extends Model<Entity> {
    @Column
    foo: string

    @Column
    bar: string
}

sequelize.addModels([Entity]);

let entity = new Entity({ foo: 'FOO' });

entity.validate({ fields: ['foo'] }).then(v => {
    console.log(v);
});
```

**Comment by RobinBuschmann** [comment]
@someApprentice thanks for reporting. Looks like the options typings are incomplete. As stated [here](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-validate) besides `fields`, `hooks` is missing as well.
