### ISSUE TITLE
Implementation of Sequelize instance in an external file causes an error of undefined model

### ISSUE THREAD

**Issue by someApprentice** [RobinBuschmann/sequelize-typescript#556]
If Sequelize instance implemented in an external file and imported in the main file, any model's creation throws error

```
ERROR: Cannot read property 'createdAt' of undefined
at Entity._initValues (/node_modules/sequelize/lib/model.js:3123:49)
at new Model (/node_modules/sequelize/lib/model.js:3097:10)
at new Model (/node_modules/sequelize-typescript/lib/models/v4/Model.js:8:9)
at new Entity(/models/Entity.ts:5:1)
at Object.<anonymous> (/app.ts:4:1)
...
```

# Test Case
```
// ./services/Database.ts
import { Sequelize } from 'sequelize-typescript';

const sequelize =  new Sequelize({
  // config
});

sequelize.addModels(['../models']);

export default sequelize;
```

```
// ./app.ts
import sequelize from './services/Database';
import { Entity } from './models/Entity.ts';

let entity = new Entity(...);
...
```

Somehow if in `./app.ts` set a variable with imported `sequelize` instance this will prevent the error

```
// ./app.ts
import sequelize from './services/Database';
import { Entity } from './models/Entity.ts';

// this will prevent error above
const db = sequelize;

let entity = new Entity(...);
...
```

Am I doing something wrong?

**Comment by RobinBuschmann** [comment]
@someApprentice Your `./services/Database.ts` has to be imported somewhere in order to initialize the db connection and to load the models. In your first example you are indeed importing your setup (`import sequelize from './services/Database';`) but I assume that during the compilation/bundling process unused imports are removed, which prevents your setup from being loaded actually.

**Comment by someApprentice** [comment]
@RobinBuschmann Understood. Issue can be closed due it isn't relevant to this library.

**Comment by RobinBuschmann** [comment]
@someApprentice What you also could do is importing it like so: `import './services/Database';` This will also help to prevent it from getting removed during bundling process.
