### ISSUE TITLE
[Multiple Relation] If one foreign key has a null relation for the same model it will be null too.

### ISSUE THREAD

**Issue by sgtkuncoro** [RobinBuschmann/sequelize-typescript#558]
one of the null keys causes another relation with the same model to not be formed.

**Comment by RobinBuschmann** [comment]
Hey @sgtkuncoro, can you provide a more advanced example? I don't really get the issue, sry!

**Comment by sgtkuncoro** [comment]
Hi @RobinBuschmann thank you for the response.

For example, I have a table `book` and `peson`, as exemplified, here is an example of the relationship..

```
@Table
class Book extends Model<Book> { 

  @ForeignKey(() => Person)
  @Column
  authorId: number;
  
  @BelongsTo(() => Person)
  author: Person; 
  
  @ForeignKey(() => Person)
  @Column
  proofreaderId: number;
  
  @BelongsTo(() => Person)
  proofreader: Person;
}

@Table
class Person extends Model<Person> {

  @HasMany(() => Book)
  writtenBooks: Book[];

  @HasMany(() => Book)
  proofedBooks: Book[];
}
```

in my case, I want if the `proofreaderId` is set (has a value) then `authorId` is `null`, and vice versa.
the problem is when the `proofreaderId` is set, and `authorId` is null (null), this causes the `proofedBooks` relation not to be formed.

```
  Book.findAll({ include: [ {as: "author", model: Person}, {as: "proofreader", model: Person} ] })  
```
the result returned from this `query` for the key `proofreader` is `null`

**Comment by RobinBuschmann** [comment]
I assume you are referring [this](https://github.com/RobinBuschmann/sequelize-typescript#multiple-relations-of-same-models). As stated there, this won't work. 
> sequelize-typescript cannot know which foreign key to use for which relation. So you have to add the foreign keys explicitly:

You have to define the foreign keys with the `@BelongsTo`/`@HasMany` decorators.

```ts
  // in class "Books":
  @BelongsTo(() => Person, 'authorId')
  author: Person; 

  @BelongsTo(() => Person, 'proofreaderId')
  proofreader: Person; 
  
  // in class "Person":
  @HasMany(() => Book, 'authorId')
  writtenBooks: Book[];

  @HasMany(() => Book, 'proofreaderId')
  proofedBooks: Book[];
```

**Comment by sgtkuncoro** [comment]
wow ... you're right,,
I am not very good at explaining it but the mistake is I made the same name for the relation, see the code below

**Wrong**
```js
// in class "Books":
  @BelongsTo(() => Person, 'authorId')
  author: Person; 

  @BelongsTo(() => Person, 'proofreaderId')
  proofreader: Person; 
  
  // in class "Person":
  @HasMany(() => Book, 'authorId')
  author: Book[];

  @HasMany(() => Book, 'proofreaderId')
  proofreader: Book[];
```
**Right**
```js
// in class "Books":
  @BelongsTo(() => Person, 'authorId')
  author: Person; 

  @BelongsTo(() => Person, 'proofreaderId')
  proofreader: Person; 
  
  // in class "Person":
  @HasMany(() => Book, 'authorId')
  writtenBooks: Book[];

  @HasMany(() => Book, 'proofreaderId')
  proofedBooks: Book[];
```
thank you @RobinBuschmann, this is a good job
