### ISSUE TITLE
Transaction with model hook (@AfterCreate) run 2 times

### ISSUE THREAD

**Issue by lacuong2009** [RobinBuschmann/sequelize-typescript#571]
Hi Guys.

I have an issue with @AfterCreate hook. It runs 2 times when I try to insert a record to the database with a transaction.

My code: insert new record to db
 ```
this.getSequelize().transaction(async (t: any) => {
            return await Transaction.build({
                EventType: EventType.list[object.EventKey],
                Type: object.Type ? object.Type : 'add',
                Point: object.Point,
                ObjectType: objectType,
                ObjectReference: objectReference,
                IsAuto: true,
                CustomerReference: customerReference,
                PartnerId: object.PartnerId
            }).save({
                transaction: t
            });
        });

```
My hook in model
```
    @AfterCreate
    static afterCreated(instance: Transaction, options: any) {
        if (options.transaction) {
            options.transaction.afterCommit(async () => {
               console.log("transaction.created");
                await HelperFactory.getAmqp().publish('transaction.created', instance)
            });
        }
    }

```
When I add console log in function afterCreated then it show 2 lines log.

**Comment by RobinBuschmann** [comment]
Hey @lacuong2009, I'm not able to reproduce your problem. Can you provide an example repo, which reproduces the issue?

**Comment by lacuong2009** [comment]
Hi. I have try agian and work fine now.

**Comment by aoleksiiuk-karsun** [comment]
facing the same issue with `@AfterCreate` and `@AfterUpdate`. Either hook is invoked twice despite the fact there's a single update or create op.

```
export default class Item extends Model<Item> {
...
  @AfterCreate
  @AfterUpdate
  static hookLogic() {
    console.log("I'm running");
  }
}
```
The console.log above is invoked twice when I update Item, or create a new one. I thought it was invoking both hooks, hence the double logic execution, and I removed `@AfterCreate`, but to no avail. A single `@AfterUpdate` hook runs twice.
Let me know if any additional info is needed from me. Thanks for your help
