### ISSUE TITLE
Missing useMaster option in query options

### ISSUE THREAD

**Issue by seancheung** [RobinBuschmann/sequelize-typescript#573]
![image](https://user-images.githubusercontent.com/5442563/54734708-70457800-4bdc-11e9-8d3f-47c991891233.png)

![image](https://user-images.githubusercontent.com/5442563/54734712-7e939400-4bdc-11e9-9a95-5a024b78f77c.png)

Missing `useMaster` option in *IFindOptions.d.ts*.
This is a replication related feature.

**Comment by RobinBuschmann** [comment]
Thanks for reporting!

**Comment by RobinBuschmann** [comment]
@seancheung Are you sure, that this is part of the "FindOptions". It seems only to be part of `sequelize.query(...)`. Can you provide a link from the sequelize docs?

**Comment by seancheung** [comment]
This is not listed in reference doc but in manual under Basic Usage part:

[http://docs.sequelizejs.com/manual/usage.html](http://docs.sequelizejs.com/manual/usage.html)

See **Read replication** section

> Each write or useMaster: true query will use write pool. For SELECT read pool will be used. Read replica are switched using a basic round robin scheduling.

It's declared in [@types/sequelize](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d8748201c7bfc38d70269af3bcaa3a5c380547af/types/sequelize/index.d.ts#L3411) but not in the [typings](https://github.com/sequelize/sequelize/blob/7a6c60d73202f35278a44b6c649f44350652e4d9/types/lib/model.d.ts#L440) shipped with sequelize. A lot of definitions seem to be missing in the latter(like generic support, etc.).

This package uses *@types/sequelize* in *[package.json](https://github.com/RobinBuschmann/sequelize-typescript/blob/e7253bbb09e9315cc27d744b742a156644742507/package.json#L48)*

**Comment by RobinBuschmann** [comment]
@seancheung  Ah OK, thanks. I will add this for `sequelize-typescript@0.6.X`. Can you create a PR for `sequelize@5`?
