### ISSUE TITLE
Using builtin sequelize validation decorators on optional fields

### ISSUE THREAD

**Issue by cookrn** [RobinBuschmann/sequelize-typescript#580]
If I have a model that looks like the following:

```typescript
import { Column, IsEmail, Model, PrimaryKey, Table } from "sequelize-typescript";

@Table
export class User extends Model<User> {
  @PrimaryKey
  @Column
  public id!: number;

  @IsEmail
  @Column
  public email?: string;
}
```

Even though the `email` field is optional (assumes default setting of `@AllowNull(true)`), the `@IsEmail` validation is still running and returning an error on that field.

Looking at the Sequelize docs, the following is written about per-attribute validators and `allowNull`.

> On the other hand, if it is set to allow null (with allowNull: true) and that value has been set to null, only the built-in validators will be skipped, while the custom validators will still run.

Thus, I was assuming that the `@IsEmail` validator would not run. Do you have any suggestions for how we could achieve the specified underlying Sequelize behavior?

**Comment by cookrn** [comment]
After looking further, I think this is a problem with a different part of our stack. I was thinking the value was `null`, but was actually an empty string `""`. Apologies for the issue churn.

**Comment by Coinhexa** [comment]
@cookrn so what would you do if you wanted to allow an empty email. My field is not email it is a picture url with a isUrl validation but i also want to allow empty strings, any suggestions?
