### ISSUE TITLE
$between syntax not working

### ISSUE THREAD

**Issue by ian-callaghan** [RobinBuschmann/sequelize-typescript#586]
The standard $between syntax doesn't seem to be working for typescript, is there an alternative syntax I have to use?
```
const games = await GamesDbGame.findAll({
            where: {
                id: {
                    $between: [0, 999999]
                }
            }
        });
```

```
Executing (default): SELECT `id`, `game_title`, `release_date`, `players`, `overview`, `last_updated`, `rating`, `coop`, `youtube`, `alternates`, `createdAt`, `updatedAt`, `platformId` FROM `GamesDbGames` AS `GamesDbGames` WHERE `GamesDbGames`.`id` = '[object Object]';
```

**Comment by BadCoder1337** [comment]
You must use a symbol operator because `$` notation is deprecated
```ts
// ...model import...
import { Sequelize } from 'sequelize-typescript';
const { Op } = Sequelize;

const games = await GamesDbGame.findAll({
            where: {
                id: {
                    [Op.between]: [0, 999999]
                }
            }
        });
```

**Comment by ian-callaghan** [comment]
> You must use a symbol operator because `$` notation is deprecated
> 
> ```ts
> // ...model import...
> import { Sequelize } from 'sequelize-typescript';
> const { Op } = Sequelize;
> 
> const games = await GamesDbGame.findAll({
>             where: {
>                 id: {
>                     [Op.between]: [0, 999999]
>                 }
>             }
>         });
> ```

Perfect thanks, Was trying to do:

```
import { Sequelize } from 'sequelize-typescript';
Sequelize.Op.between 
//or
$between
```

**Comment by ian-callaghan** [comment]
Going to re-open, the syntax above does "work" e.g.

```
import { Sequelize } from 'sequelize-typescript';
const { Op } = Sequelize;
```

But it also throws an error with the typescript compiler as Op doesn't seem to exist in the typings?

```
error TS2459: Type 'typeof Sequelize' has no property 'Op' and no string index signature.
```

**Comment by BadCoder1337** [comment]
@ian-callaghan 
Which version of sequelize, sequelize-typescript, @types/sequelize do you use? Try to update to the latest versions.

**Comment by ian-callaghan** [comment]
> @ian-callaghan
> Which version of sequelize, sequelize-typescript, @types/sequelize do you use? Try to update to the latest versions.

reinstalled the packages but get the same error.
```
        "@types/sequelize": "^4.27.46",
        "@types/bluebird": "^3.5.26",
        "@types/validator": "^10.11.0",
        "sequelize": "^5.2.9",
        "sequelize-typescript": "^1.0.0-alpha.9",
        "reflect-metadata": "^0.1.13",
```

Could you show where the definition is in the .d.ts files so I can check it is there in mine?

**Comment by BadCoder1337** [comment]
Try latest stable version of sequelize-typescript

**Comment by ian-callaghan** [comment]
> sequelize-typescript

Same error with @0.6.9 plus compiler throws a ton of errors about other things in the .d.ts file.

Managed to solve importing from sequelize although oddly that does not come up as an autocomplete option:
```
import { Op } from 'sequelize';
```

I also tries from sequelize/types which is in autocomplete but that also threw a compiler error:
```
import { Op } from 'sequelize/types';
```

Do you have an example of the above code working with it imported from sequelize-typescript properly?

**Comment by TBingooo** [comment]
@ian-callaghan 
try this 
```javascript
import { Sequelize } from 'sequelize-typescript';
const { or } = Sequelize;

Account.findOne({ where: or({email: 'xxx@xxx.com'}, {phone: '111111111111'})});
```

**Comment by TBingooo** [comment]
oh sorry, `between` is not exported from sequelize-typescript.
try this one,
```javascript
import { Op } from 'sequelize';
await GamesDbGame.findAll({
            where: {
                id: {
                    [Op.between]: [0, 999999]
                }
            }
        });
```

**Comment by ian-callaghan** [comment]
> oh sorry, `between` is not exported from sequelize-typescript.
> try this one,
> 
> ```js
> import { Op } from 'sequelize';
> await GamesDbGame.findAll({
>             where: {
>                 id: {
>                     [Op.between]: [0, 999999]
>                 }
>             }
>         });
> ```

That's what I ended up doing, it works fine no errors, just a little odd that vs code auto import doesn't show it properly and instead tries to import it from 'sequelize/types'.

**Comment by RobinBuschmann** [comment]
@ian-callaghan can we close this issue now?

**Comment by nowiczka** [comment]
I did the same as @ian-callaghan however when dockerize the application it does not work correctly... I mean, I can run the application but it seems that the models are not taking into account the conditions with Op used.
