### ISSUE TITLE
Where clauses are not working for Dates

### ISSUE THREAD

**Issue by mattwerthva** [RobinBuschmann/sequelize-typescript#592]
When I send in a where clause with a date
```{ 
	"where":{
		"updatedAt": {
			"$gt": "2019-04-02T19:03:25.495+01:00"
			}
	}
}
```

I get `... AND "Integration"."updatedAt" = '2019-04-02 04:00:00.000 +00:00'`

1) The operator is not correct.  I have tried '$gt', '$lt', 'Op.gt', 'Op.lt' ... and they all end up '='
2) Why is the data mangled to `04:00:00.000`. I am in the 04 Timezone

* I am working against cockroachDB.
* The column datatype is TIMESTAMPTZ
* my versions are:  
```
    "sequelize": "^4.43.1",
    "sequelize-typescript": "^0.6.7",
    "sequelize-cockroachdb": "^1.0.3"
```
My Model:  
```
@Table(tableOptions)
export class Integration extends Model<Integration>  {
        ...
	@Column({type: DataType.JSONB})
	public transformExpression: ObjectExpression;

	@CreatedAt
	public createdAt: Date;

	@UpdatedAt
	public updatedAt: Date;
```

I also notice the resulting SQL does not work when trying to execute in DBeaver.  I have to reformat the  timestamps into standard UTC format.  Also, why does it add deletedAt > now() - deleted in the future?
```
SELECT "id", "name", "updatedBy", "createdAt", "updatedAt", "deletedAt" FROM "integration" AS "Integration" WHERE (("Integration"."deletedAt" > '2019-04-02 20:43:37.594 +00:00' OR "Integration"."deletedAt" IS NULL) AND "Integration"."updatedAt" = '2019-04-02 04:00:00.000 +00:00');
```

I'm probably doing something wrong.  Any advice would be appreciated.

**Comment by mkaufmaner** [comment]
Have you tried to set the pg type?

```js
// timestamp without timezone
pg.types.setTypeParser(1114, (value) => {
  return moment(value).format('YYYY-MM-DDTHH:mm:ss.SSS');
});
```

**Comment by mattwerthva** [comment]
It turns out the problem was that I initialized sequelize with `operatorsAliases: false` which made it note understand `$gt`.  Setting `operatorsAliases: true` solved my problem.  BTW, please dont deprecate the string operators because we use those to pass where clauses as json.
