### ISSUE TITLE
Auto generated association functions - like '$add' - not working

### ISSUE THREAD

**Issue by edxds** [RobinBuschmann/sequelize-typescript#596]
After defining models and associations like so:
```typescript
// Player.ts
@Table({ timestamps: false })
export default class Player extends Model<Player> {
  @Column
  public name!: string;

  @Column
  public num!: number;

  @ForeignKey(() => Team)
  @Column
  public teamId!: number;

  @BelongsTo(() => Team)
  public team!: Team;
}

// Team.ts
@Table({ timestamps: false })
export default class Team extends Model<Team> {
  @Column
  public name!: string;

  @HasMany(() => Player)
  public players!: Player[];
}
```
I expected to be able to create a new Player and associate it to a existing Team like this:
```typescript
// server.ts
app.post('/player', async (req, res) => {
  const json = req.body;
  const team = await Team.findOne({
    where: { name: json.team },
  });

  const player = new Player({
    name: json.name,
    num: json.num,
  });

  await team.$add('player', player.id);
  await player.save();

  res.send(player);
});
```
but instead, teamId on Player isn't set to the Team ID and the association is not created. Instead, I have to set the Team ID manually:
```typescript
/* ... */

const json = req.body;
const team = await Team.findOne({
  where: { name: json.team },
});

const player = new Player({
  name: json.name,
  num: json.num,
  teamId: team.id,
});

/* ... */
```
Perhaps I'm doing something wrong? Or did I misunderstand the [docs](https://github.com/RobinBuschmann/sequelize-typescript#type-safe-usage-of-auto-generated-functions)?

**Comment by RobinBuschmann** [comment]
Hey @edxds, please try `await team.$add('player', player);`. At the time when you're adding the player to the team, ID of player isn't defined. Hope this helps!

**Comment by edxds** [comment]
Hi, so I really don't know why I used .id there (?), but I tried removing it and it still gave me undefined.

It does make sense, since creating a model instance with `new` doesn't give it an id since it doesn't have access to the database yet. So, saving it, assigning it to a team, and then saving it works. 

But when FKs have a non-null constraint, I'm not able to save a instance without the FK set. So, my only option is still creating the instance with the FK field set, right?

**Comment by RobinBuschmann** [comment]
@edxds You're right, you have to save the player before adding him to the team. If you want to achieve creating and adding at once, you can use `$create` instead of `$add` like so:
```ts
team.$create('player', {
    name: json.name,
    num: json.num,
});
```
(Please note, that a pure object is passed and not the player instance)

Hope this helps!

**Comment by edxds** [comment]
Okay, thanks @RobinBuschmann for taking your time to clarify this!

**Comment by FauziFadhi** [comment]
where am i wrong about this $create ?

// company
@Column({ allowNull: false, type: DataType.STRING(50) })
  name: string

  @CreatedAt
  @Column({ field: 'created_at' })
  createdAt: Date

  @UpdatedAt
  @Column({ field: 'updated_at' })
  updatedAt: Date

  @Column({ field: 'is_deleted', defaultValue: 'f', type: DataType.BOOLEAN })
  isDeleted: boolean

  @HasMany(() => CompanySettings)
  settings: CompanySettings[]

// company settings

 @ForeignKey(() => Company)
  @Column
  idCompany: number

  @BelongsTo(() => Company)
  company: Company

  @Column({ type: DataType.ENUM('default', 'alwaysApprove', 'alwaysAsking') })
  defaultBookingApproval: defaultBookingOptions

  @Column({ type: DataType.SMALLINT })
  budgetPeriod: number

  @Column({ type: DataType.CHAR(2) })
  startDate: string

  @CreatedAt
  @Column
  createdAt: Date

  @UpdatedAt
  @Column
  updatedAt: Date

  @Column({ defaultValue: 'f', type: DataType.BOOLEAN })
  isDeleted: boolean


// controller
const companies = await Company.findOne()

    await companies.$create('settings', {
      startDate: '22',
    })



Always error 
this[("create" + string_1.capitalize(...))] is not a function

tell me if need anything else

**Comment by FauziFadhi** [comment]
`sads`

**Comment by FauziFadhi** [comment]
where am i wrong about this $create mr. @RobinBuschmann ?

`// company
@column({ allowNull: false, type: DataType.STRING(50) })
name: string

@CreatedAt
@column({ field: 'created_at' })
createdAt: Date

@UpdatedAt
@column({ field: 'updated_at' })
updatedAt: Date

@column({ field: 'is_deleted', defaultValue: 'f', type: DataType.BOOLEAN })
isDeleted: boolean

@hasmany(() => CompanySettings)
settings: CompanySettings[]`

`// company settings
`
@foreignkey(() => Company)
@column
idCompany: number

@BelongsTo(() => Company)
company: Company

@column({ type: DataType.ENUM('default', 'alwaysApprove', 'alwaysAsking') })
defaultBookingApproval: defaultBookingOptions

@column({ type: DataType.SMALLINT })
budgetPeriod: number

@column({ type: DataType.CHAR(2) })
startDate: string

@CreatedAt
@column
createdAt: Date

@UpdatedAt
@column
updatedAt: Date

@column({ defaultValue: 'f', type: DataType.BOOLEAN })
isDeleted: boolean`
`

`// controller
const companies = await Company.findOne()

await companies.$create('settings', {
startDate: '22',
})`

always error
`this[("create" + string_1.capitalize(...))] is not a function`

tell me if need anything else, thank you
