### ISSUE TITLE
Model findOne returns object instead of model instance

### ISSUE THREAD

**Issue by hlohrenz** [RobinBuschmann/sequelize-typescript#598]
**Versions**

- sequelize: 5.3.0
- sequelize-typescript: canary
- typescript

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

So I define a model based on how it's listed in the docs. This worked when I was on Sequelize 4.* and Sequelize-Typescript 0.6.7, but now it's not working when I upgrade to canary and sequelize5. When I run a `findOne` query, it returns a Promise.. I use to cast it to an observable, but now it's just returning a `{}`, not the instance of the Model I'm running the query on.

**Expected behavior:**

Returns model type, not a general javascript object.

**Steps to reproduce:**

```js
import { Column, CreatedAt, Model, Table, UpdatedAt } from 'sequelize-typescript';
import { User } from '../user.model';
import { ApiModelProperty, ApiModelPropertyOptional } from '@nestjs/swagger';
import moment = require('moment');

@Table({
  timestamps: true,
  tableName: 'user_tokens'
})
export class UserToken extends Model<UserToken> {

  /**
   * SCHEMA
   */
  @ApiModelProperty()
  @Column({
    unique: {
      name: 'User',
      msg: 'User already has a token.'
    },
    primaryKey: true
  })
  user_id: number;

  @Column({
    unique: {
      name: 'Token',
      msg: 'This token is not unique.'
    },
    allowNull: false
  })
  token: string;

  @ApiModelPropertyOptional({
    type: String,
    format: 'date-time'
  })
  @CreatedAt
  created_at?: Date;

  @ApiModelPropertyOptional({
    type: String,
    format: 'date-time'
  })
  @UpdatedAt
  updated_at?: Date;

  @ApiModelPropertyOptional({
    type: String,
    format: 'date-time'
  })
  @Column({
    type: 'TIMESTAMP WITHOUT TIME ZONE',
    get () {
      const timestamp = this.getDataValue('expires_at');
      if (timestamp) {
        return moment(timestamp).format('YYYY-MM-DD HH:mm:ss ZZ');
      }
      return timestamp;
    }
  })
  expires_at?: Date;

}
```

Then I run my query like so:

```js
/**
 * Get resource by id.
 *
 * @param {number} id
 * @returns {Observable<UserToken>}
 */
getTokenByUser(id: number): Observable<UserToken> {
  return from(UserToken.findOne({
    attributes: ['user_id', 'token', 'expires_at'],
    where: {
      user_id: id
    }
  }));
}
```

I get an error 

> Type 'Observable<{}>' is not assignable to type Observable< UserToken >

_I had to put spaces since Github was removing the UserToken class name inside the brackets._
This use to work on the older versions just fine.. not sure what would have changed under the hood. I tried to dig into the code and can't find anything that would have made this break.

**Comment by RobinBuschmann** [comment]
Hey @hlohrenz, have you installed `@types/bluebird` as documented [here](http://docs.sequelizejs.com/manual/typescript.html)?

**Comment by hlohrenz** [comment]
@RobinBuschmann I just installed that package and restarted the server and I still get the same error when I try run `npm run start:dev`. :(

**Comment by RobinBuschmann** [comment]
I also mentioned `@types/bluebird` explicitly in the `1.0.0` docs now.
