### ISSUE TITLE
Add @IsNot

### ISSUE THREAD

**Issue by SMAH1** [RobinBuschmann/sequelize-typescript#60]
I use below validation in sequelize
`validate: { len: [1, 128], notEmpty: true, not: ["^ *$",'i'] }`
But in sequelize-typescript not support `not` in validation
Please add `@IsNot` for this purpose

**Comment by RobinBuschmann** [comment]
You cold set it via @Column({validate:{not:[...]}) or use @Is annotation .

But yeah, I think this could be added with something like @IsNot.

**Comment by RobinBuschmann** [comment]
@SMAH1 While looking at my code, I've noticed, that this is already implemented. `@Not` is the annotation you are looking for :)
