### ISSUE TITLE
resolveModelGetter strips Literal attribute of type

### ISSUE THREAD

**Issue by PatrickGeyer** [RobinBuschmann/sequelize-typescript#603]
**Versions**

- sequelize: 5.6.1
- sequelize-typescript: 1.0.0-alpha.9 
- typescript: 3.4.3

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

When I define a Default (or other) scope, the options get passed through ```resolveScope``` which in turn calls model-service.js ```resolveModelGetter``` function.

This resolve model getter function strips attributes defined as follows:
```
@DefaultScope({
    attributes: {
         include: [[Sequelize.literal('"test"'), 'exampleAttr']]
    }
})
```

And converts the type of the literal to a plain object, which causes the core sequelize package not to be able to generate the query correctly as it checks for ```attr instanceof Utils.Literal``` which returns false if comparing to plain object.
**Expected behavior:**

The sequelize Util.Literal type should be preserved.

**Comment by PatrickGeyer** [comment]
```
           if (maybeModelGetter(value)) {
                const maybeModel = value();
                if (isModel(maybeModel)) {
                    acc[key] = maybeModel;
                }
            }
            else if (value instanceof Utils.SequelizeMethod) { <--- Add this check
                acc[key] = value;
            }
            else if (isOptionObjectOrArray(value)) {
                acc[key] = resolveModelGetter(value);
            }
```

I added another else statement to the resolveModelGetter function as seen above and that seems to solve the issue for me.

**Comment by Chocobozzz** [comment]
Maybe that instead we could use the [deepCopy function](https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/utils/object.ts#L10), that could accept a transform parameter to change `() => Model` to `Model`. Adding the @PatrickGeyer might work, but I'm afraid it's less robust (what if we could have a Model inside a SequelizeMethod etc).

**Comment by RobinBuschmann** [comment]
@PatrickGeyer Thanks for bringing this up. I thought about to fix this by just using lambda's instead of objects (and omitting the deep assignment) This would also overcome to always write `() => Model` within the `include`:
So instead of
```ts
@DefaultScope({
  attributes: {...}
})
```
```ts
@DefaultScope(() => ({
  attributes: {...}
}))
```
@PatrickGeyer  @Chocobozzz Any thoughts about this? :)

**Comment by Chocobozzz** [comment]
@RobinBuschmann IMHO it's a good idea to forbid the first case: it will avoid confusion between `() => Model` and `Model` depending if we are in a function or not. And I think it will be more efficient than using a `deepClone`/`reduce`

**Comment by RobinBuschmann** [comment]
@PatrickGeyer 🤔Hmm, not fully initialized at this time. But we could do this: 
```ts
@DefaultScope(sequelize => ({ // <--
    attributes: [[
    Sequelize.literal(sequelize.getQueryInterface().selectQuery({...})),
    'someAttribute'
]]
}))
```

**Comment by PatrickGeyer** [comment]
If that looks reasonable to you, it could be useful. Although if there are other ways of getting to the sequelize object without passing it as a parameter to the scope function, it would probably be cleaner.
In any case, I would support making DefaultScope a function.

**Comment by RobinBuschmann** [comment]
@PatrickGeyer Can you explain why another way would be cleaner in your opinion?

I think passing it as a parameter is the cleanest solution, because it decouples the sequelize instance from the model definition. Importing the initialized sequelize instance and using it within the model definition makes the model definition again dependent on the sequelize instance. (Here I'm also thinking of the [repository mode](https://github.com/RobinBuschmann/sequelize-typescript/tree/1.0.0#repository-mode))

**Comment by PatrickGeyer** [comment]
@RobinBuschmann only because I am using my own query builder solution.
This is what I'm really doing:

```
@DefaultScope(() => {
  attributes: [[
    RelatedModel.scope('deleted').getQuery({attributes: [Sequelize.literal('COUNT(*)')]}),
    'deletedCount'
  ]]
})
```

Where the getQuery function is a static function added to my BaseModel class.
It looks like this:

```
static getQuery(params: FindOptions = {}): CustomLiteral {
        return new CustomLiteral('(' + (this.sequelize.getQueryInterface().QueryGenerator as any)
            .selectQuery(this.name, params, this).slice(0, -1) + ')');
}
```

I wouldn't want to have to pass the sequelize object to my query builder function every time.

**Comment by RobinBuschmann** [comment]
Ah ok, I see. Then I can assure you, that `RelatedModel` is initialized with a sequelize instance at the time the scopes are resolved. So the `() => ({...})` solution should work. 

The only thing that worries me is the `RelatedModel.scope('deleted')`-Part. Because the scopes get resolved in the order the model class references are passed in (`new Sequelize({models: [MyModel, RelatedModel]})`) or however the paths of your models get resolved when using globs or model paths. Which means that the scopes for `RelatedModel` need to be added before `RelatedModel.scope('deleted')` is called - But this is nothing sequelize-typescript can assure. At least I see no way to do so.

**Comment by PatrickGeyer** [comment]
@RobinBuschmann Great, that's all I needed.

No worries about the ```RelatedModel.scope()``` part, I'm actually doing something like this: 

```
RelatedModel.getQuery(RelatedModel.scopes.deleted())
```
as I also define the scope functions of each model as a static member of their class

**Comment by RobinBuschmann** [comment]
Fix is released `sequelize-typescript@1.0.0-beta.2`

**Comment by Chocobozzz** [comment]
Thanks @RobinBuschmann, it works like a charm.

**Comment by PatrickGeyer** [comment]
@RobinBuschmann thanks a lot!

Do you know if it's possible to add function scopes that are asynchronous with sequelize?
Reason I ask is because if I call ```Model.findAll(options)``` it runs a cleanup on options, but when I access the behind-the-scenes function ```getQueryInterface().selectQuery(options)```, the cleanup on the options doesn't run.
The solution for this is that I can create a hook on ```beforeFindAfterOptions``` and call findAll with my initial options. The hook will then have the cleaned options as a parameter and I can cancel the database query. However, the hook makes the function async so if I want to use the query builder in a scope, the scope has to be async as well.
e.g. see below:

```
    static async getQuery(params: FindOptions = {}): Promise<CustomLiteral> {

        const getFixedOptions = (options: any): Promise<string> => {
            const id = uuid().substr(0, 8);
            options.trackingid = id;
            return new Promise((resolve) => {
                // tslint:disable-next-line:no-shadowed-variable
                this.addHook('beforeFindAfterOptions', id, (options): any => {
                    if (options.trackingid === id) {
                        this.removeHook('beforeFindAfterOptions', id);
                        resolve(options);
                        return new Promise(() => { });
                    }
                });
                return this.findAll(options);
            });
        };

        return new CustomLiteral('(' + (this.sequelize.getQueryInterface().QueryGenerator as any)
            .selectQuery(this.name, await getFixedOptions(params), this).slice(0, -1) + ')');
    }
```

I guess this is an issue for the core sequelize library but maybe you have an opinion on this?

**Comment by RobinBuschmann** [comment]
Hey @PatrickGeyer, yeah, it is an issue for sequelize. I checked the seuqlize code: as you can see [here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1552) and [here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1558) sequelize cannot handle async scope functions at the moment, it just expects a pure object there.
