### ISSUE TITLE
$set returns Promise<unknown>

### ISSUE THREAD

**Issue by c8r821** [RobinBuschmann/sequelize-typescript#604]
**Versions**
- sequelize: 5.6.1
- sequelize-typescript: 1.0.0-beta.1
- typescript 3.4.3

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Actual behavior:**
The $set method on a model returns a promise of type unknown.

**Expected behavior:**
According to sequelize's included types this method should return a promise of type ``

**Steps to reproduce:**
Just peek into [the model.ts file](https://github.com/RobinBuschmann/sequelize-typescript/blob/1.0.0/src/model/model/model.ts#L48) and also into [sequelize's types](https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L2477)

**Comment by RobinBuschmann** [comment]
Hey @c8r821, this is intentionally set to `unknown`. First, [`$set`](https://github.com/RobinBuschmann/sequelize-typescript/blob/1.0.0/src/model/model/model.ts#L48) and [`set`](https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L2477) doesn't have the same purpose. `$set` is explicitly used for setting relational data (see [this](https://github.com/RobinBuschmann/sequelize-typescript/tree/1.0.0#type-safe-usage-of-auto-generated-functions)). Additionally I wasn't able to narrow down a specific type - Which means for one-to-one sequelize resolves with this type, for one-to-many with another and sometimes under specific circumstances with some unexpected type. What do you think? Have I overseen something? Thanks for your help

**Comment by c8r821** [comment]
Okay, I understand. Is the recommended way of dealing with this just to `as MyType` the result then?

Sorry for the misunderstanding!

**Comment by RobinBuschmann** [comment]
@c8r821 Yes, if you're sure with the type, just cast it like you mentioned :)
