### ISSUE TITLE
$get should accept same arguments as sequelize does

### ISSUE THREAD

**Issue by hlohrenz** [RobinBuschmann/sequelize-typescript#606]
**Versions**

- sequelize: 5.3.0
- sequelize-typescript: ^1.0.0-alpha.9
- typescript: ^3.0.1

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Actual behavior:**

Whenever I perform a `$get('relation', {})` on a model instance, it throws an error if I provide the `attributes` property since that second parameter only accepts `where`, `scope`, and `schema` property.

**Expected behavior:**

In Sequelize documentation, these are valid:

```ts
// ok, now they are saved... how do I get them later on?
project.getTasks().then(associatedTasks => {
  // associatedTasks is an array of tasks
})

// You can also pass filters to the getter method.
// They are equal to the options you can pass to a usual finder method.
project.getTasks({ where: 'id > 10' }).then(tasks => {
  // tasks with an id greater than 10 :)
})

// You can also only retrieve certain fields of a associated object.
project.getTasks({attributes: ['title']}).then(tasks => {
  // retrieve tasks with the attributes "title" and "id"
})
```
You can see it here: http://docs.sequelizejs.com/manual/associations.html#associating-objects

**Steps to reproduce:**

**Related code:**

I'm trying to perform something like this:

```ts
user.$get('roles', {
      attributes: {
        include: [[Sequelize.col('user_roles.is_primary'), 'is_primary'], [Sequelize.col('user_roles.expires_at'), 'expires_at']]
      }
    })).pipe(
      map((roles: Role[]) => {
        user.setDataValue('roles', roles);
        return user;
      })
```

And am getting an error since `attributes` is not accepted.

**Comment by hlohrenz** [comment]
This is happening for a lot of these methods. `$add` is another one. If you look at the documentation, you should be able to specify the `validate` option: http://docs.sequelizejs.com/class/lib/associations/belongs-to-many.js~BelongsToMany.html (scroll down to add())

**Comment by RobinBuschmann** [comment]
Hey @hlohrenz, for bringing this up. This should be already fixed with `sequelize-typescript@1.0.0-beta.1` (`sequelize-typescript@next`) - Can you confirm?

**Comment by hlohrenz** [comment]
```
src/api/auth/authority/authority.service.ts(56,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<User>'.
  Type '{}' is missing the following properties from type 'User': id, username, email, name, and 38 more.
src/api/auth/authority/authority.service.ts(57,7): error TS2322: Type '{ include: (string | Col)[][]; }' is not assignable to type 'FindAttributeOptions'.
  Property 'exclude' is missing in type '{ include: (string | Col)[][]; }' but required in type '{ exclude: string[]; include?: (string | [string | Literal | Fn, string])[]; }'.
```

That's the error I'm getting now when I have this as my query:
```ts
// user = Instance of user model
user.$get('roles', {
      attributes: {
        include: [[Sequelize.col('user_roles.is_primary'), 'is_primary'], [Sequelize.col('user_roles.expires_at'), 'expires_at']]
      }
    })
```

And I know it's because it doesn't accept `col` as a type for attributes. But when I call `getRoles()` with those arguments, it works with pure Sequelize (the latest version).

**Comment by RobinBuschmann** [comment]
OK, so your actual issue is solved. So since the other one is already reported with #568, I close this now
