### ISSUE TITLE
How to include 'set role role_write;' before running a query?

### ISSUE THREAD

**Issue by TidyIQ** [RobinBuschmann/sequelize-typescript#608]
- sequelize: 5.5.0
- sequelize-typescript: 1.0.0-beta.2
- typescript: 3.4.5

**I'm submitting a ...** 

[ ] bug report
[ ] feature request
[x] question

**Actual behavior:**
My database user was created with `noinherit` flag and no permissions on the database/table by default, so before running a query I need to run `set role role_write;` to add the user to the read/write role. If I don't do this I get an error message saying `permission denied for table foo` as the user will have no select, update, create or delete permissions available.

I know I could just change the user to inherit the role_write role, but is there any way to get sequelize-typescript to send `set role role_write;` instead?

**Comment by RobinBuschmann** [comment]
Hey @TidyIQ, unfortunately this is not related to sequelize-typescript and I assume not to sequelize as well. From my understanding sequelize isn't responsible for creating your database nor your database users. Can you ask your question on e.g. stackoverflow instead?
