### ISSUE TITLE
Create identical `attribute` in IncludeOptions and FindOptions

### ISSUE THREAD

**Issue by NitayRabi** [RobinBuschmann/sequelize-typescript#61]
In `findOptions` -  
`attributes: FindOptionsAttributesArray | { include?: FindOptionsAttributesArray, exclude?: Array<string> }`

In `IncludeOptions` (currently) - 
`attributes: string[]`

Tried creating a pull request but got 403.

**Comment by RobinBuschmann** [comment]
@NitayRabi Thanks for raising this issue. This will be in the next release.
