### ISSUE TITLE
Order Desc in @Scopes causes a type error

### ISSUE THREAD

**Issue by blankstar85** [RobinBuschmann/sequelize-typescript#610]
**Versions**

- sequelize: 5.8.1
- sequelize-typescript: 1.0.0-beta.2
- typescript: 3.4.5

**I'm submitting a ...** 

 [x] bug report
[ ] feature request

**Actual behavior:**

Types of property 'order' are incompatible.
      Type 'string[][]' is not assignable to type 'string | Fn | Col | Literal | OrderItem[] | undefined'.
        Type 'string[][]' is not assignable to type 'OrderItem[]'.
          Type 'string[]' is not assignable to type 'OrderItem'.
            Type 'string[]' is missing the following properties from type '[typeof Model, typeof Model, string, string]': 0, 1, 2, 3

**Expected behavior:**

Shouldn't have any type issue, It matches OrderItem[] and  is a [string, string] so [[string,string]] should be ok, it works outside of @Scopes. I'm not sure what i'm missing or how to solve this.

```ts
export type OrderItem =
  | string
  | Fn
  | Col
  | Literal
  | [string | Col | Fn | Literal, string]
  | [typeof Model | { model: typeof Model; as: string }, string, string]
  | [typeof Model, typeof Model, string, string];
export type Order = string | Fn | Col | Literal | OrderItem[];
```
**Steps to reproduce:**

```ts
@Scopes(() => ({
  test: {
    attributes: ['column'],
    include: [
      {
        model: model,
        where: {column: 0},
      },
    ],
    order: [['column', 'DESC']],
    where: {status: 1},
  },
}))
```

**Comment by RobinBuschmann** [comment]
@blankstar85 Thanks for reporting

**Comment by RobinBuschmann** [comment]
Fixes with `sequelize-typescript@1.0.0-beta.3`

**Comment by blankstar85** [comment]
Thanks!

**Comment by usujjualust** [comment]
![image](https://user-images.githubusercontent.com/110834519/206106715-c2a66bed-2316-4966-86bf-8c4027f83540.png)
 I m still getting this error running   "sequelize-typescript": "^2.1.5" .
