### ISSUE TITLE
Access to transaction using Sequelize

### ISSUE THREAD

**Issue by aminmc** [RobinBuschmann/sequelize-typescript#626]
**Versions**
- sequelize: 5.8.6
- sequelize-typescript: 0.6.11
- typescript3.4.5

Hello I'm trying to access the transaction function from Sequelize but I get the following exception:

TSError: ⨯ Unable to compile TypeScript:
test/model/Form.spec.ts(10,19): error TS2339: Property 'transaction' does not exist on type 'Sequelize'.

![Screenshot 2019-05-28 at 17 58 35](https://user-images.githubusercontent.com/290639/58496659-3c557880-8172-11e9-8235-4f1ae0dbcba9.png)

The following shows my set up.
```ts

import {Sequelize} from "sequelize-typescript";

const sequelize = new Sequelize({
    name: db,
    username: 'root',
    password: '',
});
sequelize.addModels([ModelA, ModelB);


```

Is there any additional dependencies I need to install?

Any help would be appreciated.

**Comment by RobinBuschmann** [comment]
@aminmc thanks for asking. sequelize@5 only works with sequelize-typescript@next. Hope this helps!

**Comment by aminmc** [comment]
Thank you for your quick reply! Will use the appropriate versions. Thanks
