### ISSUE TITLE
Dataloader does not work well with this library

### ISSUE THREAD

**Issue by kfrajtak** [RobinBuschmann/sequelize-typescript#637]
**Versions**
- sequelize: 5.3.1
- sequelize-typescript: 0.6.11
- typescript: 3.3.3333

**I'm submitting a ...** 
[X] bug report
[ ] feature request

**Actual behavior:**
When using this library in a project with GraphQL backend and [dataloader](https://github.com/mickhansen/dataloader-sequelize) the dataloader is not intercepting the static methods like `findByPK` etc. The dataloader library is properly shimming these static methods, however your library does not invoke those methods from the sequelize `Model` class, but from your `BaseClass` resulting in shimmed methods not being invoked and bypassing the dataloader.

The issue was original posted to dataloader and you can see the thread here https://github.com/mickhansen/dataloader-sequelize/issues/80#issuecomment-501246261.

I was able to fix this problem by direct modification of the compiled JS code.

[Here](https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/models/BaseModel.ts#L43) a `superFn` is invoked, which is the original function captured earlier. When I change the call to 
```
const fn = _target.__proto__[key] || superFn;
return fn.call.apply(fn, [this].concat(args));
```
the static method from the sequelize `Model` class is called (the one shimmed by dataloader library) and it works. 

I am not sure if this is the correct fix and maybe you'll come with different one.

**Expected behavior:**
I am expecting the dataloader to work and to either load objects from its cache or to batch the requests.

**Steps to reproduce:**
I have created a MVP that is available [here](https://github.com/kfrajtak/sequelize_dataloader_issue). Just modify the connection string to any database you have and change the model based on your data table.

Thanks for help,
Karel

**Comment by RobinBuschmann** [comment]
Closed due to https://github.com/RobinBuschmann/sequelize-typescript/issues/550#issuecomment-502228492
