### ISSUE TITLE
include inside include

### ISSUE THREAD

**Issue by fareshan** [RobinBuschmann/sequelize-typescript#640]
**Versions**
- sequelize: 5.8.9
- sequelize-typescript: 1.0.0-beta.3
- typescript: 3.3.3

**I'm submitting a ...** 
[ X ] bug report
[ ] feature request

Defining a scope with an "include" inside an "include" brings a typescript error:

```ts
@Scopes({
  full: {
    include: [
      {
        include: [() => QuantityAttributes],
      },
    ],
  },
})
```

error:
```
Type '{ include: { include: (() => typeof QuantityAttributes)[]; }[]; }' is not assignable to type 'Function | ScopeFindOptions | undefined'.
  Type '{ include: { include: (() => typeof QuantityAttributes)[]; }[]; }' is not assignable to type 'ScopeFindOptions'.
    Types of property 'include' are incompatible.
      Type '{ include: (() => typeof QuantityAttributes)[]; }[]' is not assignable to type 'ModelClassGetter[] | Association<Model<any, any>, Model<any, any>>[] | ScopeIncludeOptions[] | { all: true; } | undefined'.
        Type '{ include: (() => typeof QuantityAttributes)[]; }[]' is not assignable to type 'ModelClassGetter[]'.
          Type '{ include: (() => typeof QuantityAttributes)[]; }' is not assignable to type 'ModelClassGetter'.
            Object literal may only specify known properties, and 'include' does not exist in type 'ModelClassGetter'.ts(2322)
scope-table-options.d.ts(3, 5): The expected type comes from this index signature.
```

**Comment by fareshan** [comment]
I had this issue while trying to migrate from:
```
sequelize: 5.0.0-beta.12
sequelize-typescript: 0.6.9
typescript: 2.9.1
```
to:
```
sequelize: 5.8.9
sequelize-typescript: 1.0.0-beta.3
typescript: 3.3.3
```

**Comment by RobinBuschmann** [comment]
Hey @fareshan, passing objects to the `Scope` annotation is deprecated. Use an arrows function instead, like so:

```ts
@Scopes(() => ({ // <---
	full: {
		include: [{
			include: [Projects]
		}],
	},
}))
```

(Nevertheless there is a typings issue on sequelize-typescript side when using objects like you did. But since passing it like so is deprecated, it is very unlikely that this will be fixed. So use arrow functions :) )

Hope this helps!

**Comment by fareshan** [comment]
Thanks, my code contained 2 errors (or deprecated syntax). I had to:
1- use arrow function for scope
2- remove arrow function for include

This fixed my issue
Thanks @RobinBuschmann 
I close the issue

**Comment by TobiasWehrum** [comment]
@RobinBuschmann, could you add this to the Readme? It currently teaches the deprecated way of doing things, and I tripped over the same problem as described here.

**Comment by fareshan** [comment]
@TobiasWehrum It was already there. The issue is that you have to switch the 
[branch 1.0.0](https://github.com/RobinBuschmann/sequelize-typescript/tree/1.0.0) to read it

**Comment by TobiasWehrum** [comment]
I see. Then maybe a short note at the beginning of the master branch readme with a link to that branch? I don't think I would've found this anytime soon.
