### ISSUE TITLE
removeHook function does'nt work the way it should.

### ISSUE THREAD

**Issue by vinniimiranda** [RobinBuschmann/sequelize-typescript#643]
**Versions**

- sequelize: ^4.43.2",
- sequelize-typescript: "^0.6.10",
- typescript: ^3.4.5"

**I'm submitting a ...** 

[ x ] bug report
[ ] feature request

**Actual behavior:**
I'm having problems on testig my code because the external depencies that are executed in a Hook ('@AfterCreate'), in the testing file i am trying to removeHook, but it's not working, still getting the same error.

**Expected behavior:**
I don't need that the hook be executed on testing, so the removeHook function should work.

**Steps to reproduce:**
Create a  external depencie and execute some actions via hooks, and then avoid this when testing.

**Related code:**
The Action in the Hook: 

@AfterCreate
 public static async createKongConsumer(instance: Tenant) {
    const username = `tenant.${instance.slug}`;
    const consumer = await new Consumer(KongService.getInstance()).create({ username });

    instance.kongConsumerId = consumer.id;
    await instance.save();
  }

The test file: 
Tenant.removeHook('afterCreate', 'afterCreate');

**Comment by RobinBuschmann** [comment]
Hey @vinniimiranda, thanks for bringing this up. You need to give your hook a name, like so:
```ts
@AfterCreate({name: 'myHook'})
```
```ts
Tenant.removeHook('afterCreate', 'myHook');
```
It's also important to call `removeHook` after `Tenant` was added to the sequelize instance. For example:
```ts
const sequelize = new Sequelize({
   modelPaths: ['path/to/tenant']
});
// or sequelize.addModels([Tenant]);

Tenant.removeHook('afterCreate', 'myHook');
```

Hope this helps. Feel free to close this issue, if my answer solves your issue.

**Comment by vinniimiranda** [comment]
Thanks for the quick response.

I did the changes that you said, and it worked.

Thanks a lot Robin
