### ISSUE TITLE
Typescript JSONB datatype on a model?

### ISSUE THREAD

**Issue by hcabnettek** [RobinBuschmann/sequelize-typescript#644]
Trying to type a model. How can I use JSONB sequelize postgres type?

`Keep in mind sequelize-typescript does not provide typings for sequelize - these are seperate things. A lot of the types in sequelize-typescript augment, refer to, or extend what sequelize already has.`

`@Table({ modelName: "Userprefs", tableName: "userprefs" })
export default class UserPrefs extends Model<UserPrefs> {

  @PrimaryKey
  @Column({ field: "id", autoIncrement: true })
  id!: number;

  @Column({ field: "docid" })
  docId!: string;

  @CreatedAt
  @Column({ field: "created_on" })
  createdOn!: Date;

  @Column({ field: "prefs" })
  prefs!: DataTypes.JSONB;

}`

It doesn't like how I'm referring to JSONB. Can anyone help?

**Comment by oldmud0** [comment]
```typescript
@Column(DataType.JSONB)
prefs!: object;
```
Naturally, `prefs` might want to follow a certain structure rather than an arbitrary object (meaning, use a more specific type).

**Comment by hcabnettek** [comment]
@oldmud0 I am definitely interested in the underscored option. Where can I find more info?

**Comment by oldmud0** [comment]
See http://docs.sequelizejs.com/manual/models-definition.html#configuration:

```js

  // Will automatically set field option for all attributes to snake cased name.
  // Does not override attribute with field option already defined
  underscored: true,
```

**Comment by RobinBuschmann** [comment]
Closing this since it's solved

**Comment by hcabnettek** [comment]
Thanks!
