### ISSUE TITLE
getDataValue and setDataValue does not exist

### ISSUE THREAD

**Issue by fjodor-rybakov** [RobinBuschmann/sequelize-typescript#647]
**Versions**

- sequelize: 5.9.3
- sequelize-typescript: 1.0.0-beta.3
- @types/sequelize: 4.28.3
- typescript 3.5.2

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**
```
@Column({
    type: DataType.STRING,
    get(): number[] {
        return this.getDataValue("results").split(",") as number[];
    },
    set(val: number[]): void {
        this.setDataValue("results", val.join(","));
    },
})
public results: number[];
```
Typescript say
```
Property 'getDataValue' does not exist on type 'Partial<ModelAttributeColumnOptions>'.
Property 'setDataValue' does not exist on type 'Partial<ModelAttributeColumnOptions>'.
```

**Comment by RobinBuschmann** [comment]
Hey @fjodor-rybakov, when using get/set within `Column` you have to tell the compiler what `this` is. It can't be inferred here:
```ts
@Column({
    type: DataType.STRING,
    get(this: YourModel): number[] {
        return this.getDataValue("results").split(",") as number[];
    },
    set(this: YourModel, val: number[]): void {
        this.setDataValue("results", val.join(","));
    },
})
``` 

Or use get/set accessors instead:
```ts
@Column(DataType.STRING)
get results(): number[] {
  return this.getDataValue("results").split(",") as number[];
}
set results(value: number[]) {
  this.setDataValue("results", val.join(","));
}
```

Hope this helps!

**Comment by fjodor-rybakov** [comment]
> Hey @fjodor-rybakov, when using get/set within `Column` you have to tell the compiler what `this` is. It can't be inferred here:
> 
> ```ts
> @Column({
>     type: DataType.STRING,
>     get(this: YourModel): number[] {
>         return this.getDataValue("results").split(",") as number[];
>     },
>     set(this: YourModel, val: number[]): void {
>         this.setDataValue("results", val.join(","));
>     },
> })
> ```
> 
> Or use get/set accessors instead:
> 
> ```ts
> @Column(DataType.STRING)
> get results(): number[] {
>   return this.getDataValue("results").split(",") as number[];
> }
> set results(value: number[]) {
>   this.setDataValue("results", val.join(","));
> }
> ```
> 
> Hope this helps!

The first will work if the type for `this` is specified as `any`.
If specified 'MyModel' i get this error
` Argument of type '"results"' is not assignable to parameter of type '"user" | "where" | "isNewRecord" | "sequelize" | "ge
tDataValue" | "setDataValue" | "get" | "set" | "setAttributes" | "changed" | "previous" | "save" | "reload" | "validate" | ... 32 more ...`

If use second option i get throw 
`Property 'split' does not exist on type 'this["results"]'.`

Use `any` i think its bad idea

**Comment by RobinBuschmann** [comment]
Can you share a repo which reproduces the issue? For me it is working

**Comment by fjodor-rybakov** [comment]
> Can you share a repo which reproduces the issue? For me it is working

I create for you test repo with this issues https://github.com/fjodor-rybakov/sequelize-test

**Comment by fjodor-rybakov** [comment]
> Can you share a repo which reproduces the issue? For me it is working

I create for you two branches with fist and secode try

**Comment by RobinBuschmann** [comment]
@fjodor-rybakov Thanks for sharing. Seems to be an issue with the types. I don't know why they assume the same type for the dataValues and what the getters return and the setters get passed in. (You could open an issue for that on https://github.com/sequelize/sequelize) So for now you can only fix this by using `as any`:

```ts
(this.getDataValue("results") as any).split(",");
this.setDataValue("results", value.join(",") as any);
```

or you could use the JSON data type and store the number array as it is:
```ts
    @Column(DataType.JSON)
    results(): number[];
```

**Comment by fjodor-rybakov** [comment]
> @fjodor-rybakov Thanks for sharing. Seems to be an issue with the types. I don't know why they assume the same type for the dataValues and what the getters return and the setters get passed in. (You could open an issue for that on https://github.com/sequelize/sequelize) So for now you can only fix this by using `as any`:
> 
> ```ts
> (this.getDataValue("results") as any).split(",");
> this.setDataValue("results", value.join(",") as any);
> ```
> 
> or you could use the JSON data type and store the number array as it is:
> 
> ```ts
>     @Column(DataType.JSON)
>     results(): number[];
> ```

Oh, thanks! Use JSON type was better
