### ISSUE TITLE
There is no way to simultaneously pass both scope and foreignKey options to the @BelongsToMany decorator 

### ISSUE THREAD

**Issue by Plotist** [RobinBuschmann/sequelize-typescript#649]
**Versions**

- sequelize: ^5.8.6
- sequelize-typescript: ^0.6.10
- typescript: ^3.4.3

[x] bug report

**Actual behavior:**

In the `BelongsToMany.d.ts` we have two sets of arguments it can receive

```ts
export declare function BelongsToMany(associatedClassGetter: ModelClassGetter, through: ModelClassGetter | string, foreignKey?: string, otherKey?: string): Function;
export declare function BelongsToMany(associatedClassGetter: ModelClassGetter, options: IAssociationOptionsBelongsToMany): Function;
```
- In one of those we are able to pass `foreignKey` but `through` options can only receive `ModelClassGetter` (no way to pass `scope` like in `IThroughOptions`) 
- In the second one we can only send `IAssociationOptionsBelongsToMany` that receive `IThroughOptions` for `through` but won't be able to process `foreignKey`

**Expected behavior:**

Developer is able to set both `scope` and `foreignKey` for `BelongsToMany` association in order to implement polymorphic many to many associations

**Comment by Plotist** [comment]
@RobinBuschmann funniest thing - it works fine if I just add `foreignKey` to `IAssociationOptionsBelongsToMany` in `IAssociationOptionsBelongsToMany.d.ts` right in the source code like that: 

```ts
export interface IAssociationOptionsBelongsToMany extends AssociationOptionsManyToMany {
    through: ModelClassGetter | string | IThroughOptions;
    otherKey?: string | AssociationForeignKeyOptions;
    foreignKey?: string | AssociationForeignKeyOptions;
}
```

**Comment by RobinBuschmann** [comment]
Hey @Plotist, actually it should work, since `AssociationOptionsManyToMany` extends `AssociationOptions` which already provides the `foreignKey` option. See this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L1256

**Comment by Plotist** [comment]
@RobinBuschmann I've missed that. You right, it should work
But for some reason (for me) it does not (see my set of versions for `ts`, `sequelize-typescript` and `sequelize` above

```
Argument of type '{ through: { model: () => typeof UserFavorite; scope: { item_type: string; }; }; foreignKey: string; otherKey: string; }' is not assignable to parameter of type 'IAssociationOptionsBelongsToMany'.
  Object literal may only specify known properties, and 'foreignKey' does not exist in type 'IAssociationOptionsBelongsToMany'.
```

I'm not really good with either `sequelize` or `typescript` and I have no idea why it does not. Can you help out?

**Comment by Plotist** [comment]
@RobinBuschmann I'll add a little more detail. An actual code that it fails on:

```ts
    @BelongsToMany(() => User, {
        through: {
            model: () => UserFavorite,
            scope: { item_type: 'exercise' }
        },
        foreignKey: 'item_id',
        otherKey: 'user_id'
    })
```

**Comment by Plotist** [comment]
@RobinBuschmann just checking in. Can you provide assistance or should I close the issue and figure it out by myself?

**Comment by RobinBuschmann** [comment]
Hey @Plotist, completely overseen the versions of seq and seq-types you are using: sequelize version >= 5 only works with sequelize-typescript@next (1.0.0-beta.x)

Since version 5, sequelize provides its own typings.

**Comment by Plotist** [comment]
@RobinBuschmann thanks!
btw, I'm bumped up version and now see: 
Version: 
```
        "sequelize": "^5.10.2",
        "sequelize-typescript": "^1.0.0-beta.3",
```

Error:
```ts
node_modules/sequelize/types/lib/model.d.ts:64:3
    64   where?: WhereOptions;
         ~~~~~
    The expected type comes from property 'where' which is declared here on type 'NonNullFindOptions'
```

Not sure wether I should report it here on in `sequelize` (or should I report it at all)

**Comment by Plotist** [comment]
Anyway. This is not relevant since 
> \>= 5 only works with sequelize-typescript@next (1.0.0-beta.x)

Closing the issue

**Comment by Plotist** [comment]
@RobinBuschmann btw the issue above was totally my fault. 
It works as expected with ` "sequelize": "^5.10.2" ` and `"sequelize-typescript": "^1.0.0-beta.3"`

Thanks for the help!
