### ISSUE TITLE
How to make self relation

### ISSUE THREAD

**Issue by Chnapy** [RobinBuschmann/sequelize-typescript#65]
Hi
I want to make an association between 2 same objects, like this:

User.ts
```TypeScript
@Table
export default class User extends Model<User> {

    @PrimaryKey
    @AutoIncrement
    @Column(DataType.BIGINT)
    readonly id_user: number;

    //...

    @BelongsTo(() => User, 'id_top')
    top: User;
 
}
```

app.ts
```TypeScript
            const top = new User({
                username: "C2aaaa",
                email: "toto@aaa.com",
                //...
            });

            const user = new User({
                username: "Chnapy",
                email: "toto@aaa.com",
                //...
                top: top
            }, {include: [{model: Password}]});

            user.save()
```

I haven't any error, but the DB column `id_top` is set at `null` and the first user is not insert to the DB.
I tried to add `{model: User}` to the includes without success.
I switched to the 0.4.0-beta and tried to use the association options for the BelongsTo with setting `as` and use it in app.ts with `{model: User, as: 'top'}` but again without success.

Thanks for any help.

**Comment by RobinBuschmann** [comment]
Hey @Chnapy 

your best option to store both users at once is:

```typescript
    return User.create<User>({
      email: 'test',
      top: {email: 'test_top'}
    }, {include: [User]});
```
If you already have existing instances, you need to store them first, before adding any relations:

```typescript
    const top = new User({email: 'test_top_2'});
    const user = new User({email: 'test_2'});

    return Promise.all([top.save(), user.save()]).then(() => user.$set('top', top));
```

**Comment by Chnapy** [comment]
It works perfectly, thanks (again) !
