### ISSUE TITLE
Dynamic Table Name

### ISSUE THREAD

**Issue by ermamud** [RobinBuschmann/sequelize-typescript#651]
**I'm submitting a ...** 

[  ] bug report
[?] feature request
[X] question

Hi, 

I have a client that has an old system with a rotatory table system (for using a name) on MySQL. So, a new table is being created every month with the same name and the month-year as the suffix. All tables have the same schema and fields since we need to do a `UNION ALL` between several tables for building reports.

Is there a way to achieve this behavior using `sequelize-typescript`? 
Can we set a `tableName` for a model on runtime? 
Can we create multiple instances of the same models each one with a different table name?

Thank you,
Ernesto

**Comment by RobinBuschmann** [comment]
@ermamud Do I understand you correctly, that you still need access to the old tables via sequelize? Or is it enough to re-initalize sequelize with the new tables?

**Comment by ermamud** [comment]
Yes @RobinBuschmann, I need to access all the old tables plus the new ones that are being created dynamically.

**Comment by RobinBuschmann** [comment]
Does this example help somehow? (For details on whats going on there see this [comment](https://github.com/RobinBuschmann/sequelize-typescript/issues/487#issuecomment-442996094))
```ts
export type MixinType<T> = T extends new(...args: any[]) => infer R ? R : any;
export type Constructor<T = {}> = new (...args: any[]) => T;

export const cloneWithSuffix = <TBase extends Constructor>(Base: TBase, suffix: string) => {
  const modelOptions = getOptions(Base.prototype) as ModelOptions;
  @Table({
    ...modelOptions,
    tableName: modelOptions.tableName + suffix
  })
  class WithSuffix extends Base {}
  return WithSuffix;
};

export const Actor20200101 = cloneWithSuffix(Actor, '_2020-01-01');
export type Actor20200101 = MixinType<typeof Actor20200101>;

sequelize.addModels([Actor20200101]);
```

**Comment by RobinBuschmann** [comment]
@ermamud Did my answer help in any way?

**Comment by lehno** [comment]
@RobinBuschmann  your answer is perfect, how can I return a custom class name, like replace WithSuffix with Actor20200101?

**Comment by lehno** [comment]
I was able to do it using the modelName property

**Comment by shaderzz** [comment]
> I was able to do it using the modelName property
@lehno 
Could you please show your working example? Because I faced the same problem

**Comment by lehno** [comment]
@shaderzz 

```
const cloneWithPrefix = <TBase extends Constructor>(Base: TBase, prefix: string) => {
  const modelOptions = getOptions(Base.prototype) as ModelOptions;

  @Table({
    ...modelOptions,
    tableName: prefix + '_' + modelOptions.tableName,
    modelName: prefix + '_' + modelOptions.tableName,
  })
  class WithPrefix extends Base {
  }

  return WithPrefix;
};
```
---

```
const tablePrefixes = ['test', 'demo'];

export const getTables = function() {
  const tables = [];
  tablePrefixes.forEach(item => {
    const f = cloneWithPrefix(Facility, item);
    const v = cloneWithPrefix(Visit, item);
    tables.push(f, v);
  });
  return tables;
};

```
---

```
import {
  Column,
  CreatedAt,
  Model,
  Table,
  UpdatedAt,
} from 'sequelize-typescript';

@Table({
  tableName: 'facilities',
})
export class Facility extends Model<Facility> {

  @Column
  facility_identifier: string;

  @Column
  identifier_type: string;

  @Column
  external_facility_id: number;

  @CreatedAt
  created_at: Date;

  @UpdatedAt
  updated_at: Date;
}
```

**Comment by barzfen** [comment]
Not sure if this is the correct way but it works.
(I'm just a newbie coder, but it might help someone, or someone might find unforeseen errors in doing it this way)

first I created a function to create a dynamic table:
createSongBookTable.js
```

const Sequelize = require("sequelize");
const sequelize = require("./database");

//const user = sequelize.define('user');

function createSongBookTable(tablename) {
  const dbGeneratedSongbook = sequelize.define(
    tablename,
    {
      id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true,
      },
      songName: {
        type: Sequelize.STRING,
        allowNull: false,
      },
      artistName: {
        type: Sequelize.STRING,
        allowNull: false,
      },
      siglosId: {
        type: Sequelize.STRING,
        allowNull: false,
      },
    },
    { timestamps: false }
  );

  dbGeneratedSongbook.sync();
}

module.exports = createSongBookTable;
```

I also create a function to reference the dynamic table. It is very similar but doesn't use sync, as I don't want to create it if it doesn't exist. It returns the object which we can use.

referenceSongBookTable.js

```
const Sequelize = require("sequelize");
const sequelize = require("./database");

//const user = sequelize.define('user');

function referenceSongBookTable(tablename) {
  const dbGeneratedSongbook = sequelize.define(
    tablename,
    {
      id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true,
      },
      songName: {
        type: Sequelize.STRING,
        allowNull: false,
      },
      artistName: {
        type: Sequelize.STRING,
        allowNull: false,
      },
      siglosId: {
        type: Sequelize.STRING,
        allowNull: false,
      },
    },
    { timestamps: false }
  );

  return dbGeneratedSongbook;
}

module.exports = referenceSongBookTable;


```

later in my graphql resolver, I can reference the table:

code snippet: (not complete code)

```

 songBookTest: {
      type: new GraphQLList(SongType),
      args: {
        SongBook: { type: GraphQLString },
      },
      resolve: async function (parent, args) {
        mysongbook = referenceSongBookTable(args.SongBook);
        console.log(mysongbook);
        const pleasework = await mysongbook.findAll();

        return pleasework;
      },
    },
```

**Comment by Zzombiee2361** [comment]
> Does this example help somehow? (For details on whats going on there see this [comment](https://github.com/RobinBuschmann/sequelize-typescript/issues/487#issuecomment-442996094))
> 
> ```ts
> export type MixinType<T> = T extends new(...args: any[]) => infer R ? R : any;
> export type Constructor<T = {}> = new (...args: any[]) => T;
> 
> export const cloneWithSuffix = <TBase extends Constructor>(Base: TBase, suffix: string) => {
>   const modelOptions = getOptions(Base.prototype) as ModelOptions;
>   @Table({
>     ...modelOptions,
>     tableName: modelOptions.tableName + suffix
>   })
>   class WithSuffix extends Base {}
>   return WithSuffix;
> };
> 
> export const Actor20200101 = cloneWithSuffix(Actor, '_2020-01-01');
> export type Actor20200101 = MixinType<typeof Actor20200101>;
> 
> sequelize.addModels([Actor20200101]);
> ```

I'm using this code, it works flawlessly except the index. If you used `underscored` in your table, you need to use this custom decorator like so

```ts
function UnderscoredIndex<T extends Model>(target: T, key: string): void {
  annotateModelWithIndex(target, _.snakeCase(key));
}

@Table({
  underscored: true,
  tableName: 'some_table',
})
class SomeTable extends Model {
  @UnderscoredIndex
  @Column(DataType.STRING)
  declare someColumn: string;
}
```

But now I'm stuck on another issue, that the index name does not use suffix, it's generated as `some_table_some_column` no mater what. This cause a duplicate error on postgres when there's multiple suffixed table. Could someone suggest a way around this?
