### ISSUE TITLE
Sequelize v5.13.0 not supported

### ISSUE THREAD

**Issue by justinlottes** [RobinBuschmann/sequelize-typescript#662]
**Versions**

- sequelize: 5.13.0
- sequelize-typescript: 1.0.0-beta.3
- typescript: 3.5.3

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Actual behavior:**

Unable to build project.  See below for tsc output...

```
node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.d.ts:12:5 - error TS2416: Property 'model' in type 'Sequelize' is not assignable to the same property in base type 'Sequelize'.
  Type '(model: string | typeof Model) => typeof Model' is not assignable to type '(modelName: string) => ModelCtor<Model<any, any>>'.
    Type 'typeof Model' is not assignable to type 'ModelCtor<Model<any, any>>'.
      Type 'typeof Model' is not assignable to type 'new () => Model<any, any>'.
        Cannot assign an abstract constructor type to a non-abstract constructor type.

12     model(model: string | typeof Model): typeof Model;
```

**Expected behavior:**

I assume this should work.  The documentation says sequelize v5 is supported.  I have reverted back to sequelize v5.12.3 and all seems happy.

**Steps to reproduce:**

Upgrade to sequelize v5.13.0 and try to build.

**Comment by zeroFruit** [comment]
I had a same issue. in my case I used `sequelize-typescript@^1.0.0-beta.3`, `sequelize@5.10.2`. 

 I don't know exact cause but I fixed this issue by changing `sequelize@5.10.2` to `sequelize@5.1.0` as I noticed `sequelize-typescript@^1.0.0-beta.3` internally use `sequelize@5.1.0`. I know this is temporary solution and hope to fix this issue asap

**Comment by budhead2004** [comment]
@zeroFruit I tried your solution but when using mssql dialect and hitting any of my endpoints it kept throwing some error from the connection-manager.js:
`Unhandled rejection SequelizeConnectionError: Invalid arguments: "instanceName" must be a string`

However with `sequelize@5.13.0`,  `sequelize-typescript@1.0.0-beta.3`, and `ts-node-dev@1.0.0-pre.40` everything seems to function as intended. In my setup ts-node-dev ends up using ts-node version 8.3.0, typescript version 3.5.3 to server everything up.

**Comment by zeroFruit** [comment]
@budhead2004 
1. your code build successfully (ts -> js) ?
2. your mssql connection code runs with ts file?

**Comment by RobinBuschmann** [comment]
Hey @justinlottes, thanks for reporting. Just published a new beta version. (`sequelize-typescript@1.0.0-beta.4` or `sequelize-typescript@next`). Can you confirm that its working with this one?

**Comment by Chocobozzz** [comment]
It works on my side. Thanks @RobinBuschmann

**Comment by Floby** [comment]
Worked for me too.

**Comment by justinlottes** [comment]
Works for me.  Thanks!

**Comment by acconrad** [comment]
@RobinBuschmann I actually am having trouble getting this to work. I pulled the latest from `sequelize-typescript@next` and the thing is I can see in the code that `interfaces/*` should be exported via `index.ts` _but_ I'm not seeing it show up when I actually install the folder into my `node_modules`

![Screen Shot 2019-08-20 at 5 05 09 PM](https://user-images.githubusercontent.com/422184/63384527-0be63a80-c36d-11e9-9d22-9a3eb2ed3374.png)

Is it possible that not all folders (such as `interfaces`) are being properly exposed when you distribute the plugin?

**Comment by InadullaevMakhmudjon** [comment]
I have the same issue with sequelize latest version ^6.3.3 that is published 10 days ago, where it is fine with older verions[^5.22.3].

**Comment by 64J0** [comment]
All I have done to overlap this problem is to force the type of dialect to be the same of Dialect manually, like:

```typescript
import { Dialect, Sequelize } from "sequelize";

new Sequelize(
  ...some configs,
  {
    ...,
    dialect: 'mysql' as Dialect
  }
);
```

**Comment by vsouto** [comment]
Back to the future, it's now 2024 and I was having the same issue here.

In my case, I was using Model reference from 'sequelize' instead of 'sequelize-typescript'. 

![image](https://github.com/sequelize/sequelize-typescript/assets/2797129/9f19d490-3d88-43be-87a6-395de6d0864e)
