### ISSUE TITLE
Self Join with two types of relationships- Parent and Children

### ISSUE THREAD

**Issue by Madror7** [RobinBuschmann/sequelize-typescript#665]
**Versions**
- sequelize-typescript: 

**I'm submitting a ...** 
[X ] bug report

**Actual behavior:**

"Alias cannot be inferred: \"Entity\" has multiple relations with \"Entity\"", is the error I receive when I try to post to the database

**Expected behavior:**

I have a table Entity and a table EntitiesToEntities.  An Entity can have one parent and multiple children. I am trying to post to Entity but I get the above error. My code looks like: 

``` typescript
@Table({
    tableName: "Entity",
})

export default class Entity extends Model<Entity> {

    @Column(stringField)
    name: string;

    @NotNull
    @Column(enumField(EntityType))
    entityType: string;

    @CreatedAt
    createdAt: Date;

    @UpdatedAt
    updatedAt: Date;

    @BelongsToMany(() => Entity, () => EntitiesToEntities, 'parentId', 'childId')
    parent: Entity;
    
    @BelongsToMany(() => Entity, () => EntitiesToEntities, 'childId', 'parentId')
    children: Entity[];

    @HasMany(() => ContactInformation, {foreignKey: 'entityId'})
    contactInformation: ContactInformation[]

    @BeforeCreate
    static addCreationDate(instance: Entity) {
        instance.createdAt = new Date;
    }

    @BeforeUpdate
    static refreshUpdateDate(instance: Entity) {
        instance.updatedAt = new Date;
    }
}

```

How do I create this relationship?

**Comment by Madror7** [comment]
needed to add "as" in the include piece for each model. I was previously doing: 

``` typescript
        const newEntity = await new Entity(whiteListEntityInsertRequest(newEntityRequest), {include: [
                {model: ContactInformation}, 
                {model: Entity}
            ]}

```

needed to do: 

        const newEntity = await new Entity(whiteListEntityInsertRequest(newEntityRequest), {include: [
                {model: ContactInformation}, 
                {model: Entity,
                    as: 'parent',
                },
                {model: Entity,
                    as: 'children',
                }
            ]}

**Comment by richpoteto** [comment]
Cool
