### ISSUE TITLE
FindAll always returns `null` for @BelongsTo field

### ISSUE THREAD

**Issue by amites** [RobinBuschmann/sequelize-typescript#667]
Short version is that I'm unable to get a related model to populate with values

https://gist.github.com/amites/b16b24f864106121475e153c8b4d224a

The gist above duplicates the issue I'm seeing, can paste inline if helpful

With `logging: console.log` I can see that the query generated is pulling the related table data but not passing it back to the query result

assuming I'm doing something silly but been tinkering with it for a while without any progress

**Versions**
- sequelize: 5.15.2
- sequelize-typescript: 1.0.0-beta.4
- typescript: 3.5.3

**Comment by amites** [comment]
Possibly related, if I migrate from using a static initialization of `Sequelize`

from:
`export const sequelize = new Sequelize`

to:
`export function initSequelize(context) { return new Sequelize`

where context contains dynamically loaded values then I start getting some strange errors

example:
`User.findAll()`

```
Executing (default): SELECT `uid`, `name` FROM `users_example` AS `User` WHERE (`User`.`deleted_at` IS NULL);
2019-08-23 11:58:08.033 server:api:users:get (ERROR): Users.findAll: SequelizeDatabaseError: Unknown column 'User.deleted_at' in 'where clause'
```

If I comment out `deleted_at` column then it will run the query but return empty result set

```
Executing (default): SELECT `uid`, `name` FROM `users_example` AS `User`;
values:
	[]
```

If I run the query that appears in the logs (above) then it returns results as expected

Pretty new to sequelize but happy to help debug, just trying to figure out what a good entry point to start reading source code would be

**Comment by RobinBuschmann** [comment]
Hey @amites, sry for the late reply. I see 2 issues with your code.

1. 
```ts
    @ForeignKey(() => Branch)
    @Column({
        field: 'branch_uid',
    })
    branchUid: string;

    @BelongsTo(() => Branch, 'uid')
    branch: Branch;
```
`BelongsTo` and `HasMany` takes as a second argument the foreign key, not the primary key.
2. When using `ForeignKey` you don't need to specify the foreign key in the `BelongsTo` and `HasMany` annotations.

So the following should do the job:
```ts
class Base extends Model<Base> {
    // ...
    @ForeignKey(() => Branch)
    @Column({
        field: 'branch_uid',
    })
    branchUid: string;

    @BelongsTo(() => Branch)
    branch: Branch;
}
```
```ts
class Branch extends Model<Branch> {
    // ...
    @HasMany(() => Base)
    bases: Base[];
}
```
Hope this helps!

**Comment by amites** [comment]
Gracias, always a joy when it's the elusive obvious vs a real issue

At least once recognized, rather annoying when chasing it ;)
