### ISSUE TITLE
[feat] Add browser support back in

### ISSUE THREAD

**Issue by Toxicable** [RobinBuschmann/sequelize-typescript#668]
It would appear in the 1.0.0 merge the generate-browser.js script was skipped over.
This was the latest version: https://github.com/RobinBuschmann/sequelize-typescript/blob/a05f4fcaa619ab04455ca87a39dacbeb8447a2c1/generate-browser.js

Would be great to have browser support back in for 1.0.0

**Comment by RobinBuschmann** [comment]
Hey @Toxicable, thanks for bringing this up. In Version 1.0.0 the folder structure completely changed compared to 0.6.X. So that much more manual work is needed to bring this feature back alive.

Are you using real implementations (e.g. class functions) or just the types of models in your client? I'm asking because if the latter, maybe a mapped type would be a better solution?

**Comment by RobinBuschmann** [comment]
And sorry for the late reply

**Comment by Toxicable** [comment]
It's all good.
I came up with a far more simplified version here: https://github.com/RobinBuschmann/sequelize-typescript/pull/673

As for how we use them, we only use properties, we don't define any functions in out Models.
We actually go a bit further than athat and noop out all the Sequalize types on Model like this:

```
class NoopClass {}
const BaseModel: typeof NoopClass = Model as any;

@Table
export class Person extends BaseModel {
  @Colunm  
  name: string
}
```
This is so you don't get methods like `findById()`, which wont work in the browser.
Instead on the server we have a repository wrapped which use to access the DB

**Comment by RobinBuschmann** [comment]
I'm just wondering, that the bundler tries to bundle the models at all, since you only use them as types. Actually they should be omitted in general.

```ts
import {User} from './models/user';
import _ from 'lodash';

const user: User = _.assign({}, {...});
```
should become something like:
```js
var _ = require('lodash');

var user = _.assign({}, {...});
```

Nevertheless, I'm totally fine with your solution (#673). Thanks for implementing it!
