### ISSUE TITLE
Order by joined table

### ISSUE THREAD

**Issue by oscarcalvo** [RobinBuschmann/sequelize-typescript#67]
Hi, I have something like that

Restaurant.findOne<Restaurant>({
      where: { domain: domain },
      include: [
        { model: Promotion, where: { code: null } }
      ]
    });

and it generates:

SELECT "Restaurant".*, "promotions"."id" AS "promotions.id", "promotions"."type" AS "promotions.type", "promotions"."title" AS "promotions.title", "promotions"."description" AS "promotions.description", "promotions"."value" AS "promotions.value"
, "promotions"."value2" AS "promotions.value2", "promotions"."code" AS "promotions.code", "promotions"."isCompatible" AS "promotions.isCompatible", "promotions"."isActive" AS "promotions.isActive", "promotions"."maxDate" AS "promotions.maxDate", "promotions"."numberAllowedU
ses" AS "promotions.numberAllowedUses", "promotions"."currentUses" AS "promotions.currentUses", "promotions"."categoryIds" AS "promotions.categoryIds", "promotions"."itemIds" AS "promotions.itemIds", "promotions"."restaurantId" AS "promotions.restaurantId" FROM (SELECT "Res
taurant"."id", "Restaurant"."name", "Restaurant"."domain", "Restaurant"."address", "Restaurant"."shippingCosts", "Restaurant"."secondId", "Restaurant"."createdAt", "Restaurant"."updatedAt" FROM "Restaurant" AS "Restaurant" WHERE "Restaurant"."domain" = 'localhost' AND ( SEL
ECT "restaurantId" FROM "Promotion" AS "Promotion" WHERE ("Promotion"."restaurantId" = "Restaurant"."id" AND "Promotion"."code" IS NULL) LIMIT 1 ) IS NOT NULL LIMIT 1) AS "Restaurant" INNER JOIN "Promotion" AS "promotions" ON "Restaurant"."id" = "promotions"."restaurantId"
AND "promotions"."code" IS NULL;

My question is how can I order by for example promotion.currentUsers. I have tried several options like 

Restaurant.findOne<Restaurant>({
      where: { domain: domain },
      include: [
        { model: Promotion, where: { code: null } }
      ],
      order:["Promotion.currentUses"]
    });
and it says me "TypeError: Cannot read property 'type' of undefined"
or
     order:["promotions.currentUses"] :the same
or 
 order:["promotion.currentUses"] :the same
etc
if I do
   order:[{model:Promotion}] :Unable to find a valid association for model, 'Promotion'
or 
  order:[{model:Promotion, as:"promotions"}]: Unknown structure passed to order / group: promotions

so...how can I achieve this behavior please?

**Comment by RobinBuschmann** [comment]
Hey @oscarcalvo could yo try one of these approaches: http://docs.sequelizejs.com/manual/tutorial/querying.html#ordering

**Comment by oscarcalvo** [comment]
Thanks. I have tried those.
At the end it was my error because I wrote a simple query, my requeriments were different. 
I wrote just in case somebody is finding about order clause: you can put your nested models in the list and order by last one. for example if you have a main customer entity we can order by amount column of invoiceLines in this way
order: [["invoices","invoiceLines","amount","ASC"]]

**Comment by RobinBuschmann** [comment]
So, you finally got it working? :)

**Comment by oscarcalvo** [comment]
Yes, perfect. Thanks.
