### ISSUE TITLE
How to use initialAutoIncrement in sequelize-typescript

### ISSUE THREAD

**Issue by FujiBilly** [RobinBuschmann/sequelize-typescript#679]
**Versions**

- sequelize: 4.44.2
- sequelize-typescript: 0.6.11
- typescript: 3.3.3333

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Actual behavior:**

**Expected behavior:**

`sequelize-typescript` can initial start of the auto increment column

**Steps to reproduce:**

**Related code:**

such as the model with `sequelize` and `initialAutoIncrement`:
```js
return sequelize.define('bp_account', {
    account_id: {
      primaryKey: true,
      allowNull: false,
      type: DataTypes.INTEGER,
      autoIncrement: true,
      initialAutoIncrement: 100000,
      comment: '商家bp登录id'
    },
    ...
}
```

**Comment by RobinBuschmann** [comment]
Hey @FujiBilly, you can set the inital auto increment value in the table options like so:
```ts
@Table({
   initialAutoIncrement: '10000'
})
```

Hope this helps

**Comment by FujiBilly** [comment]
> Hey @FujiBilly, you can set the inital auto increment value in the table options like so:
> 
> ```ts
> @Table({
>    initialAutoIncrement: '10000'
> })
> ```
> 
> Hope this helps

**Comment by FujiBilly** [comment]
> > Hey @FujiBilly, you can set the inital auto increment value in the table options like so:
> > ```ts
> > @Table({
> >    initialAutoIncrement: '10000'
> > })
> > ```
> > 
> > 
> > Hope this helps

Hey @RobinBuschmann ,I try to use the table options, but it's useless
```
@Table({
   initialAutoIncrement: '10000'
})
```

**Comment by FujiBilly** [comment]
> **Versions**
> 
> * sequelize: 4.44.2
> * sequelize-typescript: 0.6.11
> * typescript: 3.3.3333
> 
> **I'm submitting a ...**
> 
> [ ] bug report
> [x] feature request
> 
> **Actual behavior:**
> 
> **Expected behavior:**
> 
> `sequelize-typescript` can initial start of the auto increment column
> 
> **Steps to reproduce:**
> 
> **Related code:**
> 
> such as the model with `sequelize` and `initialAutoIncrement`:
> 
> ```js
> return sequelize.define('bp_account', {
>     account_id: {
>       primaryKey: true,
>       allowNull: false,
>       type: DataTypes.INTEGER,
>       autoIncrement: true,
>       initialAutoIncrement: 100000,
>       comment: '商家bp登录id'
>     },
>     ...
> }
> ```

**Comment by RobinBuschmann** [comment]
Which dialect are you using, postgres? Just noticed that it doesn't work on postgres: https://github.com/sequelize/sequelize/issues/5954
https://sequelize.readthedocs.io/en/latest/api/sequelize/

**Comment by FujiBilly** [comment]
oh yes, thanks
