### ISSUE TITLE
Figuring out relations

### ISSUE THREAD

**Issue by lookfirst** [RobinBuschmann/sequelize-typescript#680]
Quite possibly this is my own stupidity of how to use sequelize, so I apologize in advance. That said, I'd expect some variation of what I'm doing to just work.

The good news is that I did make a point to make a sample project with a bunch of unit tests in my attempt to try to figure this out. Once we know how it works, it might be nice to add this as a working example so that others can benefit. I'll be happy to submit a PR for that.

**Versions**
```
    "sequelize": "^5.18.4",
    "sequelize-typescript": "^1.0.0",
    "typescript": "^3.6.3",
```

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Actual behavior:**

Mostly a lot of this...

```
SequelizeValidationError: notNull Violation: thing.createdById cannot be null
```

**Expected behavior:**
Insert happens correctly.

One thing I don't understand is in the sql output `thing.id` is missing from the insert:

`INSERT INTO `thing` (`createdById`,`updatedAt`,`createdAt`) VALUES ($1,$2,$3);`

**Steps to reproduce:**

Download and unzip this...

[relations.zip](https://github.com/RobinBuschmann/sequelize-typescript/files/3629559/relations.zip)

```
yarn
yarn test
```

**Comment by RobinBuschmann** [comment]
Since `Thing` depends on `Person`, you either have to create a `Thing` instance from a `Person` instance like so:
Precondition: Person need to have the relation setup as well:
```ts
class Person extends Model<Person> {
  @HasMany(() => Thing, 'createdById')
  things: Thing[];
}
```
```ts
// Assuming person is already stored and has a valid primary key
person.$create('thing', {});
```
...or you need to set the foreign key of Person instance to thing instance:
```ts
await new Thing({createdById: person.id}).save();
```

Hope this helps!

**Comment by lookfirst** [comment]
Great thanks! I'll close this as I've moved onto MikroORM v3. Cheers and thanks for the great response.
