### ISSUE TITLE
More useful possibility to define own method for model or instance

### ISSUE THREAD

**Issue by frct1** [RobinBuschmann/sequelize-typescript#684]
**Versions**

- sequelize: ^5.18.4
- sequelize-typescript: 0.6.11
- typescript3.4.3

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Actual behavior:**

Many options to create instance methods through a lot of hard to read code
**Expected behavior:**

Defining instance methods inside model definition with decorator or something like that
Creating own decorator from lib to define instance or model method like:

**Related code:**
```ts
@InstanceMethod
public doSomethingWithInstance(){}

@ModelMethod
public doSomethingWithModel(){}
```

**Comment by RobinBuschmann** [comment]
Hey @frct1, it's already possible to define model and instance methods easily. Just like in any normal class:

```ts
@Table 
class User extends Model<User> {
  instanceMethod() {}
  static modelMethod() {}
}
```

So no need for defining them in the table options like `@Table({instanceMethods: {}, model...})`

Does this resolve your issue?

**Comment by frct1** [comment]
Hello @RobinBuschmann 
WOOOOOOAH
Incredible
Got it, yes it solve the question
Awesome!
Thank you for answer
Looked for this for a week, maybe more :D

**Comment by frct1** [comment]
I think i can create PR for updating README.md about instance/model methods (currently in web a lot of creepy solutions. Actually i'm didn't test them, but look like)

If you don't mind it

**Comment by RobinBuschmann** [comment]
Thanks for asking, but it's already part of the sequelize documentation: https://sequelize.org/master/manual/models-definition.html#expansion-of-models.

**Comment by frct1** [comment]
![image](https://user-images.githubusercontent.com/25178244/66054416-9c06ca80-e53c-11e9-88d4-026d30bb918e.png)

Oh, it's become to be more sad
I missed it in official docs :(
