### ISSUE TITLE
Documentation/Support for Polymorphic Associations

### ISSUE THREAD

**Issue by connected-pjeri** [RobinBuschmann/sequelize-typescript#69]
As the title says. Not sure if it's supported in sequelize-typescript.
Eg: From the Sequelize docs: http://docs.sequelizejs.com/manual/tutorial/associations.html#1-m

**Comment by RobinBuschmann** [comment]
Hey @connected-pjeri. This should work with `sequelize-typescript@0.4.0-beta`. From `0.4.0-beta` you can define association options in the assocation annotations additonally:

For example:
```typescript
class Post extends Model<Post> {
  // ...
  @HasMany(() => Comment, {
    scope: {
      commentable: 'post'
    }
  })
  comments;
}
```
I hope this helps. Any feedback about whether you get it done or not is appreciated :)

**Comment by connected-pjeri** [comment]
Giving it a shot right now.
Trying to figure out why it says: `Error: Foreign key for "Post" is missing on "Comment".

**Comment by connected-pjeri** [comment]
Part of problem that I'm having is that I'm trying to achieve an **n:m polymorphic association** but without having a joint table.

In the Sequelize example they use Tag, Post and ItemTag as their example, but this is only necessary if you're storing additional info for Tags, eg: a tag name.

In my case I'm not looking to save an additional column so I should be allowed to collapse the ids and tables eg: 

**From**
`Subscription(id) -> ItemSubscription(id, sub_id, subscribable_type, subscribable_id) -> Source(id, content)`

**To**
`Subscription(id, subscribable_type, subscribable_id) -> Source(id, content)`

**Comment by RobinBuschmann** [comment]
Regarding:

> Giving it a shot right now.
> Trying to figure out why it says: Error: Foreign key for "Post" is missing on "Comment".

You need to tell `Post` which foreign key should be used for the relation to `Comment`:
```typescript
class Post extends Model<Post> {
  // ...
  @HasMany(() => Comment, {
    foreignKey: 'commentable_id',
    scope: {
      commentable: 'post'
    }
  })
  comments;
}
```

About your other problem: You want to achieve a n:m relation but your suggested solution looks like a 1:n relation to me. Probably I get something wrong?

**Comment by connected-pjeri** [comment]
> About your other problem: You want to achieve a n:m relation but your suggested solution looks like a > 1:n relation to me. Probably I get something wrong?
You're right, it is still an 1:n . I ended up deleting my comment after my head stopped spinning.

**Comment by RobinBuschmann** [comment]
Hey @connected-pjeri if you're happy with my answers, feel free to close this issue :)
