### ISSUE TITLE
Typescript compilation failing after I enabling `strict: true`

### ISSUE THREAD

**Issue by sudhagar10** [RobinBuschmann/sequelize-typescript#696]
**Versions**

- sequelize: 5.19.3
- sequelize-typescript: 1.0.0
- typescript: 3.6.3

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

**Actual behavior:**

Not sure if this belongs here, but after hours of looking for a solution, I don't know what else to do. 

The issue is after enabling "strict": true in tsconfig.json, compilation is failing with below logs.

**Logs**
`src/storage/models/changelog.ts:2:5 - error TS7022: '__decorate' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
      ~~~~~~~~~~
src/storage/models/changelog.ts:2:57 - error TS7006: Parameter 'decorators' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                          ~~~~~~~~~~
src/storage/models/changelog.ts:2:69 - error TS7006: Parameter 'target' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                                      ~~~~~~
src/storage/models/changelog.ts:2:77 - error TS7006: Parameter 'key' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                                              ~~~
src/storage/models/changelog.ts:2:82 - error TS7006: Parameter 'desc' implicitly has an 'any' type.

2 var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                                                                                   ~~~~
src/storage/models/changelog.ts:4:55 - error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.

4     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
                                                        ~~~~~~~~
src/storage/models/changelog.ts:4:92 - error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.

4     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
                                                                                             ~~~~~~~~
src/storage/models/changelog.ts:8:5 - error TS7022: '__metadata' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

8 var __metadata = (this && this.__metadata) || function (k, v) {
      ~~~~~~~~~~
src/storage/models/changelog.ts:8:57 - error TS7006: Parameter 'k' implicitly has an 'any' type.`

**Comment by sudhagar10** [comment]
Sorry my bad. This was due to recompilation.

In one of the files I am importing, there is this line `require('ts-node/register');` which was causing recompilation.

**Comment by iagoizi** [comment]
> Sorry my bad. This was due to recompilation.
> 
> In one of the files I am importing, there is this line `require('ts-node/register');` which was causing recompilation.

Oh, my gosh. I had the same issue (with another lib) and this was the reason. Thank you for enlightening me!
