### ISSUE TITLE
Bug: Scope with function is not added correctly

### ISSUE THREAD

**Issue by kingjerod** [RobinBuschmann/sequelize-typescript#70]
If you have a scope with a function like so:

    @Scopes({
      something: function (id) {
        return {
          where: {id: id}
        }
      }
    })

It doesn't get added properly to the Sequelize model. I was ready to open a PR to fix this, but I think it's beyond my knowledge of this module. The problem is in `resolveScope` in the lib/services/model file, it should check if the options is a function and if so, just add the scope. I'm not sure if there is something else that needs to be done to the function.

**Comment by RobinBuschmann** [comment]
@kingjerod Thanks for contributing. I've investigated this one and... yes, you're right, this is a bug.
