### ISSUE TITLE
sequelize with Sequelize.VIRTUAL,

### ISSUE THREAD

**Issue by DigiGroundJohn** [RobinBuschmann/sequelize-typescript#701]
Hi,

is there any way to achieve below in sequelize-typescript ?

const Pug = db.define('pugs', {
  firstName: {
    type: Sequelize.STRING,
  },
  lastName: {
    type: Sequelize.STRING
  },
  fullName: {
    type: Sequelize.VIRTUAL,
    get () {
      return this.getDataValue('firstName') + ' ' + this.getDataValue('lastName')
    }
  }
})

Thanks

**Comment by RobinBuschmann** [comment]
Sure:
```ts
import {Table, Column, Model, DataType} from 'sequelize-typescript';

@Table({tableName: 'plugs'})
class Pug extends Model<Pug> {
  @Column
  firstName: string;

  @Column
  lastName: string;

  @Column(DataType.VIRTUAL)
  get fullName() {
    return this.getDataValue('firstName') + ' ' + this.getDataValue('lastName');
  }
}
```

Hope this helps!

**Comment by DigiGroundJohn** [comment]
Thanks for the reply, 

But the getDataValue always returning undefined.

"myFullName": "undefined undefined",

**Comment by DigiGroundJohn** [comment]
Sorry got this, I was not selected firstName and lastName 

Thanks

**Comment by KirzhnerMark** [comment]
How do you set a virtual field with sequelize-typescript?
Here is my example:

`@Column(DataType.VIRTUAL(DataType.STRING))
get countryCode(): string | "" {
      const parcedPhoneNumber = parsePhoneNumberFromString(this.getDataValue("phoneNumber"));
      const countryCode =  parcedPhoneNumber.countryCallingCode;
      return countryCode
  }
set countryCode(value: string) {
        this.setDataValue("countryCode", value);
 }`

My getter works but the setter dosen't work.
