### ISSUE TITLE
Generate models from database

### ISSUE THREAD

**Issue by wizardnet972** [RobinBuschmann/sequelize-typescript#704]
This library provide a way to generate model classes from database? any outside tool to do that?

**Comment by RobinBuschmann** [comment]
Hey @wizardnet972, not yet. But if you‘d like to implement it, I would definitely support you with that.

**Comment by wizardnet972** [comment]
@RobinBuschmann Yeah, I'm working on it, update soon :)

**Comment by RobinBuschmann** [comment]
Sounds good. 👍
