### ISSUE TITLE
Sequelize.logging typings are incorrect

### ISSUE THREAD

**Issue by Kagu-chan** [RobinBuschmann/sequelize-typescript#705]
**Versions**
- sequelize: `^5.21.2`
- sequelize-typescript: `^1.0.0`
- typescript: `^3.6.3`

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Actual behavior:**
`SequelizeOptions->logging` provides the Sequelize Object instead of `timing: number` as second parameter

**Expected behavior:**
`SequelizeOptions->logging` should provide the typed Sequelize Object **or** the execution time of the query as stated in the current typing

**Steps to reproduce:**
Use logging for queries and see the result

**Related code:**
```ts
import {
  Sequelize,
  SequelizeOptions,
  Model,
  ModelCtor,
} from 'sequelize-typescript';
// ...
    this.dbConnection = new Sequelize({
      dialect: 'mysql',
      ...(cfg as SequelizeOptions),
      // logging: Logging.logging?: boolean | ((sql: string, timing?: number) => void)
      logging: console.debug,
    });

// cfg uses the following interface:
/**
 * Database connection options
 */
export interface DatabaseOptions {
  /**
   * Database host
   */
  host: string;

  /**
   * Database port
   */
  port: number | string;

  /**
   * Database user
   */
  username: string;

  /**
   * Database users password
   */
  password: string;

  /**
   * Database name
   */
  database: string;
}
```

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  },
  "exclude": ["node_modules", "dist"]
}
```

Output:
```
Executing (default): SELECT `id`, `createdAt`, `updatedAt` FROM `invoicePackages` AS `InvoicePackage`; { plain: false,
  raw: false,
  logging: [Function: bound consoleCall],
  showWarnings: false,
  hooks: true,
  rejectOnEmpty: false,
  originalAttributes: [ 'id', 'createdAt', 'updatedAt' ],
  attributes: [ 'id', 'createdAt', 'updatedAt' ],
  tableNames: [ 'invoicePackages' ],
  type: 'SELECT',
  model: InvoicePackage }
```

**Comment by RobinBuschmann** [comment]
Hey @Kagu-chan, thanks for reporting, but this is a sequelize issue. Since the typings are defined there https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L18, can you report it in the sequelize repo instead?

**Comment by Kagu-chan** [comment]
Thanks for the link - i didn't exactly look into the code at this point (:

For other users who may find this it's worth mentioning, that the parameter `logging.benchmark: boolean` enables exactly this behavior.

Since it's resolved in this case, i'll close the issue (:
