### ISSUE TITLE
@BeforeUpdate hook not working

### ISSUE THREAD

**Issue by neeraj87** [RobinBuschmann/sequelize-typescript#706]
**Versions**

- sequelize: ^5.21.2
- sequelize-typescript: ^1.0.0
- typescript: ^3.6.4

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

**Actual behavior:**

I have `@BeforeCreate` and `@BeforeUpdate` hook on my model which is suppose to hash the password before saving but only the before create hook works. When I do User.update(). the password is saved in plain text

**Expected behavior:**

The before update hook should also hash the password before the record is saved.

**Steps to reproduce:**

**Related code:**

```ts
import { Model, Table, Column, ForeignKey, BeforeCreate, BeforeUpdate, BelongsTo } from 'sequelize-typescript';
import { Role } from './role';
import bcrypt from 'bcrypt';

@Table({
    tableName: 'users'
})

export class User extends Model<User> {

    @Column
    firstName!: string;

    @Column
    lastName!: string;

    @Column
    password!: string;

    @Column
    email!: string;

    @Column
    isActive!: boolean;

    @Column
    companyId: string

    @ForeignKey(() => Role)
    @Column
    roleId!: string;

    @BelongsTo(() => Role)
    role!: Role;

    @BeforeCreate
    @BeforeUpdate
    static hashPassword(user: User) {
        if (user.password) {            
            const saltRounds = 10;
            var salt = bcrypt.genSaltSync(saltRounds);
            user.password = bcrypt.hashSync(user.password, salt);
        }
    }
}
```

**Comment by RobinBuschmann** [comment]
Hey @neeraj87, thanks for reporting. Can you check this issue: https://github.com/sequelize/sequelize/issues/6253 Does this solve your problem?

**Comment by neeraj87** [comment]
Thank you, it did solve the problem. The user was getting updated via both `model.update` at one place and `instance.update` at another so I had to include both the hooks to be safe. 

I think this should be mentioned in the documentation as many unsuspecting people like me will use `@BeforeUpdate` without taking into consideration if they are updating via the instance or model.
