### ISSUE TITLE
'You have an error in your SQL syntax' when i used DataType.ARRAY

### ISSUE THREAD

**Issue by wangweiwei** [RobinBuschmann/sequelize-typescript#709]
**Versions**

- sequelize: 5.21.2
- sequelize-typescript: 1.0.0
- typescript: 3.7.2

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

I've got an error when i used `DataType.ARRAY(DataType.STRING())` like this:
```TypeScript
@Table({
  underscored: true,
  paranoid: true,
  charset: 'utf8mb4',
  collate: 'utf8mb4_unicode_520_ci'
})
export class Image extends Model<Image> {
  @Column({
    type: DataType.INTEGER(),
    primaryKey: true,
    autoIncrement: true,
  })
  id!: number;

  @Column({
    type: DataType.ARRAY(DataType.STRING()),
  })
  tags: Array<string>;

  @CreatedAt
  createdAt: Date;

  @UpdatedAt
  updatedAt: Date;

  @DeletedAt
  deletedAt: Date;
}
```
sql from logging hooks function like this:
```SQL
CREATE TABLE IF NOT EXISTS `images` (
	`id` INTEGER AUTO_INCREMENT,
	`tags` VARCHAR(255)[], -- error
	`created_at` DATETIME NOT NULL,
	`updated_at` DATETIME NOT NULL,
	`deleted_at` DATETIME,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE utf8mb4_unicode_520_ci;
```
this error is:
```
SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[], `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `deleted_at`' at line 1
```

**Expected behavior:**

sql from logging hooks function like this:
```SQL
CREATE TABLE IF NOT EXISTS `images` (
	`id` INTEGER AUTO_INCREMENT,
	`tags` VARCHAR(255), -- right
	`created_at` DATETIME NOT NULL,
	`updated_at` DATETIME NOT NULL,
	`deleted_at` DATETIME,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE utf8mb4_unicode_520_ci;
```
**Steps to reproduce:**

**Related code:**

```ts
insert short code snippets here
```

**Comment by RobinBuschmann** [comment]
Hey @wangweiwei , according to the sequelize docs you have to omit the `()`. So just pass the second type, don’t function-call it: https://sequelize.org/master/class/lib/data-types.js~ARRAY.html

Hope this helps

**Comment by wangweiwei** [comment]
> Hey @wangweiwei , according to the sequelize docs you have to omit the `()`. So just pass the second type, don’t function-call it: https://sequelize.org/master/class/lib/data-types.js~ARRAY.html
> 
> Hope this helps

hi, it cant resolve the problem

**Comment by RobinBuschmann** [comment]
@wangweiwei, are you using postgres as dialect? According to https://sequelize.readthedocs.io/en/2.0/api/datatypes/#array feature is only supported for postgres

**Comment by wangweiwei** [comment]
> @wangweiwei, are you using postgres as dialect? According to https://sequelize.readthedocs.io/en/2.0/api/datatypes/#array feature is only supported for postgres

I am using mysql, thank you!
