### ISSUE TITLE
Create entity with many to many association

### ISSUE THREAD

**Issue by ouassimBenMosbah** [RobinBuschmann/sequelize-typescript#715]
**Versions** 
- sequelize: 5.21.2
- sequelize-typescript: 1.1.0
- typescript: 3.6.3

**Actual behavior:**
I have two models (`Domain` and `Request`) associated with a Many To Many relation. I would like to create a `Request` that is linked to many domains. Can i do it with the `CreateOptions` or do I have to create those associations on my own. Here is my code:

**Related code:**

`request.model.ts`
```ts
@Table
export class Request extends Model<Request> {
  @Column({ primaryKey: true, type: DataType.INTEGER, autoIncrement: true })
  idRequest: number;

  @Column({ type: DataType.STRING })
  requestReference: string;

  @BelongsToMany(() => Domain, () => DomainRequest)
  domains: Array<Domain & { DomainRequest: DomainRequest }>;
}
```

`domain.model.ts`
```ts
@Table
export class Domain extends Model<Domain> {
  @Column({ primaryKey: true, type: DataType.INTEGER, autoIncrement: true })
  idDomain: number;

  @Column({ type: DataType.STRING, allowNull: false })
  name!: string;

  @BelongsToMany(() => Request, () => DomainRequest)
  requests: Array<Request & { DomainRequest: DomainRequest }>;
}
```

`domain-request.model.ts`
```ts
@Table({ modelName: 'domainsrequests' })
export class DomainRequest extends Model<DomainRequest> {
  @ForeignKey(() => Domain)
  @Column({ primaryKey: true })
  idDomain: number;

  @ForeignKey(() => Request)
  @Column({ primaryKey: true })
  idRequest: number;

  @Column({ type: 'boolean' })
  isPrimaryDomainRequest: boolean;
}
```

`request.service.ts`
```ts
async createRequest(request: Partial<Request>): Promise<Request> {
    const { domains, ...requestToCreate } = request;
    const requestCreated: Request = await this.requestsRepository.create(requestToCreate);

    await DomainRequest.bulkCreate(domains.map(dom => ({ ...dom, idRequest: request.idRequest })));

    return requestCreated;
  }
```

Here is the data that I am sending
```
{
    "requestReference": "request1",
    "domains": [
        {
            "idDomain": 1,
            "isPrimaryDomainRequest": true
        },
        {
            "idDomain": 2,
            "isPrimaryDomainRequest": false
        }
    ]
}
```

The problem with that is that each time I will add many to many relations I will have to come in my service in order to update it.

Am I missing something ?

**Comment by RobinBuschmann** [comment]
Hey @ouassimBenMosbah , thanks for asking. But unfortunately I cannot think of a better solution. What's the issue with your provided solution?

**Comment by ouassimBenMosbah** [comment]
Hello @RobinBuschmann, the issue is that if I want to add relations to my request I will have to update all my routes as the association won't be created automatically.

And actually I tried typeorm where you only need to write:
`const requestCreated: Request = await this.requestsRepository.create(requestToCreate);`
And typeorm was automatically creating entries in the association table if domains was populated...

Thanks for your quick answer 👍

**Comment by RobinBuschmann** [comment]
Hey @ouassimBenMosbah, you could specify the one-to-many relation from `Request` to `DomainRequest` to achieve this behaviour:
```ts
@Table
export class Request extends Model<Request> {
   // ...
  @HasMany(() => DomainRequest)
  domainRequests: DomainRequest[];
}
```
And run like so `await this.requestsRepository.create(requestToCreate, {include: [DomainRequest]});`
