### ISSUE TITLE
Special requirements for 1.1.0?

### ISSUE THREAD

**Issue by chscott** [RobinBuschmann/sequelize-typescript#717]
**Versions**

- sequelize: 5.21.2
- sequelize-typescript: 1.1.0
- typescript: 3.7.3

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

(More of a question than a bug.)

**Actual behavior:**

I've inherited a project that uses sequelize-typescript bundled via webpack. The project breaks when I updated sequelize-typescript to from 1.0.0 to 1.1.0 (or from 1.0.0 to 1.1.0-beta.0). I don't see any errors other than the database activity that should happen on app start simply doesn't occur. In tracking it down, I can see that webpack is bundling far fewer references to sequelize-typescript when 1.1.0 or 1.1.0-beta.0 are installed than when 1.0.0 is installed.

I know that's not much to go on, so I've scoped the question to asking if there are any new requirements I might not be aware of when updating to 1.1.0. Specifically, it looks like https://github.com/RobinBuschmann/sequelize-typescript/commit/de6f6ab7d050cbf8f04a32399460b0c995a5ab52 was the last major change between 1.1.0 and 1.1.0-beta.0. Is anything special required as a result of that change?

**Expected behavior:**

Given that 1.1.0 was a minor release, I'd expect no breaking changes.

**Steps to reproduce:**

I don't have any readily reproducible steps, unfortunately.

**Related code:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:
Not able to provide a sample.

**Comment by RobinBuschmann** [comment]
Hey @chscott , thanks for reporting. In order to be able to use the models on client side, the feature implemented with the commit you've mentioned, was developed. Since you've bundling your app for server side, this feature shouldn't apply 🤔 What target is set in you webpack config? (Here is a [link](https://github.com/RobinBuschmann/sequelize-typescript/pull/574#issuecomment-489016551) to the PR including the discussion)

**Comment by chscott** [comment]
The target is electron-renderer. That's not something I was looking at, but a quick search of that and webpack turns up [this issue](https://github.com/webpack/webpack/issues/7953). I haven't fully digested it yet, but I wonder if it's related.

**Comment by RobinBuschmann** [comment]
> The target is electron-renderer. That's not something I was looking at, but a quick search of that and webpack turns up [this issue](https://github.com/webpack/webpack/issues/7953). I haven't fully digested it yet, but I wonder if it's related.

@Toxicable Can you have a look at this issue? Is there something we can do? Is there a workaround you can think of?

**Comment by chscott** [comment]
From the issue I linked, it may have nothing to do with sequelize-typescript at all and that the only reason 1.0.0 works for me is that it omitted the browser support, thus not giving webpack a chance to make the wrong decision. I'm on webpack 4.41.2, which I believe is impacted by that issue.

I'll try some of the workarounds from the webpack thread and update here for posterity.

**Comment by chscott** [comment]
The solution [here](https://github.com/typeorm/typeorm/issues/4210#issuecomment-543914144) worked for me. I'm not sure it's the most _desired_ solution, but it's enough for me to believe this isn't an issue with sequelize-typescript.

Thanks for the help!

**Comment by RobinBuschmann** [comment]
You're welcome! Good to here you find a solution.
