### ISSUE TITLE
How to make insert with relations

### ISSUE THREAD

**Issue by deceive3w** [RobinBuschmann/sequelize-typescript#723]
recently i am using typeorm the code its just like below and using sequelize the query doesnt work, how to do it in sequelize-typescript?

```javascript
@Table
export default class Post extends Model<Post>{
    
    @Column
    text: string

    @Column
    userId: number

    @HasMany(()=>Poll)
    polls: Poll[];
....
```
```javascript
@Table
export default class Poll extends Model<Poll>{

    @ForeignKey(() => Post)
    @Column
    postId: number;
   
    @BelongsTo(() => Post)
    post: Post;
...
```

```javascript
let poll1 = new Poll()
poll1.option = "btc"

let poll2 = new Poll()
poll2.option = "eth"
        
let post = new Post({
     text: "btc or eth?",
     userId: 1,
     polls: [poll1, poll2]
}, {
     include: [{model: Poll}]
})
await post.save()
```

and there are is have update in future to make sequelize-typescript fully support data mapper ?
Thankss

**Comment by RobinBuschmann** [comment]
Hey @deceive3w, thanks for bringing this up. To achieve this, you could do it like so:
```ts
let post = new Post({
     text: "btc or eth?",
     userId: 1,
     polls: [{option: 'btc'}, {option: 'eth'}]
}, {
     include: [{model: Poll}]
})
```
(Unfortunately sequelize only supports pure objects here, so Model instances won't work)

Hope this helps!

**Comment by RobinBuschmann** [comment]
Hey @deceive3w thanks for bringing this up. Am I right that your polls are already stored in the database and the post is newly created/stored?

**Comment by deceive3w** [comment]
@RobinBuschmann i tried ``polls: [poll1.toJSON(), poll2.toJSON()]`` it doesn't work because id is null, and try ``polls:[{option:'btc'}, {option:'eth']}`` work perfectly.  Nice Work @RobinBuschmann!

**Comment by RobinBuschmann** [comment]
In case of your polls already exists in database, you have to save `Post` first and add the polls afterwards like so:
```ts
const post = await Post.create({
     text: "btc or eth?",
     userId: 1,
});
await post.$add('polls', [new Poll({id: 1, option: '1'}), new Poll({id: 2, option: '2'})]);
```
or if you want to commit it at once, use transactions like so:
```ts
await sequelize.transaction(async transaction => {
  const post = await Post.create({
     text: "btc or eth?",
     userId: 1,
  }, {transaction});
  await post.$add('polls', [
    new Poll({id: 1, option: '1'}), 
    new Poll({id: 2, option: '2'})
  ], {transaction});
});

```

**Comment by deceive3w** [comment]
@RobinBuschmann Greattt, btw did you have a plan to support data mapper just like type-orm separating infrastructure logic in model, and make model is clean?
