### ISSUE TITLE
Unique Constraint Error

### ISSUE THREAD

**Issue by frct1** [RobinBuschmann/sequelize-typescript#724]
**Versions**

- sequelize: 5.21.3
- sequelize-typescript: 1.1.0
- typescript 3.4.3

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

Each time when new table creating there is error [SequelizeUniqueConstraintError: Validation error] in case of usage with postgresql (tested 11, 12 version).
-->

**Comment by frct1** [comment]
Tested with clean sequelize and everything ok with similar model

**Comment by RobinBuschmann** [comment]
Hey @frct1 , what was the actual issue? How did you solve your problem?

**Comment by frct1** [comment]
@RobinBuschmann 
Hi, @RobinBuschmann 

Since i'm using it with nest there is was some shitty troubles with providers. It is so strange that doesn't errored when used mariadb 🤔

**Comment by frct1** [comment]
More details: i think when database connection was provided in many places sequelize tried to run same queries for creating constraints

Just a guess.
