### ISSUE TITLE
'hasMany called with something that's not a subclass of Sequelize.Model' when importing models from another npm package

### ISSUE THREAD

**Issue by spinlud** [RobinBuschmann/sequelize-typescript#729]
**Versions**

- sequelize: 5.21.3
- sequelize-typescript: 1.1.0
- typescript: 3.7.4
- node: 10.16.3

**I'm submitting a ...** 

[x] bug report

**Actual behavior:**

I have a private npm package (let's call it `@my/tables`) that exports some `sequelize-typescript` models in pure typescript.
The structure of the package is very simple: 

```
test/
models/
    - User.ts
    - Post.ts
index.ts
```

This package will be used by other typescript projects (so I guess there is no need to compile the code). But when I try to import and use this package in another typescript project I get the following error:

```js
Error: User.hasMany called with something that's not a subclass of Sequelize.Model
```

**Steps to reproduce:**
The error occurs just after creating the sequelize connection:

```ts
import { Sequelize } from 'sequelize-typescript';
import { User, Post } from '@my/tables';


const sequelize = new Sequelize({
    dialect: 'mysql',
    database: 'mydb',
    username: 'user',
    password: 'pwd',
});

sequelize.addModels([
    Order,
    OrderItem,
]);
```

Some additional notes:
 - The same code works fine when run directly on the `@my/tables` package (see related code).
 - The `@my/tables` package has only production dependencies (except for `tsc` and `ts-node-dev`).
 - There is no error if I remove the relations from the models. 

**Related code:**
`@my/tables/package.json`
```json
{
  "name": "@my/tables",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "test": "ts-node-dev test/test.ts",
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/bluebird": "^3.5.29",
    "@types/node": "^13.1.4",
    "@types/validator": "^12.0.1",
    "mysql2": "^2.0.0",
    "reflect-metadata": "^0.1.13",
    "sequelize": "^5.21.2",
    "sequelize-typescript": "^1.1.0",
    "typescript": "^3.7.4"
  },
  "devDependencies": {
    "ts-node-dev": "^1.0.0-pre.44",
    "tsc": "^1.20150623.0"
  }
}
```

`@my/tables/models/User.ts`
```ts
import { Table, Column, Model, DataType, HasMany } from 'sequelize-typescript';
import { Post } from "./Post";

@Table({ timestamps: false })
export class User extends Model<User> {

    @Column({
        primaryKey: true,
        autoIncrement: true,
        allowNull: false,
        type: DataType.INTEGER,
    })
    id?: number;

    @Column
    name!: string;

    @HasMany(() => Post)
    posts?: Post[];
}
```

`@my/tables/models/Post.ts`
```ts
import { Table, Column, Model, DataType, BelongsTo, ForeignKey } from 'sequelize-typescript';
import { User } from "./User";

@Table({ timestamps: false })
export class Post extends Model<Post> {

    @Column({
        primaryKey: true,
        autoIncrement: true,
        allowNull: false,
        type: DataType.INTEGER,
    })
    id?: number;

    @Column({
        allowNull: false,
        type: DataType.INTEGER,
    })
    @ForeignKey(() => User)
    user_id!: number;

    @Column
    title!: string;

    @Column
    text!: string;

    @BelongsTo(() => User)
    user!: User;
}
```

`@my/tables/index.ts`
```ts
export * from './models/User'
export * from './models/Post'
```

`@my/tables/test/test.ts`
```ts
import { Sequelize } from 'sequelize-typescript';
import { User, Post } from '@my/tables';


const sequelize = new Sequelize({
    dialect: 'mysql',
    database: 'mydb',
    username: 'user',
    password: 'pwd',
});

sequelize.addModels([
    Order,
    OrderItem,
]);
```

**Comment by RobinBuschmann** [comment]
Hey @spinlud, could it be that you've got multiple sequelize packages installed? I assume it, since you've defined `sequelize` and `sequelize-typescript` as a normal dependency in your `@my/tables` package. `sequelize` does a `instanceOf Model`-check - So if you've extend your models with `Model` of sequelize package 1 and use it with sequelize package 2, the reference to `Model` is not the same and `instanceOf Model` is false. Hope this helps!

**Comment by spinlud** [comment]
Hi, thanks I figured out the same! I moved the dependencies as peer dependencies so there is no more duplication in the host project. Closing!

**Comment by stanleynguyen** [comment]
Hey @spinlud @RobinBuschmann , I'm facing the same issue in my project, but moving them to `peerDependencies` didn't work for me (The `Model` that was used still came from the upstream project i.e. one with `sequelize-typescript` and `sequelize` as `peerDependencies`). 
I suspect it could be because of how I configured the `tsconfig` path aliasing. May I see how u link `@my/tables` to the host project @spinlud ?

**Comment by chaddjohnson** [comment]
> Hi, thanks I figured out the same! I moved the dependencies as peer dependencies so there is no more duplication in the host project. Closing!

It would be really great if we could see your tsconfig.

**Comment by chaddjohnson** [comment]
> Hi, thanks I figured out the same! I moved the dependencies as peer dependencies so there is no more duplication in the host project. Closing!

@spinlud It would be really great if we could see your tsconfig.

**Comment by kyastuudaykumar** [comment]
How to perform post request where i can save data in users table and post table as a join
Example: post request body as below:

{
username: 'Test Name',
email : 'Test@gmail.com',
gender: 'M',
posts: [
                {
                name: 'Test Name',
                content: ' some content'
                },
                {
                name: 'Test Name',
                content: ' some content'
                }
          ]
}
