### ISSUE TITLE
Add connection string initialization

### ISSUE THREAD

**Issue by aventurella** [RobinBuschmann/sequelize-typescript#73]
Per the docs:
http://docs.sequelizejs.com/manual/installation/getting-started.html#setting-up-a-connection

This should be allowed to be passed into the `Sequelize` constructor:

```js
// Or you can simply use a connection uri
const sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname');
```

https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L103-L134

This appears to work (I ported from their code):

```js
function parseConnectionString(connectionString: String): any{
    let config: any = {};
    let options: any = {}

    const urlParts = url.parse(connectionString);

    options.dialect = urlParts.protocol.replace(/:$/, '');
    options.host = urlParts.hostname;

    if (options.dialect === 'sqlite' && urlParts.pathname && urlParts.pathname.indexOf('/:memory') !== 0) {
        const path = Path.join(options.host, urlParts.pathname);
        options.storage = options.storage || path;
    }

    if (urlParts.pathname) {
        config.database = urlParts.pathname.replace(/^\//, '');
    }

    if (urlParts.port) {
        options.port = urlParts.port;
    }

    if (urlParts.auth) {
        const authParts = urlParts.auth.split(':');

        config.username = authParts[0];

        if (authParts.length > 1)
            config.password = authParts.slice(1).join(':');
    }

    let result = Object.assign({}, config, options);

    return result;
}
```

**Comment by hiradimir** [comment]
+1

But, now I am using "parse-database-url".


```ts
import * as parseDbUrl from "parse-database-url";
---
      let dbConfig = parseDbUrl(process.env["DATABASE_URL"]);

      const sequelize = new Sequelize({
        name: dbConfig.database,
        username: dbConfig.user,
        password: dbConfig.password,
        dialect: dbConfig.driver,
        host: dbConfig.host,
        port: dbConfig.port,
        modelPaths: [__dirname + '/../main/models']
      });

```

**Comment by aventurella** [comment]
Winning! I'll take that all day. Personal preference for simple stuff like that which is only a few LOC i'm dependency averse. At the same time, whatever works ;)

**Comment by RobinBuschmann** [comment]
@aventurella thanks for raising this. I will consider this for the next releases. But if you're like to create a PR for that, feel free to do so. Any help is appreciated :)

**Comment by kukoo1** [comment]
@aventurella  I've recently tried implementing it using static factory function, without parser dependency.  But then I realized that it breaks backward compatibility because I had to remove the constructor.
Typescript doesn't allow neither passing spread arguments into another function nor conditional super() call.
I wonder that we should go with that path or integrate with external parser instead.

**Comment by RobinBuschmann** [comment]
Hey @kukoo1, can you show me how your approach looks like? Thank you
