### ISSUE TITLE
class-transformer usage

### ISSUE THREAD

**Issue by frct1** [RobinBuschmann/sequelize-typescript#735]
**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

Maximum call stack exceeded when we attempt to do `classToPlain` with class-transformer decorators.

**Expected behavior:**

Working @Type, @Exclude and so on `class-transformer` decorators which used in model

**Steps to reproduce:**

Create simple model and use @Exclude() decorator on any property. Then attempt to `classToPlain(user)` for example. There is will be a lot of insertions attempts (catched it with global sequelize hook.

**Comment by RobinBuschmann** [comment]
Hey @frct1 can you provide an example repo, which reproduces the issue

**Comment by frct1** [comment]
Hello, @RobinBuschmann 
Yes, that's it
https://github.com/frct1/seq-ts

**Comment by RobinBuschmann** [comment]
May I ask why you are using class-transformer? sequelize already maps the objects to class instances.

**Comment by frct1** [comment]
@RobinBuschmann 
Hi, sorry for delay
I tought about transforming result object depending from user property but i did it with custom class definition and then pass result to them

**Comment by maxoux** [comment]
I have the same problem, i use class transformer with nestjs and Exclude decorators throw an error of the same type.. Any news about this ?

**Comment by lehno** [comment]
@frct1 can you share your fix?
