### ISSUE TITLE
Date field is a string

### ISSUE THREAD

**Issue by DalerAkhmetov** [RobinBuschmann/sequelize-typescript#739]
**Versions**

- sequelize: 4.44.3
- sequelize-typescript: 0.6.11
- typescript: 3.7.5

**I'm submitting a bug report** 

**Actual behavior:**
Queries return fields with type "DataType.Date" as a string.

**Expected behavior:**

Field type should be Date as createdAt, updatedAt

**Steps to reproduce:**

I provided a code in Related code section

**Related code:**

```
class Video extends Model<Video> {
  @AllowNull(false)
  @Column
  publishedAt!: Date;
}

video = await Video.findOne({where: {id: 2}});
// video.publishedAt is a string
```

**Comment by RobinBuschmann** [comment]
Hey @DalerAkhmetov, thanks for reporting. Can you provide an example repo which reproduces the issue. For me it is working well. Thanks!

**Comment by DalerAkhmetov** [comment]
Thanks for feedback. This issue can be closed). I created example repo and found out it works fine. There was a mistake in my project, not related with sequelize-typescript.
