### ISSUE TITLE
Custom include feature

### ISSUE THREAD

**Issue by frct1** [RobinBuschmann/sequelize-typescript#745]
**I'm submitting a ...** 

[ ] bug report
[ x] feature request

**Actual behavior:**

Not possible by sequelize at this moment.

**Expected behavior:**

Processing functions while we building data object/array
**Related code:**

```ts
/* Imagine we defined propety with array type */
@Column
thing_ids: number[];

@CustomSelect(/* Here we probably can pass options object like model*/)
async custom_things(): Promise<OtherModel>// type is just for example
{ 
    return await OtherModel.findAll({
        where: {
            id: {
                $in: this.thing_ids
            }
        }
    })
}
```
In code we will tell sequelize that we need to run custom function to get objects from other model. Why it can be usable: currently sequelize can't build query to join by array items. I thing it could be simpliest workaround for this case.

**Comment by RobinBuschmann** [comment]
Hey @frct1 , probably hooks help you with it? See https://github.com/RobinBuschmann/sequelize-typescript#hooks

**Comment by frct1** [comment]
Hi @RobinBuschmann 
Yes, actually they can. But it is should be something like conditional calling depends on options
I think it is possible to check in CustomSelect decorator do we really need to call next function or just skip it

**Comment by RobinBuschmann** [comment]
Sry for the late reply. What stops you from implementing these conditions within hooks or you could implement your own decorator - I could help you with it. But from now on I think this shouldn't be implemented in sequelize-typescript itself.
