### ISSUE TITLE
sequelize automatically adds 'id' column in my table

### ISSUE THREAD

**Issue by Hwan-seok** [RobinBuschmann/sequelize-typescript#746]
**Versions**

- sequelize: ^5.21.3
- sequelize-typescript: ^1.1.0
- typescript:`3.7.5`
- mysql : 5.7

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

Following table schema makes `id` column automatically
But I have capsuleId and taggedCapsuleId In my table using primaryKey already 
```ts
@Table({
  tableName: 'capsule_tagged',
  timestamps: false,
  underscored: true,
})
export class CapsuleTaggedEntity extends Model<CapsuleTaggedEntity> {
  @Column({ type: DataType.INTEGER, primaryKey: true })
  capsuleId: number;

  @Column({ type: DataType.INTEGER, primaryKey: true })
  taggedCapsuleId: number;

  @BelongsTo(() => CapsuleLaunchedEntity, {
    constraints: false,
    foreignKey: 'id',
  })
  Capsule: CapsuleLaunchedEntity;
}

```
It makes create table statement as follows
```mysql
CREATE TABLE IF NOT EXISTS `capsule_tagged` 
(`capsule_id` INTEGER ,
 `tagged_capsule_id` INTEGER ,
 `id` INTEGER,
 PRIMARY KEY (`capsule_id`, `tagged_capsule_id`))
 ENGINE=InnoDB;
```
**Expected behavior:**

Don't have `id` column in my result table as follows
```mysql
CREATE TABLE IF NOT EXISTS `capsule_tagged` 
(`capsule_id` INTEGER ,
 `tagged_capsule_id` INTEGER ,
 PRIMARY KEY (`capsule_id`, `tagged_capsule_id`))
 ENGINE=InnoDB;
```

**Steps to reproduce:**

**Related code:**

```ts
insert short code snippets here
```

**Comment by RobinBuschmann** [comment]
Hey @Hwan-seok, this is because you defined the column `id` within the `BelongsTo` decorator:
```ts
  @BelongsTo(() => CapsuleLaunchedEntity, {
    constraints: false,
    foreignKey: 'id', // <-- This causes the id column to be created
  })
  Capsule: CapsuleLaunchedEntity;
```
So it works as expected.

See https://sequelize.org/v5/manual/associations.html#difference-between-hasone-and-belongsto for details.
