### ISSUE TITLE
Dialect MSSQL: sync({ alter: true }) is duplicating foreign keys

### ISSUE THREAD

**Issue by neokamikai** [RobinBuschmann/sequelize-typescript#747]
**Versions**

- sequelize: 5.21.3
- sequelize-typescript: 1.1.0
- typescript: 3.7.5

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

I'm using dialect 'mssql'. When I do sync({ alter: true }), all foreign keys for the model are created again without dropping the existing ones.
Also, even if i set the `foreignKey: { name: 'fk_custom_name' }` option for BelongsTo decorator it still generates the key with some other name (generated by the database, it seems). I didn't test if the same happens for BelongsToMany decorator.

**Expected behavior:**

Drop Existing foreign key for an association before creating it again when sync({ alter: true }) is called, as to only have one foreign key for a certain association.

**Steps to reproduce:**

**Related code:**

`index.ts`
```ts
import { Sequelize, Model, BelongsTo, ForeignKey, Column, Table, HasMany, DataType } from 'sequelize-typescript';

@Table({ tableName: 'tb_account', schema: 'dbo', freezeTableName: true })
class Account extends Model<Account>{
    @Column({ autoIncrement: true, primaryKey: true, type: DataType.BIGINT })
    id: number;

    @Column({ field: 'name', type: DataType.STRING(50), allowNull: false })
    name: string;

    @HasMany(() => Contact, { foreignKey: { name: 'fk_account_contacts' }, onDelete: 'NO ACTION' })
    contacts: Array<Contact>;
}

@Table({ tableName: 'tb_contact', schema: 'dbo', freezeTableName: true })
class Contact extends Model<Contact>{
    @Column({ autoIncrement: true, primaryKey: true, type: DataType.BIGINT })
    id: number;

    @Column({ field: 'name', type: DataType.STRING(50), allowNull: false })
    name: string;

    @Column({ field: 'phone', type: DataType.STRING(50), allowNull: true })
    phone: string;

    @Column({ field: 'email', type: DataType.STRING(255), allowNull: true })
    email: string;

    @ForeignKey(() => Account)
    @Column({ field: 'idAccount', type: DataType.BIGINT, allowNull: true })
    idAccount: number;

    @BelongsTo(() => Account, { foreignKey: { name: 'fk_account_contacts' }, onDelete: 'NO ACTION' })
    contacts: Account;
}

(async () => {
    const sequelize = new Sequelize({ host: 'localhost', logging: false, username:'test', password:'test',  dialect: 'mssql', database: 'test' });
    await sequelize.addModels([Account, Contact]);
    console.log('Sync Account Model..');
    await Account.sync({ alter: true });
    console.log('Sync Contact Model..');
    await Contact.sync({ alter: true });
    console.log('Finished!');

})()
    .catch(e => {
        console.log(e);
    })
```
`tsconfig.json`
```json
{
    "compileOnSave": true,
    "exclude": [
        "node_modules/**/*",
        "tests/**/*",
        "config/*.d.ts"
    ],
    "compilerOptions": {
        "experimentalDecorators": true,
        "alwaysStrict": true,
        "declaration": true,
        "declarationMap": true,
        "resolveJsonModule": true,
        "sourceMap": true,
        "lib": [
            "ES2020",
            "ScriptHost",
            "DOM"
        ],
        "module": "CommonJS",
        "target": "ES2019",
        "emitDecoratorMetadata": true
    }
}
```
Result of running the code above:
![image](https://user-images.githubusercontent.com/4462017/75985960-f29d7980-5ecb-11ea-87ff-81967437c7a0.png)

As you may also have noticed, after the first run, the Contact model is created with the foreign key created twice. And after each run it adds the same foreign key twice again and again.

**Comment by RobinBuschmann** [comment]
Hey @neokamikai, sorry for the late reply. This seems to be sequelize-only related and should be reported [here](https://github.com/sequelize/sequelize/issues). Nevertheless according to the docs of sequelize you shouldn't use this for production anyway:
> Alters tables to fit models. Provide an object for additional configuration. Not recommended for production use. If not further configured deletes data in columns that were removed or had their type changed in the model.
(https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html)
