### ISSUE TITLE
Static decrement method for Model

### ISSUE THREAD

**Issue by Duplicated** [RobinBuschmann/sequelize-typescript#749]
From #276 , I have just noticed that a static `decrement` method is still missing. Mind if I put in a PR for this one?

**Comment by RobinBuschmann** [comment]
Hey @Duplicated, thanks for reporting, but this should be fixed with sequelize. sequelize-typescript@1 uses the official typings of sequelize. So if you want to add `decrement` it should be added here: https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L1517
