### ISSUE TITLE
Cannot access static members of model with .schema() call

### ISSUE THREAD

**Issue by kacepe** [RobinBuschmann/sequelize-typescript#750]
**Versions**
- sequelize: 5.21.5
- sequelize-typescript: 1.1.0
- typescript 3.8.3

**I'm submitting a ...** 
[ x ] bug report
[ ] feature request

**Actual behavior:**
When you call `.schema()` method of model then call static member typescript says that member doesn't exist.

**Expected behavior:**
Ability to use static members of model without warnings.

**Steps to reproduce:**
You need model with static member defined, call `schema` method of it and then try to use any static member.

**Related code:**
```
const model = ModelWithStaticMethodDefinied.schema('blah');

model.staticMethod();
```

**Comment by kacepe** [comment]
FYI:
It might be easy fixed by adding `schema` method to model definition:
```ts
static schema<T>(this: NonAbstract<T>, schema: string, options?: SchemaOptions): NonAbstract<T>;
```

**Comment by RobinBuschmann** [comment]
Hey @kacepe, thanks for reporting. For me in is working very well. sequelize-typescript uses the official typings and `schema` is already defined there. See this https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L1626

**Comment by kacepe** [comment]
@RobinBuschmann Idk how it can works for you.
Here is a code example:
https://repl.it/repls/FrequentLostGraphicslibrary

**Comment by RobinBuschmann** [comment]
Ah sry, I didn't understand it in the first place. Now I see. Anyways, this need to be fixed in the official sequelize typings: https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L1626

**Comment by RobinBuschmann** [comment]
Closing this since it isn't an issue with sequelize-typescript but an issue with sequelize.
