### ISSUE TITLE
Error: Foreign key for "User" is missing on "Person" [Repo included]

### ISSUE THREAD

**Issue by hkyq** [RobinBuschmann/sequelize-typescript#754]
Hi, possibly related to #751 

**Versions** 
- sequelize: 5.21.5
- sequelize-typescript: 1.1.0 
- typescript:  3.8.3

**I'm submitting a ...** 

[x] bug report
[ ] feature request

Having an issue with foreign keys. Here are my models:

`person.ts`
```ts
import { Table, BelongsTo, PrimaryKey, Column, Length, Model } from "sequelize-typescript";
import User from './user'

@Table
export default class Person extends Model<Person> {

    @Length({min: 2, max: 24})
    @Column
    name: string

    @BelongsTo(() => User)
    user: User
}
```

`user.ts`
```ts
import {Table, Column, Model, HasMany, PrimaryKey, IsEmail, Length, Default} from 'sequelize-typescript';
import Person from './person';

@Table
export default class User extends Model<User> {

    @IsEmail
    @Column
    email: string

    @HasMany(() => Person)
    persons: Person[]
}
```

When I create a `Sequelize` instance as described in the docs with the models, I get

```
        throw new Error(`Foreign key for "${relatedClass.name}" is missing ` +
              ^
Error: Foreign key for "User" is missing on "Person".
```
Not really sure why. I tried to follow the docs as closely as I could. 

### Reproducing 
Clone my example [repo](https://github.com/hkyq/seprob). Run `npm i` and then `npm run start`.

**Comment by hkyq** [comment]
Forgot 

```ts
    @ForeignKey(() => User)
    userId: number
``` 
In Person model. Oops.

**Comment by IonelLupu** [comment]
So, we are required to define both the relation AND the foreign key column as two separate properties in the class? @sometimescool22

**Comment by ChristianVaughn** [comment]
> So, we are required to define both the relation AND the foreign key column as two separate properties in the class? @sometimescool22

I was wondering the same thing. I am upgrading from non-ts sequelize v4 and only had to define the belongsTo for the relationship to be created along with defining the column but not defining the refrence when defining the column.

So in sequelize-typescript do belongsTo relationships also require the @ForeignKey declarator on the column definition?

**Comment by mwayne16** [comment]
> > So, we are required to define both the relation AND the foreign key column as two separate properties in the class? @sometimescool22
> 
> 
> 
> I was wondering the same thing. I am upgrading from non-ts sequelize v4 and only had to define the belongsTo for the relationship to be created along with defining the column but not defining the refrence when defining the column.
> 
> 
> 
> So in sequelize-typescript do belongsTo relationships also require the @ForeignKey declarator on the column definition?

Yes you have to include the @ForeignKey decorator. Removing it will cause sequelize to throw a fit about missing fk
