### ISSUE TITLE
CASCADE don't working with BelongsTo

### ISSUE THREAD

**Issue by lleonesouza** [RobinBuschmann/sequelize-typescript#755]
**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Actual behavior:**
Hi,
I'm tryng to destroy() with Cascade but it's not working, I already try it in a lot of different ways, the relations is working. but I don't why Cascade not. 

versions: 
"sequelize": "^5.21.5",
"sequelize-typescript": "^1.1.0"
"typescript": "^3.8.3",

my models:
```ts
@Table({ tableName: "store"})
class Store extends Model<Store> {
  @AutoIncrement
  @Unique
  @PrimaryKey
  @Column(DataType.STRING)
  id: string;

  @NotEmpty
  @AllowNull(false)
  @Column(DataType.STRING)
  title: string;

  @HasMany(() => Categories, {
    foreignKey: "store_id"
      onUpdate: "CASCADE",
      onDelete: "CASCADE"
  })
  categories: Categories[];
}
```

```ts
@Table({ tableName: "categorie", timestamps: true })
class Categories extends Model<Categories> {
  @AutoIncrement
  @Unique
  @PrimaryKey
  @Column(DataType.STRING)
  id: string;

  @NotEmpty
  @AllowNull(false)
  @Column(DataType.STRING)
  title: string;

  @ForeignKey(() => Store)
  @Column(DataType.STRING)
  storeId: string;

  @BelongsTo(() => Store, {
        foreignKey: "store_id"
        onUpdate: "CASCADE",
        onDelete: "CASCADE"
    })
  store: Store;
}
```
I'm using "underscored": true at config file

my querie is:
```ts
Store.destroy({ where: { id }})
```

And thanks to create 'sequelize-typescript', it's really nice.

**Comment by RobinBuschmann** [comment]
Hey @lleonesouza sry for the late reply. This doesn't seem to be an issue with sequelize-typescript but with sequelize - You should report it [here](https://github.com/sequelize/sequelize)
