### ISSUE TITLE
Unable to get type-safe access to the dataValues property on models 

### ISSUE THREAD

**Issue by robwells124** [RobinBuschmann/sequelize-typescript#760]
**Versions**

- sequelize: 5.21.2
- sequelize-typescript: 1.1.0
- typescript3.8.3

**I'm submitting a ...** 

[X ] bug report
[ ] feature request

**Actual behavior:**

Unable to get typing safe access to the foreign key of a model in a many-to-one association from using model.dataValues. When using the property dataValues on my instance, Typescript flags up that "Property 'dataValues' does not exist on type "ActivityModel" ". However when using "// @ts-ignore",  the dataValues  property returns all data in the model and allows me to access the foreign key value. 

**Expected behavior:**

Should be able to use the dataValues property on my model with sequelize-typescript providing valid types

**Steps to reproduce:**

1. Create a 1-n relationship with 2 models with 
2. On the many side of the relationship, use the @BelongsTo decorator and use the  AssociationOptions.foreignKey property to set the foreign key attribute
3. Create instances of those models, and try to access any of the attributes in your model through "foo.dataValues.bar". Then try it using // @ts-ignore  

**Related code:**

```ts
//tsconfig.json
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "lib": [
            "es2016",
            "esnext.asynciterable"
        ],
        "esModuleInterop": true,
        "target": "es6",
        "noImplicitAny": true,
        "strictNullChecks": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": ["node_modules/*"]
        }
    },
    "include": ["src/**/*"]
}

/*
Replicated Code
*/

//Throws an error
ActivityModel.findAll().then((activityData) => {
        activityData.map((activity) => {
            console.log(activity.dataValues.listingId)
        })
    })


//This logs the models foreign key
ActivityModel.findAll().then((activityData) => {
        activityData.map((activity) => {
            // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
            // @ts-ignore
            console.log(activity.dataValues.listingId)
        })
    })
```

**Comment by RobinBuschmann** [comment]
Hey @robwells124. There is a getter for that. See official typings: https://github.com/sequelize/sequelize/blob/master/types/lib/model.d.ts#L2539

Anyways, if you have good reasons to add the `dataValues` property to the typings, you would have to create an issue or PR in the sequelize project.

**Comment by Silly-V** [comment]
I have the same issue, if dataValues is available in the return type of say `bulkCreate()`, why doesn't typescript like this property when used on the result of bulkCreate? I have to do ( as any) to bypass this.
