### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by artoodeeto** [RobinBuschmann/sequelize-typescript#764]
Hello. This is really awesome. Planning to migrate from typeorm to sequelize. Quick question though. We’re confused. Whe using sequelize which documentation should we read? This one or the main sequelize? Can we the code from main sequelize to here?

**Comment by RobinBuschmann** [comment]
Hey @artoodeeto thanks and sry for the late reply. I would recommend to use the documentation from sequelize-typescript and for any detailed information check the official sequelize docs.
