### ISSUE TITLE
import Datatype from Sequellize-Typescript returns empty object

### ISSUE THREAD

**Issue by Alkanores** [RobinBuschmann/sequelize-typescript#767]
I was trying to import Datatype by this ways:

```
import {
    DataType
} from 'sequelize-typescript';
```

`require('sequelize-typescript');`

`import * as sequelizeTypescript from 'sequelize-typescript';`

But in all cases Datatype is empty object. How can I fix it?

**Comment by RobinBuschmann** [comment]
Hey @Alkanores sry for the late reply. Can you provide an example repo which reproduces the issue?

**Comment by Alkanores** [comment]
Heh, I solve it) Just added in webpack externals

`externals: {
    'sequelize-typescript': 'commonjs sequelize-typescript'
}`
