### ISSUE TITLE
Composite Constraint

### ISSUE THREAD

**Issue by connected-pjeri** [RobinBuschmann/sequelize-typescript#78]
How can I define a composite constraint at the model level?

Eg: I have a table named `Preferences(id, userId, name, value)` and I want to make it so that the combination of **userId** and **name** is **unique**.

**Comment by RobinBuschmann** [comment]
```typescript
@Unique
userId: string;

@Unique
name: string;
```
or as primary keys

```typescript
@PrimaryKey
userId: string;

@PrimaryKey
name: string;
```

**Comment by connected-pjeri** [comment]
But that would make both userId and name independently unique right? I mean the case where you want the combination of userId + name as the primary key.

Eg: inserting (1,'lang') and (1, 'tz') is valid, not inserting (1,'lang') and (1,'lang') is not.

**Comment by RobinBuschmann** [comment]
Marking both columns as primary key makes them in combination as primary key. So that it creates a query like:
```
CREATE TABLE IF NOT EXISTS `TableName` (`id` INT(11) auto_increment , `name` VARCHAR(100) , PRIMARY KEY (`id`, `name`)) 
```
