### ISSUE TITLE
Incompatible with sequelize 6.0.0-beta.6

### ISSUE THREAD

**Issue by AlexDede** [RobinBuschmann/sequelize-typescript#785]
**Versions**

- sequelize: 6.0.0-beta.6
- sequelize-typescript: 1.1.0
- typescript: 3.9.2

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Actual behavior:**

`2322 Type 'typeof MyClassName' is not assignable to type 'Includeable'.
  Type 'typeof MyClassName' is not assignable to type 'typeof Model'.
    Types of property 'init' are incompatible.
      Type '(attributes: ModelAttributes<Model<any, any>>, options: InitOptions<Model<any, any>>) => void' is not assignable to type '<M extends Model<any, any> = Model<any, any>>(this: ModelCtor<M>, attributes: ModelAttributes<M>, options: InitOptions<M>) => Model<...>'.
`

**Expected behavior:**

sequelize-typescript must be compatible with sequelize 6.0.0-beta.6 or higher

**Comment by kf6kjg** [comment]
Just created PR #787 to solve this. Please give that a try and report your results.
