### ISSUE TITLE
bluebird typings are still referenced

### ISSUE THREAD

**Issue by ShaharHD** [RobinBuschmann/sequelize-typescript#792]
According to `yarn` the bluebird are still referenced.

```shell
yarn add sequelize-typescript
yarn add v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > sequelize-typescript@1.1.0" has unmet peer dependency "@types/bluebird@*".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ sequelize-typescript@1.1.0
info All dependencies
└─ sequelize-typescript@1.1.0
```

See here https://github.com/RobinBuschmann/sequelize-typescript/blob/master/package.json#L75

**Comment by RobinBuschmann** [comment]
Hey @ShaharHD, this is because the latest sequelize version (Version 5.21.11) still requires bluebird.

**Comment by ShaharHD** [comment]
But the warning regarding this comes only from `sequelize-typescript`.
latest version of sequelize (if it was new project, as with `yarn install sequelize sequelize-typescript`) will not install bluebird typings, or am I mistaken?
