### ISSUE TITLE
Does class-validator work well with sequelize-typescript?

### ISSUE THREAD

**Issue by oney** [RobinBuschmann/sequelize-typescript#806]
I haven't tried using [class-validator](https://github.com/typestack/class-validator) with sequelize-typescript, but I'd like to ask first, does class-validator work well with sequelize-typescript?

**Comment by MagicLegend** [comment]
Why would the [built-in validations](https://github.com/RobinBuschmann/sequelize-typescript#model-validation) work for this? Those are really extensive as well, and so far have suited all my needs.

**Comment by gzlock** [comment]
@MagicLegend 
How to validate more than one columns value with sequelize-typescript?

**Comment by MagicLegend** [comment]
@gzlock What do you mean? You can add multiple annotations to a single column if desired. E.g. (from the docs):
```js
@IsDate
@IsBefore('2017-02-27')
@Column
producedAt: Date;
```

Make sure `@Column` is the last entry though, otherwise ST will start erroring out about it.
