### ISSUE TITLE
Error when defining relationships (BelongsTo, ForeignKey, HasMany etc)

### ISSUE THREAD

**Issue by Evanion** [RobinBuschmann/sequelize-typescript#821]
**Versions**

- sequelize: ^6.3.3
- sequelize-typescript: ^1.1.0
- typescript: ^3.9.7

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

**Actual behavior:**
I'm getting a type error when I try and define a relationship between Models

**Expected behavior:**
Being able to define relationships as per the docs and examples

**Related code:**
![Screenshot 2020-07-29 at 15 40 12](https://user-images.githubusercontent.com/319799/88808795-99ecb700-d1b3-11ea-95e0-4dc78e89aa57.png)
![Screenshot 2020-07-29 at 15 49 25](https://user-images.githubusercontent.com/319799/88808836-a4a74c00-d1b3-11ea-8b0c-ebf2e6d7bdb3.png)
![Screenshot 2020-07-29 at 15 49 39](https://user-images.githubusercontent.com/319799/88808856-aa9d2d00-d1b3-11ea-814a-b7b7330cc0ed.png)
![Screenshot 2020-07-29 at 15 56 36](https://user-images.githubusercontent.com/319799/88809212-25664800-d1b4-11ea-9a22-a11c4a4220c2.png)
![Screenshot 2020-07-29 at 15 56 47](https://user-images.githubusercontent.com/319799/88809218-27300b80-d1b4-11ea-89a8-5ce9132a3506.png)

**Comment by maracaipe** [comment]
Hi @Evanion, this is the same issue at lot of people are having here. I have commented on issue #813 this: 

> I have this same issue. Could resolve this by removing the type constructor (`<Questions>`, `<Options>`).
> 
> In my case I had a QuestionsAttributes interface and had to change:
> 
>     class TalentData extends Model<TalentData, TalentDataAttributes>
> 
> to:
> 
>     class TalentData extends Model implements TalentDataAttributes
> 
> But this really appears to be a sequelize-typescript error.

**Comment by crrobinson14** [comment]
I had this same issue this morning and cross-compared my current project against one that was still working. I noticed I had a few modules with later versions, especially Typescript, Sequelize itself, and some of the @types incudes, so I downgraded them and this resolved the problem.

For reference, this is working for me. Later versions of Sequelize and other deps are not:

```
  "dependencies": {
    "mysql2": "^2.1.0",
    "reflect-metadata": "^0.1.13",
    "sequelize": "^5.22.2",
    "sequelize-typescript": "^1.1.0"
  },
  "devDependencies": {
    "@types/sequelize": "^4.28.9",
    "@types/bluebird": "^3.5.32",
    "@types/validator": "^13.0.0",
    "@types/node": "^14.0.13",
    "typescript": "^3.9.5"
  },
```

**Comment by mugbomah** [comment]
Yeah, having similar issue. Downgraded from v 6 to "sequelize": "^5.22.2" and error disappeared.

**Comment by ltbittner** [comment]
+1 Getting the same error. Downgrading to `5.22.2` also resolved the issue for me.

**Comment by vanthome** [comment]
Same here, a fix would be great

**Comment by jgburet** [comment]
Problem comes from 
- https://github.com/RobinBuschmann/sequelize-typescript/blob/da83a611d87c4b32f4348071054bccbe677ba7a4/src/associations/belongs-to/belongs-to-association.ts#L21
- https://github.com/RobinBuschmann/sequelize-typescript/blob/da83a611d87c4b32f4348071054bccbe677ba7a4/src/associations/belongs-to-many/belongs-to-many-association.ts#L23
- https://github.com/RobinBuschmann/sequelize-typescript/blob/da83a611d87c4b32f4348071054bccbe677ba7a4/src/associations/has/has-association.ts#L21
