### ISSUE TITLE
models in sequelize constructor or in include relations ts error.

### ISSUE THREAD

**Issue by ahmedthinkdifferent** [RobinBuschmann/sequelize-typescript#826]
i have user model :-
import { Column, Model, Table } from 'sequelize-typescript';

@Table({
  tableName: 'users',
})
export class User extends Model<User> {
  @Column
  name: string;

  @Column
  age: number;

}

TS2322: Type 'typeof User' is not assignable to type 'string | ModelCtor<Model<any, any>>'.   Type 'typeof User' is not assignable to type 'ModelCtor<Model<any, any>>'.     Type 'typeof User' is not assignable to type 'typeof Model'.       Construct signature return types 'User' and 'Model<T, T2>' are incompatible.         The types of '_attributes' are incompatible between these types.           Type 'User' is not assignable to type 'T'.             'T' could be instantiated with an arbitrary type which could be unrelated to 'User'.

**Comment by Tyldar** [comment]
Same here. Looks like it's not compatible with latest version of sequelize. Works fine with the `5.21.7`

**Comment by techird** [comment]
thanks @Segfaultd , fixed after install sequelize@5
