### ISSUE TITLE
 No default export defined for file "X" or export does not satisfy filename. with ts-jest

### ISSUE THREAD

**Issue by oktapodia** [RobinBuschmann/sequelize-typescript#840]
**Versions**

- sequelize: 5.22.3
- sequelize-typescript: 1.1.0
- typescript: 3.9.7

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

Using `sequelize-typescript` with `ts-node` is perfectly working, however, when running the E2E tests with `ts-jest`, I am getting the following error:

```
 No default export defined for file "X" or export does not satisfy filename.
```

The class is named `X` like its own file

```
// X.ts

import {
  Table,
  Column,
  Model,
  AllowNull,
} from "sequelize-typescript"
@Table({ underscored: true })
class X extends Model<X> {
  @AllowNull(false)
  @Column
  name!: string;

}

export default X

```

I did add some logging [here](https://github.com/RobinBuschmann/sequelize-typescript/blob/master/src/sequelize/sequelize/sequelize-service.ts#L57) to see what's happening and 

Running with ts-node:
```
{ default: X } '/private/var/www/project/models/X'
```

Running with ts-jest:
```
{ } '/private/var/www/project/models/X'
```

**Expected behavior:**

Make the tests working with ts-jest

**Steps to reproduce:**

**Related code:**

```ts
insert short code snippets here
```

**Comment by oktapodia** [comment]
any ideas?

**Comment by zhangchi1** [comment]
Hi @oktapodia , I am facing the same error, where I have `models = [__dirname + "/../path/to/my/models"]` add in my Sequelize. I'm wondering did you solve this issue?

**Comment by oibukun-mufin** [comment]
@oktapodia 

How were you able to solve this issue  , im having the same issue

**Comment by odeyemiibukunajewole** [comment]
@oktapodia ,

How were you able to solve this issue , im currently having the same issue
