### ISSUE TITLE
Sequelize v6 compatibility?

### ISSUE THREAD

**Issue by spinlud** [RobinBuschmann/sequelize-typescript#844]
Is sequelize v6 compatibility still in beta? Any ETA?

**Comment by Benjamin-Gardien** [comment]
+1

**Comment by QuanticPotatoes** [comment]
+1

**Comment by dgomez-orangeloops** [comment]
+1

**Comment by thetminko** [comment]
+1

**Comment by Benjamin-Gardien** [comment]
Apparently @next allow sequelize v6 compatibility #787 
Any update @RobinBuschmann ? 🙏🏼

**Comment by Divlo** [comment]
Most likely this pull request added support for v6 compatibility #807.
What need to be done, to fully release `sequelize-typescript@2.0` (as a stable release) ? @RobinBuschmann 
Maybe we can help, to get this thing done! 🚀

**Comment by lukashroch** [comment]
#807 should compatible with v6 up to v6.1 only.

v6.2 introduced some breaking changes to types mostly. You can try #856 for latest (v6.3.5) support

**Comment by Benjamin-Gardien** [comment]
We tried to work with sequelize-typescript@next ([2.0-beta](https://www.npmjs.com/package/sequelize-typescript/v/2.0.0-beta.0)) with Nest-Js, it works with sequelize v6.1. @RobinBuschmann we can help you to release v6.3.5 compatibility @lukashroch @Divlo 🤷🏼‍♂️

**Comment by Divlo** [comment]
As discussed in #871.
I installed `sequelize-typescript@2.0.0-beta.1` in my project and I've got many TypeScript errors...
It seems like it stills doesn't work.

![Capture1_6](https://user-images.githubusercontent.com/25207499/103172134-9d16cc80-4851-11eb-8c03-da888fce3408.png)

**Comment by goalia** [comment]
Can you show us the « Invitation » model ? 
I think it’s because you extends Model in your file like extends Model<Invitation>

**Comment by lukashroch** [comment]
Looks like you're using old v5 class declaration. You must update all models to reflect v6 changes.

**Comment by Divlo** [comment]
Yes, am I doing something wrong ? @goalia 

![Capture1_7](https://user-images.githubusercontent.com/25207499/103172289-ba986600-4852-11eb-8857-65713f7b24a2.png)

**Comment by lukashroch** [comment]
@Divlo, check out #865, it describes the changes for model declarations

**Comment by Divlo** [comment]
Thanks @lukashroch! It solves the problem. :+1:

**Comment by spinlud** [comment]
I was testing the latest beta `2.0.0-beta.1`, the following works with just `sequelize` `v6.3.5`:

```ts
import { Sequelize, Optional, Model, DataTypes } from 'sequelize';

interface PersonAttributes {
    id: number;
    name: string;
    country?: string;
}

interface PersonCreationAttributes extends Optional<PersonAttributes, 'country'> {}

class Person extends Model<PersonAttributes, PersonCreationAttributes> implements PersonAttributes {
    id!: number;
    name!: string;
    country?: string;
}


(async () => {
    const sequelize =  new Sequelize({
        dialect: 'mysql',
        host: 'localhost',
        port: 3306,
        database: 'testdb',
        username: 'admin',
        password: 'admin',
        logQueryParameters: true,
        logging: true,
    });

    await sequelize.authenticate();

    Person.init({
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false
        },
        country: {
            type: DataTypes.STRING,
            allowNull: true
        }
    }, {
        tableName: 'Person',
        sequelize
    });

    await sequelize.sync();

    const p = new Person({
        id: 1,
        name: 'Ken'
    });

    await p.save();

    const persons = await Person.findAll();
    console.log(persons);

    await sequelize.close();
})();
```

The following does not work, using `sequelize-typscript`:

```ts
import { Optional } from 'sequelize';
import { Sequelize, Model } from "sequelize-typescript";

interface PersonAttributes {
    id: number;
    name: string;
    country?: string;
}

interface PersonCreationAttributes extends Optional<PersonAttributes, 'country'> {}

class Person extends Model<PersonAttributes, PersonCreationAttributes> implements PersonAttributes {
    id!: number;
    name!: string;
    country?: string;
}


(async () => {
    const sequelize =  new Sequelize({
        dialect: 'mysql',
        host: 'localhost',
        port: 1234,
        database: 'testdb',
        username: 'sa',
        password: 'Passw0rd88!',
        logQueryParameters: true,
        logging: true,
    });

    await sequelize.authenticate();
    
    await sequelize.addModels([Person]); // <-- compiler complains

    await sequelize.sync();

    const p = new Person({
        id: 1,
        name: 'Ken'
    });

    await p.save();

    const persons = await Person.findAll();
    console.log(persons);

    await sequelize.close();
})();
```
![image](https://user-images.githubusercontent.com/12783208/104131948-4d202580-537a-11eb-917a-82917cce1d5b.png)

Am I missing something?

**Comment by goalia** [comment]
Hello @spinlud, you need to replace the following:
`class Person extends Model<PersonAttributes, PersonCreationAttributes> implements PersonAttributes`
by `class Person extends Model implements PersonAttributes`

**Comment by spinlud** [comment]
@goalia thanks but this solution doesn't provide type checking on model creation, which I guess is the main reason to extends `Model<ModelAttributes, ModelCreationAttributes>` signature. Is there any ongoing work on this?

**Comment by antonstjernquist** [comment]
@spinlud https://github.com/sequelize/sequelize/pull/11820

This PR was created a long time ago. I'm not sure what to do :/

**Comment by spinlud** [comment]
@antonstjernquist it looks like that that PR was left unmerged, this one has been merged instead https://github.com/sequelize/sequelize/pull/12405.

There is this other PR https://github.com/RobinBuschmann/sequelize-typescript/pull/868 which seems trying to fix issue about Model generics signature

**Comment by Divlo** [comment]
`sequelize-typescript@2.0.0` has been released! :smile: 
If you encounter bugs, feel free to open new issues!
