### ISSUE TITLE
Sequelize-Typescript 1.1.0 compile error against Sequelize 6.3.5

### ISSUE THREAD

**Issue by craigmcc** [RobinBuschmann/sequelize-typescript#853]
Tried to create a brand new project against the following versions:
* sequelize 6.3.5
* sequelize-typescript 1.1.0
* typescript 4.0.5

But get a compile error when trying to start up -- cannot find getQueryInterface() method.  I ran into this with an older project as well, and downgrading sequelize to 5.22.3 made it work (but of course gives up on the later changes in sequelize itself).

Is there any way to get this to work?  I see there were some previous commits that dealt with some issues for sequelize 6, but this one is a blocker for me.

**Comment by EdByrnee** [comment]
I think 1.1.0 is only compatible with sequelize 5
What about 
`npm install --save sequelize-typescript@next`
to install v2 beta

**Comment by Divlo** [comment]
`sequelize-typescript@2.0.0` has been released! :smile:
