### ISSUE TITLE
updatedAt is actually updated_at 

### ISSUE THREAD

**Issue by DanieleMabiloft** [RobinBuschmann/sequelize-typescript#860]
**Versions**

- sequelize: 5.22.3
- sequelize-typescript: 1.1.0
- typescript: 4.1.2

**I'm submitting a ...** 

[ x ] bug report
[ ] feature request

When I try to access to the property updatedAt of an istance of a model it returns undefined, due to the fact that it's actually called updated_at, the problem is that using myIstance.updated_at the linter gives back an error telling me that the property updated_at does not exist for myIstance type, i checked the definitions and it's effectively declared as updatedAt

**Comment by antonstjernquist** [comment]
Perhaps it's because of the naming strategy? It's hard to tell without any code or example.

https://sequelize.org/master/manual/naming-strategies.html
