### ISSUE TITLE
Do we have a release note?

### ISSUE THREAD

**Issue by BruceHem** [RobinBuschmann/sequelize-typescript#87]
@RobinBuschmann, Something like a change log or history would be helpful in order to keep up with changes to the module.

**Comment by RobinBuschmann** [comment]
Currently we have not. But we should have one, you're absolutely right.

**Comment by RobinBuschmann** [comment]
@BruceHem It's done for `0.4.0` and will be added on every future release.

**Comment by BruceHem** [comment]
Thanks u so much! 🎉🎉🎉
