### ISSUE TITLE
Trying to initialize a database results in: SequelizeDatabaseError: SQLITE_ERROR: no such table: Users

### ISSUE THREAD

**Issue by rdvhoorn** [RobinBuschmann/sequelize-typescript#874]
Have been rewriting a backend using sequelize in typescript, and recently discovered this beauty of a library. Loving it so far, but running into a problem. Thus beware for noob mistakes, but cant seem to figure this one out myself.

**Versions**
- sequelize: 5.22.3
- sequelize-typescript: 1.1.0
- typescript: 3.9.7

Have set up all my models now with sequelize-typescript. Have my `db.ts` file for creating my database:
```ts
const storage = "data.sqlite";
export const db: Sequelize = new Sequelize({
    database: "db",
    dialect: "sqlite",
    username: null,
    password: null,
    storage,
});

/** lots of import **/

db.addModels([Activity, User, ... More models ...]);
```

For running and testing the server, we always had a script that initialized the instance of the database (data.sqlite file) and imported the first few instances of each of the models for easy testing. Im trying to get this to work now, but running into some problems. In this script, we first define the stuff we want to initialize in arrays and then call bulkCreate on the models like this:

```ts
all([
    Role.bulkCreate(roles).then(function(result: any): void {
        console.log("Created roles");
    }),
    User.bulkCreate(users).then(function(result: any): void {
        console.log("Created users");
    }),
    Group.bulkCreate(groups).then(function(result: any): void {
        console.log("Created groups");
    }),
    Activity.bulkCreate(activities).then(function(result: any): void {
        console.log("Created activities");
    })
]).then(function(): any { /** more stuff **/}
```

Whenever running this (running it using: `npx ts-node src/import_initial.ts`), it logs `Executing (default): INSERT INTO 'Users' ..... ` and then shows all the correct information, after which it gives an error message `SequelizeDatabaseError: SQLITE_ERROR: no such table: Users`. To what I understand, the User model should create a table in the db called User and not Users. I already tried to force the name of the table, but the same error persists. The problem seems to be that the model is added to the sequelize instance, but the table is not created. Anybody knows how to solve this? Thanks a lot in advance!

If you want to see the full code: https://github.com/Confluente/backend-v2/tree/sequelize-typescript-implementation (don't look too much around yet :P routes and stuff still needs to be rewritten. But with db.ts, all the models, and the import_initial.ts script you should have everything that regards my current question.)

**Comment by rdvhoorn** [comment]
Something i figured out alnog the way which i forgot to mention is that initially it did not add the models to the sequelize instance. Somehow the last line of the db.ts file did not execute, not sure why? So what i ended up doing is to add the addModels call to the initialize db script which did work. So the above db.addModels is actually not executed, and what is run instead is the same line but then in the script.

**Comment by rdvhoorn** [comment]
If i run it in `:memory:` the same issue persists

**Comment by rdvhoorn** [comment]
@RobinBuschmann any chance you could help me with this?

**Comment by rdvhoorn** [comment]
I quickly looked back at what i did on the day i closed the issue. 
https://github.com/Confluente/backend-v2/commit/bd4a05a94aa847f1482c21da5b249cce06d10fa2 this is the commit i made that day (check the import initial file). 

What i suspect that worked for me is to encapsulate the code in 
```
(async () => {

    await db.sync({force: true});

    // Code here
})
```

**Comment by albedoa** [comment]
This issue is the first google result for `"SQLITE_ERROR" "sequelize"` and `"no such table" "sequelize"`.

I am copying the basic example on [the Sequelize homepage](https://sequelize.org/) exactly. The error happens at the `User.create()` call.

Does the example omit a step that is assumed to be obvious? Or are others experiencing the same issue? I am using Sequelize v6.37.3.

**Edit:** Throwing in a `sequelize.sync()` call fixed things.

**Comment by fsq** [comment]
Seeing same error in my jest test.
What's NOT working and causing `Error: SQLITE_ERROR: no such table`:
```typescript
  beforeAll(async () => {
    await sequelize.models.User.sync({ force: true });
  });
```
What is working:
```typescript
  beforeAll(async () => {
    await sequelize.sync({ force: true });
  });
```
