### ISSUE TITLE
Fork new sequelize-ts to support Sequelize v6

### ISSUE THREAD

**Issue by hsluoyz** [RobinBuschmann/sequelize-typescript#876]
New fork: https://github.com/node-casbin/sequelize-ts
==========

We have an urgent need to support Sequelize v6. We have to fork it because the current PRs are not handled very quickly. Currently we are testing this PR: https://github.com/RobinBuschmann/sequelize-typescript/pull/868#issuecomment-757403641 but encountered some issue.

I also saw the current PR doesn't use CI to run all tests. Maybe need to add a Travis CI or GitHub Actions to the repo.

Hope somebody also interested in it can join us, thanks!

**Comment by Divlo** [comment]
@hsluoyz Instead to create a fork, we should continue to work on this repo, `sequelize-typescript@2.0.0` has been released, so it supports `sequelize >= 6.0.0`. :smile:

**Comment by hsluoyz** [comment]
@Divlo hi, did v2.0.0 release resolve this issue? https://github.com/RobinBuschmann/sequelize-typescript/pull/868

I asked this because we encountered a similar issue here: https://github.com/node-casbin/sequelize-adapter/issues/34

I also tried by myself but still has error even for sequelize 6.2.0:

```
    "sequelize": "^6.2.0",
    "sequelize-typescript": "^2.0.0"
```

```
$ jest --forceExit
 FAIL  test/adapter.test.ts
  ● Test suite failed to run

    src/adapter.ts:46:31 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Type 'typeof CasbinRule' is not assignable to type 'string | ModelCtor<Model<any, any>>'.
          Type 'typeof CasbinRule' is not assignable to type 'ModelCtor<Model<any, any>>'.
            Type 'typeof CasbinRule' is not assignable to type 'typeof Model'.
              Types of parameters 'values' and 'values' are incompatible.
                Type 'TCreationAttributes | undefined' is not assignable to type 'CasbinRule | undefined'.
                  Type 'TCreationAttributes' is not assignable to type 'CasbinRule | undefined'.
                    Type '{}' is not assignable to type 'CasbinRule'.
                      Type 'TCreationAttributes' is not assignable to type 'CasbinRule'.
                        Type '{}' is missing the following properties from type 'CasbinRule': ptype, v0, v1, v2, and 39 more.

    46     this.sequelize.addModels([CasbinRule]);
                                     ~~~~~~~~~~

      node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.d.ts:16:5
        16     addModels(arg: Array<ModelCtor | string>): any;
               ~~~~~~~~~
        The last overload is declared here.
```

Can you help me have a look? Thanks!

**Comment by Divlo** [comment]
@hsluoyz Hey, I don't know if it has been fixed, but please open issues/PR so we can improve `sequelize-typescript` together.
Also you could provider "steps to reproduce so we can fix it easier".

**Comment by hsluoyz** [comment]
@Divlo here's the PR: https://github.com/RobinBuschmann/sequelize-typescript/pull/868
