### ISSUE TITLE
angular custom exception, retry and catch blocks in angular

### ISSUE THREAD

**Issue by axayi** [RobinBuschmann/sequelize-typescript#877]
I am trying log custom exception in angular using TS but not catch block is not executing getting following error
i have implemented handleError() Method - where custom exception messages are available

LoadList(): Observable<ABC[]> {
return this.http.get<ABC[]>(this.apiUrl).pipe(
retry(1),
catchError(this.handleError)

//  //catchError((error: any) => {
//  //  return this.handleerror; //observable.throw(new error(error));
//  //})
}

i am getting below error and catch block is not working

![image](https://user-images.githubusercontent.com/65702213/104228104-63101200-5470-11eb-937f-d4216abbb133.png)

**Comment by Divlo** [comment]
This issue is not related to `sequelize-typescript`.
