### ISSUE TITLE
Specifying a `field` in the @Column decorator does not map back to the decorated name.

### ISSUE THREAD

**Issue by aventurella** [RobinBuschmann/sequelize-typescript#89]
For example:
```
@Column({field: 'search_name', type: DataType.STRING })
searchName: string;
```

When querying on this model only `search_name` is returned and `searchName` is undefined on the model.

**Comment by aventurella** [comment]
This seems to work to map the names back to the `@Column` defined names

```typescript
let modelAttributes = (<any>MyModel).attributes;
queryResult.forEach(row => {
    for(let key in modelAttributes){
        let column = modelAttributes[key];

        if((<any>row).dataValues[column.field] !== undefined){
            row[column.fieldName] = (<any>row).dataValues[column.field];
        }
    }
})
```

Now `myRow.toJSON()` still does the wrong thing, it returns the `field` name not the column name. but that could also be solved with 1 override of `toJSON` to look at the class's attributes again.

**Comment by RobinBuschmann** [comment]
Hey @aventurella Thanks for reporting. Can you provide a more advanced example or much better a repository which shows the issue? Which version are you using? I cannot reproduce it - for me it is working very well.

**Comment by aventurella** [comment]
You know what I think it is... In my particular model, I have 2 blob fields that host a JPG. So when I query for list views etc, I need to omit those 2 blob fields so I query only specific attributes:

```typescript
MyModel
.findAll<MyModel>({
    order: [ ['created_at', 'DESC'] ],
    attributes: ['id', 'created_at', 'name', 'another_column_2', 'another_column_1']
})
```

My guess is when that is the query path, aka via `attributes` that the remapping doesn't happen.

**Comment by RobinBuschmann** [comment]
Are you using the name of the properties or the name of the fields in the attributes array?

**Comment by aventurella** [comment]
When I use the names of the properties, it fails to query. aka, if I use `anotherColumn1` in the `attributes` I get a SQL error that the column does not exist. So I have to use `another_column_1` in the `attributes`

**Comment by aventurella** [comment]
Side note, this lib is really great, thanks for putting in the time to write/maintain it.

**Comment by RobinBuschmann** [comment]
Hey thank you very much.

Normally you should use the property name. Which sequelize and which sequelize-typescript version are you using?

With sequelize-typescript `0.4.0` and sequelize `4.3.2` it is working as expected.

**Comment by aventurella** [comment]
Ah.. i'm using 0.3.5 and 4.0.0.. I'll bump! thanks!

**Comment by aventurella** [comment]
Yup! looks like it's not an issue in 0.4.0.. THANKS!!!!

**Comment by RobinBuschmann** [comment]
Did you updated sequelize as well? So could it be that the issue was caused by sequelize?
