### ISSUE TITLE
Question: Can the following snippet have automatically type conversion?

### ISSUE THREAD

**Issue by BruceHem** [RobinBuschmann/sequelize-typescript#90]
Since sequelize v4 DECIMAL type now returns string.

Below maximum_fee_amt is define as number, but runtime will be string.
```
@Column({ type: DataType.DECIMAL(10, 2) })
maximum_fee_amt: number;
```

This is my workaround.
```
@Column({ type: DataType.DECIMAL(10, 2) })
get maximum_fee_amt(): number {
  return +this.getDataValue('maximum_fee_amt');
};
```

Do you guys think it's possible to have this auto type conversion? like the following:

This would auto return a number;
```
@Column({ type: DataType.DECIMAL(10, 2) })
maximum_fee_amt: number;
```

and below would auto return a string;
```
@Column({ type: DataType.DECIMAL(10, 2) })
maximum_fee_amt: string;
```

**Comment by RobinBuschmann** [comment]
@BruceHem Is this behavior documented in sequelize v4 somewhere? Or could this be a bug?

**Comment by BruceHem** [comment]
here http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

it says "DataTypes.DECIMAL returns string for MySQL and Postgres."

**Comment by RobinBuschmann** [comment]
Thanks.

Hmm, I think we should change as less as possible of the behavior of sequelize in sequelize-typescript. So I would suggest to keep it as it is.

But you could add your own annotation to your project to achieve this:

```typescript
import {addAttributeOptions} from "sequelize-typescript/lib/services/models";

function ToNumber(target: any, propertyKey: string): any {
    addAttributeOptions(target, propertyKey, {
        get(): any {
            return +this.getDataValue(propertyKey);
        }
    });
}

@ToNumber
@Column({ type: DataType.DECIMAL(10, 2) })
maximum_fee_amt: number;
```

What's your opinion about it?

**Comment by RobinBuschmann** [comment]
@BruceHem Does this work for you? Can we close this issue then? Thank you :)

**Comment by BruceHem** [comment]
Oops Yes it works

**Comment by riskgod** [comment]
this one help for me Thanks~
