### ISSUE TITLE
Include + HasMany + column alias + order = incorrect query

### ISSUE THREAD

**Issue by kingjerod** [RobinBuschmann/sequelize-typescript#91]
First you need a model with a column alias:
    
    @Column({type: DataType.DATEONLY, field: 'date_start'})
    dateStart: Date;

And on the same model, a HasMany:

    @HasMany(() => ImageModel, {foreignKey: 'userId'})
    images: ImageModel[]

Then do a find like so:

    UserModel.findOne<UserModel>({
        where: {id: 1}, order: [['dateStart', 'DESC']], include: [ImageModel]
    })

This will create an inner query that grabs the user model and does the order by the non alias name `date_start`. Then it joins it with the images, and tries to order again with the same non alias `date_start`, which fails because it's been aliased to `dateStart`. This is the resulting query:

    SELECT
    "UserModel".*, "images"."id" AS "images.id",
    "images"."user_id" AS "images.userId",
    "images"."url" AS "images.url"
    FROM
	(
		SELECT
			"UserModel"."id",
			"UserModel"."date_start" AS "dateStart",
			"UserModel"."name",
		FROM
			"users" AS "UserModel"
		WHERE
			"UserModel"."id" = 1
		ORDER BY
			"UserModel"."date_start" DESC
		LIMIT 1
	) AS "UserModel"
    LEFT OUTER JOIN "images" AS "images" ON "UserModel"."id" = "images"."user_id"
    ORDER BY
    "UserModel"."date_start" DESC;

**Comment by RobinBuschmann** [comment]
Hey @kingjerod sounds like a sequelize issue to me. Can you reproduce this with pure sequelize? If so, this should be reported to the sequelize team.
Which sequelize and sequelize-typescript version are you using?

**Comment by kingjerod** [comment]
I'll give it a go with regular Sequelize. Using sequelize 4.2.1, and sequelize-typescript 0.4.0

**Comment by kingjerod** [comment]
Yup, looks like a Sequelize issue. I have opened an issue with them. 

https://github.com/sequelize/sequelize/issues/8100

**Comment by RobinBuschmann** [comment]
@kingjerod Thank you
