### ISSUE TITLE
DataType.TEXT Columns

### ISSUE THREAD

**Issue by connected-pjeri** [RobinBuschmann/sequelize-typescript#95]
Hi @RobinBuschmann, it seems there is a problem with TEXT type columns. I think it's at the model level because migrations are ran correctly and I can also insert rows into the DB directly.

I'm defining the column in the model in the same way as it is in the README. Do you mind confirming if this works for you?

In order to reproduce the bug all you need to do is define a new object of that model. Eg:

``` typescript
const modelName = new ModelName({
  payload
})
```

**ModelName.ts**
``` typescript
@AllowNull(false)
@Column(DataType.TEXT)
payload: string;
```

**Error log**
```
TypeError: Cannot read property 'hasPrimaryKeys' of undefined
    at Log.Model (/Users/project_dir/node_modules/sequelize/lib/mo
del.js:2960:51)
    at Model (/Users/project_dir/node_modules/sequelize-typescript
/lib/models/v4/Model.js:8:9)
    at Log (/Users/project_dir/dist/public/js/server.bundle.js:259
2:11)
    at LogController.saveLog (/Users/project_dir/dist/public/js/se
rver.bundle.js:2534:25)
    at /Users/project_dir/dist/public/js/server.bundle.js:2056:44
    at Layer.handle [as handle_request] (/Users/project_dir/node_m
odules/express/lib/router/layer.js:95:5)
...
```

**Comment by RobinBuschmann** [comment]
@connected-pjeri this appears when ModelName is not added to a `Sequelize` instance of sequelize-typescript

So you need to initialize the model first like:

```typescript
import {Sequelize} from 'sequelize-typescript';

const sequelize = new Sequelize({
  ...,
  modelPaths: ['path/to/models-directory']
});

// or

sequelize.addModels([ModelName]);

// then you can call
const modelName = new ModelName({
  payload
})
```

But you revealed a bug though: `Model not initialized: "ModelName" needs to be added to a Sequelize instance before "$expandAttributes" can be called.` should be thrown instead of `Cannot read property 'hasPrimaryKeys' of undefined`

**Comment by RobinBuschmann** [comment]
See #96

**Comment by connected-pjeri** [comment]
Of course, I'm often forgetting this step. Thank you so much. Also, thanks for the bug surfacing silver lining lol.

**Comment by RobinBuschmann** [comment]
You're welcome
