### ISSUE TITLE
Constraint already exists when starting app a second time using sequelize sync({ alter: true })

### ISSUE THREAD

**Issue by SNeugber** [RobinBuschmann/sequelize-typescript#99]
Hi,

I'm not sure if this is a problem with just sequelize or sequelize-typescript, or a combination of both. I thought that maybe it's to do with the way sequelize-typescript generates the models, but feel free to close this if I should open the issue on the sequelize package instead.

When I run the app for the second time using sequelize.sync({ alter: true }), it tries to recreate a foreign key that already exists.

Error:
```
Unhandled rejection SequelizeDatabaseError: constraint "userId_foreign_idx" for relation "PushDevice" already exists
```

Models:
```
@Table
export default class User extends Model<User> {

  ... 

  @HasMany(() => PushDevice)
  devices: PushDevice[];

  ...
}


@Table
export default class PushDevice extends Model<PushDevice> {

  @ForeignKey(() => User)
  @Column
  userId: number;

  @BelongsTo(() => User)
  user: User;

  @Column
  deviceId: string;
}
```

Queries it tries to execute for the PushDevice model:
```
Executing (default): SELECT pk.constraint_type as "Constraint", c.column_name as "Field", c.column_default as "Default", c.is_nullable as "Null", (CASE WHEN c.udt_name = 'hstore' THEN c.udt_name ELSE c.data_type END) || (CASE WHEN c.character_maximum_length IS NOT NULL THEN '(' || c.character_maximum_length || ')' ELSE '' END) as "Type", (SELECT array_agg(e.enumlabel) FROM pg_catalog.pg_type t JOIN pg_catalog.pg_enum e ON t.oid=e.enumtypid WHERE t.typname=c.udt_name) AS "special" FROM information_schema.columns c LEFT JOIN (SELECT tc.table_schema, tc.table_name, cu.column_name, tc.constraint_type FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.KEY_COLUMN_USAGE  cu ON tc.table_schema=cu.table_schema and tc.table_name=cu.table_name and tc.constraint_name=cu.constraint_name and tc.constraint_type='PRIMARY KEY') pk ON pk.table_schema=c.table_schema AND pk.table_name=c.table_name AND pk.column_name=c.column_name WHERE c.table_name = 'PushDevice' AND c.table_schema = 'public'

Executing (default): ALTER TABLE "PushDevice"  ADD CONSTRAINT "userId_foreign_idx" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;

```

The output of the first of those queries is:

Constraint | Field | Default | Null | Type | special
-- | -- | -- | -- | -- | --
PRIMARY KEY | id | nextval('"PushDevice_id_seq"'::regclass) | NO | integer |  
  | userId |   | YES | integer |  
  | deviceId |   | YES | character varying(255)

Seems to me like the query doesn't retrieve the foreign key, so it tries to recreate it?

Versions used:
sequelize: 4.5.0
sequelize-typescript: 0.4.0
postgresql: 9.6

Thanks!

**Comment by RobinBuschmann** [comment]
Hey @SNeugber, thanks for reporting. I'm on vacation and therefore have no possibilities to investigate this. But you can try to reproduce this with pure sequelize in order to check if the issue occurs as well. Thank you :)

**Comment by SNeugber** [comment]
Sure, will try and get to it next week :)

**Comment by RobinBuschmann** [comment]
Hey @SNeugber, you couldn't know that, but this is not the equivalent of how sequelize-typescript is doing this with pure sequelize under the hood. And I didn't know that a `reference` option exists for configuring foreign keys like that. So its my fault.

I will investigate this on next weekend.

**Comment by RobinBuschmann** [comment]
OK, here we go: The equivalent in pure sequelize is:

```javascript
const {Sequelize, DataTypes} = require('sequelize');

const sequelize = new Sequelize({
    database: 'st-issue-99',
    host: 'localhost',
    username: 'root',
    dialect: 'mysql',
    password: ''
});

const User = sequelize.define('User', {
    name: DataTypes.STRING
});

const PushDevice = sequelize.define('PushDevice', {
    name: DataTypes.STRING
});

User.hasMany(PushDevice, {foreignKey: 'userId'});
PushDevice.belongsTo(User, {foreignKey: 'userId'});

sequelize.sync({ alter: true })
    .then(() => {
        return User.create({ name: 'user' });
    })
    .then((user) => {
        return PushDevice.create({ name: 'device', userId: user.id });
    })
    .then((device) => {
        console.log(device);
    })
    .catch(err => {
        console.error(err);
    })
;
```
And I'm getting an error as well: `SequelizeDatabaseError: Can't write; duplicate key in table ...`

Probably that's the intended behavior, but I don't really know what `alter` does. So it doesn't seem to be an sequelize-typescript issue. Can you ask or report this to sequelize instead? :)

**Comment by kukoo1** [comment]
`alter` is a safer alternative to `force: true`.
It alters table instead of `DROP TABLE` then `CREATE TABLE`

Actually it's sequelize bug [](https://github.com/sequelize/sequelize/issues/7649) [](https://github.com/sequelize/sequelize/issues/7606)

**Comment by SNeugber** [comment]
Thanks for finding this @kukoo1 ! Saves me having to open the bug with sequelize.
